
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =
[{
  "houseId": "1",
  "previousWaterMetering": "379",
  "currentWaterMetering": "391",
  "metersConsumed": "12",
  "differenceOfUse": "95",
  "total": "400",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "2",
  "previousWaterMetering": "109",
  "currentWaterMetering": "113",
  "metersConsumed": "4",
  "differenceOfUse": "95",
  "total": "224",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "3",
  "previousWaterMetering": "430",
  "currentWaterMetering": "443",
  "metersConsumed": "13",
  "differenceOfUse": "95",
  "total": "427",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "4",
  "previousWaterMetering": "360",
  "currentWaterMetering": "374",
  "metersConsumed": "14",
  "differenceOfUse": "95",
  "total": "452",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "5",
  "previousWaterMetering": "187",
  "currentWaterMetering": "192",
  "metersConsumed": "5",
  "differenceOfUse": "95",
  "total": "241",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "6",
  "previousWaterMetering": "313",
  "currentWaterMetering": "322",
  "metersConsumed": "9",
  "differenceOfUse": "95",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "7",
  "previousWaterMetering": "445",
  "currentWaterMetering": "454",
  "metersConsumed": "9",
  "differenceOfUse": "95",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "8",
  "previousWaterMetering": "108",
  "currentWaterMetering": "108",
  "metersConsumed": "0",
  "differenceOfUse": "95",
  "total": "158",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "9",
  "previousWaterMetering": "225",
  "currentWaterMetering": "230",
  "metersConsumed": "5",
  "differenceOfUse": "95",
  "total": "241",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "10",
  "previousWaterMetering": "415",
  "currentWaterMetering": "423",
  "metersConsumed": "8",
  "differenceOfUse": "95",
  "total": "300",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "11",
  "previousWaterMetering": "545",
  "currentWaterMetering": "559",
  "metersConsumed": "14",
  "differenceOfUse": "95",
  "total": "452",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "12",
  "previousWaterMetering": "304",
  "currentWaterMetering": "311",
  "metersConsumed": "7",
  "differenceOfUse": "95",
  "total": "280",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "13",
  "previousWaterMetering": "219",
  "currentWaterMetering": "228",
  "metersConsumed": "9",
  "differenceOfUse": "95",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "14",
  "previousWaterMetering": "423",
  "currentWaterMetering": "437",
  "metersConsumed": "14",
  "differenceOfUse": "95",
  "total": "452",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "15",
  "previousWaterMetering": "210",
  "currentWaterMetering": "211",
  "metersConsumed": "1",
  "differenceOfUse": "95",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "16",
  "previousWaterMetering": "196",
  "currentWaterMetering": "200",
  "metersConsumed": "4",
  "differenceOfUse": "95",
  "total": "224",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "17",
  "previousWaterMetering": "260",
  "currentWaterMetering": "268",
  "metersConsumed": "8",
  "differenceOfUse": "95",
  "total": "300",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "18",
  "previousWaterMetering": "302",
  "currentWaterMetering": "309",
  "metersConsumed": "7",
  "differenceOfUse": "95",
  "total": "280",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "19",
  "previousWaterMetering": "44",
  "currentWaterMetering": "52",
  "metersConsumed": "8",
  "differenceOfUse": "95",
  "total": "300",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "20",
  "previousWaterMetering": "286",
  "currentWaterMetering": "303",
  "metersConsumed": "17",
  "differenceOfUse": "95",
  "total": "530",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "21",
  "previousWaterMetering": "294",
  "currentWaterMetering": "303",
  "metersConsumed": "9",
  "differenceOfUse": "95",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "22",
  "previousWaterMetering": "296",
  "currentWaterMetering": "302",
  "metersConsumed": "6",
  "differenceOfUse": "95",
  "total": "260",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "23",
  "previousWaterMetering": "579",
  "currentWaterMetering": "594",
  "metersConsumed": "15",
  "differenceOfUse": "95",
  "total": "478",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "24",
  "previousWaterMetering": "268",
  "currentWaterMetering": "273",
  "metersConsumed": "5",
  "differenceOfUse": "95",
  "total": "241",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "25",
  "previousWaterMetering": "168",
  "currentWaterMetering": "174",
  "metersConsumed": "6",
  "differenceOfUse": "95",
  "total": "260",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "26",
  "previousWaterMetering": "34",
  "currentWaterMetering": "34",
  "metersConsumed": "0",
  "differenceOfUse": "95",
  "total": "158",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "27",
  "previousWaterMetering": "233",
  "currentWaterMetering": "242",
  "metersConsumed": "9",
  "differenceOfUse": "95",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "28",
  "previousWaterMetering": "42",
  "currentWaterMetering": "42",
  "metersConsumed": "0",
  "differenceOfUse": "95",
  "total": "158",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "29",
  "previousWaterMetering": "150",
  "currentWaterMetering": "160",
  "metersConsumed": "10",
  "differenceOfUse": "95",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "30",
  "previousWaterMetering": "441",
  "currentWaterMetering": "451",
  "metersConsumed": "10",
  "differenceOfUse": "95",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "31",
  "previousWaterMetering": "280",
  "currentWaterMetering": "290",
  "metersConsumed": "10",
  "differenceOfUse": "95",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "32",
  "previousWaterMetering": "444",
  "currentWaterMetering": "457",
  "metersConsumed": "13",
  "differenceOfUse": "95",
  "total": "427",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "33",
  "previousWaterMetering": "139",
  "currentWaterMetering": "140",
  "metersConsumed": "1",
  "differenceOfUse": "95",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "34",
  "previousWaterMetering": "403",
  "currentWaterMetering": "411",
  "metersConsumed": "8",
  "differenceOfUse": "95",
  "total": "300",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "35",
  "previousWaterMetering": "583",
  "currentWaterMetering": "601",
  "metersConsumed": "18",
  "differenceOfUse": "95",
  "total": "556",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "36",
  "previousWaterMetering": "361",
  "currentWaterMetering": "381",
  "metersConsumed": "20",
  "differenceOfUse": "95",
  "total": "610",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "37",
  "previousWaterMetering": "241",
  "currentWaterMetering": "248",
  "metersConsumed": "7",
  "differenceOfUse": "95",
  "total": "280",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "38",
  "previousWaterMetering": "418",
  "currentWaterMetering": "427",
  "metersConsumed": "9",
  "differenceOfUse": "95",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "39",
  "previousWaterMetering": "252",
  "currentWaterMetering": "259",
  "metersConsumed": "7",
  "differenceOfUse": "95",
  "total": "280",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "40",
  "previousWaterMetering": "91",
  "currentWaterMetering": "92",
  "metersConsumed": "1",
  "differenceOfUse": "95",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "41",
  "previousWaterMetering": "528",
  "currentWaterMetering": "540",
  "metersConsumed": "12",
  "differenceOfUse": "95",
  "total": "400",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "42",
  "previousWaterMetering": "463",
  "currentWaterMetering": "477",
  "metersConsumed": "14",
  "differenceOfUse": "95",
  "total": "452",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "43",
  "previousWaterMetering": "187",
  "currentWaterMetering": "189",
  "metersConsumed": "2",
  "differenceOfUse": "95",
  "total": "190",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "44",
  "previousWaterMetering": "87",
  "currentWaterMetering": "89",
  "metersConsumed": "2",
  "differenceOfUse": "95",
  "total": "190",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "45",
  "previousWaterMetering": "528",
  "currentWaterMetering": "537",
  "metersConsumed": "9",
  "differenceOfUse": "95",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "46",
  "previousWaterMetering": "186",
  "currentWaterMetering": "191",
  "metersConsumed": "5",
  "differenceOfUse": "95",
  "total": "241",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "47",
  "previousWaterMetering": "504",
  "currentWaterMetering": "509",
  "metersConsumed": "5",
  "differenceOfUse": "95",
  "total": "241",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "48",
  "previousWaterMetering": "172",
  "currentWaterMetering": "178",
  "metersConsumed": "6",
  "differenceOfUse": "95",
  "total": "260",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "49",
  "previousWaterMetering": "352",
  "currentWaterMetering": "362",
  "metersConsumed": "10",
  "differenceOfUse": "95",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "50",
  "previousWaterMetering": "169",
  "currentWaterMetering": "175",
  "metersConsumed": "6",
  "differenceOfUse": "95",
  "total": "260",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "51",
  "previousWaterMetering": "86",
  "currentWaterMetering": "89",
  "metersConsumed": "3",
  "differenceOfUse": "95",
  "total": "207",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "52",
  "previousWaterMetering": "287",
  "currentWaterMetering": "293",
  "metersConsumed": "6",
  "differenceOfUse": "95",
  "total": "260",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "53",
  "previousWaterMetering": "120",
  "currentWaterMetering": "124",
  "metersConsumed": "4",
  "differenceOfUse": "95",
  "total": "224",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "54",
  "previousWaterMetering": "427",
  "currentWaterMetering": "438",
  "metersConsumed": "11",
  "differenceOfUse": "95",
  "total": "377",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "95",
  "total": "158",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "56",
  "previousWaterMetering": "6",
  "currentWaterMetering": "6",
  "metersConsumed": "0",
  "differenceOfUse": "95",
  "total": "158",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "57",
  "previousWaterMetering": "603",
  "currentWaterMetering": "604",
  "metersConsumed": "1",
  "differenceOfUse": "95",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "58",
  "previousWaterMetering": "375",
  "currentWaterMetering": "383",
  "metersConsumed": "8",
  "differenceOfUse": "95",
  "total": "300",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "59",
  "previousWaterMetering": "222",
  "currentWaterMetering": "235",
  "metersConsumed": "13",
  "differenceOfUse": "95",
  "total": "427",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "60",
  "previousWaterMetering": "271",
  "currentWaterMetering": "281",
  "metersConsumed": "10",
  "differenceOfUse": "95",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "61",
  "previousWaterMetering": "81",
  "currentWaterMetering": "82",
  "metersConsumed": "1",
  "differenceOfUse": "95",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "62",
  "previousWaterMetering": "223",
  "currentWaterMetering": "230",
  "metersConsumed": "7",
  "differenceOfUse": "95",
  "total": "280",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "63",
  "previousWaterMetering": "595",
  "currentWaterMetering": "614",
  "metersConsumed": "19",
  "differenceOfUse": "95",
  "total": "583",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "64",
  "previousWaterMetering": "173",
  "currentWaterMetering": "181",
  "metersConsumed": "8",
  "differenceOfUse": "95",
  "total": "300",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "65",
  "previousWaterMetering": "672",
  "currentWaterMetering": "685",
  "metersConsumed": "13",
  "differenceOfUse": "95",
  "total": "427",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "66",
  "previousWaterMetering": "135",
  "currentWaterMetering": "137",
  "metersConsumed": "2",
  "differenceOfUse": "95",
  "total": "190",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "67",
  "previousWaterMetering": "225",
  "currentWaterMetering": "231",
  "metersConsumed": "6",
  "differenceOfUse": "95",
  "total": "260",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "95",
  "total": "158",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "69",
  "previousWaterMetering": "406",
  "currentWaterMetering": "420",
  "metersConsumed": "14",
  "differenceOfUse": "95",
  "total": "452",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "70",
  "previousWaterMetering": "84",
  "currentWaterMetering": "91",
  "metersConsumed": "7",
  "differenceOfUse": "95",
  "total": "280",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "71",
  "previousWaterMetering": "245",
  "currentWaterMetering": "254",
  "metersConsumed": "9",
  "differenceOfUse": "95",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "72",
  "previousWaterMetering": "214",
  "currentWaterMetering": "223",
  "metersConsumed": "9",
  "differenceOfUse": "95",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "73",
  "previousWaterMetering": "191",
  "currentWaterMetering": "196",
  "metersConsumed": "5",
  "differenceOfUse": "95",
  "total": "241",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "74",
  "previousWaterMetering": "116",
  "currentWaterMetering": "120",
  "metersConsumed": "4",
  "differenceOfUse": "95",
  "total": "224",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "75",
  "previousWaterMetering": "375",
  "currentWaterMetering": "385",
  "metersConsumed": "10",
  "differenceOfUse": "95",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "76",
  "previousWaterMetering": "36",
  "currentWaterMetering": "40",
  "metersConsumed": "4",
  "differenceOfUse": "95",
  "total": "224",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "77",
  "previousWaterMetering": "631",
  "currentWaterMetering": "647",
  "metersConsumed": "16",
  "differenceOfUse": "95",
  "total": "503",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "78",
  "previousWaterMetering": "38",
  "currentWaterMetering": "39",
  "metersConsumed": "1",
  "differenceOfUse": "95",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "79",
  "previousWaterMetering": "307",
  "currentWaterMetering": "316",
  "metersConsumed": "9",
  "differenceOfUse": "95",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "80",
  "previousWaterMetering": "387",
  "currentWaterMetering": "397",
  "metersConsumed": "10",
  "differenceOfUse": "95",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "81",
  "previousWaterMetering": "73",
  "currentWaterMetering": "80",
  "metersConsumed": "7",
  "differenceOfUse": "95",
  "total": "280",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "82",
  "previousWaterMetering": "300",
  "currentWaterMetering": "311",
  "metersConsumed": "11",
  "differenceOfUse": "95",
  "total": "377",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "83",
  "previousWaterMetering": "189",
  "currentWaterMetering": "194",
  "metersConsumed": "5",
  "differenceOfUse": "95",
  "total": "241",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "84",
  "previousWaterMetering": "229",
  "currentWaterMetering": "234",
  "metersConsumed": "5",
  "differenceOfUse": "95",
  "total": "241",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "85",
  "previousWaterMetering": "222",
  "currentWaterMetering": "230",
  "metersConsumed": "8",
  "differenceOfUse": "95",
  "total": "300",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "86",
  "previousWaterMetering": "57",
  "currentWaterMetering": "68",
  "metersConsumed": "11",
  "differenceOfUse": "95",
  "total": "377",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "87",
  "previousWaterMetering": "192",
  "currentWaterMetering": "192",
  "metersConsumed": "0",
  "differenceOfUse": "95",
  "total": "158",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "88",
  "previousWaterMetering": "324",
  "currentWaterMetering": "333",
  "metersConsumed": "9",
  "differenceOfUse": "95",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "89",
  "previousWaterMetering": "570",
  "currentWaterMetering": "586",
  "metersConsumed": "16",
  "differenceOfUse": "95",
  "total": "503",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "90",
  "previousWaterMetering": "522",
  "currentWaterMetering": "547",
  "metersConsumed": "25",
  "differenceOfUse": "95",
  "total": "807",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "91",
  "previousWaterMetering": "284",
  "currentWaterMetering": "288",
  "metersConsumed": "4",
  "differenceOfUse": "95",
  "total": "224",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "92",
  "previousWaterMetering": "386",
  "currentWaterMetering": "400",
  "metersConsumed": "14",
  "differenceOfUse": "95",
  "total": "452",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "93",
  "previousWaterMetering": "188",
  "currentWaterMetering": "194",
  "metersConsumed": "6",
  "differenceOfUse": "95",
  "total": "260",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "94",
  "previousWaterMetering": "383",
  "currentWaterMetering": "392",
  "metersConsumed": "9",
  "differenceOfUse": "95",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "95",
  "previousWaterMetering": "63",
  "currentWaterMetering": "63",
  "metersConsumed": "0",
  "differenceOfUse": "95",
  "total": "158",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "96",
  "previousWaterMetering": "124",
  "currentWaterMetering": "126",
  "metersConsumed": "2",
  "differenceOfUse": "95",
  "total": "190",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "97",
  "previousWaterMetering": "174",
  "currentWaterMetering": "178",
  "metersConsumed": "4",
  "differenceOfUse": "95",
  "total": "224",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "98",
  "previousWaterMetering": "78",
  "currentWaterMetering": "80",
  "metersConsumed": "2",
  "differenceOfUse": "95",
  "total": "190",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "99",
  "previousWaterMetering": "217",
  "currentWaterMetering": "230",
  "metersConsumed": "13",
  "differenceOfUse": "95",
  "total": "427",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "95",
  "total": "158",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "101",
  "previousWaterMetering": "183",
  "currentWaterMetering": "188",
  "metersConsumed": "5",
  "differenceOfUse": "95",
  "total": "241",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "102",
  "previousWaterMetering": "117",
  "currentWaterMetering": "121",
  "metersConsumed": "4",
  "differenceOfUse": "95",
  "total": "224",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
},
{
  "houseId": "103",
  "previousWaterMetering": "6",
  "currentWaterMetering": "8",
  "metersConsumed": "2",
  "differenceOfUse": "95",
  "total": "190",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2025"
}]
;

export const reportShimul = data;
