
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =
[{
  "houseId": "1",
  "previousWaterMetering": "447",
  "currentWaterMetering": "460",
  "metersConsumed": "13",
  "differenceOfUse": "0",
  "total": "336",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "2",
  "previousWaterMetering": "146",
  "currentWaterMetering": "154",
  "metersConsumed": "8",
  "differenceOfUse": "0",
  "total": "208",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "3",
  "previousWaterMetering": "496",
  "currentWaterMetering": "510",
  "metersConsumed": "14",
  "differenceOfUse": "0",
  "total": "362",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "4",
  "previousWaterMetering": "408",
  "currentWaterMetering": "419",
  "metersConsumed": "11",
  "differenceOfUse": "0",
  "total": "285",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "5",
  "previousWaterMetering": "219",
  "currentWaterMetering": "226",
  "metersConsumed": "7",
  "differenceOfUse": "0",
  "total": "187",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "6",
  "previousWaterMetering": "354",
  "currentWaterMetering": "360",
  "metersConsumed": "6",
  "differenceOfUse": "0",
  "total": "167",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "7",
  "previousWaterMetering": "498",
  "currentWaterMetering": "512",
  "metersConsumed": "14",
  "differenceOfUse": "0",
  "total": "362",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "8",
  "previousWaterMetering": "207",
  "currentWaterMetering": "207",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "64",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "9",
  "previousWaterMetering": "249",
  "currentWaterMetering": "254",
  "metersConsumed": "5",
  "differenceOfUse": "0",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "10",
  "previousWaterMetering": "466",
  "currentWaterMetering": "476",
  "metersConsumed": "10",
  "differenceOfUse": "0",
  "total": "262",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "11",
  "previousWaterMetering": "626",
  "currentWaterMetering": "640",
  "metersConsumed": "14",
  "differenceOfUse": "0",
  "total": "362",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "12",
  "previousWaterMetering": "349",
  "currentWaterMetering": "360",
  "metersConsumed": "11",
  "differenceOfUse": "0",
  "total": "285",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "13",
  "previousWaterMetering": "248",
  "currentWaterMetering": "257",
  "metersConsumed": "9",
  "differenceOfUse": "0",
  "total": "239",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "14",
  "previousWaterMetering": "477",
  "currentWaterMetering": "490",
  "metersConsumed": "13",
  "differenceOfUse": "0",
  "total": "336",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "15",
  "previousWaterMetering": "218",
  "currentWaterMetering": "224",
  "metersConsumed": "6",
  "differenceOfUse": "0",
  "total": "167",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "16",
  "previousWaterMetering": "232",
  "currentWaterMetering": "238",
  "metersConsumed": "6",
  "differenceOfUse": "0",
  "total": "167",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "17",
  "previousWaterMetering": "298",
  "currentWaterMetering": "305",
  "metersConsumed": "7",
  "differenceOfUse": "0",
  "total": "187",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "18",
  "previousWaterMetering": "336",
  "currentWaterMetering": "341",
  "metersConsumed": "5",
  "differenceOfUse": "0",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "19",
  "previousWaterMetering": "76",
  "currentWaterMetering": "82",
  "metersConsumed": "6",
  "differenceOfUse": "0",
  "total": "167",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "20",
  "previousWaterMetering": "405",
  "currentWaterMetering": "425",
  "metersConsumed": "20",
  "differenceOfUse": "0",
  "total": "521",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "21",
  "previousWaterMetering": "352",
  "currentWaterMetering": "362",
  "metersConsumed": "10",
  "differenceOfUse": "0",
  "total": "262",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "22",
  "previousWaterMetering": "329",
  "currentWaterMetering": "336",
  "metersConsumed": "7",
  "differenceOfUse": "0",
  "total": "187",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "23",
  "previousWaterMetering": "661",
  "currentWaterMetering": "677",
  "metersConsumed": "16",
  "differenceOfUse": "0",
  "total": "413",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "24",
  "previousWaterMetering": "292",
  "currentWaterMetering": "300",
  "metersConsumed": "8",
  "differenceOfUse": "0",
  "total": "208",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "25",
  "previousWaterMetering": "201",
  "currentWaterMetering": "209",
  "metersConsumed": "8",
  "differenceOfUse": "0",
  "total": "208",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "26",
  "previousWaterMetering": "34",
  "currentWaterMetering": "34",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "48",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "27",
  "previousWaterMetering": "267",
  "currentWaterMetering": "272",
  "metersConsumed": "5",
  "differenceOfUse": "0",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "28",
  "previousWaterMetering": "42",
  "currentWaterMetering": "42",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "48",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "29",
  "previousWaterMetering": "188",
  "currentWaterMetering": "193",
  "metersConsumed": "5",
  "differenceOfUse": "0",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "30",
  "previousWaterMetering": "501",
  "currentWaterMetering": "511",
  "metersConsumed": "10",
  "differenceOfUse": "0",
  "total": "262",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "31",
  "previousWaterMetering": "330",
  "currentWaterMetering": "343",
  "metersConsumed": "13",
  "differenceOfUse": "0",
  "total": "336",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "32",
  "previousWaterMetering": "508",
  "currentWaterMetering": "523",
  "metersConsumed": "15",
  "differenceOfUse": "0",
  "total": "388",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "33",
  "previousWaterMetering": "146",
  "currentWaterMetering": "147",
  "metersConsumed": "1",
  "differenceOfUse": "0",
  "total": "80",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "34",
  "previousWaterMetering": "455",
  "currentWaterMetering": "467",
  "metersConsumed": "12",
  "differenceOfUse": "0",
  "total": "309",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "35",
  "previousWaterMetering": "680",
  "currentWaterMetering": "699",
  "metersConsumed": "19",
  "differenceOfUse": "0",
  "total": "494",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "36",
  "previousWaterMetering": "426",
  "currentWaterMetering": "436",
  "metersConsumed": "10",
  "differenceOfUse": "0",
  "total": "262",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "37",
  "previousWaterMetering": "282",
  "currentWaterMetering": "289",
  "metersConsumed": "7",
  "differenceOfUse": "0",
  "total": "187",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "38",
  "previousWaterMetering": "445",
  "currentWaterMetering": "455",
  "metersConsumed": "10",
  "differenceOfUse": "0",
  "total": "262",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "39",
  "previousWaterMetering": "289",
  "currentWaterMetering": "293",
  "metersConsumed": "4",
  "differenceOfUse": "0",
  "total": "130",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "40",
  "previousWaterMetering": "97",
  "currentWaterMetering": "97",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "64",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "41",
  "previousWaterMetering": "591",
  "currentWaterMetering": "598",
  "metersConsumed": "7",
  "differenceOfUse": "0",
  "total": "187",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "42",
  "previousWaterMetering": "540",
  "currentWaterMetering": "556",
  "metersConsumed": "16",
  "differenceOfUse": "0",
  "total": "413",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "43",
  "previousWaterMetering": "197",
  "currentWaterMetering": "199",
  "metersConsumed": "2",
  "differenceOfUse": "0",
  "total": "96",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "44",
  "previousWaterMetering": "108",
  "currentWaterMetering": "112",
  "metersConsumed": "4",
  "differenceOfUse": "0",
  "total": "130",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "45",
  "previousWaterMetering": "597",
  "currentWaterMetering": "606",
  "metersConsumed": "9",
  "differenceOfUse": "0",
  "total": "239",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "46",
  "previousWaterMetering": "213",
  "currentWaterMetering": "218",
  "metersConsumed": "5",
  "differenceOfUse": "0",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "47",
  "previousWaterMetering": "534",
  "currentWaterMetering": "546",
  "metersConsumed": "12",
  "differenceOfUse": "0",
  "total": "309",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "48",
  "previousWaterMetering": "211",
  "currentWaterMetering": "218",
  "metersConsumed": "7",
  "differenceOfUse": "0",
  "total": "187",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "49",
  "previousWaterMetering": "407",
  "currentWaterMetering": "418",
  "metersConsumed": "11",
  "differenceOfUse": "0",
  "total": "285",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "50",
  "previousWaterMetering": "339",
  "currentWaterMetering": "550",
  "metersConsumed": "211",
  "differenceOfUse": "0",
  "total": "9456",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "51",
  "previousWaterMetering": "101",
  "currentWaterMetering": "103",
  "metersConsumed": "2",
  "differenceOfUse": "0",
  "total": "96",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "52",
  "previousWaterMetering": "319",
  "currentWaterMetering": "323",
  "metersConsumed": "4",
  "differenceOfUse": "0",
  "total": "130",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "53",
  "previousWaterMetering": "141",
  "currentWaterMetering": "144",
  "metersConsumed": "3",
  "differenceOfUse": "0",
  "total": "113",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "54",
  "previousWaterMetering": "484",
  "currentWaterMetering": "494",
  "metersConsumed": "10",
  "differenceOfUse": "0",
  "total": "262",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "48",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "56",
  "previousWaterMetering": "7",
  "currentWaterMetering": "7",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "48",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "57",
  "previousWaterMetering": "638",
  "currentWaterMetering": "652",
  "metersConsumed": "14",
  "differenceOfUse": "0",
  "total": "362",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "58",
  "previousWaterMetering": "410",
  "currentWaterMetering": "414",
  "metersConsumed": "4",
  "differenceOfUse": "0",
  "total": "130",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "59",
  "previousWaterMetering": "280",
  "currentWaterMetering": "290",
  "metersConsumed": "10",
  "differenceOfUse": "0",
  "total": "262",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "60",
  "previousWaterMetering": "321",
  "currentWaterMetering": "331",
  "metersConsumed": "10",
  "differenceOfUse": "0",
  "total": "262",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "61",
  "previousWaterMetering": "91",
  "currentWaterMetering": "92",
  "metersConsumed": "1",
  "differenceOfUse": "0",
  "total": "80",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "62",
  "previousWaterMetering": "269",
  "currentWaterMetering": "296",
  "metersConsumed": "27",
  "differenceOfUse": "0",
  "total": "837",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "63",
  "previousWaterMetering": "689",
  "currentWaterMetering": "705",
  "metersConsumed": "16",
  "differenceOfUse": "0",
  "total": "413",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "64",
  "previousWaterMetering": "189",
  "currentWaterMetering": "195",
  "metersConsumed": "6",
  "differenceOfUse": "0",
  "total": "151",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "65",
  "previousWaterMetering": "739",
  "currentWaterMetering": "749",
  "metersConsumed": "10",
  "differenceOfUse": "0",
  "total": "262",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "66",
  "previousWaterMetering": "148",
  "currentWaterMetering": "150",
  "metersConsumed": "2",
  "differenceOfUse": "0",
  "total": "96",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "67",
  "previousWaterMetering": "264",
  "currentWaterMetering": "271",
  "metersConsumed": "7",
  "differenceOfUse": "0",
  "total": "187",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "48",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "69",
  "previousWaterMetering": "472",
  "currentWaterMetering": "485",
  "metersConsumed": "13",
  "differenceOfUse": "0",
  "total": "336",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "70",
  "previousWaterMetering": "117",
  "currentWaterMetering": "123",
  "metersConsumed": "6",
  "differenceOfUse": "0",
  "total": "167",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "71",
  "previousWaterMetering": "290",
  "currentWaterMetering": "298",
  "metersConsumed": "8",
  "differenceOfUse": "0",
  "total": "208",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "72",
  "previousWaterMetering": "253",
  "currentWaterMetering": "260",
  "metersConsumed": "7",
  "differenceOfUse": "0",
  "total": "187",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "73",
  "previousWaterMetering": "222",
  "currentWaterMetering": "226",
  "metersConsumed": "4",
  "differenceOfUse": "0",
  "total": "130",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "74",
  "previousWaterMetering": "135",
  "currentWaterMetering": "139",
  "metersConsumed": "4",
  "differenceOfUse": "0",
  "total": "130",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "75",
  "previousWaterMetering": "431",
  "currentWaterMetering": "439",
  "metersConsumed": "8",
  "differenceOfUse": "0",
  "total": "208",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "76",
  "previousWaterMetering": "41",
  "currentWaterMetering": "41",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "64",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "77",
  "previousWaterMetering": "715",
  "currentWaterMetering": "734",
  "metersConsumed": "19",
  "differenceOfUse": "0",
  "total": "494",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "78",
  "previousWaterMetering": "45",
  "currentWaterMetering": "45",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "64",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "79",
  "previousWaterMetering": "352",
  "currentWaterMetering": "361",
  "metersConsumed": "9",
  "differenceOfUse": "0",
  "total": "239",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "80",
  "previousWaterMetering": "447",
  "currentWaterMetering": "464",
  "metersConsumed": "17",
  "differenceOfUse": "0",
  "total": "440",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "81",
  "previousWaterMetering": "113",
  "currentWaterMetering": "129",
  "metersConsumed": "16",
  "differenceOfUse": "0",
  "total": "413",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "82",
  "previousWaterMetering": "358",
  "currentWaterMetering": "362",
  "metersConsumed": "4",
  "differenceOfUse": "0",
  "total": "130",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "83",
  "previousWaterMetering": "216",
  "currentWaterMetering": "220",
  "metersConsumed": "4",
  "differenceOfUse": "0",
  "total": "130",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "84",
  "previousWaterMetering": "260",
  "currentWaterMetering": "265",
  "metersConsumed": "5",
  "differenceOfUse": "0",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "85",
  "previousWaterMetering": "267",
  "currentWaterMetering": "275",
  "metersConsumed": "8",
  "differenceOfUse": "0",
  "total": "208",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "86",
  "previousWaterMetering": "114",
  "currentWaterMetering": "122",
  "metersConsumed": "8",
  "differenceOfUse": "0",
  "total": "208",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "87",
  "previousWaterMetering": "254",
  "currentWaterMetering": "271",
  "metersConsumed": "17",
  "differenceOfUse": "0",
  "total": "440",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "88",
  "previousWaterMetering": "366",
  "currentWaterMetering": "373",
  "metersConsumed": "7",
  "differenceOfUse": "0",
  "total": "187",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "89",
  "previousWaterMetering": "653",
  "currentWaterMetering": "668",
  "metersConsumed": "15",
  "differenceOfUse": "0",
  "total": "388",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "90",
  "previousWaterMetering": "658",
  "currentWaterMetering": "685",
  "metersConsumed": "27",
  "differenceOfUse": "0",
  "total": "837",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "91",
  "previousWaterMetering": "314",
  "currentWaterMetering": "323",
  "metersConsumed": "9",
  "differenceOfUse": "0",
  "total": "239",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "92",
  "previousWaterMetering": "452",
  "currentWaterMetering": "461",
  "metersConsumed": "9",
  "differenceOfUse": "0",
  "total": "239",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "93",
  "previousWaterMetering": "222",
  "currentWaterMetering": "231",
  "metersConsumed": "9",
  "differenceOfUse": "0",
  "total": "239",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "94",
  "previousWaterMetering": "451",
  "currentWaterMetering": "459",
  "metersConsumed": "8",
  "differenceOfUse": "0",
  "total": "208",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "95",
  "previousWaterMetering": "64",
  "currentWaterMetering": "64",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "48",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "96",
  "previousWaterMetering": "143",
  "currentWaterMetering": "147",
  "metersConsumed": "4",
  "differenceOfUse": "0",
  "total": "130",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "97",
  "previousWaterMetering": "191",
  "currentWaterMetering": "197",
  "metersConsumed": "6",
  "differenceOfUse": "0",
  "total": "167",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "98",
  "previousWaterMetering": "97",
  "currentWaterMetering": "100",
  "metersConsumed": "3",
  "differenceOfUse": "0",
  "total": "113",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "99",
  "previousWaterMetering": "233",
  "currentWaterMetering": "233",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "48",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "48",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "101",
  "previousWaterMetering": "207",
  "currentWaterMetering": "212",
  "metersConsumed": "5",
  "differenceOfUse": "0",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "102",
  "previousWaterMetering": "138",
  "currentWaterMetering": "141",
  "metersConsumed": "3",
  "differenceOfUse": "0",
  "total": "113",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
},
{
  "houseId": "103",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "48",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Junio",
  "paymentMonth": "Agosto",
  "year": "2025"
}]
;

export const reportShimul = data;
