
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =

[{
  "houseId": "1",
  "previousWaterMetering": "355",
  "currentWaterMetering": "366",
  "metersConsumed": "11",
  "differenceOfUse": "98",
  "total": "376",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "2",
  "previousWaterMetering": "93",
  "currentWaterMetering": "98",
  "metersConsumed": "5",
  "differenceOfUse": "98",
  "total": "243",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "3",
  "previousWaterMetering": "406",
  "currentWaterMetering": "420",
  "metersConsumed": "14",
  "differenceOfUse": "98",
  "total": "451",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "4",
  "previousWaterMetering": "314",
  "currentWaterMetering": "334",
  "metersConsumed": "20",
  "differenceOfUse": "98",
  "total": "607",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "5",
  "previousWaterMetering": "175",
  "currentWaterMetering": "181",
  "metersConsumed": "6",
  "differenceOfUse": "98",
  "total": "261",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "6",
  "previousWaterMetering": "296",
  "currentWaterMetering": "304",
  "metersConsumed": "8",
  "differenceOfUse": "98",
  "total": "301",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "7",
  "previousWaterMetering": "424",
  "currentWaterMetering": "433",
  "metersConsumed": "9",
  "differenceOfUse": "98",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "8",
  "previousWaterMetering": "101",
  "currentWaterMetering": "107",
  "metersConsumed": "6",
  "differenceOfUse": "98",
  "total": "261",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "9",
  "previousWaterMetering": "211",
  "currentWaterMetering": "216",
  "metersConsumed": "5",
  "differenceOfUse": "98",
  "total": "243",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "10",
  "previousWaterMetering": "398",
  "currentWaterMetering": "406",
  "metersConsumed": "8",
  "differenceOfUse": "98",
  "total": "301",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "11",
  "previousWaterMetering": "518",
  "currentWaterMetering": "533",
  "metersConsumed": "15",
  "differenceOfUse": "98",
  "total": "476",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "12",
  "previousWaterMetering": "288",
  "currentWaterMetering": "296",
  "metersConsumed": "8",
  "differenceOfUse": "98",
  "total": "301",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "13",
  "previousWaterMetering": "216",
  "currentWaterMetering": "218",
  "metersConsumed": "2",
  "differenceOfUse": "98",
  "total": "192",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "14",
  "previousWaterMetering": "392",
  "currentWaterMetering": "404",
  "metersConsumed": "12",
  "differenceOfUse": "98",
  "total": "399",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "15",
  "previousWaterMetering": "206",
  "currentWaterMetering": "207",
  "metersConsumed": "1",
  "differenceOfUse": "98",
  "total": "176",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "16",
  "previousWaterMetering": "184",
  "currentWaterMetering": "190",
  "metersConsumed": "6",
  "differenceOfUse": "98",
  "total": "261",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "17",
  "previousWaterMetering": "240",
  "currentWaterMetering": "250",
  "metersConsumed": "10",
  "differenceOfUse": "98",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "18",
  "previousWaterMetering": "292",
  "currentWaterMetering": "298",
  "metersConsumed": "6",
  "differenceOfUse": "98",
  "total": "261",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "19",
  "previousWaterMetering": "33",
  "currentWaterMetering": "37",
  "metersConsumed": "4",
  "differenceOfUse": "98",
  "total": "225",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "20",
  "previousWaterMetering": "265",
  "currentWaterMetering": "277",
  "metersConsumed": "12",
  "differenceOfUse": "98",
  "total": "399",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "21",
  "previousWaterMetering": "276",
  "currentWaterMetering": "284",
  "metersConsumed": "8",
  "differenceOfUse": "98",
  "total": "301",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "22",
  "previousWaterMetering": "279",
  "currentWaterMetering": "287",
  "metersConsumed": "8",
  "differenceOfUse": "98",
  "total": "301",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "23",
  "previousWaterMetering": "548",
  "currentWaterMetering": "564",
  "metersConsumed": "16",
  "differenceOfUse": "98",
  "total": "501",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "24",
  "previousWaterMetering": "247",
  "currentWaterMetering": "257",
  "metersConsumed": "10",
  "differenceOfUse": "98",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "25",
  "previousWaterMetering": "157",
  "currentWaterMetering": "162",
  "metersConsumed": "5",
  "differenceOfUse": "98",
  "total": "243",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "26",
  "previousWaterMetering": "34",
  "currentWaterMetering": "34",
  "metersConsumed": "0",
  "differenceOfUse": "98",
  "total": "161",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "27",
  "previousWaterMetering": "213",
  "currentWaterMetering": "226",
  "metersConsumed": "13",
  "differenceOfUse": "98",
  "total": "426",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "28",
  "previousWaterMetering": "42",
  "currentWaterMetering": "42",
  "metersConsumed": "0",
  "differenceOfUse": "98",
  "total": "161",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "29",
  "previousWaterMetering": "137",
  "currentWaterMetering": "143",
  "metersConsumed": "6",
  "differenceOfUse": "98",
  "total": "261",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "30",
  "previousWaterMetering": "423",
  "currentWaterMetering": "435",
  "metersConsumed": "12",
  "differenceOfUse": "98",
  "total": "399",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "31",
  "previousWaterMetering": "263",
  "currentWaterMetering": "270",
  "metersConsumed": "7",
  "differenceOfUse": "98",
  "total": "281",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "32",
  "previousWaterMetering": "418",
  "currentWaterMetering": "431",
  "metersConsumed": "13",
  "differenceOfUse": "98",
  "total": "426",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "33",
  "previousWaterMetering": "136",
  "currentWaterMetering": "137",
  "metersConsumed": "1",
  "differenceOfUse": "98",
  "total": "176",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "34",
  "previousWaterMetering": "377",
  "currentWaterMetering": "394",
  "metersConsumed": "17",
  "differenceOfUse": "98",
  "total": "528",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "35",
  "previousWaterMetering": "545",
  "currentWaterMetering": "563",
  "metersConsumed": "18",
  "differenceOfUse": "98",
  "total": "553",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "36",
  "previousWaterMetering": "336",
  "currentWaterMetering": "347",
  "metersConsumed": "11",
  "differenceOfUse": "98",
  "total": "376",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "37",
  "previousWaterMetering": "222",
  "currentWaterMetering": "233",
  "metersConsumed": "11",
  "differenceOfUse": "98",
  "total": "376",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "38",
  "previousWaterMetering": "404",
  "currentWaterMetering": "409",
  "metersConsumed": "5",
  "differenceOfUse": "98",
  "total": "243",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "39",
  "previousWaterMetering": "250",
  "currentWaterMetering": "251",
  "metersConsumed": "1",
  "differenceOfUse": "98",
  "total": "176",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "40",
  "previousWaterMetering": "89",
  "currentWaterMetering": "90",
  "metersConsumed": "1",
  "differenceOfUse": "98",
  "total": "176",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "41",
  "previousWaterMetering": "506",
  "currentWaterMetering": "519",
  "metersConsumed": "13",
  "differenceOfUse": "98",
  "total": "426",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "42",
  "previousWaterMetering": "434",
  "currentWaterMetering": "449",
  "metersConsumed": "15",
  "differenceOfUse": "98",
  "total": "476",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "43",
  "previousWaterMetering": "185",
  "currentWaterMetering": "186",
  "metersConsumed": "1",
  "differenceOfUse": "98",
  "total": "176",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "44",
  "previousWaterMetering": "82",
  "currentWaterMetering": "85",
  "metersConsumed": "3",
  "differenceOfUse": "98",
  "total": "208",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "45",
  "previousWaterMetering": "499",
  "currentWaterMetering": "510",
  "metersConsumed": "11",
  "differenceOfUse": "98",
  "total": "376",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "46",
  "previousWaterMetering": "176",
  "currentWaterMetering": "182",
  "metersConsumed": "6",
  "differenceOfUse": "98",
  "total": "261",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "47",
  "previousWaterMetering": "489",
  "currentWaterMetering": "500",
  "metersConsumed": "11",
  "differenceOfUse": "98",
  "total": "376",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "48",
  "previousWaterMetering": "156",
  "currentWaterMetering": "163",
  "metersConsumed": "7",
  "differenceOfUse": "98",
  "total": "281",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "49",
  "previousWaterMetering": "330",
  "currentWaterMetering": "340",
  "metersConsumed": "10",
  "differenceOfUse": "98",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "50",
  "previousWaterMetering": "156",
  "currentWaterMetering": "162",
  "metersConsumed": "6",
  "differenceOfUse": "98",
  "total": "261",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "51",
  "previousWaterMetering": "81",
  "currentWaterMetering": "84",
  "metersConsumed": "3",
  "differenceOfUse": "98",
  "total": "208",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "52",
  "previousWaterMetering": "275",
  "currentWaterMetering": "281",
  "metersConsumed": "6",
  "differenceOfUse": "98",
  "total": "261",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "53",
  "previousWaterMetering": "116",
  "currentWaterMetering": "118",
  "metersConsumed": "2",
  "differenceOfUse": "98",
  "total": "192",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "54",
  "previousWaterMetering": "405",
  "currentWaterMetering": "416",
  "metersConsumed": "11",
  "differenceOfUse": "98",
  "total": "376",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "98",
  "total": "161",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "56",
  "previousWaterMetering": "5",
  "currentWaterMetering": "5",
  "metersConsumed": "0",
  "differenceOfUse": "98",
  "total": "161",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "57",
  "previousWaterMetering": "595",
  "currentWaterMetering": "600",
  "metersConsumed": "5",
  "differenceOfUse": "98",
  "total": "243",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "58",
  "previousWaterMetering": "365",
  "currentWaterMetering": "370",
  "metersConsumed": "5",
  "differenceOfUse": "98",
  "total": "243",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "59",
  "previousWaterMetering": "200",
  "currentWaterMetering": "209",
  "metersConsumed": "9",
  "differenceOfUse": "98",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "60",
  "previousWaterMetering": "253",
  "currentWaterMetering": "262",
  "metersConsumed": "9",
  "differenceOfUse": "98",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "61",
  "previousWaterMetering": "78",
  "currentWaterMetering": "80",
  "metersConsumed": "2",
  "differenceOfUse": "98",
  "total": "192",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "62",
  "previousWaterMetering": "212",
  "currentWaterMetering": "219",
  "metersConsumed": "7",
  "differenceOfUse": "98",
  "total": "281",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "63",
  "previousWaterMetering": "556",
  "currentWaterMetering": "575",
  "metersConsumed": "19",
  "differenceOfUse": "98",
  "total": "580",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "64",
  "previousWaterMetering": "159",
  "currentWaterMetering": "165",
  "metersConsumed": "6",
  "differenceOfUse": "98",
  "total": "261",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "65",
  "previousWaterMetering": "638",
  "currentWaterMetering": "655",
  "metersConsumed": "17",
  "differenceOfUse": "98",
  "total": "528",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "66",
  "previousWaterMetering": "130",
  "currentWaterMetering": "133",
  "metersConsumed": "3",
  "differenceOfUse": "98",
  "total": "208",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "67",
  "previousWaterMetering": "212",
  "currentWaterMetering": "219",
  "metersConsumed": "7",
  "differenceOfUse": "98",
  "total": "281",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "98",
  "total": "161",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "69",
  "previousWaterMetering": "380",
  "currentWaterMetering": "392",
  "metersConsumed": "12",
  "differenceOfUse": "98",
  "total": "399",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "70",
  "previousWaterMetering": "74",
  "currentWaterMetering": "79",
  "metersConsumed": "5",
  "differenceOfUse": "98",
  "total": "243",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "71",
  "previousWaterMetering": "232",
  "currentWaterMetering": "239",
  "metersConsumed": "7",
  "differenceOfUse": "98",
  "total": "281",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "72",
  "previousWaterMetering": "201",
  "currentWaterMetering": "208",
  "metersConsumed": "7",
  "differenceOfUse": "98",
  "total": "281",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "73",
  "previousWaterMetering": "178",
  "currentWaterMetering": "184",
  "metersConsumed": "6",
  "differenceOfUse": "98",
  "total": "261",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "74",
  "previousWaterMetering": "110",
  "currentWaterMetering": "113",
  "metersConsumed": "3",
  "differenceOfUse": "98",
  "total": "208",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "75",
  "previousWaterMetering": "351",
  "currentWaterMetering": "361",
  "metersConsumed": "10",
  "differenceOfUse": "98",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "76",
  "previousWaterMetering": "28",
  "currentWaterMetering": "32",
  "metersConsumed": "4",
  "differenceOfUse": "98",
  "total": "225",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "77",
  "previousWaterMetering": "592",
  "currentWaterMetering": "612",
  "metersConsumed": "20",
  "differenceOfUse": "98",
  "total": "607",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "78",
  "previousWaterMetering": "36",
  "currentWaterMetering": "37",
  "metersConsumed": "1",
  "differenceOfUse": "98",
  "total": "176",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "79",
  "previousWaterMetering": "284",
  "currentWaterMetering": "294",
  "metersConsumed": "10",
  "differenceOfUse": "98",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "80",
  "previousWaterMetering": "364",
  "currentWaterMetering": "372",
  "metersConsumed": "8",
  "differenceOfUse": "98",
  "total": "301",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "81",
  "previousWaterMetering": "61",
  "currentWaterMetering": "65",
  "metersConsumed": "4",
  "differenceOfUse": "98",
  "total": "225",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "82",
  "previousWaterMetering": "277",
  "currentWaterMetering": "289",
  "metersConsumed": "12",
  "differenceOfUse": "98",
  "total": "399",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "83",
  "previousWaterMetering": "181",
  "currentWaterMetering": "185",
  "metersConsumed": "4",
  "differenceOfUse": "98",
  "total": "225",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "84",
  "previousWaterMetering": "218",
  "currentWaterMetering": "225",
  "metersConsumed": "7",
  "differenceOfUse": "98",
  "total": "281",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "85",
  "previousWaterMetering": "206",
  "currentWaterMetering": "213",
  "metersConsumed": "7",
  "differenceOfUse": "98",
  "total": "281",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "86",
  "previousWaterMetering": "34",
  "currentWaterMetering": "44",
  "metersConsumed": "10",
  "differenceOfUse": "98",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "87",
  "previousWaterMetering": "181",
  "currentWaterMetering": "189",
  "metersConsumed": "8",
  "differenceOfUse": "98",
  "total": "301",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "88",
  "previousWaterMetering": "308",
  "currentWaterMetering": "316",
  "metersConsumed": "8",
  "differenceOfUse": "98",
  "total": "301",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "89",
  "previousWaterMetering": "542",
  "currentWaterMetering": "557",
  "metersConsumed": "15",
  "differenceOfUse": "98",
  "total": "476",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "90",
  "previousWaterMetering": "471",
  "currentWaterMetering": "495",
  "metersConsumed": "24",
  "differenceOfUse": "98",
  "total": "744",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "91",
  "previousWaterMetering": "253",
  "currentWaterMetering": "272",
  "metersConsumed": "19",
  "differenceOfUse": "98",
  "total": "580",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "92",
  "previousWaterMetering": "369",
  "currentWaterMetering": "379",
  "metersConsumed": "10",
  "differenceOfUse": "98",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "93",
  "previousWaterMetering": "176",
  "currentWaterMetering": "181",
  "metersConsumed": "5",
  "differenceOfUse": "98",
  "total": "243",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "94",
  "previousWaterMetering": "362",
  "currentWaterMetering": "372",
  "metersConsumed": "10",
  "differenceOfUse": "98",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "95",
  "previousWaterMetering": "63",
  "currentWaterMetering": "63",
  "metersConsumed": "0",
  "differenceOfUse": "98",
  "total": "161",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "96",
  "previousWaterMetering": "118",
  "currentWaterMetering": "123",
  "metersConsumed": "5",
  "differenceOfUse": "98",
  "total": "243",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "97",
  "previousWaterMetering": "167",
  "currentWaterMetering": "170",
  "metersConsumed": "3",
  "differenceOfUse": "98",
  "total": "208",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "98",
  "previousWaterMetering": "75",
  "currentWaterMetering": "75",
  "metersConsumed": "0",
  "differenceOfUse": "98",
  "total": "161",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "99",
  "previousWaterMetering": "207",
  "currentWaterMetering": "209",
  "metersConsumed": "2",
  "differenceOfUse": "98",
  "total": "192",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "98",
  "total": "161",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "101",
  "previousWaterMetering": "175",
  "currentWaterMetering": "179",
  "metersConsumed": "4",
  "differenceOfUse": "98",
  "total": "225",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "102",
  "previousWaterMetering": "110",
  "currentWaterMetering": "113",
  "metersConsumed": "3",
  "differenceOfUse": "98",
  "total": "208",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
},
{
  "houseId": "103",
  "previousWaterMetering": "6",
  "currentWaterMetering": "6",
  "metersConsumed": "0",
  "differenceOfUse": "98",
  "total": "161",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2025"
}];

export const reportShimul = data;
