
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =
[{
  "houseId": "1",
  "previousWaterMetering": "405",
  "currentWaterMetering": "420",
  "metersConsumed": "15",
  "differenceOfUse": "16",
  "total": "399",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "2",
  "previousWaterMetering": "119",
  "currentWaterMetering": "131",
  "metersConsumed": "12",
  "differenceOfUse": "16",
  "total": "321",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "3",
  "previousWaterMetering": "458",
  "currentWaterMetering": "471",
  "metersConsumed": "13",
  "differenceOfUse": "16",
  "total": "348",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "4",
  "previousWaterMetering": "383",
  "currentWaterMetering": "393",
  "metersConsumed": "10",
  "differenceOfUse": "16",
  "total": "275",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "5",
  "previousWaterMetering": "198",
  "currentWaterMetering": "206",
  "metersConsumed": "8",
  "differenceOfUse": "16",
  "total": "221",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "6",
  "previousWaterMetering": "329",
  "currentWaterMetering": "339",
  "metersConsumed": "10",
  "differenceOfUse": "16",
  "total": "275",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "7",
  "previousWaterMetering": "464",
  "currentWaterMetering": "476",
  "metersConsumed": "12",
  "differenceOfUse": "16",
  "total": "321",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "8",
  "previousWaterMetering": "108",
  "currentWaterMetering": "108",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "79",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "9",
  "previousWaterMetering": "235",
  "currentWaterMetering": "240",
  "metersConsumed": "5",
  "differenceOfUse": "16",
  "total": "162",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "10",
  "previousWaterMetering": "432",
  "currentWaterMetering": "446",
  "metersConsumed": "14",
  "differenceOfUse": "16",
  "total": "373",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "11",
  "previousWaterMetering": "575",
  "currentWaterMetering": "592",
  "metersConsumed": "17",
  "differenceOfUse": "16",
  "total": "451",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "12",
  "previousWaterMetering": "319",
  "currentWaterMetering": "328",
  "metersConsumed": "9",
  "differenceOfUse": "16",
  "total": "252",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "13",
  "previousWaterMetering": "230",
  "currentWaterMetering": "241",
  "metersConsumed": "11",
  "differenceOfUse": "16",
  "total": "298",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "14",
  "previousWaterMetering": "451",
  "currentWaterMetering": "460",
  "metersConsumed": "9",
  "differenceOfUse": "16",
  "total": "252",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "15",
  "previousWaterMetering": "215",
  "currentWaterMetering": "216",
  "metersConsumed": "1",
  "differenceOfUse": "16",
  "total": "95",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "16",
  "previousWaterMetering": "206",
  "currentWaterMetering": "211",
  "metersConsumed": "5",
  "differenceOfUse": "16",
  "total": "162",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "17",
  "previousWaterMetering": "275",
  "currentWaterMetering": "283",
  "metersConsumed": "8",
  "differenceOfUse": "16",
  "total": "221",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "18",
  "previousWaterMetering": "316",
  "currentWaterMetering": "322",
  "metersConsumed": "6",
  "differenceOfUse": "16",
  "total": "181",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "19",
  "previousWaterMetering": "57",
  "currentWaterMetering": "63",
  "metersConsumed": "6",
  "differenceOfUse": "16",
  "total": "181",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "20",
  "previousWaterMetering": "329",
  "currentWaterMetering": "360",
  "metersConsumed": "31",
  "differenceOfUse": "16",
  "total": "1108",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "21",
  "previousWaterMetering": "314",
  "currentWaterMetering": "323",
  "metersConsumed": "9",
  "differenceOfUse": "16",
  "total": "252",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "22",
  "previousWaterMetering": "308",
  "currentWaterMetering": "315",
  "metersConsumed": "7",
  "differenceOfUse": "16",
  "total": "201",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "23",
  "previousWaterMetering": "609",
  "currentWaterMetering": "627",
  "metersConsumed": "18",
  "differenceOfUse": "16",
  "total": "477",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "24",
  "previousWaterMetering": "273",
  "currentWaterMetering": "273",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "79",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "25",
  "previousWaterMetering": "181",
  "currentWaterMetering": "187",
  "metersConsumed": "6",
  "differenceOfUse": "16",
  "total": "181",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "26",
  "previousWaterMetering": "34",
  "currentWaterMetering": "34",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "79",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "27",
  "previousWaterMetering": "248",
  "currentWaterMetering": "254",
  "metersConsumed": "6",
  "differenceOfUse": "16",
  "total": "181",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "28",
  "previousWaterMetering": "42",
  "currentWaterMetering": "42",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "79",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "29",
  "previousWaterMetering": "167",
  "currentWaterMetering": "178",
  "metersConsumed": "11",
  "differenceOfUse": "16",
  "total": "298",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "30",
  "previousWaterMetering": "462",
  "currentWaterMetering": "476",
  "metersConsumed": "14",
  "differenceOfUse": "16",
  "total": "373",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "31",
  "previousWaterMetering": "300",
  "currentWaterMetering": "309",
  "metersConsumed": "9",
  "differenceOfUse": "16",
  "total": "252",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "32",
  "previousWaterMetering": "469",
  "currentWaterMetering": "482",
  "metersConsumed": "13",
  "differenceOfUse": "16",
  "total": "348",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "33",
  "previousWaterMetering": "142",
  "currentWaterMetering": "144",
  "metersConsumed": "2",
  "differenceOfUse": "16",
  "total": "111",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "34",
  "previousWaterMetering": "421",
  "currentWaterMetering": "434",
  "metersConsumed": "13",
  "differenceOfUse": "16",
  "total": "348",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "35",
  "previousWaterMetering": "621",
  "currentWaterMetering": "640",
  "metersConsumed": "19",
  "differenceOfUse": "16",
  "total": "504",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "36",
  "previousWaterMetering": "393",
  "currentWaterMetering": "402",
  "metersConsumed": "9",
  "differenceOfUse": "16",
  "total": "252",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "37",
  "previousWaterMetering": "258",
  "currentWaterMetering": "267",
  "metersConsumed": "9",
  "differenceOfUse": "16",
  "total": "252",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "38",
  "previousWaterMetering": "431",
  "currentWaterMetering": "437",
  "metersConsumed": "6",
  "differenceOfUse": "16",
  "total": "181",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "39",
  "previousWaterMetering": "270",
  "currentWaterMetering": "277",
  "metersConsumed": "7",
  "differenceOfUse": "16",
  "total": "201",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "40",
  "previousWaterMetering": "94",
  "currentWaterMetering": "94",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "79",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "41",
  "previousWaterMetering": "552",
  "currentWaterMetering": "566",
  "metersConsumed": "14",
  "differenceOfUse": "16",
  "total": "373",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "42",
  "previousWaterMetering": "490",
  "currentWaterMetering": "506",
  "metersConsumed": "16",
  "differenceOfUse": "16",
  "total": "424",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "43",
  "previousWaterMetering": "191",
  "currentWaterMetering": "193",
  "metersConsumed": "2",
  "differenceOfUse": "16",
  "total": "111",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "44",
  "previousWaterMetering": "92",
  "currentWaterMetering": "98",
  "metersConsumed": "6",
  "differenceOfUse": "16",
  "total": "181",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "45",
  "previousWaterMetering": "556",
  "currentWaterMetering": "572",
  "metersConsumed": "16",
  "differenceOfUse": "16",
  "total": "424",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "46",
  "previousWaterMetering": "197",
  "currentWaterMetering": "203",
  "metersConsumed": "6",
  "differenceOfUse": "16",
  "total": "181",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "47",
  "previousWaterMetering": "514",
  "currentWaterMetering": "521",
  "metersConsumed": "7",
  "differenceOfUse": "16",
  "total": "201",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "48",
  "previousWaterMetering": "185",
  "currentWaterMetering": "191",
  "metersConsumed": "6",
  "differenceOfUse": "16",
  "total": "181",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "49",
  "previousWaterMetering": "374",
  "currentWaterMetering": "385",
  "metersConsumed": "11",
  "differenceOfUse": "16",
  "total": "298",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "50",
  "previousWaterMetering": "186",
  "currentWaterMetering": "200",
  "metersConsumed": "14",
  "differenceOfUse": "16",
  "total": "373",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "51",
  "previousWaterMetering": "91",
  "currentWaterMetering": "94",
  "metersConsumed": "3",
  "differenceOfUse": "16",
  "total": "128",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "52",
  "previousWaterMetering": "300",
  "currentWaterMetering": "306",
  "metersConsumed": "6",
  "differenceOfUse": "16",
  "total": "181",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "53",
  "previousWaterMetering": "129",
  "currentWaterMetering": "134",
  "metersConsumed": "5",
  "differenceOfUse": "16",
  "total": "162",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "54",
  "previousWaterMetering": "449",
  "currentWaterMetering": "460",
  "metersConsumed": "11",
  "differenceOfUse": "16",
  "total": "298",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "79",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "56",
  "previousWaterMetering": "6",
  "currentWaterMetering": "6",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "79",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "57",
  "previousWaterMetering": "607",
  "currentWaterMetering": "607",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "79",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "58",
  "previousWaterMetering": "389",
  "currentWaterMetering": "397",
  "metersConsumed": "8",
  "differenceOfUse": "16",
  "total": "221",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "59",
  "previousWaterMetering": "247",
  "currentWaterMetering": "259",
  "metersConsumed": "12",
  "differenceOfUse": "16",
  "total": "321",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "60",
  "previousWaterMetering": "291",
  "currentWaterMetering": "302",
  "metersConsumed": "11",
  "differenceOfUse": "16",
  "total": "298",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "61",
  "previousWaterMetering": "84",
  "currentWaterMetering": "86",
  "metersConsumed": "2",
  "differenceOfUse": "16",
  "total": "111",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "62",
  "previousWaterMetering": "242",
  "currentWaterMetering": "247",
  "metersConsumed": "5",
  "differenceOfUse": "16",
  "total": "162",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "63",
  "previousWaterMetering": "634",
  "currentWaterMetering": "652",
  "metersConsumed": "18",
  "differenceOfUse": "16",
  "total": "477",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "64",
  "previousWaterMetering": "187",
  "currentWaterMetering": "187",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "79",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "65",
  "previousWaterMetering": "698",
  "currentWaterMetering": "712",
  "metersConsumed": "14",
  "differenceOfUse": "16",
  "total": "373",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "66",
  "previousWaterMetering": "140",
  "currentWaterMetering": "143",
  "metersConsumed": "3",
  "differenceOfUse": "16",
  "total": "128",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "67",
  "previousWaterMetering": "237",
  "currentWaterMetering": "245",
  "metersConsumed": "8",
  "differenceOfUse": "16",
  "total": "221",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "79",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "69",
  "previousWaterMetering": "431",
  "currentWaterMetering": "448",
  "metersConsumed": "17",
  "differenceOfUse": "16",
  "total": "451",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "70",
  "previousWaterMetering": "98",
  "currentWaterMetering": "104",
  "metersConsumed": "6",
  "differenceOfUse": "16",
  "total": "181",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "71",
  "previousWaterMetering": "262",
  "currentWaterMetering": "272",
  "metersConsumed": "10",
  "differenceOfUse": "16",
  "total": "275",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "72",
  "previousWaterMetering": "233",
  "currentWaterMetering": "241",
  "metersConsumed": "8",
  "differenceOfUse": "16",
  "total": "221",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "73",
  "previousWaterMetering": "203",
  "currentWaterMetering": "209",
  "metersConsumed": "6",
  "differenceOfUse": "16",
  "total": "181",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "74",
  "previousWaterMetering": "123",
  "currentWaterMetering": "127",
  "metersConsumed": "4",
  "differenceOfUse": "16",
  "total": "145",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "75",
  "previousWaterMetering": "394",
  "currentWaterMetering": "406",
  "metersConsumed": "12",
  "differenceOfUse": "16",
  "total": "321",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "76",
  "previousWaterMetering": "40",
  "currentWaterMetering": "40",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "79",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "77",
  "previousWaterMetering": "662",
  "currentWaterMetering": "680",
  "metersConsumed": "18",
  "differenceOfUse": "16",
  "total": "477",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "78",
  "previousWaterMetering": "40",
  "currentWaterMetering": "41",
  "metersConsumed": "1",
  "differenceOfUse": "16",
  "total": "95",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "79",
  "previousWaterMetering": "324",
  "currentWaterMetering": "333",
  "metersConsumed": "9",
  "differenceOfUse": "16",
  "total": "252",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "80",
  "previousWaterMetering": "406",
  "currentWaterMetering": "412",
  "metersConsumed": "6",
  "differenceOfUse": "16",
  "total": "181",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "81",
  "previousWaterMetering": "96",
  "currentWaterMetering": "107",
  "metersConsumed": "11",
  "differenceOfUse": "16",
  "total": "298",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "82",
  "previousWaterMetering": "321",
  "currentWaterMetering": "335",
  "metersConsumed": "14",
  "differenceOfUse": "16",
  "total": "373",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "83",
  "previousWaterMetering": "199",
  "currentWaterMetering": "205",
  "metersConsumed": "6",
  "differenceOfUse": "16",
  "total": "181",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "84",
  "previousWaterMetering": "240",
  "currentWaterMetering": "247",
  "metersConsumed": "7",
  "differenceOfUse": "16",
  "total": "201",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "85",
  "previousWaterMetering": "239",
  "currentWaterMetering": "248",
  "metersConsumed": "9",
  "differenceOfUse": "16",
  "total": "252",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "86",
  "previousWaterMetering": "78",
  "currentWaterMetering": "93",
  "metersConsumed": "15",
  "differenceOfUse": "16",
  "total": "399",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "87",
  "previousWaterMetering": "210",
  "currentWaterMetering": "225",
  "metersConsumed": "15",
  "differenceOfUse": "16",
  "total": "399",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "88",
  "previousWaterMetering": "341",
  "currentWaterMetering": "350",
  "metersConsumed": "9",
  "differenceOfUse": "16",
  "total": "252",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "89",
  "previousWaterMetering": "602",
  "currentWaterMetering": "619",
  "metersConsumed": "17",
  "differenceOfUse": "16",
  "total": "451",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "90",
  "previousWaterMetering": "574",
  "currentWaterMetering": "604",
  "metersConsumed": "30",
  "differenceOfUse": "16",
  "total": "1039",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "91",
  "previousWaterMetering": "292",
  "currentWaterMetering": "301",
  "metersConsumed": "9",
  "differenceOfUse": "16",
  "total": "252",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "92",
  "previousWaterMetering": "417",
  "currentWaterMetering": "430",
  "metersConsumed": "13",
  "differenceOfUse": "16",
  "total": "348",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "93",
  "previousWaterMetering": "200",
  "currentWaterMetering": "207",
  "metersConsumed": "7",
  "differenceOfUse": "16",
  "total": "201",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "94",
  "previousWaterMetering": "409",
  "currentWaterMetering": "423",
  "metersConsumed": "14",
  "differenceOfUse": "16",
  "total": "373",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "95",
  "previousWaterMetering": "63",
  "currentWaterMetering": "64",
  "metersConsumed": "1",
  "differenceOfUse": "16",
  "total": "95",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "96",
  "previousWaterMetering": "130",
  "currentWaterMetering": "135",
  "metersConsumed": "5",
  "differenceOfUse": "16",
  "total": "162",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "97",
  "previousWaterMetering": "180",
  "currentWaterMetering": "182",
  "metersConsumed": "2",
  "differenceOfUse": "16",
  "total": "111",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "98",
  "previousWaterMetering": "88",
  "currentWaterMetering": "90",
  "metersConsumed": "2",
  "differenceOfUse": "16",
  "total": "111",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "99",
  "previousWaterMetering": "232",
  "currentWaterMetering": "232",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "79",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "79",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "101",
  "previousWaterMetering": "192",
  "currentWaterMetering": "197",
  "metersConsumed": "5",
  "differenceOfUse": "16",
  "total": "162",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "102",
  "previousWaterMetering": "125",
  "currentWaterMetering": "131",
  "metersConsumed": "6",
  "differenceOfUse": "16",
  "total": "181",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
},
{
  "houseId": "103",
  "previousWaterMetering": "10",
  "currentWaterMetering": "10",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "79",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2025"
}]
;

export const reportShimul = data;
