
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =

[{
  "houseId": "1",
  "previousWaterMetering": "342",
  "currentWaterMetering": "355",
  "metersConsumed": "13",
  "differenceOfUse": "70",
  "total": "398",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "2",
  "previousWaterMetering": "89",
  "currentWaterMetering": "93",
  "metersConsumed": "4",
  "differenceOfUse": "70",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "3",
  "previousWaterMetering": "394",
  "currentWaterMetering": "406",
  "metersConsumed": "12",
  "differenceOfUse": "70",
  "total": "371",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "4",
  "previousWaterMetering": "297",
  "currentWaterMetering": "314",
  "metersConsumed": "17",
  "differenceOfUse": "70",
  "total": "500",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "5",
  "previousWaterMetering": "170",
  "currentWaterMetering": "175",
  "metersConsumed": "5",
  "differenceOfUse": "70",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "6",
  "previousWaterMetering": "287",
  "currentWaterMetering": "296",
  "metersConsumed": "9",
  "differenceOfUse": "70",
  "total": "303",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "7",
  "previousWaterMetering": "413",
  "currentWaterMetering": "424",
  "metersConsumed": "11",
  "differenceOfUse": "70",
  "total": "348",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "8",
  "previousWaterMetering": "95",
  "currentWaterMetering": "101",
  "metersConsumed": "6",
  "differenceOfUse": "70",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "9",
  "previousWaterMetering": "207",
  "currentWaterMetering": "211",
  "metersConsumed": "4",
  "differenceOfUse": "70",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "10",
  "previousWaterMetering": "388",
  "currentWaterMetering": "398",
  "metersConsumed": "10",
  "differenceOfUse": "70",
  "total": "326",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "11",
  "previousWaterMetering": "503",
  "currentWaterMetering": "518",
  "metersConsumed": "15",
  "differenceOfUse": "70",
  "total": "448",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "12",
  "previousWaterMetering": "278",
  "currentWaterMetering": "288",
  "metersConsumed": "10",
  "differenceOfUse": "70",
  "total": "326",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "13",
  "previousWaterMetering": "209",
  "currentWaterMetering": "216",
  "metersConsumed": "7",
  "differenceOfUse": "70",
  "total": "253",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "14",
  "previousWaterMetering": "377",
  "currentWaterMetering": "392",
  "metersConsumed": "15",
  "differenceOfUse": "70",
  "total": "448",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "15",
  "previousWaterMetering": "201",
  "currentWaterMetering": "206",
  "metersConsumed": "5",
  "differenceOfUse": "70",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "16",
  "previousWaterMetering": "178",
  "currentWaterMetering": "184",
  "metersConsumed": "6",
  "differenceOfUse": "70",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "17",
  "previousWaterMetering": "232",
  "currentWaterMetering": "240",
  "metersConsumed": "8",
  "differenceOfUse": "70",
  "total": "273",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "18",
  "previousWaterMetering": "285",
  "currentWaterMetering": "292",
  "metersConsumed": "7",
  "differenceOfUse": "70",
  "total": "253",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "19",
  "previousWaterMetering": "27",
  "currentWaterMetering": "33",
  "metersConsumed": "6",
  "differenceOfUse": "70",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "20",
  "previousWaterMetering": "246",
  "currentWaterMetering": "265",
  "metersConsumed": "19",
  "differenceOfUse": "70",
  "total": "552",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "21",
  "previousWaterMetering": "266",
  "currentWaterMetering": "276",
  "metersConsumed": "10",
  "differenceOfUse": "70",
  "total": "326",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "22",
  "previousWaterMetering": "270",
  "currentWaterMetering": "279",
  "metersConsumed": "9",
  "differenceOfUse": "70",
  "total": "303",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "23",
  "previousWaterMetering": "532",
  "currentWaterMetering": "548",
  "metersConsumed": "16",
  "differenceOfUse": "70",
  "total": "473",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "24",
  "previousWaterMetering": "238",
  "currentWaterMetering": "247",
  "metersConsumed": "9",
  "differenceOfUse": "70",
  "total": "303",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "25",
  "previousWaterMetering": "150",
  "currentWaterMetering": "157",
  "metersConsumed": "7",
  "differenceOfUse": "70",
  "total": "253",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "26",
  "previousWaterMetering": "34",
  "currentWaterMetering": "34",
  "metersConsumed": "0",
  "differenceOfUse": "70",
  "total": "133",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "27",
  "previousWaterMetering": "205",
  "currentWaterMetering": "213",
  "metersConsumed": "8",
  "differenceOfUse": "70",
  "total": "273",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "28",
  "previousWaterMetering": "42",
  "currentWaterMetering": "42",
  "metersConsumed": "0",
  "differenceOfUse": "70",
  "total": "133",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "29",
  "previousWaterMetering": "131",
  "currentWaterMetering": "137",
  "metersConsumed": "6",
  "differenceOfUse": "70",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "30",
  "previousWaterMetering": "406",
  "currentWaterMetering": "423",
  "metersConsumed": "17",
  "differenceOfUse": "70",
  "total": "500",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "31",
  "previousWaterMetering": "253",
  "currentWaterMetering": "263",
  "metersConsumed": "10",
  "differenceOfUse": "70",
  "total": "326",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "32",
  "previousWaterMetering": "405",
  "currentWaterMetering": "418",
  "metersConsumed": "13",
  "differenceOfUse": "70",
  "total": "398",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "33",
  "previousWaterMetering": "135",
  "currentWaterMetering": "136",
  "metersConsumed": "1",
  "differenceOfUse": "70",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "34",
  "previousWaterMetering": "368",
  "currentWaterMetering": "377",
  "metersConsumed": "9",
  "differenceOfUse": "70",
  "total": "303",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "35",
  "previousWaterMetering": "525",
  "currentWaterMetering": "545",
  "metersConsumed": "20",
  "differenceOfUse": "70",
  "total": "579",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "36",
  "previousWaterMetering": "323",
  "currentWaterMetering": "336",
  "metersConsumed": "13",
  "differenceOfUse": "70",
  "total": "398",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "37",
  "previousWaterMetering": "216",
  "currentWaterMetering": "222",
  "metersConsumed": "6",
  "differenceOfUse": "70",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "38",
  "previousWaterMetering": "403",
  "currentWaterMetering": "404",
  "metersConsumed": "1",
  "differenceOfUse": "70",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "39",
  "previousWaterMetering": "245",
  "currentWaterMetering": "250",
  "metersConsumed": "5",
  "differenceOfUse": "70",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "40",
  "previousWaterMetering": "88",
  "currentWaterMetering": "89",
  "metersConsumed": "1",
  "differenceOfUse": "70",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "41",
  "previousWaterMetering": "493",
  "currentWaterMetering": "506",
  "metersConsumed": "13",
  "differenceOfUse": "70",
  "total": "398",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "42",
  "previousWaterMetering": "417",
  "currentWaterMetering": "434",
  "metersConsumed": "17",
  "differenceOfUse": "70",
  "total": "500",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "43",
  "previousWaterMetering": "183",
  "currentWaterMetering": "185",
  "metersConsumed": "2",
  "differenceOfUse": "70",
  "total": "164",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "44",
  "previousWaterMetering": "79",
  "currentWaterMetering": "82",
  "metersConsumed": "3",
  "differenceOfUse": "70",
  "total": "180",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "45",
  "previousWaterMetering": "484",
  "currentWaterMetering": "499",
  "metersConsumed": "15",
  "differenceOfUse": "70",
  "total": "448",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "46",
  "previousWaterMetering": "170",
  "currentWaterMetering": "176",
  "metersConsumed": "6",
  "differenceOfUse": "70",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "47",
  "previousWaterMetering": "476",
  "currentWaterMetering": "489",
  "metersConsumed": "13",
  "differenceOfUse": "70",
  "total": "398",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "48",
  "previousWaterMetering": "147",
  "currentWaterMetering": "156",
  "metersConsumed": "9",
  "differenceOfUse": "70",
  "total": "303",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "49",
  "previousWaterMetering": "320",
  "currentWaterMetering": "330",
  "metersConsumed": "10",
  "differenceOfUse": "70",
  "total": "326",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "50",
  "previousWaterMetering": "148",
  "currentWaterMetering": "156",
  "metersConsumed": "8",
  "differenceOfUse": "70",
  "total": "273",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "51",
  "previousWaterMetering": "79",
  "currentWaterMetering": "81",
  "metersConsumed": "2",
  "differenceOfUse": "70",
  "total": "164",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "52",
  "previousWaterMetering": "268",
  "currentWaterMetering": "275",
  "metersConsumed": "7",
  "differenceOfUse": "70",
  "total": "253",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "53",
  "previousWaterMetering": "114",
  "currentWaterMetering": "116",
  "metersConsumed": "2",
  "differenceOfUse": "70",
  "total": "164",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "54",
  "previousWaterMetering": "394",
  "currentWaterMetering": "405",
  "metersConsumed": "11",
  "differenceOfUse": "70",
  "total": "348",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "70",
  "total": "133",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "56",
  "previousWaterMetering": "5",
  "currentWaterMetering": "5",
  "metersConsumed": "0",
  "differenceOfUse": "70",
  "total": "133",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "57",
  "previousWaterMetering": "588",
  "currentWaterMetering": "595",
  "metersConsumed": "7",
  "differenceOfUse": "70",
  "total": "253",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "58",
  "previousWaterMetering": "359",
  "currentWaterMetering": "365",
  "metersConsumed": "6",
  "differenceOfUse": "70",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "59",
  "previousWaterMetering": "190",
  "currentWaterMetering": "200",
  "metersConsumed": "10",
  "differenceOfUse": "70",
  "total": "326",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "60",
  "previousWaterMetering": "242",
  "currentWaterMetering": "253",
  "metersConsumed": "11",
  "differenceOfUse": "70",
  "total": "348",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "61",
  "previousWaterMetering": "77",
  "currentWaterMetering": "78",
  "metersConsumed": "1",
  "differenceOfUse": "70",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "62",
  "previousWaterMetering": "204",
  "currentWaterMetering": "212",
  "metersConsumed": "8",
  "differenceOfUse": "70",
  "total": "273",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "63",
  "previousWaterMetering": "539",
  "currentWaterMetering": "556",
  "metersConsumed": "17",
  "differenceOfUse": "70",
  "total": "500",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "64",
  "previousWaterMetering": "151",
  "currentWaterMetering": "159",
  "metersConsumed": "8",
  "differenceOfUse": "70",
  "total": "273",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "65",
  "previousWaterMetering": "587",
  "currentWaterMetering": "638",
  "metersConsumed": "51",
  "differenceOfUse": "70",
  "total": "2788",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "66",
  "previousWaterMetering": "128",
  "currentWaterMetering": "130",
  "metersConsumed": "2",
  "differenceOfUse": "70",
  "total": "164",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "67",
  "previousWaterMetering": "203",
  "currentWaterMetering": "212",
  "metersConsumed": "9",
  "differenceOfUse": "70",
  "total": "303",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "70",
  "total": "133",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "69",
  "previousWaterMetering": "367",
  "currentWaterMetering": "380",
  "metersConsumed": "13",
  "differenceOfUse": "70",
  "total": "398",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "70",
  "previousWaterMetering": "70",
  "currentWaterMetering": "74",
  "metersConsumed": "4",
  "differenceOfUse": "70",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "71",
  "previousWaterMetering": "224",
  "currentWaterMetering": "232",
  "metersConsumed": "8",
  "differenceOfUse": "70",
  "total": "273",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "72",
  "previousWaterMetering": "195",
  "currentWaterMetering": "201",
  "metersConsumed": "6",
  "differenceOfUse": "70",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "73",
  "previousWaterMetering": "171",
  "currentWaterMetering": "178",
  "metersConsumed": "7",
  "differenceOfUse": "70",
  "total": "253",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "74",
  "previousWaterMetering": "106",
  "currentWaterMetering": "110",
  "metersConsumed": "4",
  "differenceOfUse": "70",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "75",
  "previousWaterMetering": "346",
  "currentWaterMetering": "351",
  "metersConsumed": "5",
  "differenceOfUse": "70",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "76",
  "previousWaterMetering": "26",
  "currentWaterMetering": "28",
  "metersConsumed": "2",
  "differenceOfUse": "70",
  "total": "164",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "77",
  "previousWaterMetering": "574",
  "currentWaterMetering": "592",
  "metersConsumed": "18",
  "differenceOfUse": "70",
  "total": "525",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "78",
  "previousWaterMetering": "35",
  "currentWaterMetering": "36",
  "metersConsumed": "1",
  "differenceOfUse": "70",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "79",
  "previousWaterMetering": "271",
  "currentWaterMetering": "284",
  "metersConsumed": "13",
  "differenceOfUse": "70",
  "total": "398",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "80",
  "previousWaterMetering": "354",
  "currentWaterMetering": "364",
  "metersConsumed": "10",
  "differenceOfUse": "70",
  "total": "326",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "81",
  "previousWaterMetering": "54",
  "currentWaterMetering": "61",
  "metersConsumed": "7",
  "differenceOfUse": "70",
  "total": "253",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "82",
  "previousWaterMetering": "265",
  "currentWaterMetering": "277",
  "metersConsumed": "12",
  "differenceOfUse": "70",
  "total": "371",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "83",
  "previousWaterMetering": "177",
  "currentWaterMetering": "181",
  "metersConsumed": "4",
  "differenceOfUse": "70",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "84",
  "previousWaterMetering": "212",
  "currentWaterMetering": "218",
  "metersConsumed": "6",
  "differenceOfUse": "70",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "85",
  "previousWaterMetering": "197",
  "currentWaterMetering": "206",
  "metersConsumed": "9",
  "differenceOfUse": "70",
  "total": "303",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "86",
  "previousWaterMetering": "24",
  "currentWaterMetering": "34",
  "metersConsumed": "10",
  "differenceOfUse": "70",
  "total": "326",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "87",
  "previousWaterMetering": "173",
  "currentWaterMetering": "181",
  "metersConsumed": "8",
  "differenceOfUse": "70",
  "total": "273",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "88",
  "previousWaterMetering": "299",
  "currentWaterMetering": "308",
  "metersConsumed": "9",
  "differenceOfUse": "70",
  "total": "303",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "89",
  "previousWaterMetering": "526",
  "currentWaterMetering": "542",
  "metersConsumed": "16",
  "differenceOfUse": "70",
  "total": "473",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "90",
  "previousWaterMetering": "440",
  "currentWaterMetering": "471",
  "metersConsumed": "31",
  "differenceOfUse": "70",
  "total": "1133",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "91",
  "previousWaterMetering": "232",
  "currentWaterMetering": "253",
  "metersConsumed": "21",
  "differenceOfUse": "70",
  "total": "608",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "92",
  "previousWaterMetering": "356",
  "currentWaterMetering": "369",
  "metersConsumed": "13",
  "differenceOfUse": "70",
  "total": "398",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "93",
  "previousWaterMetering": "171",
  "currentWaterMetering": "176",
  "metersConsumed": "5",
  "differenceOfUse": "70",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "94",
  "previousWaterMetering": "352",
  "currentWaterMetering": "362",
  "metersConsumed": "10",
  "differenceOfUse": "70",
  "total": "326",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "95",
  "previousWaterMetering": "62",
  "currentWaterMetering": "63",
  "metersConsumed": "1",
  "differenceOfUse": "70",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "96",
  "previousWaterMetering": "113",
  "currentWaterMetering": "118",
  "metersConsumed": "5",
  "differenceOfUse": "70",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "97",
  "previousWaterMetering": "161",
  "currentWaterMetering": "167",
  "metersConsumed": "6",
  "differenceOfUse": "70",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "98",
  "previousWaterMetering": "75",
  "currentWaterMetering": "75",
  "metersConsumed": "0",
  "differenceOfUse": "70",
  "total": "133",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "99",
  "previousWaterMetering": "205",
  "currentWaterMetering": "207",
  "metersConsumed": "2",
  "differenceOfUse": "70",
  "total": "164",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "70",
  "total": "133",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "101",
  "previousWaterMetering": "170",
  "currentWaterMetering": "175",
  "metersConsumed": "5",
  "differenceOfUse": "70",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "102",
  "previousWaterMetering": "105",
  "currentWaterMetering": "110",
  "metersConsumed": "5",
  "differenceOfUse": "70",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
},
{
  "houseId": "103",
  "previousWaterMetering": "6",
  "currentWaterMetering": "6",
  "metersConsumed": "0",
  "differenceOfUse": "70",
  "total": "133",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2024"
}];

export const reportShimul = data;
