 
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =
[{
  "houseId": "1",
  "previousWaterMetering": "505",
  "currentWaterMetering": "516",
  "metersConsumed": "11",
  "differenceOfUse": "40",
  "total": "334",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "2",
  "previousWaterMetering": "180",
  "currentWaterMetering": "184",
  "metersConsumed": "4",
  "differenceOfUse": "40",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "3",
  "previousWaterMetering": "548",
  "currentWaterMetering": "548",
  "metersConsumed": "0",
  "differenceOfUse": "40",
  "total": "106",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "4",
  "previousWaterMetering": "448",
  "currentWaterMetering": "455",
  "metersConsumed": "7",
  "differenceOfUse": "40",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "5",
  "previousWaterMetering": "239",
  "currentWaterMetering": "239",
  "metersConsumed": "0",
  "differenceOfUse": "40",
  "total": "106",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "6",
  "previousWaterMetering": "388",
  "currentWaterMetering": "408",
  "metersConsumed": "20",
  "differenceOfUse": "40",
  "total": "576",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "7",
  "previousWaterMetering": "554",
  "currentWaterMetering": "562",
  "metersConsumed": "8",
  "differenceOfUse": "40",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "8",
  "previousWaterMetering": "209",
  "currentWaterMetering": "209",
  "metersConsumed": "0",
  "differenceOfUse": "40",
  "total": "106",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "9",
  "previousWaterMetering": "269",
  "currentWaterMetering": "273",
  "metersConsumed": "4",
  "differenceOfUse": "40",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "10",
  "previousWaterMetering": "502",
  "currentWaterMetering": "508",
  "metersConsumed": "6",
  "differenceOfUse": "40",
  "total": "212",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "11",
  "previousWaterMetering": "676",
  "currentWaterMetering": "689",
  "metersConsumed": "13",
  "differenceOfUse": "40",
  "total": "386",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "12",
  "previousWaterMetering": "387",
  "currentWaterMetering": "397",
  "metersConsumed": "10",
  "differenceOfUse": "40",
  "total": "310",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "13",
  "previousWaterMetering": "276",
  "currentWaterMetering": "279",
  "metersConsumed": "3",
  "differenceOfUse": "40",
  "total": "156",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "14",
  "previousWaterMetering": "523",
  "currentWaterMetering": "532",
  "metersConsumed": "9",
  "differenceOfUse": "40",
  "total": "286",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "15",
  "previousWaterMetering": "240",
  "currentWaterMetering": "244",
  "metersConsumed": "4",
  "differenceOfUse": "40",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "16",
  "previousWaterMetering": "258",
  "currentWaterMetering": "264",
  "metersConsumed": "6",
  "differenceOfUse": "40",
  "total": "212",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "17",
  "previousWaterMetering": "324",
  "currentWaterMetering": "329",
  "metersConsumed": "5",
  "differenceOfUse": "40",
  "total": "193",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "18",
  "previousWaterMetering": "361",
  "currentWaterMetering": "366",
  "metersConsumed": "5",
  "differenceOfUse": "40",
  "total": "193",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "19",
  "previousWaterMetering": "107",
  "currentWaterMetering": "114",
  "metersConsumed": "7",
  "differenceOfUse": "40",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "20",
  "previousWaterMetering": "432",
  "currentWaterMetering": "437",
  "metersConsumed": "5",
  "differenceOfUse": "40",
  "total": "193",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "21",
  "previousWaterMetering": "395",
  "currentWaterMetering": "406",
  "metersConsumed": "11",
  "differenceOfUse": "40",
  "total": "334",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "22",
  "previousWaterMetering": "364",
  "currentWaterMetering": "372",
  "metersConsumed": "8",
  "differenceOfUse": "40",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "23",
  "previousWaterMetering": "731",
  "currentWaterMetering": "748",
  "metersConsumed": "17",
  "differenceOfUse": "40",
  "total": "493",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "24",
  "previousWaterMetering": "327",
  "currentWaterMetering": "333",
  "metersConsumed": "6",
  "differenceOfUse": "40",
  "total": "212",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "25",
  "previousWaterMetering": "229",
  "currentWaterMetering": "235",
  "metersConsumed": "6",
  "differenceOfUse": "40",
  "total": "212",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "26",
  "previousWaterMetering": "34",
  "currentWaterMetering": "34",
  "metersConsumed": "0",
  "differenceOfUse": "40",
  "total": "106",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "27",
  "previousWaterMetering": "334",
  "currentWaterMetering": "345",
  "metersConsumed": "11",
  "differenceOfUse": "40",
  "total": "334",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "28",
  "previousWaterMetering": "44",
  "currentWaterMetering": "47",
  "metersConsumed": "3",
  "differenceOfUse": "40",
  "total": "156",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "29",
  "previousWaterMetering": "196",
  "currentWaterMetering": "197",
  "metersConsumed": "1",
  "differenceOfUse": "40",
  "total": "123",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "30",
  "previousWaterMetering": "564",
  "currentWaterMetering": "576",
  "metersConsumed": "12",
  "differenceOfUse": "40",
  "total": "358",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "31",
  "previousWaterMetering": "377",
  "currentWaterMetering": "385",
  "metersConsumed": "8",
  "differenceOfUse": "40",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "32",
  "previousWaterMetering": "574",
  "currentWaterMetering": "586",
  "metersConsumed": "12",
  "differenceOfUse": "40",
  "total": "358",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "33",
  "previousWaterMetering": "157",
  "currentWaterMetering": "158",
  "metersConsumed": "1",
  "differenceOfUse": "40",
  "total": "123",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "34",
  "previousWaterMetering": "501",
  "currentWaterMetering": "509",
  "metersConsumed": "8",
  "differenceOfUse": "40",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "35",
  "previousWaterMetering": "760",
  "currentWaterMetering": "777",
  "metersConsumed": "17",
  "differenceOfUse": "40",
  "total": "493",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "36",
  "previousWaterMetering": "487",
  "currentWaterMetering": "494",
  "metersConsumed": "7",
  "differenceOfUse": "40",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "37",
  "previousWaterMetering": "316",
  "currentWaterMetering": "324",
  "metersConsumed": "8",
  "differenceOfUse": "40",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "38",
  "previousWaterMetering": "481",
  "currentWaterMetering": "491",
  "metersConsumed": "10",
  "differenceOfUse": "40",
  "total": "310",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "39",
  "previousWaterMetering": "314",
  "currentWaterMetering": "318",
  "metersConsumed": "4",
  "differenceOfUse": "40",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "40",
  "previousWaterMetering": "102",
  "currentWaterMetering": "103",
  "metersConsumed": "1",
  "differenceOfUse": "40",
  "total": "123",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "41",
  "previousWaterMetering": "632",
  "currentWaterMetering": "641",
  "metersConsumed": "9",
  "differenceOfUse": "40",
  "total": "286",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "42",
  "previousWaterMetering": "605",
  "currentWaterMetering": "616",
  "metersConsumed": "11",
  "differenceOfUse": "40",
  "total": "334",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "43",
  "previousWaterMetering": "207",
  "currentWaterMetering": "209",
  "metersConsumed": "2",
  "differenceOfUse": "40",
  "total": "139",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "44",
  "previousWaterMetering": "127",
  "currentWaterMetering": "131",
  "metersConsumed": "4",
  "differenceOfUse": "40",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "45",
  "previousWaterMetering": "660",
  "currentWaterMetering": "673",
  "metersConsumed": "13",
  "differenceOfUse": "40",
  "total": "386",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "46",
  "previousWaterMetering": "235",
  "currentWaterMetering": "241",
  "metersConsumed": "6",
  "differenceOfUse": "40",
  "total": "212",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "47",
  "previousWaterMetering": "572",
  "currentWaterMetering": "577",
  "metersConsumed": "5",
  "differenceOfUse": "40",
  "total": "193",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "48",
  "previousWaterMetering": "248",
  "currentWaterMetering": "255",
  "metersConsumed": "7",
  "differenceOfUse": "40",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "49",
  "previousWaterMetering": "457",
  "currentWaterMetering": "469",
  "metersConsumed": "12",
  "differenceOfUse": "40",
  "total": "358",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "50",
  "previousWaterMetering": "560",
  "currentWaterMetering": "561",
  "metersConsumed": "1",
  "differenceOfUse": "40",
  "total": "123",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "51",
  "previousWaterMetering": "111",
  "currentWaterMetering": "113",
  "metersConsumed": "2",
  "differenceOfUse": "40",
  "total": "139",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "52",
  "previousWaterMetering": "342",
  "currentWaterMetering": "348",
  "metersConsumed": "6",
  "differenceOfUse": "40",
  "total": "212",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "53",
  "previousWaterMetering": "159",
  "currentWaterMetering": "163",
  "metersConsumed": "4",
  "differenceOfUse": "40",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "54",
  "previousWaterMetering": "532",
  "currentWaterMetering": "548",
  "metersConsumed": "16",
  "differenceOfUse": "40",
  "total": "464",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "40",
  "total": "106",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "56",
  "previousWaterMetering": "7",
  "currentWaterMetering": "8",
  "metersConsumed": "1",
  "differenceOfUse": "40",
  "total": "123",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "57",
  "previousWaterMetering": "682",
  "currentWaterMetering": "692",
  "metersConsumed": "10",
  "differenceOfUse": "40",
  "total": "310",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "58",
  "previousWaterMetering": "436",
  "currentWaterMetering": "440",
  "metersConsumed": "4",
  "differenceOfUse": "40",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "59",
  "previousWaterMetering": "321",
  "currentWaterMetering": "328",
  "metersConsumed": "7",
  "differenceOfUse": "40",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "60",
  "previousWaterMetering": "365",
  "currentWaterMetering": "373",
  "metersConsumed": "8",
  "differenceOfUse": "40",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "61",
  "previousWaterMetering": "99",
  "currentWaterMetering": "101",
  "metersConsumed": "2",
  "differenceOfUse": "40",
  "total": "139",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "62",
  "previousWaterMetering": "335",
  "currentWaterMetering": "357",
  "metersConsumed": "22",
  "differenceOfUse": "40",
  "total": "636",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "63",
  "previousWaterMetering": "754",
  "currentWaterMetering": "767",
  "metersConsumed": "13",
  "differenceOfUse": "40",
  "total": "386",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "64",
  "previousWaterMetering": "222",
  "currentWaterMetering": "230",
  "metersConsumed": "8",
  "differenceOfUse": "40",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "65",
  "previousWaterMetering": "793",
  "currentWaterMetering": "807",
  "metersConsumed": "14",
  "differenceOfUse": "40",
  "total": "412",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "66",
  "previousWaterMetering": "158",
  "currentWaterMetering": "168",
  "metersConsumed": "10",
  "differenceOfUse": "40",
  "total": "310",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "67",
  "previousWaterMetering": "296",
  "currentWaterMetering": "302",
  "metersConsumed": "6",
  "differenceOfUse": "40",
  "total": "212",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "40",
  "total": "106",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "69",
  "previousWaterMetering": "527",
  "currentWaterMetering": "540",
  "metersConsumed": "13",
  "differenceOfUse": "40",
  "total": "386",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "70",
  "previousWaterMetering": "142",
  "currentWaterMetering": "147",
  "metersConsumed": "5",
  "differenceOfUse": "40",
  "total": "193",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "71",
  "previousWaterMetering": "327",
  "currentWaterMetering": "335",
  "metersConsumed": "8",
  "differenceOfUse": "40",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "72",
  "previousWaterMetering": "280",
  "currentWaterMetering": "286",
  "metersConsumed": "6",
  "differenceOfUse": "40",
  "total": "212",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "73",
  "previousWaterMetering": "244",
  "currentWaterMetering": "249",
  "metersConsumed": "5",
  "differenceOfUse": "40",
  "total": "193",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "74",
  "previousWaterMetering": "150",
  "currentWaterMetering": "153",
  "metersConsumed": "3",
  "differenceOfUse": "40",
  "total": "156",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "75",
  "previousWaterMetering": "467",
  "currentWaterMetering": "475",
  "metersConsumed": "8",
  "differenceOfUse": "40",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "76",
  "previousWaterMetering": "41",
  "currentWaterMetering": "42",
  "metersConsumed": "1",
  "differenceOfUse": "40",
  "total": "123",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "77",
  "previousWaterMetering": "786",
  "currentWaterMetering": "802",
  "metersConsumed": "16",
  "differenceOfUse": "40",
  "total": "464",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "78",
  "previousWaterMetering": "52",
  "currentWaterMetering": "55",
  "metersConsumed": "3",
  "differenceOfUse": "40",
  "total": "156",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "79",
  "previousWaterMetering": "389",
  "currentWaterMetering": "396",
  "metersConsumed": "7",
  "differenceOfUse": "40",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "80",
  "previousWaterMetering": "497",
  "currentWaterMetering": "514",
  "metersConsumed": "17",
  "differenceOfUse": "40",
  "total": "493",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "81",
  "previousWaterMetering": "164",
  "currentWaterMetering": "175",
  "metersConsumed": "11",
  "differenceOfUse": "40",
  "total": "334",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "82",
  "previousWaterMetering": "376",
  "currentWaterMetering": "383",
  "metersConsumed": "7",
  "differenceOfUse": "40",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "83",
  "previousWaterMetering": "233",
  "currentWaterMetering": "237",
  "metersConsumed": "4",
  "differenceOfUse": "40",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "84",
  "previousWaterMetering": "272",
  "currentWaterMetering": "278",
  "metersConsumed": "6",
  "differenceOfUse": "40",
  "total": "212",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "85",
  "previousWaterMetering": "300",
  "currentWaterMetering": "307",
  "metersConsumed": "7",
  "differenceOfUse": "40",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "86",
  "previousWaterMetering": "176",
  "currentWaterMetering": "189",
  "metersConsumed": "13",
  "differenceOfUse": "40",
  "total": "386",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "87",
  "previousWaterMetering": "322",
  "currentWaterMetering": "337",
  "metersConsumed": "15",
  "differenceOfUse": "40",
  "total": "439",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "88",
  "previousWaterMetering": "396",
  "currentWaterMetering": "400",
  "metersConsumed": "4",
  "differenceOfUse": "40",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "89",
  "previousWaterMetering": "708",
  "currentWaterMetering": "717",
  "metersConsumed": "9",
  "differenceOfUse": "40",
  "total": "286",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "90",
  "previousWaterMetering": "769",
  "currentWaterMetering": "793",
  "metersConsumed": "24",
  "differenceOfUse": "40",
  "total": "721",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "91",
  "previousWaterMetering": "338",
  "currentWaterMetering": "344",
  "metersConsumed": "6",
  "differenceOfUse": "40",
  "total": "212",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "92",
  "previousWaterMetering": "483",
  "currentWaterMetering": "490",
  "metersConsumed": "7",
  "differenceOfUse": "40",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "93",
  "previousWaterMetering": "262",
  "currentWaterMetering": "269",
  "metersConsumed": "7",
  "differenceOfUse": "40",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "94",
  "previousWaterMetering": "494",
  "currentWaterMetering": "501",
  "metersConsumed": "7",
  "differenceOfUse": "40",
  "total": "233",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "95",
  "previousWaterMetering": "64",
  "currentWaterMetering": "64",
  "metersConsumed": "0",
  "differenceOfUse": "40",
  "total": "106",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "96",
  "previousWaterMetering": "159",
  "currentWaterMetering": "163",
  "metersConsumed": "4",
  "differenceOfUse": "40",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "97",
  "previousWaterMetering": "217",
  "currentWaterMetering": "219",
  "metersConsumed": "2",
  "differenceOfUse": "40",
  "total": "139",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "98",
  "previousWaterMetering": "100",
  "currentWaterMetering": "100",
  "metersConsumed": "0",
  "differenceOfUse": "40",
  "total": "106",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "99",
  "previousWaterMetering": "234",
  "currentWaterMetering": "237",
  "metersConsumed": "3",
  "differenceOfUse": "40",
  "total": "156",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "40",
  "total": "106",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "101",
  "previousWaterMetering": "228",
  "currentWaterMetering": "232",
  "metersConsumed": "4",
  "differenceOfUse": "40",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "102",
  "previousWaterMetering": "152",
  "currentWaterMetering": "155",
  "metersConsumed": "3",
  "differenceOfUse": "40",
  "total": "156",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
},
{
  "houseId": "103",
  "previousWaterMetering": "13",
  "currentWaterMetering": "13",
  "metersConsumed": "0",
  "differenceOfUse": "40",
  "total": "106",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Octubre",
  "paymentMonth": "Diciembre",
  "year": "2025"
}]
;

export const reportShimul = data;
