
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] = 
[
      {
        "houseId": "1",
        "previousWaterMetering": "331",
        "currentWaterMetering": "342",
        "metersConsumed": "11",
        "differenceOfUse": "54",
        "total": "329",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "2",
        "previousWaterMetering": "84",
        "currentWaterMetering": "89",
        "metersConsumed": "5",
        "differenceOfUse": "54",
        "total": "197",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "3",
        "previousWaterMetering": "382",
        "currentWaterMetering": "394",
        "metersConsumed": "12",
        "differenceOfUse": "54",
        "total": "351",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "4",
        "previousWaterMetering": "282",
        "currentWaterMetering": "297",
        "metersConsumed": "15",
        "differenceOfUse": "54",
        "total": "427",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "5",
        "previousWaterMetering": "162",
        "currentWaterMetering": "170",
        "metersConsumed": "8",
        "differenceOfUse": "54",
        "total": "254",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "6",
        "previousWaterMetering": "278",
        "currentWaterMetering": "287",
        "metersConsumed": "9",
        "differenceOfUse": "54",
        "total": "284",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "7",
        "previousWaterMetering": "403",
        "currentWaterMetering": "413",
        "metersConsumed": "10",
        "differenceOfUse": "54",
        "total": "307",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "8",
        "previousWaterMetering": "91",
        "currentWaterMetering": "95",
        "metersConsumed": "4",
        "differenceOfUse": "54",
        "total": "179",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "9",
        "previousWaterMetering": "202",
        "currentWaterMetering": "207",
        "metersConsumed": "5",
        "differenceOfUse": "54",
        "total": "197",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "10",
        "previousWaterMetering": "379",
        "currentWaterMetering": "388",
        "metersConsumed": "9",
        "differenceOfUse": "54",
        "total": "284",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "11",
        "previousWaterMetering": "485",
        "currentWaterMetering": "503",
        "metersConsumed": "18",
        "differenceOfUse": "54",
        "total": "503",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "12",
        "previousWaterMetering": "268",
        "currentWaterMetering": "278",
        "metersConsumed": "10",
        "differenceOfUse": "54",
        "total": "307",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "13",
        "previousWaterMetering": "208",
        "currentWaterMetering": "209",
        "metersConsumed": "1",
        "differenceOfUse": "54",
        "total": "131",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "14",
        "previousWaterMetering": "368",
        "currentWaterMetering": "377",
        "metersConsumed": "9",
        "differenceOfUse": "54",
        "total": "284",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "15",
        "previousWaterMetering": "197",
        "currentWaterMetering": "201",
        "metersConsumed": "4",
        "differenceOfUse": "54",
        "total": "179",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "16",
        "previousWaterMetering": "174",
        "currentWaterMetering": "178",
        "metersConsumed": "4",
        "differenceOfUse": "54",
        "total": "179",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "17",
        "previousWaterMetering": "225",
        "currentWaterMetering": "232",
        "metersConsumed": "7",
        "differenceOfUse": "54",
        "total": "234",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "18",
        "previousWaterMetering": "281",
        "currentWaterMetering": "285",
        "metersConsumed": "4",
        "differenceOfUse": "54",
        "total": "179",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "19",
        "previousWaterMetering": "21",
        "currentWaterMetering": "27",
        "metersConsumed": "6",
        "differenceOfUse": "54",
        "total": "215",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "20",
        "previousWaterMetering": "232",
        "currentWaterMetering": "246",
        "metersConsumed": "14",
        "differenceOfUse": "54",
        "total": "402",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "21",
        "previousWaterMetering": "259",
        "currentWaterMetering": "266",
        "metersConsumed": "7",
        "differenceOfUse": "54",
        "total": "234",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "22",
        "previousWaterMetering": "261",
        "currentWaterMetering": "270",
        "metersConsumed": "9",
        "differenceOfUse": "54",
        "total": "284",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "23",
        "previousWaterMetering": "517",
        "currentWaterMetering": "532",
        "metersConsumed": "15",
        "differenceOfUse": "54",
        "total": "427",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "24",
        "previousWaterMetering": "229",
        "currentWaterMetering": "238",
        "metersConsumed": "9",
        "differenceOfUse": "54",
        "total": "284",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "25",
        "previousWaterMetering": "144",
        "currentWaterMetering": "150",
        "metersConsumed": "6",
        "differenceOfUse": "54",
        "total": "215",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "26",
        "previousWaterMetering": "34",
        "currentWaterMetering": "34",
        "metersConsumed": "0",
        "differenceOfUse": "54",
        "total": "116",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "27",
        "previousWaterMetering": "198",
        "currentWaterMetering": "205",
        "metersConsumed": "7",
        "differenceOfUse": "54",
        "total": "234",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "28",
        "previousWaterMetering": "41",
        "currentWaterMetering": "42",
        "metersConsumed": "1",
        "differenceOfUse": "54",
        "total": "131",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "29",
        "previousWaterMetering": "118",
        "currentWaterMetering": "131",
        "metersConsumed": "13",
        "differenceOfUse": "54",
        "total": "378",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "30",
        "previousWaterMetering": "392",
        "currentWaterMetering": "406",
        "metersConsumed": "14",
        "differenceOfUse": "54",
        "total": "402",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "31",
        "previousWaterMetering": "245",
        "currentWaterMetering": "253",
        "metersConsumed": "8",
        "differenceOfUse": "54",
        "total": "254",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "32",
        "previousWaterMetering": "392",
        "currentWaterMetering": "405",
        "metersConsumed": "13",
        "differenceOfUse": "54",
        "total": "378",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "33",
        "previousWaterMetering": "134",
        "currentWaterMetering": "135",
        "metersConsumed": "1",
        "differenceOfUse": "54",
        "total": "131",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "34",
        "previousWaterMetering": "358",
        "currentWaterMetering": "368",
        "metersConsumed": "10",
        "differenceOfUse": "54",
        "total": "307",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "35",
        "previousWaterMetering": "503",
        "currentWaterMetering": "525",
        "metersConsumed": "22",
        "differenceOfUse": "54",
        "total": "613",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "36",
        "previousWaterMetering": "313",
        "currentWaterMetering": "323",
        "metersConsumed": "10",
        "differenceOfUse": "54",
        "total": "307",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "37",
        "previousWaterMetering": "205",
        "currentWaterMetering": "216",
        "metersConsumed": "11",
        "differenceOfUse": "54",
        "total": "329",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "38",
        "previousWaterMetering": "403",
        "currentWaterMetering": "403",
        "metersConsumed": "0",
        "differenceOfUse": "54",
        "total": "116",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "39",
        "previousWaterMetering": "238",
        "currentWaterMetering": "245",
        "metersConsumed": "7",
        "differenceOfUse": "54",
        "total": "234",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "40",
        "previousWaterMetering": "87",
        "currentWaterMetering": "88",
        "metersConsumed": "1",
        "differenceOfUse": "54",
        "total": "131",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "41",
        "previousWaterMetering": "480",
        "currentWaterMetering": "493",
        "metersConsumed": "13",
        "differenceOfUse": "54",
        "total": "378",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "42",
        "previousWaterMetering": "403",
        "currentWaterMetering": "417",
        "metersConsumed": "14",
        "differenceOfUse": "54",
        "total": "402",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "43",
        "previousWaterMetering": "181",
        "currentWaterMetering": "183",
        "metersConsumed": "2",
        "differenceOfUse": "54",
        "total": "147",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "44",
        "previousWaterMetering": "77",
        "currentWaterMetering": "79",
        "metersConsumed": "2",
        "differenceOfUse": "54",
        "total": "147",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "45",
        "previousWaterMetering": "467",
        "currentWaterMetering": "484",
        "metersConsumed": "17",
        "differenceOfUse": "54",
        "total": "478",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "46",
        "previousWaterMetering": "164",
        "currentWaterMetering": "170",
        "metersConsumed": "6",
        "differenceOfUse": "54",
        "total": "215",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "47",
        "previousWaterMetering": "467",
        "currentWaterMetering": "476",
        "metersConsumed": "9",
        "differenceOfUse": "54",
        "total": "284",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "48",
        "previousWaterMetering": "140",
        "currentWaterMetering": "147",
        "metersConsumed": "7",
        "differenceOfUse": "54",
        "total": "234",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "49",
        "previousWaterMetering": "310",
        "currentWaterMetering": "320",
        "metersConsumed": "10",
        "differenceOfUse": "54",
        "total": "307",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "50",
        "previousWaterMetering": "143",
        "currentWaterMetering": "148",
        "metersConsumed": "5",
        "differenceOfUse": "54",
        "total": "197",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "51",
        "previousWaterMetering": "77",
        "currentWaterMetering": "79",
        "metersConsumed": "2",
        "differenceOfUse": "54",
        "total": "147",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "52",
        "previousWaterMetering": "259",
        "currentWaterMetering": "268",
        "metersConsumed": "9",
        "differenceOfUse": "54",
        "total": "284",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "53",
        "previousWaterMetering": "112",
        "currentWaterMetering": "114",
        "metersConsumed": "2",
        "differenceOfUse": "54",
        "total": "147",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "54",
        "previousWaterMetering": "383",
        "currentWaterMetering": "394",
        "metersConsumed": "11",
        "differenceOfUse": "54",
        "total": "329",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "55",
        "previousWaterMetering": "11",
        "currentWaterMetering": "11",
        "metersConsumed": "0",
        "differenceOfUse": "54",
        "total": "116",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "56",
        "previousWaterMetering": "5",
        "currentWaterMetering": "5",
        "metersConsumed": "0",
        "differenceOfUse": "54",
        "total": "116",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "57",
        "previousWaterMetering": "584",
        "currentWaterMetering": "588",
        "metersConsumed": "4",
        "differenceOfUse": "54",
        "total": "179",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "58",
        "previousWaterMetering": "347",
        "currentWaterMetering": "359",
        "metersConsumed": "12",
        "differenceOfUse": "54",
        "total": "351",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "59",
        "previousWaterMetering": "179",
        "currentWaterMetering": "190",
        "metersConsumed": "11",
        "differenceOfUse": "54",
        "total": "329",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "60",
        "previousWaterMetering": "232",
        "currentWaterMetering": "242",
        "metersConsumed": "10",
        "differenceOfUse": "54",
        "total": "307",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "61",
        "previousWaterMetering": "76",
        "currentWaterMetering": "77",
        "metersConsumed": "1",
        "differenceOfUse": "54",
        "total": "131",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "62",
        "previousWaterMetering": "196",
        "currentWaterMetering": "204",
        "metersConsumed": "8",
        "differenceOfUse": "54",
        "total": "254",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "63",
        "previousWaterMetering": "522",
        "currentWaterMetering": "539",
        "metersConsumed": "17",
        "differenceOfUse": "54",
        "total": "478",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "64",
        "previousWaterMetering": "147",
        "currentWaterMetering": "151",
        "metersConsumed": "4",
        "differenceOfUse": "54",
        "total": "179",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "65",
        "previousWaterMetering": "569",
        "currentWaterMetering": "587",
        "metersConsumed": "18",
        "differenceOfUse": "54",
        "total": "503",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "66",
        "previousWaterMetering": "126",
        "currentWaterMetering": "128",
        "metersConsumed": "2",
        "differenceOfUse": "54",
        "total": "147",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "67",
        "previousWaterMetering": "196",
        "currentWaterMetering": "203",
        "metersConsumed": "7",
        "differenceOfUse": "54",
        "total": "234",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "68",
        "previousWaterMetering": "8",
        "currentWaterMetering": "8",
        "metersConsumed": "0",
        "differenceOfUse": "54",
        "total": "116",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "69",
        "previousWaterMetering": "351",
        "currentWaterMetering": "367",
        "metersConsumed": "16",
        "differenceOfUse": "54",
        "total": "451",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "70",
        "previousWaterMetering": "70",
        "currentWaterMetering": "70",
        "metersConsumed": "0",
        "differenceOfUse": "54",
        "total": "116",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "71",
        "previousWaterMetering": "216",
        "currentWaterMetering": "224",
        "metersConsumed": "8",
        "differenceOfUse": "54",
        "total": "254",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "72",
        "previousWaterMetering": "188",
        "currentWaterMetering": "195",
        "metersConsumed": "7",
        "differenceOfUse": "54",
        "total": "234",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "73",
        "previousWaterMetering": "164",
        "currentWaterMetering": "171",
        "metersConsumed": "7",
        "differenceOfUse": "54",
        "total": "234",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "74",
        "previousWaterMetering": "103",
        "currentWaterMetering": "106",
        "metersConsumed": "3",
        "differenceOfUse": "54",
        "total": "163",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "75",
        "previousWaterMetering": "339",
        "currentWaterMetering": "346",
        "metersConsumed": "7",
        "differenceOfUse": "54",
        "total": "234",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "76",
        "previousWaterMetering": "24",
        "currentWaterMetering": "26",
        "metersConsumed": "2",
        "differenceOfUse": "54",
        "total": "147",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "77",
        "previousWaterMetering": "559",
        "currentWaterMetering": "574",
        "metersConsumed": "15",
        "differenceOfUse": "54",
        "total": "427",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "78",
        "previousWaterMetering": "35",
        "currentWaterMetering": "35",
        "metersConsumed": "0",
        "differenceOfUse": "54",
        "total": "116",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "79",
        "previousWaterMetering": "258",
        "currentWaterMetering": "271",
        "metersConsumed": "13",
        "differenceOfUse": "54",
        "total": "378",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "80",
        "previousWaterMetering": "343",
        "currentWaterMetering": "354",
        "metersConsumed": "11",
        "differenceOfUse": "54",
        "total": "329",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "81",
        "previousWaterMetering": "50",
        "currentWaterMetering": "54",
        "metersConsumed": "4",
        "differenceOfUse": "54",
        "total": "179",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "82",
        "previousWaterMetering": "252",
        "currentWaterMetering": "265",
        "metersConsumed": "13",
        "differenceOfUse": "54",
        "total": "378",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "83",
        "previousWaterMetering": "172",
        "currentWaterMetering": "177",
        "metersConsumed": "5",
        "differenceOfUse": "54",
        "total": "197",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "84",
        "previousWaterMetering": "208",
        "currentWaterMetering": "212",
        "metersConsumed": "4",
        "differenceOfUse": "54",
        "total": "179",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "85",
        "previousWaterMetering": "191",
        "currentWaterMetering": "197",
        "metersConsumed": "6",
        "differenceOfUse": "54",
        "total": "215",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "86",
        "previousWaterMetering": "15",
        "currentWaterMetering": "24",
        "metersConsumed": "9",
        "differenceOfUse": "54",
        "total": "284",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "87",
        "previousWaterMetering": "166",
        "currentWaterMetering": "173",
        "metersConsumed": "7",
        "differenceOfUse": "54",
        "total": "234",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "88",
        "previousWaterMetering": "290",
        "currentWaterMetering": "299",
        "metersConsumed": "9",
        "differenceOfUse": "54",
        "total": "284",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "89",
        "previousWaterMetering": "509",
        "currentWaterMetering": "526",
        "metersConsumed": "17",
        "differenceOfUse": "54",
        "total": "478",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "90",
        "previousWaterMetering": "415",
        "currentWaterMetering": "440",
        "metersConsumed": "25",
        "differenceOfUse": "54",
        "total": "747",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "91",
        "previousWaterMetering": "212",
        "currentWaterMetering": "232",
        "metersConsumed": "20",
        "differenceOfUse": "54",
        "total": "556",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "92",
        "previousWaterMetering": "343",
        "currentWaterMetering": "356",
        "metersConsumed": "13",
        "differenceOfUse": "54",
        "total": "378",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "93",
        "previousWaterMetering": "163",
        "currentWaterMetering": "171",
        "metersConsumed": "8",
        "differenceOfUse": "54",
        "total": "254",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "94",
        "previousWaterMetering": "343",
        "currentWaterMetering": "352",
        "metersConsumed": "9",
        "differenceOfUse": "54",
        "total": "284",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "95",
        "previousWaterMetering": "62",
        "currentWaterMetering": "62",
        "metersConsumed": "0",
        "differenceOfUse": "54",
        "total": "116",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "96",
        "previousWaterMetering": "108",
        "currentWaterMetering": "113",
        "metersConsumed": "5",
        "differenceOfUse": "54",
        "total": "197",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "97",
        "previousWaterMetering": "148",
        "currentWaterMetering": "161",
        "metersConsumed": "13",
        "differenceOfUse": "54",
        "total": "378",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "98",
        "previousWaterMetering": "74",
        "currentWaterMetering": "75",
        "metersConsumed": "1",
        "differenceOfUse": "54",
        "total": "131",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "99",
        "previousWaterMetering": "203",
        "currentWaterMetering": "205",
        "metersConsumed": "2",
        "differenceOfUse": "54",
        "total": "147",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "100",
        "previousWaterMetering": "3",
        "currentWaterMetering": "3",
        "metersConsumed": "0",
        "differenceOfUse": "54",
        "total": "116",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "101",
        "previousWaterMetering": "166",
        "currentWaterMetering": "170",
        "metersConsumed": "4",
        "differenceOfUse": "54",
        "total": "179",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "102",
        "previousWaterMetering": "101",
        "currentWaterMetering": "105",
        "metersConsumed": "4",
        "differenceOfUse": "54",
        "total": "179",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      },
      {
        "houseId": "103",
        "previousWaterMetering": "6",
        "currentWaterMetering": "6",
        "metersConsumed": "0",
        "differenceOfUse": "54",
        "total": "116",
        "condo": "Shimul",
        "caKey": "shimulac",
        "periodOfUse": "Septiembre",
        "paymentMonth": "Noviembre",
        "year": "2024"
      }
    ]
;

export const reportShimul = data;
