 
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =
[{
  "houseId": "1",
  "previousWaterMetering": "541",
  "currentWaterMetering": "552",
  "metersConsumed": "11",
  "differenceOfUse": "55",
  "total": "352",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "2",
  "previousWaterMetering": "193",
  "currentWaterMetering": "194",
  "metersConsumed": "1",
  "differenceOfUse": "55",
  "total": "139",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "3",
  "previousWaterMetering": "548",
  "currentWaterMetering": "548",
  "metersConsumed": "0",
  "differenceOfUse": "55",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "4",
  "previousWaterMetering": "480",
  "currentWaterMetering": "492",
  "metersConsumed": "12",
  "differenceOfUse": "55",
  "total": "377",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "5",
  "previousWaterMetering": "471",
  "currentWaterMetering": "481",
  "metersConsumed": "10",
  "differenceOfUse": "55",
  "total": "329",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "6",
  "previousWaterMetering": "419",
  "currentWaterMetering": "434",
  "metersConsumed": "15",
  "differenceOfUse": "55",
  "total": "459",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "7",
  "previousWaterMetering": "599",
  "currentWaterMetering": "616",
  "metersConsumed": "17",
  "differenceOfUse": "55",
  "total": "514",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "8",
  "previousWaterMetering": "211",
  "currentWaterMetering": "212",
  "metersConsumed": "1",
  "differenceOfUse": "55",
  "total": "139",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "9",
  "previousWaterMetering": "286",
  "currentWaterMetering": "291",
  "metersConsumed": "5",
  "differenceOfUse": "55",
  "total": "210",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "10",
  "previousWaterMetering": "523",
  "currentWaterMetering": "530",
  "metersConsumed": "7",
  "differenceOfUse": "55",
  "total": "250",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "11",
  "previousWaterMetering": "723",
  "currentWaterMetering": "736",
  "metersConsumed": "13",
  "differenceOfUse": "55",
  "total": "405",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "12",
  "previousWaterMetering": "422",
  "currentWaterMetering": "432",
  "metersConsumed": "10",
  "differenceOfUse": "55",
  "total": "329",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "13",
  "previousWaterMetering": "286",
  "currentWaterMetering": "287",
  "metersConsumed": "1",
  "differenceOfUse": "55",
  "total": "139",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "14",
  "previousWaterMetering": "565",
  "currentWaterMetering": "575",
  "metersConsumed": "10",
  "differenceOfUse": "55",
  "total": "329",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "15",
  "previousWaterMetering": "252",
  "currentWaterMetering": "256",
  "metersConsumed": "4",
  "differenceOfUse": "55",
  "total": "191",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "16",
  "previousWaterMetering": "277",
  "currentWaterMetering": "283",
  "metersConsumed": "6",
  "differenceOfUse": "55",
  "total": "229",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "17",
  "previousWaterMetering": "346",
  "currentWaterMetering": "358",
  "metersConsumed": "12",
  "differenceOfUse": "55",
  "total": "377",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "18",
  "previousWaterMetering": "371",
  "currentWaterMetering": "374",
  "metersConsumed": "3",
  "differenceOfUse": "55",
  "total": "173",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "19",
  "previousWaterMetering": "131",
  "currentWaterMetering": "137",
  "metersConsumed": "6",
  "differenceOfUse": "55",
  "total": "229",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "20.1",
  "previousWaterMetering": "309",
  "currentWaterMetering": "0",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "0",
  "condo": "0",
  "caKey": "0",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "0"
},
{
  "houseId": "20",
  "previousWaterMetering": "456",
  "currentWaterMetering": "467",
  "metersConsumed": "11",
  "differenceOfUse": "55",
  "total": "352",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "21",
  "previousWaterMetering": "422",
  "currentWaterMetering": "430",
  "metersConsumed": "8",
  "differenceOfUse": "55",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "22",
  "previousWaterMetering": "388",
  "currentWaterMetering": "396",
  "metersConsumed": "8",
  "differenceOfUse": "55",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "23",
  "previousWaterMetering": "781",
  "currentWaterMetering": "794",
  "metersConsumed": "13",
  "differenceOfUse": "55",
  "total": "405",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "24",
  "previousWaterMetering": "354",
  "currentWaterMetering": "362",
  "metersConsumed": "8",
  "differenceOfUse": "55",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "25",
  "previousWaterMetering": "249",
  "currentWaterMetering": "254",
  "metersConsumed": "5",
  "differenceOfUse": "55",
  "total": "210",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "26",
  "previousWaterMetering": "36",
  "currentWaterMetering": "36",
  "metersConsumed": "0",
  "differenceOfUse": "55",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "27",
  "previousWaterMetering": "356",
  "currentWaterMetering": "364",
  "metersConsumed": "8",
  "differenceOfUse": "55",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "28",
  "previousWaterMetering": "53",
  "currentWaterMetering": "57",
  "metersConsumed": "4",
  "differenceOfUse": "55",
  "total": "191",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "29",
  "previousWaterMetering": "210",
  "currentWaterMetering": "215",
  "metersConsumed": "5",
  "differenceOfUse": "55",
  "total": "210",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "30",
  "previousWaterMetering": "593",
  "currentWaterMetering": "601",
  "metersConsumed": "8",
  "differenceOfUse": "55",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "31",
  "previousWaterMetering": "409",
  "currentWaterMetering": "418",
  "metersConsumed": "9",
  "differenceOfUse": "55",
  "total": "304",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "32",
  "previousWaterMetering": "617",
  "currentWaterMetering": "632",
  "metersConsumed": "15",
  "differenceOfUse": "55",
  "total": "459",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "33",
  "previousWaterMetering": "161",
  "currentWaterMetering": "163",
  "metersConsumed": "2",
  "differenceOfUse": "55",
  "total": "155",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "34",
  "previousWaterMetering": "527",
  "currentWaterMetering": "535",
  "metersConsumed": "8",
  "differenceOfUse": "55",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "35",
  "previousWaterMetering": "827",
  "currentWaterMetering": "846",
  "metersConsumed": "19",
  "differenceOfUse": "55",
  "total": "569",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "36",
  "previousWaterMetering": "509",
  "currentWaterMetering": "516",
  "metersConsumed": "7",
  "differenceOfUse": "55",
  "total": "250",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "37",
  "previousWaterMetering": "343",
  "currentWaterMetering": "352",
  "metersConsumed": "9",
  "differenceOfUse": "55",
  "total": "304",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "38",
  "previousWaterMetering": "507",
  "currentWaterMetering": "515",
  "metersConsumed": "8",
  "differenceOfUse": "55",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "39",
  "previousWaterMetering": "329",
  "currentWaterMetering": "335",
  "metersConsumed": "6",
  "differenceOfUse": "55",
  "total": "229",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "40",
  "previousWaterMetering": "106",
  "currentWaterMetering": "107",
  "metersConsumed": "1",
  "differenceOfUse": "55",
  "total": "139",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "41",
  "previousWaterMetering": "660",
  "currentWaterMetering": "671",
  "metersConsumed": "11",
  "differenceOfUse": "55",
  "total": "352",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "42",
  "previousWaterMetering": "649",
  "currentWaterMetering": "663",
  "metersConsumed": "14",
  "differenceOfUse": "55",
  "total": "432",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "43",
  "previousWaterMetering": "215",
  "currentWaterMetering": "221",
  "metersConsumed": "6",
  "differenceOfUse": "55",
  "total": "229",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "44",
  "previousWaterMetering": "140",
  "currentWaterMetering": "144",
  "metersConsumed": "4",
  "differenceOfUse": "55",
  "total": "191",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "45",
  "previousWaterMetering": "711",
  "currentWaterMetering": "731",
  "metersConsumed": "20",
  "differenceOfUse": "55",
  "total": "598",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "46",
  "previousWaterMetering": "252",
  "currentWaterMetering": "257",
  "metersConsumed": "5",
  "differenceOfUse": "55",
  "total": "210",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "47",
  "previousWaterMetering": "592",
  "currentWaterMetering": "601",
  "metersConsumed": "9",
  "differenceOfUse": "55",
  "total": "304",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "48",
  "previousWaterMetering": "277",
  "currentWaterMetering": "283",
  "metersConsumed": "6",
  "differenceOfUse": "55",
  "total": "229",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "49",
  "previousWaterMetering": "495",
  "currentWaterMetering": "510",
  "metersConsumed": "15",
  "differenceOfUse": "55",
  "total": "459",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "50",
  "previousWaterMetering": "563",
  "currentWaterMetering": "564",
  "metersConsumed": "1",
  "differenceOfUse": "55",
  "total": "139",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "51",
  "previousWaterMetering": "118",
  "currentWaterMetering": "120",
  "metersConsumed": "2",
  "differenceOfUse": "55",
  "total": "155",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "52",
  "previousWaterMetering": "357",
  "currentWaterMetering": "364",
  "metersConsumed": "7",
  "differenceOfUse": "55",
  "total": "250",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "53",
  "previousWaterMetering": "170",
  "currentWaterMetering": "176",
  "metersConsumed": "6",
  "differenceOfUse": "55",
  "total": "229",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "54",
  "previousWaterMetering": "570",
  "currentWaterMetering": "582",
  "metersConsumed": "12",
  "differenceOfUse": "55",
  "total": "377",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "55",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "56",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "55",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "57",
  "previousWaterMetering": "712",
  "currentWaterMetering": "723",
  "metersConsumed": "11",
  "differenceOfUse": "55",
  "total": "352",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "58",
  "previousWaterMetering": "453",
  "currentWaterMetering": "461",
  "metersConsumed": "8",
  "differenceOfUse": "55",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "59",
  "previousWaterMetering": "348",
  "currentWaterMetering": "360",
  "metersConsumed": "12",
  "differenceOfUse": "55",
  "total": "377",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "60",
  "previousWaterMetering": "390",
  "currentWaterMetering": "401",
  "metersConsumed": "11",
  "differenceOfUse": "55",
  "total": "352",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "61",
  "previousWaterMetering": "102",
  "currentWaterMetering": "105",
  "metersConsumed": "3",
  "differenceOfUse": "55",
  "total": "173",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "62",
  "previousWaterMetering": "370",
  "currentWaterMetering": "370",
  "metersConsumed": "0",
  "differenceOfUse": "55",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "63",
  "previousWaterMetering": "795",
  "currentWaterMetering": "810",
  "metersConsumed": "15",
  "differenceOfUse": "55",
  "total": "459",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "64",
  "previousWaterMetering": "243",
  "currentWaterMetering": "250",
  "metersConsumed": "7",
  "differenceOfUse": "55",
  "total": "250",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "65",
  "previousWaterMetering": "835",
  "currentWaterMetering": "848",
  "metersConsumed": "13",
  "differenceOfUse": "55",
  "total": "405",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "66",
  "previousWaterMetering": "176",
  "currentWaterMetering": "177",
  "metersConsumed": "1",
  "differenceOfUse": "55",
  "total": "139",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "67",
  "previousWaterMetering": "318",
  "currentWaterMetering": "325",
  "metersConsumed": "7",
  "differenceOfUse": "55",
  "total": "250",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "55",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "69",
  "previousWaterMetering": "570",
  "currentWaterMetering": "585",
  "metersConsumed": "15",
  "differenceOfUse": "55",
  "total": "459",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "70",
  "previousWaterMetering": "160",
  "currentWaterMetering": "166",
  "metersConsumed": "6",
  "differenceOfUse": "55",
  "total": "229",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "71",
  "previousWaterMetering": "350",
  "currentWaterMetering": "358",
  "metersConsumed": "8",
  "differenceOfUse": "55",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "72",
  "previousWaterMetering": "301",
  "currentWaterMetering": "308",
  "metersConsumed": "7",
  "differenceOfUse": "55",
  "total": "250",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "73",
  "previousWaterMetering": "261",
  "currentWaterMetering": "267",
  "metersConsumed": "6",
  "differenceOfUse": "55",
  "total": "229",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "74",
  "previousWaterMetering": "160",
  "currentWaterMetering": "162",
  "metersConsumed": "2",
  "differenceOfUse": "55",
  "total": "155",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "75",
  "previousWaterMetering": "491",
  "currentWaterMetering": "500",
  "metersConsumed": "9",
  "differenceOfUse": "55",
  "total": "304",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "76",
  "previousWaterMetering": "42",
  "currentWaterMetering": "42",
  "metersConsumed": "0",
  "differenceOfUse": "55",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "77",
  "previousWaterMetering": "847",
  "currentWaterMetering": "859",
  "metersConsumed": "12",
  "differenceOfUse": "55",
  "total": "377",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "78",
  "previousWaterMetering": "62",
  "currentWaterMetering": "64",
  "metersConsumed": "2",
  "differenceOfUse": "55",
  "total": "155",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "79",
  "previousWaterMetering": "410",
  "currentWaterMetering": "414",
  "metersConsumed": "4",
  "differenceOfUse": "55",
  "total": "191",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "80",
  "previousWaterMetering": "544",
  "currentWaterMetering": "561",
  "metersConsumed": "17",
  "differenceOfUse": "55",
  "total": "514",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "81",
  "previousWaterMetering": "198",
  "currentWaterMetering": "204",
  "metersConsumed": "6",
  "differenceOfUse": "55",
  "total": "229",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "82",
  "previousWaterMetering": "402",
  "currentWaterMetering": "408",
  "metersConsumed": "6",
  "differenceOfUse": "55",
  "total": "229",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "83",
  "previousWaterMetering": "245",
  "currentWaterMetering": "246",
  "metersConsumed": "1",
  "differenceOfUse": "55",
  "total": "139",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "84",
  "previousWaterMetering": "290",
  "currentWaterMetering": "295",
  "metersConsumed": "5",
  "differenceOfUse": "55",
  "total": "210",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "85",
  "previousWaterMetering": "324",
  "currentWaterMetering": "331",
  "metersConsumed": "7",
  "differenceOfUse": "55",
  "total": "250",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "86",
  "previousWaterMetering": "217",
  "currentWaterMetering": "227",
  "metersConsumed": "10",
  "differenceOfUse": "55",
  "total": "329",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "87",
  "previousWaterMetering": "364",
  "currentWaterMetering": "378",
  "metersConsumed": "14",
  "differenceOfUse": "55",
  "total": "432",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "88",
  "previousWaterMetering": "411",
  "currentWaterMetering": "417",
  "metersConsumed": "6",
  "differenceOfUse": "55",
  "total": "229",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "89",
  "previousWaterMetering": "742",
  "currentWaterMetering": "753",
  "metersConsumed": "11",
  "differenceOfUse": "55",
  "total": "352",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "90",
  "previousWaterMetering": "850",
  "currentWaterMetering": "876",
  "metersConsumed": "26",
  "differenceOfUse": "55",
  "total": "864",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "91",
  "previousWaterMetering": "357",
  "currentWaterMetering": "366",
  "metersConsumed": "9",
  "differenceOfUse": "55",
  "total": "304",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "92",
  "previousWaterMetering": "507",
  "currentWaterMetering": "514",
  "metersConsumed": "7",
  "differenceOfUse": "55",
  "total": "250",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "93",
  "previousWaterMetering": "293",
  "currentWaterMetering": "306",
  "metersConsumed": "13",
  "differenceOfUse": "55",
  "total": "405",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "94",
  "previousWaterMetering": "517",
  "currentWaterMetering": "528",
  "metersConsumed": "11",
  "differenceOfUse": "55",
  "total": "352",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "95",
  "previousWaterMetering": "64",
  "currentWaterMetering": "64",
  "metersConsumed": "0",
  "differenceOfUse": "55",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "96",
  "previousWaterMetering": "169",
  "currentWaterMetering": "172",
  "metersConsumed": "3",
  "differenceOfUse": "55",
  "total": "173",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "97",
  "previousWaterMetering": "222",
  "currentWaterMetering": "230",
  "metersConsumed": "8",
  "differenceOfUse": "55",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "98",
  "previousWaterMetering": "100",
  "currentWaterMetering": "105",
  "metersConsumed": "5",
  "differenceOfUse": "55",
  "total": "210",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "99",
  "previousWaterMetering": "237",
  "currentWaterMetering": "238",
  "metersConsumed": "1",
  "differenceOfUse": "55",
  "total": "139",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "55",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "101",
  "previousWaterMetering": "246",
  "currentWaterMetering": "252",
  "metersConsumed": "6",
  "differenceOfUse": "55",
  "total": "229",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "102",
  "previousWaterMetering": "160",
  "currentWaterMetering": "163",
  "metersConsumed": "3",
  "differenceOfUse": "55",
  "total": "173",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
},
{
  "houseId": "103",
  "previousWaterMetering": "13",
  "currentWaterMetering": "13",
  "metersConsumed": "0",
  "differenceOfUse": "55",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Enero",
  "paymentMonth": "Marzo",
  "year": "2026"
}]
;

export const reportShimul = data;
