 
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =
[{
  "houseId": "1",
  "previousWaterMetering": "552",
  "currentWaterMetering": "562",
  "metersConsumed": "10",
  "differenceOfUse": "22",
  "total": "296",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "2",
  "previousWaterMetering": "194",
  "currentWaterMetering": "197",
  "metersConsumed": "3",
  "differenceOfUse": "22",
  "total": "140",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "3",
  "previousWaterMetering": "548",
  "currentWaterMetering": "548",
  "metersConsumed": "0",
  "differenceOfUse": "22",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "4",
  "previousWaterMetering": "492",
  "currentWaterMetering": "502",
  "metersConsumed": "10",
  "differenceOfUse": "22",
  "total": "296",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "5",
  "previousWaterMetering": "481",
  "currentWaterMetering": "494",
  "metersConsumed": "13",
  "differenceOfUse": "22",
  "total": "372",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "6",
  "previousWaterMetering": "434",
  "currentWaterMetering": "456",
  "metersConsumed": "22",
  "differenceOfUse": "22",
  "total": "626",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "7",
  "previousWaterMetering": "616",
  "currentWaterMetering": "632",
  "metersConsumed": "16",
  "differenceOfUse": "22",
  "total": "452",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "8",
  "previousWaterMetering": "212",
  "currentWaterMetering": "213",
  "metersConsumed": "1",
  "differenceOfUse": "22",
  "total": "106",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "9",
  "previousWaterMetering": "291",
  "currentWaterMetering": "296",
  "metersConsumed": "5",
  "differenceOfUse": "22",
  "total": "177",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "10",
  "previousWaterMetering": "530",
  "currentWaterMetering": "545",
  "metersConsumed": "15",
  "differenceOfUse": "22",
  "total": "426",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "11",
  "previousWaterMetering": "736",
  "currentWaterMetering": "751",
  "metersConsumed": "15",
  "differenceOfUse": "22",
  "total": "426",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "12",
  "previousWaterMetering": "432",
  "currentWaterMetering": "443",
  "metersConsumed": "11",
  "differenceOfUse": "22",
  "total": "319",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "13",
  "previousWaterMetering": "287",
  "currentWaterMetering": "289",
  "metersConsumed": "2",
  "differenceOfUse": "22",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "14",
  "previousWaterMetering": "575",
  "currentWaterMetering": "597",
  "metersConsumed": "22",
  "differenceOfUse": "22",
  "total": "626",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "15",
  "previousWaterMetering": "256",
  "currentWaterMetering": "261",
  "metersConsumed": "5",
  "differenceOfUse": "22",
  "total": "177",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "16",
  "previousWaterMetering": "283",
  "currentWaterMetering": "291",
  "metersConsumed": "8",
  "differenceOfUse": "22",
  "total": "239",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "17",
  "previousWaterMetering": "358",
  "currentWaterMetering": "364",
  "metersConsumed": "6",
  "differenceOfUse": "22",
  "total": "196",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "18",
  "previousWaterMetering": "374",
  "currentWaterMetering": "376",
  "metersConsumed": "2",
  "differenceOfUse": "22",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "19",
  "previousWaterMetering": "137",
  "currentWaterMetering": "146",
  "metersConsumed": "9",
  "differenceOfUse": "22",
  "total": "271",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "20.1",
  "previousWaterMetering": "314",
  "currentWaterMetering": "0",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "0",
  "condo": "0",
  "caKey": "0",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "20",
  "previousWaterMetering": "467",
  "currentWaterMetering": "481",
  "metersConsumed": "14",
  "differenceOfUse": "22",
  "total": "399",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "21",
  "previousWaterMetering": "430",
  "currentWaterMetering": "439",
  "metersConsumed": "9",
  "differenceOfUse": "22",
  "total": "271",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "22",
  "previousWaterMetering": "396",
  "currentWaterMetering": "405",
  "metersConsumed": "9",
  "differenceOfUse": "22",
  "total": "271",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "23",
  "previousWaterMetering": "794",
  "currentWaterMetering": "810",
  "metersConsumed": "16",
  "differenceOfUse": "22",
  "total": "452",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "24",
  "previousWaterMetering": "362",
  "currentWaterMetering": "372",
  "metersConsumed": "10",
  "differenceOfUse": "22",
  "total": "296",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "25",
  "previousWaterMetering": "254",
  "currentWaterMetering": "260",
  "metersConsumed": "6",
  "differenceOfUse": "22",
  "total": "196",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "26",
  "previousWaterMetering": "36",
  "currentWaterMetering": "36",
  "metersConsumed": "0",
  "differenceOfUse": "22",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "27",
  "previousWaterMetering": "364",
  "currentWaterMetering": "371",
  "metersConsumed": "7",
  "differenceOfUse": "22",
  "total": "217",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "28",
  "previousWaterMetering": "57",
  "currentWaterMetering": "60",
  "metersConsumed": "3",
  "differenceOfUse": "22",
  "total": "140",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "29",
  "previousWaterMetering": "215",
  "currentWaterMetering": "219",
  "metersConsumed": "4",
  "differenceOfUse": "22",
  "total": "158",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "30",
  "previousWaterMetering": "601",
  "currentWaterMetering": "612",
  "metersConsumed": "11",
  "differenceOfUse": "22",
  "total": "319",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "31",
  "previousWaterMetering": "418",
  "currentWaterMetering": "431",
  "metersConsumed": "13",
  "differenceOfUse": "22",
  "total": "372",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "32",
  "previousWaterMetering": "632",
  "currentWaterMetering": "650",
  "metersConsumed": "18",
  "differenceOfUse": "22",
  "total": "508",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "33",
  "previousWaterMetering": "163",
  "currentWaterMetering": "165",
  "metersConsumed": "2",
  "differenceOfUse": "22",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "34",
  "previousWaterMetering": "535",
  "currentWaterMetering": "545",
  "metersConsumed": "10",
  "differenceOfUse": "22",
  "total": "296",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "35",
  "previousWaterMetering": "846",
  "currentWaterMetering": "869",
  "metersConsumed": "23",
  "differenceOfUse": "22",
  "total": "657",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "36",
  "previousWaterMetering": "516",
  "currentWaterMetering": "524",
  "metersConsumed": "8",
  "differenceOfUse": "22",
  "total": "239",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "37",
  "previousWaterMetering": "352",
  "currentWaterMetering": "361",
  "metersConsumed": "9",
  "differenceOfUse": "22",
  "total": "271",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "38",
  "previousWaterMetering": "515",
  "currentWaterMetering": "519",
  "metersConsumed": "4",
  "differenceOfUse": "22",
  "total": "158",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "39",
  "previousWaterMetering": "335",
  "currentWaterMetering": "343",
  "metersConsumed": "8",
  "differenceOfUse": "22",
  "total": "239",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "40",
  "previousWaterMetering": "107",
  "currentWaterMetering": "108",
  "metersConsumed": "1",
  "differenceOfUse": "22",
  "total": "106",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "41",
  "previousWaterMetering": "671",
  "currentWaterMetering": "681",
  "metersConsumed": "10",
  "differenceOfUse": "22",
  "total": "296",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "42",
  "previousWaterMetering": "663",
  "currentWaterMetering": "679",
  "metersConsumed": "16",
  "differenceOfUse": "22",
  "total": "452",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "43",
  "previousWaterMetering": "221",
  "currentWaterMetering": "229",
  "metersConsumed": "8",
  "differenceOfUse": "22",
  "total": "239",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "44",
  "previousWaterMetering": "144",
  "currentWaterMetering": "150",
  "metersConsumed": "6",
  "differenceOfUse": "22",
  "total": "196",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "45",
  "previousWaterMetering": "731",
  "currentWaterMetering": "751",
  "metersConsumed": "20",
  "differenceOfUse": "22",
  "total": "565",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "46",
  "previousWaterMetering": "257",
  "currentWaterMetering": "262",
  "metersConsumed": "5",
  "differenceOfUse": "22",
  "total": "177",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "47",
  "previousWaterMetering": "601",
  "currentWaterMetering": "607",
  "metersConsumed": "6",
  "differenceOfUse": "22",
  "total": "196",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "48",
  "previousWaterMetering": "283",
  "currentWaterMetering": "291",
  "metersConsumed": "8",
  "differenceOfUse": "22",
  "total": "239",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "49",
  "previousWaterMetering": "510",
  "currentWaterMetering": "526",
  "metersConsumed": "16",
  "differenceOfUse": "22",
  "total": "452",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "50",
  "previousWaterMetering": "564",
  "currentWaterMetering": "565",
  "metersConsumed": "1",
  "differenceOfUse": "22",
  "total": "106",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "51",
  "previousWaterMetering": "120",
  "currentWaterMetering": "122",
  "metersConsumed": "2",
  "differenceOfUse": "22",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "52",
  "previousWaterMetering": "364",
  "currentWaterMetering": "370",
  "metersConsumed": "6",
  "differenceOfUse": "22",
  "total": "196",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "53",
  "previousWaterMetering": "176",
  "currentWaterMetering": "183",
  "metersConsumed": "7",
  "differenceOfUse": "22",
  "total": "217",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "54",
  "previousWaterMetering": "582",
  "currentWaterMetering": "595",
  "metersConsumed": "13",
  "differenceOfUse": "22",
  "total": "372",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "22",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "56",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "22",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "57",
  "previousWaterMetering": "723",
  "currentWaterMetering": "737",
  "metersConsumed": "14",
  "differenceOfUse": "22",
  "total": "399",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "58",
  "previousWaterMetering": "461",
  "currentWaterMetering": "470",
  "metersConsumed": "9",
  "differenceOfUse": "22",
  "total": "271",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "59",
  "previousWaterMetering": "360",
  "currentWaterMetering": "371",
  "metersConsumed": "11",
  "differenceOfUse": "22",
  "total": "319",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "60",
  "previousWaterMetering": "401",
  "currentWaterMetering": "413",
  "metersConsumed": "12",
  "differenceOfUse": "22",
  "total": "344",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "61",
  "previousWaterMetering": "105",
  "currentWaterMetering": "106",
  "metersConsumed": "1",
  "differenceOfUse": "22",
  "total": "106",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "62",
  "previousWaterMetering": "370",
  "currentWaterMetering": "373",
  "metersConsumed": "3",
  "differenceOfUse": "22",
  "total": "140",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "63",
  "previousWaterMetering": "810",
  "currentWaterMetering": "825",
  "metersConsumed": "15",
  "differenceOfUse": "22",
  "total": "426",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "64",
  "previousWaterMetering": "250",
  "currentWaterMetering": "259",
  "metersConsumed": "9",
  "differenceOfUse": "22",
  "total": "271",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "65",
  "previousWaterMetering": "848",
  "currentWaterMetering": "862",
  "metersConsumed": "14",
  "differenceOfUse": "22",
  "total": "399",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "66",
  "previousWaterMetering": "177",
  "currentWaterMetering": "179",
  "metersConsumed": "2",
  "differenceOfUse": "22",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "67",
  "previousWaterMetering": "325",
  "currentWaterMetering": "335",
  "metersConsumed": "10",
  "differenceOfUse": "22",
  "total": "296",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "22",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "69",
  "previousWaterMetering": "585",
  "currentWaterMetering": "603",
  "metersConsumed": "18",
  "differenceOfUse": "22",
  "total": "508",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "70",
  "previousWaterMetering": "166",
  "currentWaterMetering": "173",
  "metersConsumed": "7",
  "differenceOfUse": "22",
  "total": "217",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "71",
  "previousWaterMetering": "358",
  "currentWaterMetering": "366",
  "metersConsumed": "8",
  "differenceOfUse": "22",
  "total": "239",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "72",
  "previousWaterMetering": "308",
  "currentWaterMetering": "317",
  "metersConsumed": "9",
  "differenceOfUse": "22",
  "total": "271",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "73",
  "previousWaterMetering": "267",
  "currentWaterMetering": "273",
  "metersConsumed": "6",
  "differenceOfUse": "22",
  "total": "196",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "74",
  "previousWaterMetering": "162",
  "currentWaterMetering": "165",
  "metersConsumed": "3",
  "differenceOfUse": "22",
  "total": "140",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "75",
  "previousWaterMetering": "500",
  "currentWaterMetering": "508",
  "metersConsumed": "8",
  "differenceOfUse": "22",
  "total": "239",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "76",
  "previousWaterMetering": "42",
  "currentWaterMetering": "43",
  "metersConsumed": "1",
  "differenceOfUse": "22",
  "total": "106",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "77",
  "previousWaterMetering": "859",
  "currentWaterMetering": "859",
  "metersConsumed": "0",
  "differenceOfUse": "22",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "78",
  "previousWaterMetering": "64",
  "currentWaterMetering": "65",
  "metersConsumed": "1",
  "differenceOfUse": "22",
  "total": "106",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "79",
  "previousWaterMetering": "414",
  "currentWaterMetering": "422",
  "metersConsumed": "8",
  "differenceOfUse": "22",
  "total": "239",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "80",
  "previousWaterMetering": "561",
  "currentWaterMetering": "579",
  "metersConsumed": "18",
  "differenceOfUse": "22",
  "total": "508",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "81",
  "previousWaterMetering": "204",
  "currentWaterMetering": "218",
  "metersConsumed": "14",
  "differenceOfUse": "22",
  "total": "399",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "82",
  "previousWaterMetering": "408",
  "currentWaterMetering": "415",
  "metersConsumed": "7",
  "differenceOfUse": "22",
  "total": "217",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "83",
  "previousWaterMetering": "246",
  "currentWaterMetering": "246",
  "metersConsumed": "0",
  "differenceOfUse": "22",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "84",
  "previousWaterMetering": "295",
  "currentWaterMetering": "301",
  "metersConsumed": "6",
  "differenceOfUse": "22",
  "total": "196",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "85",
  "previousWaterMetering": "331",
  "currentWaterMetering": "341",
  "metersConsumed": "10",
  "differenceOfUse": "22",
  "total": "296",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "86",
  "previousWaterMetering": "227",
  "currentWaterMetering": "239",
  "metersConsumed": "12",
  "differenceOfUse": "22",
  "total": "344",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "87",
  "previousWaterMetering": "378",
  "currentWaterMetering": "390",
  "metersConsumed": "12",
  "differenceOfUse": "22",
  "total": "344",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "88",
  "previousWaterMetering": "417",
  "currentWaterMetering": "422",
  "metersConsumed": "5",
  "differenceOfUse": "22",
  "total": "177",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "89",
  "previousWaterMetering": "753",
  "currentWaterMetering": "769",
  "metersConsumed": "16",
  "differenceOfUse": "22",
  "total": "452",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "90",
  "previousWaterMetering": "876",
  "currentWaterMetering": "905",
  "metersConsumed": "29",
  "differenceOfUse": "22",
  "total": "1029",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "91",
  "previousWaterMetering": "366",
  "currentWaterMetering": "374",
  "metersConsumed": "8",
  "differenceOfUse": "22",
  "total": "239",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "92",
  "previousWaterMetering": "514",
  "currentWaterMetering": "522",
  "metersConsumed": "8",
  "differenceOfUse": "22",
  "total": "239",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "93",
  "previousWaterMetering": "306",
  "currentWaterMetering": "320",
  "metersConsumed": "14",
  "differenceOfUse": "22",
  "total": "399",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "94",
  "previousWaterMetering": "528",
  "currentWaterMetering": "538",
  "metersConsumed": "10",
  "differenceOfUse": "22",
  "total": "296",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "95",
  "previousWaterMetering": "64",
  "currentWaterMetering": "66",
  "metersConsumed": "2",
  "differenceOfUse": "22",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "96",
  "previousWaterMetering": "172",
  "currentWaterMetering": "174",
  "metersConsumed": "2",
  "differenceOfUse": "22",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "97",
  "previousWaterMetering": "230",
  "currentWaterMetering": "232",
  "metersConsumed": "2",
  "differenceOfUse": "22",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "98",
  "previousWaterMetering": "105",
  "currentWaterMetering": "106",
  "metersConsumed": "1",
  "differenceOfUse": "22",
  "total": "106",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "99",
  "previousWaterMetering": "238",
  "currentWaterMetering": "238",
  "metersConsumed": "0",
  "differenceOfUse": "22",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "22",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "101",
  "previousWaterMetering": "252",
  "currentWaterMetering": "262",
  "metersConsumed": "10",
  "differenceOfUse": "22",
  "total": "296",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "102",
  "previousWaterMetering": "163",
  "currentWaterMetering": "165",
  "metersConsumed": "2",
  "differenceOfUse": "22",
  "total": "122",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
},
{
  "houseId": "103",
  "previousWaterMetering": "13",
  "currentWaterMetering": "13",
  "metersConsumed": "0",
  "differenceOfUse": "22",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2026"
}]
;

export const reportShimul = data;
