
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =
[{
  "houseId": "1",
  "previousWaterMetering": "490",
  "currentWaterMetering": "505",
  "metersConsumed": "15",
  "differenceOfUse": "5",
  "total": "398",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "2",
  "previousWaterMetering": "174",
  "currentWaterMetering": "180",
  "metersConsumed": "6",
  "differenceOfUse": "5",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "3",
  "previousWaterMetering": "542",
  "currentWaterMetering": "548",
  "metersConsumed": "6",
  "differenceOfUse": "5",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "4",
  "previousWaterMetering": "441",
  "currentWaterMetering": "448",
  "metersConsumed": "7",
  "differenceOfUse": "5",
  "total": "195",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "5",
  "previousWaterMetering": "239",
  "currentWaterMetering": "239",
  "metersConsumed": "0",
  "differenceOfUse": "5",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "6",
  "previousWaterMetering": "365",
  "currentWaterMetering": "388",
  "metersConsumed": "23",
  "differenceOfUse": "5",
  "total": "623",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "7",
  "previousWaterMetering": "542",
  "currentWaterMetering": "554",
  "metersConsumed": "12",
  "differenceOfUse": "5",
  "total": "318",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "8",
  "previousWaterMetering": "208",
  "currentWaterMetering": "209",
  "metersConsumed": "1",
  "differenceOfUse": "5",
  "total": "86",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "9",
  "previousWaterMetering": "264",
  "currentWaterMetering": "269",
  "metersConsumed": "5",
  "differenceOfUse": "5",
  "total": "155",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "10",
  "previousWaterMetering": "496",
  "currentWaterMetering": "502",
  "metersConsumed": "6",
  "differenceOfUse": "5",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "11",
  "previousWaterMetering": "662",
  "currentWaterMetering": "676",
  "metersConsumed": "14",
  "differenceOfUse": "5",
  "total": "372",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "12",
  "previousWaterMetering": "378",
  "currentWaterMetering": "387",
  "metersConsumed": "9",
  "differenceOfUse": "5",
  "total": "247",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "13",
  "previousWaterMetering": "268",
  "currentWaterMetering": "276",
  "metersConsumed": "8",
  "differenceOfUse": "5",
  "total": "216",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "14",
  "previousWaterMetering": "509",
  "currentWaterMetering": "523",
  "metersConsumed": "14",
  "differenceOfUse": "5",
  "total": "372",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "15",
  "previousWaterMetering": "236",
  "currentWaterMetering": "240",
  "metersConsumed": "4",
  "differenceOfUse": "5",
  "total": "137",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "16",
  "previousWaterMetering": "251",
  "currentWaterMetering": "258",
  "metersConsumed": "7",
  "differenceOfUse": "5",
  "total": "195",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "17",
  "previousWaterMetering": "318",
  "currentWaterMetering": "324",
  "metersConsumed": "6",
  "differenceOfUse": "5",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "18",
  "previousWaterMetering": "356",
  "currentWaterMetering": "361",
  "metersConsumed": "5",
  "differenceOfUse": "5",
  "total": "155",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "19",
  "previousWaterMetering": "90",
  "currentWaterMetering": "107",
  "metersConsumed": "17",
  "differenceOfUse": "5",
  "total": "451",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "20",
  "previousWaterMetering": "427",
  "currentWaterMetering": "432",
  "metersConsumed": "5",
  "differenceOfUse": "5",
  "total": "155",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "21",
  "previousWaterMetering": "382",
  "currentWaterMetering": "395",
  "metersConsumed": "13",
  "differenceOfUse": "5",
  "total": "346",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "22",
  "previousWaterMetering": "354",
  "currentWaterMetering": "364",
  "metersConsumed": "10",
  "differenceOfUse": "5",
  "total": "271",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "23",
  "previousWaterMetering": "712",
  "currentWaterMetering": "731",
  "metersConsumed": "19",
  "differenceOfUse": "5",
  "total": "506",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "24",
  "previousWaterMetering": "318",
  "currentWaterMetering": "327",
  "metersConsumed": "9",
  "differenceOfUse": "5",
  "total": "247",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "25",
  "previousWaterMetering": "223",
  "currentWaterMetering": "229",
  "metersConsumed": "6",
  "differenceOfUse": "5",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "26",
  "previousWaterMetering": "34",
  "currentWaterMetering": "34",
  "metersConsumed": "0",
  "differenceOfUse": "5",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "27",
  "previousWaterMetering": "322",
  "currentWaterMetering": "334",
  "metersConsumed": "12",
  "differenceOfUse": "5",
  "total": "318",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "28",
  "previousWaterMetering": "43",
  "currentWaterMetering": "44",
  "metersConsumed": "1",
  "differenceOfUse": "5",
  "total": "86",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "29",
  "previousWaterMetering": "196",
  "currentWaterMetering": "196",
  "metersConsumed": "0",
  "differenceOfUse": "5",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "30",
  "previousWaterMetering": "549",
  "currentWaterMetering": "564",
  "metersConsumed": "15",
  "differenceOfUse": "5",
  "total": "398",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "31",
  "previousWaterMetering": "366",
  "currentWaterMetering": "377",
  "metersConsumed": "11",
  "differenceOfUse": "5",
  "total": "294",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "32",
  "previousWaterMetering": "559",
  "currentWaterMetering": "574",
  "metersConsumed": "15",
  "differenceOfUse": "5",
  "total": "398",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "33",
  "previousWaterMetering": "155",
  "currentWaterMetering": "157",
  "metersConsumed": "2",
  "differenceOfUse": "5",
  "total": "102",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "34",
  "previousWaterMetering": "494",
  "currentWaterMetering": "501",
  "metersConsumed": "7",
  "differenceOfUse": "5",
  "total": "195",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "35",
  "previousWaterMetering": "742",
  "currentWaterMetering": "760",
  "metersConsumed": "18",
  "differenceOfUse": "5",
  "total": "478",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "36",
  "previousWaterMetering": "476",
  "currentWaterMetering": "487",
  "metersConsumed": "11",
  "differenceOfUse": "5",
  "total": "294",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "37",
  "previousWaterMetering": "304",
  "currentWaterMetering": "316",
  "metersConsumed": "12",
  "differenceOfUse": "5",
  "total": "318",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "38",
  "previousWaterMetering": "470",
  "currentWaterMetering": "481",
  "metersConsumed": "11",
  "differenceOfUse": "5",
  "total": "294",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "39",
  "previousWaterMetering": "307",
  "currentWaterMetering": "314",
  "metersConsumed": "7",
  "differenceOfUse": "5",
  "total": "195",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "40",
  "previousWaterMetering": "101",
  "currentWaterMetering": "102",
  "metersConsumed": "1",
  "differenceOfUse": "5",
  "total": "86",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "41",
  "previousWaterMetering": "624",
  "currentWaterMetering": "632",
  "metersConsumed": "8",
  "differenceOfUse": "5",
  "total": "216",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "42",
  "previousWaterMetering": "590",
  "currentWaterMetering": "605",
  "metersConsumed": "15",
  "differenceOfUse": "5",
  "total": "398",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "43",
  "previousWaterMetering": "204",
  "currentWaterMetering": "207",
  "metersConsumed": "3",
  "differenceOfUse": "5",
  "total": "119",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "44",
  "previousWaterMetering": "122",
  "currentWaterMetering": "127",
  "metersConsumed": "5",
  "differenceOfUse": "5",
  "total": "155",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "45",
  "previousWaterMetering": "642",
  "currentWaterMetering": "660",
  "metersConsumed": "18",
  "differenceOfUse": "5",
  "total": "478",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "46",
  "previousWaterMetering": "228",
  "currentWaterMetering": "235",
  "metersConsumed": "7",
  "differenceOfUse": "5",
  "total": "195",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "47",
  "previousWaterMetering": "563",
  "currentWaterMetering": "572",
  "metersConsumed": "9",
  "differenceOfUse": "5",
  "total": "247",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "48",
  "previousWaterMetering": "239",
  "currentWaterMetering": "248",
  "metersConsumed": "9",
  "differenceOfUse": "5",
  "total": "247",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "49",
  "previousWaterMetering": "444",
  "currentWaterMetering": "457",
  "metersConsumed": "13",
  "differenceOfUse": "5",
  "total": "346",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "50",
  "previousWaterMetering": "557",
  "currentWaterMetering": "560",
  "metersConsumed": "3",
  "differenceOfUse": "5",
  "total": "119",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "51",
  "previousWaterMetering": "108",
  "currentWaterMetering": "111",
  "metersConsumed": "3",
  "differenceOfUse": "5",
  "total": "119",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "52",
  "previousWaterMetering": "337",
  "currentWaterMetering": "342",
  "metersConsumed": "5",
  "differenceOfUse": "5",
  "total": "155",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "53",
  "previousWaterMetering": "155",
  "currentWaterMetering": "159",
  "metersConsumed": "4",
  "differenceOfUse": "5",
  "total": "137",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "54",
  "previousWaterMetering": "518",
  "currentWaterMetering": "532",
  "metersConsumed": "14",
  "differenceOfUse": "5",
  "total": "372",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "5",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "56",
  "previousWaterMetering": "7",
  "currentWaterMetering": "7",
  "metersConsumed": "0",
  "differenceOfUse": "5",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "57",
  "previousWaterMetering": "670",
  "currentWaterMetering": "682",
  "metersConsumed": "12",
  "differenceOfUse": "5",
  "total": "318",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "58",
  "previousWaterMetering": "428",
  "currentWaterMetering": "436",
  "metersConsumed": "8",
  "differenceOfUse": "5",
  "total": "216",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "59",
  "previousWaterMetering": "311",
  "currentWaterMetering": "321",
  "metersConsumed": "10",
  "differenceOfUse": "5",
  "total": "271",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "60",
  "previousWaterMetering": "352",
  "currentWaterMetering": "365",
  "metersConsumed": "13",
  "differenceOfUse": "5",
  "total": "346",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "61",
  "previousWaterMetering": "97",
  "currentWaterMetering": "99",
  "metersConsumed": "2",
  "differenceOfUse": "5",
  "total": "102",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "62",
  "previousWaterMetering": "332",
  "currentWaterMetering": "335",
  "metersConsumed": "3",
  "differenceOfUse": "5",
  "total": "119",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "63",
  "previousWaterMetering": "738",
  "currentWaterMetering": "754",
  "metersConsumed": "16",
  "differenceOfUse": "5",
  "total": "423",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "64",
  "previousWaterMetering": "215",
  "currentWaterMetering": "222",
  "metersConsumed": "7",
  "differenceOfUse": "5",
  "total": "195",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "65",
  "previousWaterMetering": "778",
  "currentWaterMetering": "793",
  "metersConsumed": "15",
  "differenceOfUse": "5",
  "total": "398",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "66",
  "previousWaterMetering": "155",
  "currentWaterMetering": "158",
  "metersConsumed": "3",
  "differenceOfUse": "5",
  "total": "119",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "67",
  "previousWaterMetering": "289",
  "currentWaterMetering": "296",
  "metersConsumed": "7",
  "differenceOfUse": "5",
  "total": "195",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "5",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "69",
  "previousWaterMetering": "513",
  "currentWaterMetering": "527",
  "metersConsumed": "14",
  "differenceOfUse": "5",
  "total": "372",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "70",
  "previousWaterMetering": "137",
  "currentWaterMetering": "142",
  "metersConsumed": "5",
  "differenceOfUse": "5",
  "total": "155",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "71",
  "previousWaterMetering": "320",
  "currentWaterMetering": "327",
  "metersConsumed": "7",
  "differenceOfUse": "5",
  "total": "195",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "72",
  "previousWaterMetering": "273",
  "currentWaterMetering": "280",
  "metersConsumed": "7",
  "differenceOfUse": "5",
  "total": "195",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "73",
  "previousWaterMetering": "239",
  "currentWaterMetering": "244",
  "metersConsumed": "5",
  "differenceOfUse": "5",
  "total": "155",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "74",
  "previousWaterMetering": "147",
  "currentWaterMetering": "150",
  "metersConsumed": "3",
  "differenceOfUse": "5",
  "total": "119",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "75",
  "previousWaterMetering": "458",
  "currentWaterMetering": "467",
  "metersConsumed": "9",
  "differenceOfUse": "5",
  "total": "247",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "76",
  "previousWaterMetering": "41",
  "currentWaterMetering": "41",
  "metersConsumed": "0",
  "differenceOfUse": "5",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "77",
  "previousWaterMetering": "770",
  "currentWaterMetering": "786",
  "metersConsumed": "16",
  "differenceOfUse": "5",
  "total": "423",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "78",
  "previousWaterMetering": "48",
  "currentWaterMetering": "52",
  "metersConsumed": "4",
  "differenceOfUse": "5",
  "total": "137",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "79",
  "previousWaterMetering": "384",
  "currentWaterMetering": "389",
  "metersConsumed": "5",
  "differenceOfUse": "5",
  "total": "155",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "80",
  "previousWaterMetering": "486",
  "currentWaterMetering": "497",
  "metersConsumed": "11",
  "differenceOfUse": "5",
  "total": "294",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "81",
  "previousWaterMetering": "151",
  "currentWaterMetering": "164",
  "metersConsumed": "13",
  "differenceOfUse": "5",
  "total": "346",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "82",
  "previousWaterMetering": "365",
  "currentWaterMetering": "376",
  "metersConsumed": "11",
  "differenceOfUse": "5",
  "total": "294",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "83",
  "previousWaterMetering": "228",
  "currentWaterMetering": "233",
  "metersConsumed": "5",
  "differenceOfUse": "5",
  "total": "155",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "84",
  "previousWaterMetering": "270",
  "currentWaterMetering": "272",
  "metersConsumed": "2",
  "differenceOfUse": "5",
  "total": "102",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "85",
  "previousWaterMetering": "292",
  "currentWaterMetering": "300",
  "metersConsumed": "8",
  "differenceOfUse": "5",
  "total": "216",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "86",
  "previousWaterMetering": "159",
  "currentWaterMetering": "176",
  "metersConsumed": "17",
  "differenceOfUse": "5",
  "total": "451",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "87",
  "previousWaterMetering": "303",
  "currentWaterMetering": "322",
  "metersConsumed": "19",
  "differenceOfUse": "5",
  "total": "506",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "88",
  "previousWaterMetering": "388",
  "currentWaterMetering": "396",
  "metersConsumed": "8",
  "differenceOfUse": "5",
  "total": "216",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "89",
  "previousWaterMetering": "696",
  "currentWaterMetering": "708",
  "metersConsumed": "12",
  "differenceOfUse": "5",
  "total": "318",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "90",
  "previousWaterMetering": "741",
  "currentWaterMetering": "769",
  "metersConsumed": "28",
  "differenceOfUse": "5",
  "total": "917",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "91",
  "previousWaterMetering": "330",
  "currentWaterMetering": "338",
  "metersConsumed": "8",
  "differenceOfUse": "5",
  "total": "216",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "92",
  "previousWaterMetering": "476",
  "currentWaterMetering": "483",
  "metersConsumed": "7",
  "differenceOfUse": "5",
  "total": "195",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "93",
  "previousWaterMetering": "251",
  "currentWaterMetering": "262",
  "metersConsumed": "11",
  "differenceOfUse": "5",
  "total": "294",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "94",
  "previousWaterMetering": "485",
  "currentWaterMetering": "494",
  "metersConsumed": "9",
  "differenceOfUse": "5",
  "total": "247",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "95",
  "previousWaterMetering": "64",
  "currentWaterMetering": "64",
  "metersConsumed": "0",
  "differenceOfUse": "5",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "96",
  "previousWaterMetering": "155",
  "currentWaterMetering": "159",
  "metersConsumed": "4",
  "differenceOfUse": "5",
  "total": "137",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "97",
  "previousWaterMetering": "211",
  "currentWaterMetering": "217",
  "metersConsumed": "6",
  "differenceOfUse": "5",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "98",
  "previousWaterMetering": "100",
  "currentWaterMetering": "100",
  "metersConsumed": "0",
  "differenceOfUse": "5",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "99",
  "previousWaterMetering": "234",
  "currentWaterMetering": "234",
  "metersConsumed": "0",
  "differenceOfUse": "5",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "5",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "101",
  "previousWaterMetering": "223",
  "currentWaterMetering": "228",
  "metersConsumed": "5",
  "differenceOfUse": "5",
  "total": "155",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "102",
  "previousWaterMetering": "149",
  "currentWaterMetering": "152",
  "metersConsumed": "3",
  "differenceOfUse": "5",
  "total": "119",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
},
{
  "houseId": "103",
  "previousWaterMetering": "13",
  "currentWaterMetering": "13",
  "metersConsumed": "0",
  "differenceOfUse": "5",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Septiembre",
  "paymentMonth": "Noviembre",
  "year": "2025"
}]
;

export const reportShimul = data;
