
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] = 
[
  {
    "houseId": "1",
    "previousWaterMetering": "320",
    "currentWaterMetering": "331",
    "metersConsumed": "11",
    "differenceOfUse": "62",
    "total": "337",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "2",
    "previousWaterMetering": "79",
    "currentWaterMetering": "84",
    "metersConsumed": "5",
    "differenceOfUse": "62",
    "total": "205",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "3",
    "previousWaterMetering": "367",
    "currentWaterMetering": "382",
    "metersConsumed": "15",
    "differenceOfUse": "62",
    "total": "435",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "4",
    "previousWaterMetering": "270",
    "currentWaterMetering": "282",
    "metersConsumed": "12",
    "differenceOfUse": "62",
    "total": "359",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "5",
    "previousWaterMetering": "154",
    "currentWaterMetering": "162",
    "metersConsumed": "8",
    "differenceOfUse": "62",
    "total": "262",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "6",
    "previousWaterMetering": "272",
    "currentWaterMetering": "278",
    "metersConsumed": "6",
    "differenceOfUse": "62",
    "total": "223",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "7",
    "previousWaterMetering": "392",
    "currentWaterMetering": "403",
    "metersConsumed": "11",
    "differenceOfUse": "62",
    "total": "337",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "8",
    "previousWaterMetering": "87",
    "currentWaterMetering": "91",
    "metersConsumed": "4",
    "differenceOfUse": "62",
    "total": "187",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "9",
    "previousWaterMetering": "197",
    "currentWaterMetering": "202",
    "metersConsumed": "5",
    "differenceOfUse": "62",
    "total": "205",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "10",
    "previousWaterMetering": "369",
    "currentWaterMetering": "379",
    "metersConsumed": "10",
    "differenceOfUse": "62",
    "total": "315",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "11",
    "previousWaterMetering": "472",
    "currentWaterMetering": "485",
    "metersConsumed": "13",
    "differenceOfUse": "62",
    "total": "386",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "12",
    "previousWaterMetering": "262",
    "currentWaterMetering": "268",
    "metersConsumed": "6",
    "differenceOfUse": "62",
    "total": "223",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "13",
    "previousWaterMetering": "201",
    "currentWaterMetering": "208",
    "metersConsumed": "7",
    "differenceOfUse": "62",
    "total": "242",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "14",
    "previousWaterMetering": "356",
    "currentWaterMetering": "368",
    "metersConsumed": "12",
    "differenceOfUse": "62",
    "total": "359",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "15",
    "previousWaterMetering": "193",
    "currentWaterMetering": "197",
    "metersConsumed": "4",
    "differenceOfUse": "62",
    "total": "187",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "16",
    "previousWaterMetering": "168",
    "currentWaterMetering": "174",
    "metersConsumed": "6",
    "differenceOfUse": "62",
    "total": "223",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "17",
    "previousWaterMetering": "218",
    "currentWaterMetering": "225",
    "metersConsumed": "7",
    "differenceOfUse": "62",
    "total": "242",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "18",
    "previousWaterMetering": "277",
    "currentWaterMetering": "281",
    "metersConsumed": "4",
    "differenceOfUse": "62",
    "total": "187",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "19",
    "previousWaterMetering": "14",
    "currentWaterMetering": "21",
    "metersConsumed": "7",
    "differenceOfUse": "62",
    "total": "242",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "20",
    "previousWaterMetering": "221",
    "currentWaterMetering": "232",
    "metersConsumed": "11",
    "differenceOfUse": "62",
    "total": "337",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "21",
    "previousWaterMetering": "250",
    "currentWaterMetering": "259",
    "metersConsumed": "9",
    "differenceOfUse": "62",
    "total": "292",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "22",
    "previousWaterMetering": "253",
    "currentWaterMetering": "261",
    "metersConsumed": "8",
    "differenceOfUse": "62",
    "total": "262",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "23",
    "previousWaterMetering": "501",
    "currentWaterMetering": "517",
    "metersConsumed": "16",
    "differenceOfUse": "62",
    "total": "459",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "24",
    "previousWaterMetering": "220",
    "currentWaterMetering": "229",
    "metersConsumed": "9",
    "differenceOfUse": "62",
    "total": "292",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "25",
    "previousWaterMetering": "140",
    "currentWaterMetering": "144",
    "metersConsumed": "4",
    "differenceOfUse": "62",
    "total": "187",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "26",
    "previousWaterMetering": "34",
    "currentWaterMetering": "34",
    "metersConsumed": "0",
    "differenceOfUse": "62",
    "total": "124",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "27",
    "previousWaterMetering": "191",
    "currentWaterMetering": "198",
    "metersConsumed": "7",
    "differenceOfUse": "62",
    "total": "242",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "28",
    "previousWaterMetering": "41",
    "currentWaterMetering": "41",
    "metersConsumed": "0",
    "differenceOfUse": "62",
    "total": "124",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "29",
    "previousWaterMetering": "117",
    "currentWaterMetering": "118",
    "metersConsumed": "1",
    "differenceOfUse": "62",
    "total": "139",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "30",
    "previousWaterMetering": "376",
    "currentWaterMetering": "392",
    "metersConsumed": "16",
    "differenceOfUse": "62",
    "total": "459",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "31",
    "previousWaterMetering": "239",
    "currentWaterMetering": "245",
    "metersConsumed": "6",
    "differenceOfUse": "62",
    "total": "223",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "32",
    "previousWaterMetering": "379",
    "currentWaterMetering": "392",
    "metersConsumed": "13",
    "differenceOfUse": "62",
    "total": "386",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "33",
    "previousWaterMetering": "132",
    "currentWaterMetering": "134",
    "metersConsumed": "2",
    "differenceOfUse": "62",
    "total": "155",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "34",
    "previousWaterMetering": "343",
    "currentWaterMetering": "358",
    "metersConsumed": "15",
    "differenceOfUse": "62",
    "total": "435",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "35",
    "previousWaterMetering": "486",
    "currentWaterMetering": "503",
    "metersConsumed": "17",
    "differenceOfUse": "62",
    "total": "486",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "36",
    "previousWaterMetering": "299",
    "currentWaterMetering": "313",
    "metersConsumed": "14",
    "differenceOfUse": "62",
    "total": "410",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "37",
    "previousWaterMetering": "194",
    "currentWaterMetering": "205",
    "metersConsumed": "11",
    "differenceOfUse": "62",
    "total": "337",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "38",
    "previousWaterMetering": "396",
    "currentWaterMetering": "403",
    "metersConsumed": "7",
    "differenceOfUse": "62",
    "total": "242",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "39",
    "previousWaterMetering": "230",
    "currentWaterMetering": "238",
    "metersConsumed": "8",
    "differenceOfUse": "62",
    "total": "262",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "40",
    "previousWaterMetering": "86",
    "currentWaterMetering": "87",
    "metersConsumed": "1",
    "differenceOfUse": "62",
    "total": "139",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "41",
    "previousWaterMetering": "465",
    "currentWaterMetering": "480",
    "metersConsumed": "15",
    "differenceOfUse": "62",
    "total": "435",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "42",
    "previousWaterMetering": "389",
    "currentWaterMetering": "403",
    "metersConsumed": "14",
    "differenceOfUse": "62",
    "total": "410",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "43",
    "previousWaterMetering": "179",
    "currentWaterMetering": "181",
    "metersConsumed": "2",
    "differenceOfUse": "62",
    "total": "155",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "44",
    "previousWaterMetering": "75",
    "currentWaterMetering": "77",
    "metersConsumed": "2",
    "differenceOfUse": "62",
    "total": "155",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "45",
    "previousWaterMetering": "453",
    "currentWaterMetering": "467",
    "metersConsumed": "14",
    "differenceOfUse": "62",
    "total": "410",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "46",
    "previousWaterMetering": "160",
    "currentWaterMetering": "164",
    "metersConsumed": "4",
    "differenceOfUse": "62",
    "total": "187",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "47",
    "previousWaterMetering": "451",
    "currentWaterMetering": "467",
    "metersConsumed": "16",
    "differenceOfUse": "62",
    "total": "459",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "48",
    "previousWaterMetering": "134",
    "currentWaterMetering": "140",
    "metersConsumed": "6",
    "differenceOfUse": "62",
    "total": "223",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "49",
    "previousWaterMetering": "298",
    "currentWaterMetering": "310",
    "metersConsumed": "12",
    "differenceOfUse": "62",
    "total": "359",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "50",
    "previousWaterMetering": "138",
    "currentWaterMetering": "143",
    "metersConsumed": "5",
    "differenceOfUse": "62",
    "total": "205",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "51",
    "previousWaterMetering": "74",
    "currentWaterMetering": "77",
    "metersConsumed": "3",
    "differenceOfUse": "62",
    "total": "171",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "52",
    "previousWaterMetering": "253",
    "currentWaterMetering": "259",
    "metersConsumed": "6",
    "differenceOfUse": "62",
    "total": "223",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "53",
    "previousWaterMetering": "110",
    "currentWaterMetering": "112",
    "metersConsumed": "2",
    "differenceOfUse": "62",
    "total": "155",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "54",
    "previousWaterMetering": "373",
    "currentWaterMetering": "383",
    "metersConsumed": "10",
    "differenceOfUse": "62",
    "total": "315",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "55",
    "previousWaterMetering": "11",
    "currentWaterMetering": "11",
    "metersConsumed": "0",
    "differenceOfUse": "62",
    "total": "124",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "56",
    "previousWaterMetering": "5",
    "currentWaterMetering": "5",
    "metersConsumed": "0",
    "differenceOfUse": "62",
    "total": "124",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "57",
    "previousWaterMetering": "581",
    "currentWaterMetering": "584",
    "metersConsumed": "3",
    "differenceOfUse": "62",
    "total": "171",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "58",
    "previousWaterMetering": "338",
    "currentWaterMetering": "347",
    "metersConsumed": "9",
    "differenceOfUse": "62",
    "total": "292",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "59",
    "previousWaterMetering": "168",
    "currentWaterMetering": "179",
    "metersConsumed": "11",
    "differenceOfUse": "62",
    "total": "337",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "60",
    "previousWaterMetering": "220",
    "currentWaterMetering": "232",
    "metersConsumed": "12",
    "differenceOfUse": "62",
    "total": "359",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "61",
    "previousWaterMetering": "71",
    "currentWaterMetering": "76",
    "metersConsumed": "5",
    "differenceOfUse": "62",
    "total": "205",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "62",
    "previousWaterMetering": "189",
    "currentWaterMetering": "196",
    "metersConsumed": "7",
    "differenceOfUse": "62",
    "total": "242",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "63",
    "previousWaterMetering": "507",
    "currentWaterMetering": "522",
    "metersConsumed": "15",
    "differenceOfUse": "62",
    "total": "435",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "64",
    "previousWaterMetering": "140",
    "currentWaterMetering": "147",
    "metersConsumed": "7",
    "differenceOfUse": "62",
    "total": "242",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "65",
    "previousWaterMetering": "552",
    "currentWaterMetering": "569",
    "metersConsumed": "17",
    "differenceOfUse": "62",
    "total": "486",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "66",
    "previousWaterMetering": "124",
    "currentWaterMetering": "126",
    "metersConsumed": "2",
    "differenceOfUse": "62",
    "total": "155",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "67",
    "previousWaterMetering": "190",
    "currentWaterMetering": "196",
    "metersConsumed": "6",
    "differenceOfUse": "62",
    "total": "223",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "68",
    "previousWaterMetering": "8",
    "currentWaterMetering": "8",
    "metersConsumed": "0",
    "differenceOfUse": "62",
    "total": "124",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "69",
    "previousWaterMetering": "335",
    "currentWaterMetering": "351",
    "metersConsumed": "16",
    "differenceOfUse": "62",
    "total": "459",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "70",
    "previousWaterMetering": "70",
    "currentWaterMetering": "70",
    "metersConsumed": "0",
    "differenceOfUse": "62",
    "total": "124",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "71",
    "previousWaterMetering": "207",
    "currentWaterMetering": "216",
    "metersConsumed": "9",
    "differenceOfUse": "62",
    "total": "292",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "72",
    "previousWaterMetering": "182",
    "currentWaterMetering": "188",
    "metersConsumed": "6",
    "differenceOfUse": "62",
    "total": "223",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "73",
    "previousWaterMetering": "159",
    "currentWaterMetering": "164",
    "metersConsumed": "5",
    "differenceOfUse": "62",
    "total": "205",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "74",
    "previousWaterMetering": "101",
    "currentWaterMetering": "103",
    "metersConsumed": "2",
    "differenceOfUse": "62",
    "total": "155",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "75",
    "previousWaterMetering": "329",
    "currentWaterMetering": "339",
    "metersConsumed": "10",
    "differenceOfUse": "62",
    "total": "315",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "76",
    "previousWaterMetering": "22",
    "currentWaterMetering": "24",
    "metersConsumed": "2",
    "differenceOfUse": "62",
    "total": "155",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "77",
    "previousWaterMetering": "543",
    "currentWaterMetering": "559",
    "metersConsumed": "16",
    "differenceOfUse": "62",
    "total": "459",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "78",
    "previousWaterMetering": "34",
    "currentWaterMetering": "35",
    "metersConsumed": "1",
    "differenceOfUse": "62",
    "total": "139",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "79",
    "previousWaterMetering": "255",
    "currentWaterMetering": "258",
    "metersConsumed": "3",
    "differenceOfUse": "62",
    "total": "171",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "80",
    "previousWaterMetering": "328",
    "currentWaterMetering": "343",
    "metersConsumed": "15",
    "differenceOfUse": "62",
    "total": "435",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "81",
    "previousWaterMetering": "49",
    "currentWaterMetering": "50",
    "metersConsumed": "1",
    "differenceOfUse": "62",
    "total": "139",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "82",
    "previousWaterMetering": "240",
    "currentWaterMetering": "252",
    "metersConsumed": "12",
    "differenceOfUse": "62",
    "total": "359",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "83",
    "previousWaterMetering": "167",
    "currentWaterMetering": "172",
    "metersConsumed": "5",
    "differenceOfUse": "62",
    "total": "205",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "84",
    "previousWaterMetering": "204",
    "currentWaterMetering": "208",
    "metersConsumed": "4",
    "differenceOfUse": "62",
    "total": "187",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "85",
    "previousWaterMetering": "183",
    "currentWaterMetering": "191",
    "metersConsumed": "8",
    "differenceOfUse": "62",
    "total": "262",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "86",
    "previousWaterMetering": "11",
    "currentWaterMetering": "15",
    "metersConsumed": "4",
    "differenceOfUse": "62",
    "total": "187",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "87",
    "previousWaterMetering": "159",
    "currentWaterMetering": "166",
    "metersConsumed": "7",
    "differenceOfUse": "62",
    "total": "242",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "88",
    "previousWaterMetering": "282",
    "currentWaterMetering": "290",
    "metersConsumed": "8",
    "differenceOfUse": "62",
    "total": "262",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "89",
    "previousWaterMetering": "490",
    "currentWaterMetering": "509",
    "metersConsumed": "19",
    "differenceOfUse": "62",
    "total": "537",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "90",
    "previousWaterMetering": "395",
    "currentWaterMetering": "415",
    "metersConsumed": "20",
    "differenceOfUse": "62",
    "total": "564",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "91",
    "previousWaterMetering": "204",
    "currentWaterMetering": "212",
    "metersConsumed": "8",
    "differenceOfUse": "62",
    "total": "262",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "92",
    "previousWaterMetering": "332",
    "currentWaterMetering": "343",
    "metersConsumed": "11",
    "differenceOfUse": "62",
    "total": "337",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "93",
    "previousWaterMetering": "155",
    "currentWaterMetering": "163",
    "metersConsumed": "8",
    "differenceOfUse": "62",
    "total": "262",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "94",
    "previousWaterMetering": "333",
    "currentWaterMetering": "343",
    "metersConsumed": "10",
    "differenceOfUse": "62",
    "total": "315",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "95",
    "previousWaterMetering": "61",
    "currentWaterMetering": "62",
    "metersConsumed": "1",
    "differenceOfUse": "62",
    "total": "139",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "96",
    "previousWaterMetering": "103",
    "currentWaterMetering": "108",
    "metersConsumed": "5",
    "differenceOfUse": "62",
    "total": "205",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "97",
    "previousWaterMetering": "143",
    "currentWaterMetering": "148",
    "metersConsumed": "5",
    "differenceOfUse": "62",
    "total": "205",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "98",
    "previousWaterMetering": "72",
    "currentWaterMetering": "74",
    "metersConsumed": "2",
    "differenceOfUse": "62",
    "total": "155",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "99",
    "previousWaterMetering": "200",
    "currentWaterMetering": "203",
    "metersConsumed": "3",
    "differenceOfUse": "62",
    "total": "171",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "100",
    "previousWaterMetering": "3",
    "currentWaterMetering": "3",
    "metersConsumed": "0",
    "differenceOfUse": "62",
    "total": "124",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "101",
    "previousWaterMetering": "160",
    "currentWaterMetering": "166",
    "metersConsumed": "6",
    "differenceOfUse": "62",
    "total": "223",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "102",
    "previousWaterMetering": "97",
    "currentWaterMetering": "101",
    "metersConsumed": "4",
    "differenceOfUse": "62",
    "total": "187",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  },
  {
    "houseId": "103",
    "previousWaterMetering": "6",
    "currentWaterMetering": "6",
    "metersConsumed": "0",
    "differenceOfUse": "62",
    "total": "124",
    "condo": "Shimul",
    "caKey": "shimulac",
    "periodOfUse": "Agosto",
    "paymentMonth": "Octubre",
    "year": "2024"
  }
]
;

export const reportShimul = data;
