
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =
[{
  "houseId": "1",
  "previousWaterMetering": "433",
  "currentWaterMetering": "447",
  "metersConsumed": "14",
  "differenceOfUse": "-80",
  "total": "282",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "2",
  "previousWaterMetering": "137",
  "currentWaterMetering": "146",
  "metersConsumed": "9",
  "differenceOfUse": "-80",
  "total": "159",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "3",
  "previousWaterMetering": "485",
  "currentWaterMetering": "496",
  "metersConsumed": "11",
  "differenceOfUse": "-80",
  "total": "205",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "4",
  "previousWaterMetering": "404",
  "currentWaterMetering": "408",
  "metersConsumed": "4",
  "differenceOfUse": "-80",
  "total": "50",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "5",
  "previousWaterMetering": "212",
  "currentWaterMetering": "219",
  "metersConsumed": "7",
  "differenceOfUse": "-80",
  "total": "107",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "6",
  "previousWaterMetering": "346",
  "currentWaterMetering": "354",
  "metersConsumed": "8",
  "differenceOfUse": "-80",
  "total": "128",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "7",
  "previousWaterMetering": "485",
  "currentWaterMetering": "498",
  "metersConsumed": "13",
  "differenceOfUse": "-80",
  "total": "256",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "8",
  "previousWaterMetering": "206",
  "currentWaterMetering": "207",
  "metersConsumed": "1",
  "differenceOfUse": "-80",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "9",
  "previousWaterMetering": "245",
  "currentWaterMetering": "249",
  "metersConsumed": "4",
  "differenceOfUse": "-80",
  "total": "50",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "10",
  "previousWaterMetering": "456",
  "currentWaterMetering": "466",
  "metersConsumed": "10",
  "differenceOfUse": "-80",
  "total": "182",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "11",
  "previousWaterMetering": "606",
  "currentWaterMetering": "626",
  "metersConsumed": "20",
  "differenceOfUse": "-80",
  "total": "441",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "12",
  "previousWaterMetering": "338",
  "currentWaterMetering": "349",
  "metersConsumed": "11",
  "differenceOfUse": "-80",
  "total": "205",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "13",
  "previousWaterMetering": "247",
  "currentWaterMetering": "248",
  "metersConsumed": "1",
  "differenceOfUse": "-80",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "14",
  "previousWaterMetering": "467",
  "currentWaterMetering": "477",
  "metersConsumed": "10",
  "differenceOfUse": "-80",
  "total": "182",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "15",
  "previousWaterMetering": "216",
  "currentWaterMetering": "218",
  "metersConsumed": "2",
  "differenceOfUse": "-80",
  "total": "16",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "16",
  "previousWaterMetering": "221",
  "currentWaterMetering": "232",
  "metersConsumed": "11",
  "differenceOfUse": "-80",
  "total": "205",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "17",
  "previousWaterMetering": "291",
  "currentWaterMetering": "298",
  "metersConsumed": "7",
  "differenceOfUse": "-80",
  "total": "107",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "18",
  "previousWaterMetering": "328",
  "currentWaterMetering": "336",
  "metersConsumed": "8",
  "differenceOfUse": "-80",
  "total": "128",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "19",
  "previousWaterMetering": "68",
  "currentWaterMetering": "76",
  "metersConsumed": "8",
  "differenceOfUse": "-80",
  "total": "128",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "20",
  "previousWaterMetering": "382",
  "currentWaterMetering": "405",
  "metersConsumed": "23",
  "differenceOfUse": "-80",
  "total": "530",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "21",
  "previousWaterMetering": "334",
  "currentWaterMetering": "352",
  "metersConsumed": "18",
  "differenceOfUse": "-80",
  "total": "387",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "22",
  "previousWaterMetering": "322",
  "currentWaterMetering": "329",
  "metersConsumed": "7",
  "differenceOfUse": "-80",
  "total": "107",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "23",
  "previousWaterMetering": "642",
  "currentWaterMetering": "661",
  "metersConsumed": "19",
  "differenceOfUse": "-80",
  "total": "414",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "24",
  "previousWaterMetering": "282",
  "currentWaterMetering": "292",
  "metersConsumed": "10",
  "differenceOfUse": "-80",
  "total": "182",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "25",
  "previousWaterMetering": "195",
  "currentWaterMetering": "201",
  "metersConsumed": "6",
  "differenceOfUse": "-80",
  "total": "87",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "26",
  "previousWaterMetering": "34",
  "currentWaterMetering": "34",
  "metersConsumed": "0",
  "differenceOfUse": "-80",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "27",
  "previousWaterMetering": "260",
  "currentWaterMetering": "267",
  "metersConsumed": "7",
  "differenceOfUse": "-80",
  "total": "107",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "28",
  "previousWaterMetering": "42",
  "currentWaterMetering": "42",
  "metersConsumed": "0",
  "differenceOfUse": "-80",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "29",
  "previousWaterMetering": "184",
  "currentWaterMetering": "188",
  "metersConsumed": "4",
  "differenceOfUse": "-80",
  "total": "50",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "30",
  "previousWaterMetering": "490",
  "currentWaterMetering": "501",
  "metersConsumed": "11",
  "differenceOfUse": "-80",
  "total": "205",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "31",
  "previousWaterMetering": "320",
  "currentWaterMetering": "330",
  "metersConsumed": "10",
  "differenceOfUse": "-80",
  "total": "182",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "32",
  "previousWaterMetering": "495",
  "currentWaterMetering": "508",
  "metersConsumed": "13",
  "differenceOfUse": "-80",
  "total": "256",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "33",
  "previousWaterMetering": "145",
  "currentWaterMetering": "146",
  "metersConsumed": "1",
  "differenceOfUse": "-80",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "34",
  "previousWaterMetering": "441",
  "currentWaterMetering": "455",
  "metersConsumed": "14",
  "differenceOfUse": "-80",
  "total": "282",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "35",
  "previousWaterMetering": "661",
  "currentWaterMetering": "680",
  "metersConsumed": "19",
  "differenceOfUse": "-80",
  "total": "414",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "36",
  "previousWaterMetering": "414",
  "currentWaterMetering": "426",
  "metersConsumed": "12",
  "differenceOfUse": "-80",
  "total": "229",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "37",
  "previousWaterMetering": "272",
  "currentWaterMetering": "282",
  "metersConsumed": "10",
  "differenceOfUse": "-80",
  "total": "182",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "38",
  "previousWaterMetering": "441",
  "currentWaterMetering": "445",
  "metersConsumed": "4",
  "differenceOfUse": "-80",
  "total": "50",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "39",
  "previousWaterMetering": "283",
  "currentWaterMetering": "289",
  "metersConsumed": "6",
  "differenceOfUse": "-80",
  "total": "87",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "40",
  "previousWaterMetering": "95",
  "currentWaterMetering": "97",
  "metersConsumed": "2",
  "differenceOfUse": "-80",
  "total": "16",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "41",
  "previousWaterMetering": "579",
  "currentWaterMetering": "591",
  "metersConsumed": "12",
  "differenceOfUse": "-80",
  "total": "229",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "42",
  "previousWaterMetering": "521",
  "currentWaterMetering": "540",
  "metersConsumed": "19",
  "differenceOfUse": "-80",
  "total": "414",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "43",
  "previousWaterMetering": "196",
  "currentWaterMetering": "197",
  "metersConsumed": "1",
  "differenceOfUse": "-80",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "44",
  "previousWaterMetering": "103",
  "currentWaterMetering": "108",
  "metersConsumed": "5",
  "differenceOfUse": "-80",
  "total": "68",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "45",
  "previousWaterMetering": "585",
  "currentWaterMetering": "597",
  "metersConsumed": "12",
  "differenceOfUse": "-80",
  "total": "229",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "46",
  "previousWaterMetering": "207",
  "currentWaterMetering": "213",
  "metersConsumed": "6",
  "differenceOfUse": "-80",
  "total": "87",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "47",
  "previousWaterMetering": "528",
  "currentWaterMetering": "534",
  "metersConsumed": "6",
  "differenceOfUse": "-80",
  "total": "87",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "48",
  "previousWaterMetering": "201",
  "currentWaterMetering": "211",
  "metersConsumed": "10",
  "differenceOfUse": "-80",
  "total": "182",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "49",
  "previousWaterMetering": "397",
  "currentWaterMetering": "407",
  "metersConsumed": "10",
  "differenceOfUse": "-80",
  "total": "182",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "50",
  "previousWaterMetering": "218",
  "currentWaterMetering": "339",
  "metersConsumed": "121",
  "differenceOfUse": "-80",
  "total": "9172",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "51",
  "previousWaterMetering": "98",
  "currentWaterMetering": "101",
  "metersConsumed": "3",
  "differenceOfUse": "-80",
  "total": "33",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "52",
  "previousWaterMetering": "312",
  "currentWaterMetering": "319",
  "metersConsumed": "7",
  "differenceOfUse": "-80",
  "total": "107",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "53",
  "previousWaterMetering": "138",
  "currentWaterMetering": "141",
  "metersConsumed": "3",
  "differenceOfUse": "-80",
  "total": "33",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "54",
  "previousWaterMetering": "471",
  "currentWaterMetering": "484",
  "metersConsumed": "13",
  "differenceOfUse": "-80",
  "total": "256",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "-80",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "56",
  "previousWaterMetering": "7",
  "currentWaterMetering": "7",
  "metersConsumed": "0",
  "differenceOfUse": "-80",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "57",
  "previousWaterMetering": "622",
  "currentWaterMetering": "638",
  "metersConsumed": "16",
  "differenceOfUse": "-80",
  "total": "333",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "58",
  "previousWaterMetering": "404",
  "currentWaterMetering": "410",
  "metersConsumed": "6",
  "differenceOfUse": "-80",
  "total": "87",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "59",
  "previousWaterMetering": "268",
  "currentWaterMetering": "280",
  "metersConsumed": "12",
  "differenceOfUse": "-80",
  "total": "229",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "60",
  "previousWaterMetering": "312",
  "currentWaterMetering": "321",
  "metersConsumed": "9",
  "differenceOfUse": "-80",
  "total": "159",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "61",
  "previousWaterMetering": "89",
  "currentWaterMetering": "91",
  "metersConsumed": "2",
  "differenceOfUse": "-80",
  "total": "16",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "62",
  "previousWaterMetering": "252",
  "currentWaterMetering": "269",
  "metersConsumed": "17",
  "differenceOfUse": "-80",
  "total": "360",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "63",
  "previousWaterMetering": "672",
  "currentWaterMetering": "689",
  "metersConsumed": "17",
  "differenceOfUse": "-80",
  "total": "360",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "64",
  "previousWaterMetering": "189",
  "currentWaterMetering": "189",
  "metersConsumed": "0",
  "differenceOfUse": "-80",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "65",
  "previousWaterMetering": "725",
  "currentWaterMetering": "739",
  "metersConsumed": "14",
  "differenceOfUse": "-80",
  "total": "282",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "66",
  "previousWaterMetering": "145",
  "currentWaterMetering": "148",
  "metersConsumed": "3",
  "differenceOfUse": "-80",
  "total": "33",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "67",
  "previousWaterMetering": "254",
  "currentWaterMetering": "264",
  "metersConsumed": "10",
  "differenceOfUse": "-80",
  "total": "182",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "-80",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "69",
  "previousWaterMetering": "459",
  "currentWaterMetering": "472",
  "metersConsumed": "13",
  "differenceOfUse": "-80",
  "total": "256",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "70",
  "previousWaterMetering": "111",
  "currentWaterMetering": "117",
  "metersConsumed": "6",
  "differenceOfUse": "-80",
  "total": "87",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "71",
  "previousWaterMetering": "281",
  "currentWaterMetering": "290",
  "metersConsumed": "9",
  "differenceOfUse": "-80",
  "total": "159",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "72",
  "previousWaterMetering": "246",
  "currentWaterMetering": "253",
  "metersConsumed": "7",
  "differenceOfUse": "-80",
  "total": "107",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "73",
  "previousWaterMetering": "214",
  "currentWaterMetering": "222",
  "metersConsumed": "8",
  "differenceOfUse": "-80",
  "total": "128",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "74",
  "previousWaterMetering": "132",
  "currentWaterMetering": "135",
  "metersConsumed": "3",
  "differenceOfUse": "-80",
  "total": "33",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "75",
  "previousWaterMetering": "418",
  "currentWaterMetering": "431",
  "metersConsumed": "13",
  "differenceOfUse": "-80",
  "total": "256",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "76",
  "previousWaterMetering": "40",
  "currentWaterMetering": "41",
  "metersConsumed": "1",
  "differenceOfUse": "-80",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "77",
  "previousWaterMetering": "697",
  "currentWaterMetering": "715",
  "metersConsumed": "18",
  "differenceOfUse": "-80",
  "total": "387",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "78",
  "previousWaterMetering": "43",
  "currentWaterMetering": "45",
  "metersConsumed": "2",
  "differenceOfUse": "-80",
  "total": "16",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "79",
  "previousWaterMetering": "341",
  "currentWaterMetering": "352",
  "metersConsumed": "11",
  "differenceOfUse": "-80",
  "total": "205",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "80",
  "previousWaterMetering": "426",
  "currentWaterMetering": "447",
  "metersConsumed": "21",
  "differenceOfUse": "-80",
  "total": "471",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "81",
  "previousWaterMetering": "108",
  "currentWaterMetering": "113",
  "metersConsumed": "5",
  "differenceOfUse": "-80",
  "total": "68",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "82",
  "previousWaterMetering": "346",
  "currentWaterMetering": "358",
  "metersConsumed": "12",
  "differenceOfUse": "-80",
  "total": "229",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "83",
  "previousWaterMetering": "210",
  "currentWaterMetering": "216",
  "metersConsumed": "6",
  "differenceOfUse": "-80",
  "total": "87",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "84",
  "previousWaterMetering": "253",
  "currentWaterMetering": "260",
  "metersConsumed": "7",
  "differenceOfUse": "-80",
  "total": "107",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "85",
  "previousWaterMetering": "257",
  "currentWaterMetering": "267",
  "metersConsumed": "10",
  "differenceOfUse": "-80",
  "total": "182",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "86",
  "previousWaterMetering": "99",
  "currentWaterMetering": "114",
  "metersConsumed": "15",
  "differenceOfUse": "-80",
  "total": "308",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "87",
  "previousWaterMetering": "237",
  "currentWaterMetering": "254",
  "metersConsumed": "17",
  "differenceOfUse": "-80",
  "total": "360",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "88",
  "previousWaterMetering": "359",
  "currentWaterMetering": "366",
  "metersConsumed": "7",
  "differenceOfUse": "-80",
  "total": "107",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "89",
  "previousWaterMetering": "636",
  "currentWaterMetering": "653",
  "metersConsumed": "17",
  "differenceOfUse": "-80",
  "total": "360",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "90",
  "previousWaterMetering": "632",
  "currentWaterMetering": "658",
  "metersConsumed": "26",
  "differenceOfUse": "-80",
  "total": "697",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "91",
  "previousWaterMetering": "308",
  "currentWaterMetering": "314",
  "metersConsumed": "6",
  "differenceOfUse": "-80",
  "total": "87",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "92",
  "previousWaterMetering": "438",
  "currentWaterMetering": "452",
  "metersConsumed": "14",
  "differenceOfUse": "-80",
  "total": "282",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "93",
  "previousWaterMetering": "212",
  "currentWaterMetering": "222",
  "metersConsumed": "10",
  "differenceOfUse": "-80",
  "total": "182",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "94",
  "previousWaterMetering": "436",
  "currentWaterMetering": "451",
  "metersConsumed": "15",
  "differenceOfUse": "-80",
  "total": "308",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "95",
  "previousWaterMetering": "64",
  "currentWaterMetering": "64",
  "metersConsumed": "0",
  "differenceOfUse": "-80",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "96",
  "previousWaterMetering": "139",
  "currentWaterMetering": "143",
  "metersConsumed": "4",
  "differenceOfUse": "-80",
  "total": "50",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "97",
  "previousWaterMetering": "184",
  "currentWaterMetering": "191",
  "metersConsumed": "7",
  "differenceOfUse": "-80",
  "total": "107",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "98",
  "previousWaterMetering": "94",
  "currentWaterMetering": "97",
  "metersConsumed": "3",
  "differenceOfUse": "-80",
  "total": "33",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "99",
  "previousWaterMetering": "233",
  "currentWaterMetering": "233",
  "metersConsumed": "0",
  "differenceOfUse": "-80",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "-80",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "101",
  "previousWaterMetering": "202",
  "currentWaterMetering": "207",
  "metersConsumed": "5",
  "differenceOfUse": "-80",
  "total": "68",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "102",
  "previousWaterMetering": "134",
  "currentWaterMetering": "138",
  "metersConsumed": "4",
  "differenceOfUse": "-80",
  "total": "50",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
},
{
  "houseId": "103",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "-80",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2025"
}]
;

export const reportShimul = data;
