
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =
[{
  "houseId": "1",
  "previousWaterMetering": "391",
  "currentWaterMetering": "405",
  "metersConsumed": "14",
  "differenceOfUse": "72",
  "total": "429",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "2",
  "previousWaterMetering": "113",
  "currentWaterMetering": "119",
  "metersConsumed": "6",
  "differenceOfUse": "72",
  "total": "237",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "3",
  "previousWaterMetering": "443",
  "currentWaterMetering": "458",
  "metersConsumed": "15",
  "differenceOfUse": "72",
  "total": "455",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "4",
  "previousWaterMetering": "374",
  "currentWaterMetering": "383",
  "metersConsumed": "9",
  "differenceOfUse": "72",
  "total": "308",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "5",
  "previousWaterMetering": "192",
  "currentWaterMetering": "198",
  "metersConsumed": "6",
  "differenceOfUse": "72",
  "total": "237",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "6",
  "previousWaterMetering": "322",
  "currentWaterMetering": "329",
  "metersConsumed": "7",
  "differenceOfUse": "72",
  "total": "257",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "7",
  "previousWaterMetering": "454",
  "currentWaterMetering": "464",
  "metersConsumed": "10",
  "differenceOfUse": "72",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "8",
  "previousWaterMetering": "108",
  "currentWaterMetering": "108",
  "metersConsumed": "0",
  "differenceOfUse": "72",
  "total": "135",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "9",
  "previousWaterMetering": "230",
  "currentWaterMetering": "235",
  "metersConsumed": "5",
  "differenceOfUse": "72",
  "total": "218",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "10",
  "previousWaterMetering": "423",
  "currentWaterMetering": "432",
  "metersConsumed": "9",
  "differenceOfUse": "72",
  "total": "308",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "11",
  "previousWaterMetering": "559",
  "currentWaterMetering": "575",
  "metersConsumed": "16",
  "differenceOfUse": "72",
  "total": "480",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "12",
  "previousWaterMetering": "311",
  "currentWaterMetering": "319",
  "metersConsumed": "8",
  "differenceOfUse": "72",
  "total": "277",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "13",
  "previousWaterMetering": "228",
  "currentWaterMetering": "230",
  "metersConsumed": "2",
  "differenceOfUse": "72",
  "total": "167",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "14",
  "previousWaterMetering": "437",
  "currentWaterMetering": "451",
  "metersConsumed": "14",
  "differenceOfUse": "72",
  "total": "429",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "15",
  "previousWaterMetering": "211",
  "currentWaterMetering": "215",
  "metersConsumed": "4",
  "differenceOfUse": "72",
  "total": "201",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "16",
  "previousWaterMetering": "200",
  "currentWaterMetering": "206",
  "metersConsumed": "6",
  "differenceOfUse": "72",
  "total": "237",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "17",
  "previousWaterMetering": "268",
  "currentWaterMetering": "275",
  "metersConsumed": "7",
  "differenceOfUse": "72",
  "total": "257",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "18",
  "previousWaterMetering": "309",
  "currentWaterMetering": "316",
  "metersConsumed": "7",
  "differenceOfUse": "72",
  "total": "257",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "19",
  "previousWaterMetering": "52",
  "currentWaterMetering": "57",
  "metersConsumed": "5",
  "differenceOfUse": "72",
  "total": "218",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "20",
  "previousWaterMetering": "303",
  "currentWaterMetering": "329",
  "metersConsumed": "26",
  "differenceOfUse": "72",
  "total": "840",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "21",
  "previousWaterMetering": "303",
  "currentWaterMetering": "314",
  "metersConsumed": "11",
  "differenceOfUse": "72",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "22",
  "previousWaterMetering": "302",
  "currentWaterMetering": "308",
  "metersConsumed": "6",
  "differenceOfUse": "72",
  "total": "237",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "23",
  "previousWaterMetering": "594",
  "currentWaterMetering": "609",
  "metersConsumed": "15",
  "differenceOfUse": "72",
  "total": "455",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "24",
  "previousWaterMetering": "273",
  "currentWaterMetering": "273",
  "metersConsumed": "0",
  "differenceOfUse": "72",
  "total": "135",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "25",
  "previousWaterMetering": "174",
  "currentWaterMetering": "181",
  "metersConsumed": "7",
  "differenceOfUse": "72",
  "total": "257",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "26",
  "previousWaterMetering": "34",
  "currentWaterMetering": "34",
  "metersConsumed": "0",
  "differenceOfUse": "72",
  "total": "135",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "27",
  "previousWaterMetering": "242",
  "currentWaterMetering": "248",
  "metersConsumed": "6",
  "differenceOfUse": "72",
  "total": "237",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "28",
  "previousWaterMetering": "42",
  "currentWaterMetering": "42",
  "metersConsumed": "0",
  "differenceOfUse": "72",
  "total": "135",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "29",
  "previousWaterMetering": "160",
  "currentWaterMetering": "167",
  "metersConsumed": "7",
  "differenceOfUse": "72",
  "total": "257",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "30",
  "previousWaterMetering": "451",
  "currentWaterMetering": "462",
  "metersConsumed": "11",
  "differenceOfUse": "72",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "31",
  "previousWaterMetering": "290",
  "currentWaterMetering": "300",
  "metersConsumed": "10",
  "differenceOfUse": "72",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "32",
  "previousWaterMetering": "457",
  "currentWaterMetering": "469",
  "metersConsumed": "12",
  "differenceOfUse": "72",
  "total": "377",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "33",
  "previousWaterMetering": "140",
  "currentWaterMetering": "142",
  "metersConsumed": "2",
  "differenceOfUse": "72",
  "total": "167",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "34",
  "previousWaterMetering": "411",
  "currentWaterMetering": "421",
  "metersConsumed": "10",
  "differenceOfUse": "72",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "35",
  "previousWaterMetering": "601",
  "currentWaterMetering": "621",
  "metersConsumed": "20",
  "differenceOfUse": "72",
  "total": "587",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "36",
  "previousWaterMetering": "381",
  "currentWaterMetering": "393",
  "metersConsumed": "12",
  "differenceOfUse": "72",
  "total": "377",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "37",
  "previousWaterMetering": "248",
  "currentWaterMetering": "258",
  "metersConsumed": "10",
  "differenceOfUse": "72",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "38",
  "previousWaterMetering": "427",
  "currentWaterMetering": "431",
  "metersConsumed": "4",
  "differenceOfUse": "72",
  "total": "201",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "39",
  "previousWaterMetering": "259",
  "currentWaterMetering": "270",
  "metersConsumed": "11",
  "differenceOfUse": "72",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "40",
  "previousWaterMetering": "92",
  "currentWaterMetering": "94",
  "metersConsumed": "2",
  "differenceOfUse": "72",
  "total": "167",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "41",
  "previousWaterMetering": "540",
  "currentWaterMetering": "552",
  "metersConsumed": "12",
  "differenceOfUse": "72",
  "total": "377",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "42",
  "previousWaterMetering": "477",
  "currentWaterMetering": "490",
  "metersConsumed": "13",
  "differenceOfUse": "72",
  "total": "404",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "43",
  "previousWaterMetering": "189",
  "currentWaterMetering": "191",
  "metersConsumed": "2",
  "differenceOfUse": "72",
  "total": "167",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "44",
  "previousWaterMetering": "89",
  "currentWaterMetering": "92",
  "metersConsumed": "3",
  "differenceOfUse": "72",
  "total": "184",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "45",
  "previousWaterMetering": "537",
  "currentWaterMetering": "556",
  "metersConsumed": "19",
  "differenceOfUse": "72",
  "total": "560",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "46",
  "previousWaterMetering": "191",
  "currentWaterMetering": "197",
  "metersConsumed": "6",
  "differenceOfUse": "72",
  "total": "237",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "47",
  "previousWaterMetering": "509",
  "currentWaterMetering": "514",
  "metersConsumed": "5",
  "differenceOfUse": "72",
  "total": "218",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "48",
  "previousWaterMetering": "178",
  "currentWaterMetering": "185",
  "metersConsumed": "7",
  "differenceOfUse": "72",
  "total": "257",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "49",
  "previousWaterMetering": "362",
  "currentWaterMetering": "374",
  "metersConsumed": "12",
  "differenceOfUse": "72",
  "total": "377",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "50",
  "previousWaterMetering": "175",
  "currentWaterMetering": "186",
  "metersConsumed": "11",
  "differenceOfUse": "72",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "51",
  "previousWaterMetering": "89",
  "currentWaterMetering": "91",
  "metersConsumed": "2",
  "differenceOfUse": "72",
  "total": "167",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "52",
  "previousWaterMetering": "293",
  "currentWaterMetering": "300",
  "metersConsumed": "7",
  "differenceOfUse": "72",
  "total": "257",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "53",
  "previousWaterMetering": "124",
  "currentWaterMetering": "129",
  "metersConsumed": "5",
  "differenceOfUse": "72",
  "total": "218",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "54",
  "previousWaterMetering": "438",
  "currentWaterMetering": "449",
  "metersConsumed": "11",
  "differenceOfUse": "72",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "72",
  "total": "135",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "56",
  "previousWaterMetering": "6",
  "currentWaterMetering": "6",
  "metersConsumed": "0",
  "differenceOfUse": "72",
  "total": "135",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "57",
  "previousWaterMetering": "604",
  "currentWaterMetering": "607",
  "metersConsumed": "3",
  "differenceOfUse": "72",
  "total": "184",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "58",
  "previousWaterMetering": "383",
  "currentWaterMetering": "389",
  "metersConsumed": "6",
  "differenceOfUse": "72",
  "total": "237",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "59",
  "previousWaterMetering": "235",
  "currentWaterMetering": "247",
  "metersConsumed": "12",
  "differenceOfUse": "72",
  "total": "377",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "60",
  "previousWaterMetering": "281",
  "currentWaterMetering": "291",
  "metersConsumed": "10",
  "differenceOfUse": "72",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "61",
  "previousWaterMetering": "82",
  "currentWaterMetering": "84",
  "metersConsumed": "2",
  "differenceOfUse": "72",
  "total": "167",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "62",
  "previousWaterMetering": "230",
  "currentWaterMetering": "242",
  "metersConsumed": "12",
  "differenceOfUse": "72",
  "total": "377",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "63",
  "previousWaterMetering": "614",
  "currentWaterMetering": "634",
  "metersConsumed": "20",
  "differenceOfUse": "72",
  "total": "587",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "64",
  "previousWaterMetering": "181",
  "currentWaterMetering": "187",
  "metersConsumed": "6",
  "differenceOfUse": "72",
  "total": "237",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "65",
  "previousWaterMetering": "685",
  "currentWaterMetering": "698",
  "metersConsumed": "13",
  "differenceOfUse": "72",
  "total": "404",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "66",
  "previousWaterMetering": "137",
  "currentWaterMetering": "140",
  "metersConsumed": "3",
  "differenceOfUse": "72",
  "total": "184",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "67",
  "previousWaterMetering": "231",
  "currentWaterMetering": "237",
  "metersConsumed": "6",
  "differenceOfUse": "72",
  "total": "237",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "72",
  "total": "135",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "69",
  "previousWaterMetering": "420",
  "currentWaterMetering": "431",
  "metersConsumed": "11",
  "differenceOfUse": "72",
  "total": "354",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "70",
  "previousWaterMetering": "91",
  "currentWaterMetering": "98",
  "metersConsumed": "7",
  "differenceOfUse": "72",
  "total": "257",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "71",
  "previousWaterMetering": "254",
  "currentWaterMetering": "262",
  "metersConsumed": "8",
  "differenceOfUse": "72",
  "total": "277",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "72",
  "previousWaterMetering": "223",
  "currentWaterMetering": "233",
  "metersConsumed": "10",
  "differenceOfUse": "72",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "73",
  "previousWaterMetering": "196",
  "currentWaterMetering": "203",
  "metersConsumed": "7",
  "differenceOfUse": "72",
  "total": "257",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "74",
  "previousWaterMetering": "120",
  "currentWaterMetering": "123",
  "metersConsumed": "3",
  "differenceOfUse": "72",
  "total": "184",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "75",
  "previousWaterMetering": "385",
  "currentWaterMetering": "394",
  "metersConsumed": "9",
  "differenceOfUse": "72",
  "total": "308",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "76",
  "previousWaterMetering": "40",
  "currentWaterMetering": "40",
  "metersConsumed": "0",
  "differenceOfUse": "72",
  "total": "135",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "77",
  "previousWaterMetering": "647",
  "currentWaterMetering": "662",
  "metersConsumed": "15",
  "differenceOfUse": "72",
  "total": "455",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "78",
  "previousWaterMetering": "39",
  "currentWaterMetering": "40",
  "metersConsumed": "1",
  "differenceOfUse": "72",
  "total": "151",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "79",
  "previousWaterMetering": "316",
  "currentWaterMetering": "324",
  "metersConsumed": "8",
  "differenceOfUse": "72",
  "total": "277",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "80",
  "previousWaterMetering": "397",
  "currentWaterMetering": "406",
  "metersConsumed": "9",
  "differenceOfUse": "72",
  "total": "308",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "81",
  "previousWaterMetering": "80",
  "currentWaterMetering": "96",
  "metersConsumed": "16",
  "differenceOfUse": "72",
  "total": "480",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "82",
  "previousWaterMetering": "311",
  "currentWaterMetering": "321",
  "metersConsumed": "10",
  "differenceOfUse": "72",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "83",
  "previousWaterMetering": "194",
  "currentWaterMetering": "199",
  "metersConsumed": "5",
  "differenceOfUse": "72",
  "total": "218",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "84",
  "previousWaterMetering": "234",
  "currentWaterMetering": "240",
  "metersConsumed": "6",
  "differenceOfUse": "72",
  "total": "237",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "85",
  "previousWaterMetering": "230",
  "currentWaterMetering": "239",
  "metersConsumed": "9",
  "differenceOfUse": "72",
  "total": "308",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "86",
  "previousWaterMetering": "68",
  "currentWaterMetering": "78",
  "metersConsumed": "10",
  "differenceOfUse": "72",
  "total": "331",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "87",
  "previousWaterMetering": "192",
  "currentWaterMetering": "210",
  "metersConsumed": "18",
  "differenceOfUse": "72",
  "total": "533",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "88",
  "previousWaterMetering": "333",
  "currentWaterMetering": "341",
  "metersConsumed": "8",
  "differenceOfUse": "72",
  "total": "277",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "89",
  "previousWaterMetering": "586",
  "currentWaterMetering": "602",
  "metersConsumed": "16",
  "differenceOfUse": "72",
  "total": "480",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "90",
  "previousWaterMetering": "547",
  "currentWaterMetering": "574",
  "metersConsumed": "27",
  "differenceOfUse": "72",
  "total": "900",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "91",
  "previousWaterMetering": "288",
  "currentWaterMetering": "292",
  "metersConsumed": "4",
  "differenceOfUse": "72",
  "total": "201",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "92",
  "previousWaterMetering": "400",
  "currentWaterMetering": "417",
  "metersConsumed": "17",
  "differenceOfUse": "72",
  "total": "507",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "93",
  "previousWaterMetering": "194",
  "currentWaterMetering": "200",
  "metersConsumed": "6",
  "differenceOfUse": "72",
  "total": "237",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "94",
  "previousWaterMetering": "392",
  "currentWaterMetering": "409",
  "metersConsumed": "17",
  "differenceOfUse": "72",
  "total": "507",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "95",
  "previousWaterMetering": "63",
  "currentWaterMetering": "63",
  "metersConsumed": "0",
  "differenceOfUse": "72",
  "total": "135",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "96",
  "previousWaterMetering": "126",
  "currentWaterMetering": "130",
  "metersConsumed": "4",
  "differenceOfUse": "72",
  "total": "201",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "97",
  "previousWaterMetering": "178",
  "currentWaterMetering": "180",
  "metersConsumed": "2",
  "differenceOfUse": "72",
  "total": "167",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "98",
  "previousWaterMetering": "80",
  "currentWaterMetering": "88",
  "metersConsumed": "8",
  "differenceOfUse": "72",
  "total": "277",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "99",
  "previousWaterMetering": "230",
  "currentWaterMetering": "232",
  "metersConsumed": "2",
  "differenceOfUse": "72",
  "total": "167",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "72",
  "total": "135",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "101",
  "previousWaterMetering": "188",
  "currentWaterMetering": "192",
  "metersConsumed": "4",
  "differenceOfUse": "72",
  "total": "201",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "102",
  "previousWaterMetering": "121",
  "currentWaterMetering": "125",
  "metersConsumed": "4",
  "differenceOfUse": "72",
  "total": "201",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
},
{
  "houseId": "103",
  "previousWaterMetering": "8",
  "currentWaterMetering": "10",
  "metersConsumed": "2",
  "differenceOfUse": "72",
  "total": "167",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Febrero",
  "paymentMonth": "Abril",
  "year": "2025"
}]
;

export const reportShimul = data;
