 
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =
[{
  "houseId": "1",
  "previousWaterMetering": "516",
  "currentWaterMetering": "531",
  "metersConsumed": "15",
  "differenceOfUse": "0",
  "total": "399",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "10",
  "previousWaterMetering": "508",
  "currentWaterMetering": "517",
  "metersConsumed": "9",
  "differenceOfUse": "0",
  "total": "246",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "66",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "101",
  "previousWaterMetering": "232",
  "currentWaterMetering": "239",
  "metersConsumed": "7",
  "differenceOfUse": "0",
  "total": "193",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "102",
  "previousWaterMetering": "155",
  "currentWaterMetering": "158",
  "metersConsumed": "3",
  "differenceOfUse": "0",
  "total": "116",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "103",
  "previousWaterMetering": "13",
  "currentWaterMetering": "13",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "66",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "11",
  "previousWaterMetering": "689",
  "currentWaterMetering": "708",
  "metersConsumed": "19",
  "differenceOfUse": "0",
  "total": "508",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "12",
  "previousWaterMetering": "397",
  "currentWaterMetering": "410",
  "metersConsumed": "13",
  "differenceOfUse": "0",
  "total": "346",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "13",
  "previousWaterMetering": "279",
  "currentWaterMetering": "286",
  "metersConsumed": "7",
  "differenceOfUse": "0",
  "total": "193",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "14",
  "previousWaterMetering": "532",
  "currentWaterMetering": "549",
  "metersConsumed": "17",
  "differenceOfUse": "0",
  "total": "453",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "15",
  "previousWaterMetering": "244",
  "currentWaterMetering": "250",
  "metersConsumed": "6",
  "differenceOfUse": "0",
  "total": "172",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "16",
  "previousWaterMetering": "264",
  "currentWaterMetering": "273",
  "metersConsumed": "9",
  "differenceOfUse": "0",
  "total": "246",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "17",
  "previousWaterMetering": "329",
  "currentWaterMetering": "338",
  "metersConsumed": "9",
  "differenceOfUse": "0",
  "total": "246",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "18",
  "previousWaterMetering": "366",
  "currentWaterMetering": "371",
  "metersConsumed": "5",
  "differenceOfUse": "0",
  "total": "153",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "19",
  "previousWaterMetering": "114",
  "currentWaterMetering": "127",
  "metersConsumed": "13",
  "differenceOfUse": "0",
  "total": "346",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "2",
  "previousWaterMetering": "184",
  "currentWaterMetering": "188",
  "metersConsumed": "4",
  "differenceOfUse": "0",
  "total": "134",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "20",
  "previousWaterMetering": "437",
  "currentWaterMetering": "446",
  "metersConsumed": "9",
  "differenceOfUse": "0",
  "total": "246",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "21",
  "previousWaterMetering": "406",
  "currentWaterMetering": "415",
  "metersConsumed": "9",
  "differenceOfUse": "0",
  "total": "246",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "22",
  "previousWaterMetering": "372",
  "currentWaterMetering": "382",
  "metersConsumed": "10",
  "differenceOfUse": "0",
  "total": "270",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "23",
  "previousWaterMetering": "748",
  "currentWaterMetering": "770",
  "metersConsumed": "22",
  "differenceOfUse": "0",
  "total": "596",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "24",
  "previousWaterMetering": "333",
  "currentWaterMetering": "345",
  "metersConsumed": "12",
  "differenceOfUse": "0",
  "total": "318",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "25",
  "previousWaterMetering": "235",
  "currentWaterMetering": "244",
  "metersConsumed": "9",
  "differenceOfUse": "0",
  "total": "246",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "26",
  "previousWaterMetering": "34",
  "currentWaterMetering": "36",
  "metersConsumed": "2",
  "differenceOfUse": "0",
  "total": "99",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "27",
  "previousWaterMetering": "345",
  "currentWaterMetering": "353",
  "metersConsumed": "8",
  "differenceOfUse": "0",
  "total": "214",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "28",
  "previousWaterMetering": "47",
  "currentWaterMetering": "51",
  "metersConsumed": "4",
  "differenceOfUse": "0",
  "total": "134",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "29",
  "previousWaterMetering": "197",
  "currentWaterMetering": "205",
  "metersConsumed": "8",
  "differenceOfUse": "0",
  "total": "214",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "3",
  "previousWaterMetering": "548",
  "currentWaterMetering": "548",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "66",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "30",
  "previousWaterMetering": "576",
  "currentWaterMetering": "593",
  "metersConsumed": "17",
  "differenceOfUse": "0",
  "total": "453",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "31",
  "previousWaterMetering": "385",
  "currentWaterMetering": "399",
  "metersConsumed": "14",
  "differenceOfUse": "0",
  "total": "372",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "32",
  "previousWaterMetering": "586",
  "currentWaterMetering": "605",
  "metersConsumed": "19",
  "differenceOfUse": "0",
  "total": "508",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "33",
  "previousWaterMetering": "158",
  "currentWaterMetering": "161",
  "metersConsumed": "3",
  "differenceOfUse": "0",
  "total": "116",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "34",
  "previousWaterMetering": "509",
  "currentWaterMetering": "527",
  "metersConsumed": "18",
  "differenceOfUse": "0",
  "total": "480",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "35",
  "previousWaterMetering": "777",
  "currentWaterMetering": "805",
  "metersConsumed": "28",
  "differenceOfUse": "0",
  "total": "925",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "36",
  "previousWaterMetering": "494",
  "currentWaterMetering": "504",
  "metersConsumed": "10",
  "differenceOfUse": "0",
  "total": "270",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "37",
  "previousWaterMetering": "324",
  "currentWaterMetering": "335",
  "metersConsumed": "11",
  "differenceOfUse": "0",
  "total": "294",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "38",
  "previousWaterMetering": "491",
  "currentWaterMetering": "502",
  "metersConsumed": "11",
  "differenceOfUse": "0",
  "total": "294",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "39",
  "previousWaterMetering": "318",
  "currentWaterMetering": "326",
  "metersConsumed": "8",
  "differenceOfUse": "0",
  "total": "214",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "4",
  "previousWaterMetering": "455",
  "currentWaterMetering": "464",
  "metersConsumed": "9",
  "differenceOfUse": "0",
  "total": "246",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "40",
  "previousWaterMetering": "103",
  "currentWaterMetering": "105",
  "metersConsumed": "2",
  "differenceOfUse": "0",
  "total": "99",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "41",
  "previousWaterMetering": "641",
  "currentWaterMetering": "656",
  "metersConsumed": "15",
  "differenceOfUse": "0",
  "total": "399",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "42",
  "previousWaterMetering": "616",
  "currentWaterMetering": "636",
  "metersConsumed": "20",
  "differenceOfUse": "0",
  "total": "536",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "43",
  "previousWaterMetering": "209",
  "currentWaterMetering": "212",
  "metersConsumed": "3",
  "differenceOfUse": "0",
  "total": "116",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "44",
  "previousWaterMetering": "131",
  "currentWaterMetering": "137",
  "metersConsumed": "6",
  "differenceOfUse": "0",
  "total": "172",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "45",
  "previousWaterMetering": "673",
  "currentWaterMetering": "694",
  "metersConsumed": "21",
  "differenceOfUse": "0",
  "total": "567",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "46",
  "previousWaterMetering": "241",
  "currentWaterMetering": "247",
  "metersConsumed": "6",
  "differenceOfUse": "0",
  "total": "172",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "47",
  "previousWaterMetering": "577",
  "currentWaterMetering": "586",
  "metersConsumed": "9",
  "differenceOfUse": "0",
  "total": "246",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "48",
  "previousWaterMetering": "255",
  "currentWaterMetering": "272",
  "metersConsumed": "17",
  "differenceOfUse": "0",
  "total": "453",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "49",
  "previousWaterMetering": "469",
  "currentWaterMetering": "483",
  "metersConsumed": "14",
  "differenceOfUse": "0",
  "total": "372",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "5",
  "previousWaterMetering": "239",
  "currentWaterMetering": "356",
  "metersConsumed": "117",
  "differenceOfUse": "0",
  "total": "9089",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "50",
  "previousWaterMetering": "561",
  "currentWaterMetering": "563",
  "metersConsumed": "2",
  "differenceOfUse": "0",
  "total": "99",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "51",
  "previousWaterMetering": "113",
  "currentWaterMetering": "116",
  "metersConsumed": "3",
  "differenceOfUse": "0",
  "total": "116",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "52",
  "previousWaterMetering": "348",
  "currentWaterMetering": "353",
  "metersConsumed": "5",
  "differenceOfUse": "0",
  "total": "153",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "53",
  "previousWaterMetering": "163",
  "currentWaterMetering": "167",
  "metersConsumed": "4",
  "differenceOfUse": "0",
  "total": "134",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "54",
  "previousWaterMetering": "548",
  "currentWaterMetering": "560",
  "metersConsumed": "12",
  "differenceOfUse": "0",
  "total": "318",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "66",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "56",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "66",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "57",
  "previousWaterMetering": "692",
  "currentWaterMetering": "705",
  "metersConsumed": "13",
  "differenceOfUse": "0",
  "total": "346",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "58",
  "previousWaterMetering": "440",
  "currentWaterMetering": "448",
  "metersConsumed": "8",
  "differenceOfUse": "0",
  "total": "214",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "59",
  "previousWaterMetering": "328",
  "currentWaterMetering": "341",
  "metersConsumed": "13",
  "differenceOfUse": "0",
  "total": "346",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "6",
  "previousWaterMetering": "408",
  "currentWaterMetering": "414",
  "metersConsumed": "6",
  "differenceOfUse": "0",
  "total": "172",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "60",
  "previousWaterMetering": "373",
  "currentWaterMetering": "386",
  "metersConsumed": "13",
  "differenceOfUse": "0",
  "total": "346",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "61",
  "previousWaterMetering": "101",
  "currentWaterMetering": "102",
  "metersConsumed": "1",
  "differenceOfUse": "0",
  "total": "83",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "62",
  "previousWaterMetering": "357",
  "currentWaterMetering": "366",
  "metersConsumed": "9",
  "differenceOfUse": "0",
  "total": "246",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "63",
  "previousWaterMetering": "767",
  "currentWaterMetering": "785",
  "metersConsumed": "18",
  "differenceOfUse": "0",
  "total": "480",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "64",
  "previousWaterMetering": "230",
  "currentWaterMetering": "239",
  "metersConsumed": "9",
  "differenceOfUse": "0",
  "total": "246",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "65",
  "previousWaterMetering": "807",
  "currentWaterMetering": "823",
  "metersConsumed": "16",
  "differenceOfUse": "0",
  "total": "424",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "66",
  "previousWaterMetering": "168",
  "currentWaterMetering": "172",
  "metersConsumed": "4",
  "differenceOfUse": "0",
  "total": "134",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "67",
  "previousWaterMetering": "302",
  "currentWaterMetering": "311",
  "metersConsumed": "9",
  "differenceOfUse": "0",
  "total": "246",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "66",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "69",
  "previousWaterMetering": "540",
  "currentWaterMetering": "556",
  "metersConsumed": "16",
  "differenceOfUse": "0",
  "total": "424",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "7",
  "previousWaterMetering": "562",
  "currentWaterMetering": "582",
  "metersConsumed": "20",
  "differenceOfUse": "0",
  "total": "536",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "70",
  "previousWaterMetering": "147",
  "currentWaterMetering": "156",
  "metersConsumed": "9",
  "differenceOfUse": "0",
  "total": "246",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "71",
  "previousWaterMetering": "335",
  "currentWaterMetering": "347",
  "metersConsumed": "12",
  "differenceOfUse": "0",
  "total": "318",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "72",
  "previousWaterMetering": "286",
  "currentWaterMetering": "294",
  "metersConsumed": "8",
  "differenceOfUse": "0",
  "total": "214",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "73",
  "previousWaterMetering": "249",
  "currentWaterMetering": "257",
  "metersConsumed": "8",
  "differenceOfUse": "0",
  "total": "214",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "74",
  "previousWaterMetering": "153",
  "currentWaterMetering": "157",
  "metersConsumed": "4",
  "differenceOfUse": "0",
  "total": "134",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "75",
  "previousWaterMetering": "475",
  "currentWaterMetering": "486",
  "metersConsumed": "11",
  "differenceOfUse": "0",
  "total": "294",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "76",
  "previousWaterMetering": "42",
  "currentWaterMetering": "42",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "66",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "77",
  "previousWaterMetering": "802",
  "currentWaterMetering": "830",
  "metersConsumed": "28",
  "differenceOfUse": "0",
  "total": "925",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "78",
  "previousWaterMetering": "55",
  "currentWaterMetering": "60",
  "metersConsumed": "5",
  "differenceOfUse": "0",
  "total": "153",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "79",
  "previousWaterMetering": "396",
  "currentWaterMetering": "404",
  "metersConsumed": "8",
  "differenceOfUse": "0",
  "total": "214",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "8",
  "previousWaterMetering": "209",
  "currentWaterMetering": "210",
  "metersConsumed": "1",
  "differenceOfUse": "0",
  "total": "83",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "80",
  "previousWaterMetering": "514",
  "currentWaterMetering": "535",
  "metersConsumed": "21",
  "differenceOfUse": "0",
  "total": "567",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "81",
  "previousWaterMetering": "175",
  "currentWaterMetering": "190",
  "metersConsumed": "15",
  "differenceOfUse": "0",
  "total": "399",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "82",
  "previousWaterMetering": "383",
  "currentWaterMetering": "395",
  "metersConsumed": "12",
  "differenceOfUse": "0",
  "total": "318",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "83",
  "previousWaterMetering": "237",
  "currentWaterMetering": "244",
  "metersConsumed": "7",
  "differenceOfUse": "0",
  "total": "193",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "84",
  "previousWaterMetering": "278",
  "currentWaterMetering": "286",
  "metersConsumed": "8",
  "differenceOfUse": "0",
  "total": "214",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "85",
  "previousWaterMetering": "307",
  "currentWaterMetering": "318",
  "metersConsumed": "11",
  "differenceOfUse": "0",
  "total": "294",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "86",
  "previousWaterMetering": "189",
  "currentWaterMetering": "210",
  "metersConsumed": "21",
  "differenceOfUse": "0",
  "total": "567",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "87",
  "previousWaterMetering": "337",
  "currentWaterMetering": "355",
  "metersConsumed": "18",
  "differenceOfUse": "0",
  "total": "480",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "88",
  "previousWaterMetering": "400",
  "currentWaterMetering": "407",
  "metersConsumed": "7",
  "differenceOfUse": "0",
  "total": "193",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "89",
  "previousWaterMetering": "717",
  "currentWaterMetering": "732",
  "metersConsumed": "15",
  "differenceOfUse": "0",
  "total": "399",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "9",
  "previousWaterMetering": "273",
  "currentWaterMetering": "280",
  "metersConsumed": "7",
  "differenceOfUse": "0",
  "total": "193",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "90",
  "previousWaterMetering": "793",
  "currentWaterMetering": "827",
  "metersConsumed": "34",
  "differenceOfUse": "0",
  "total": "1338",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "91",
  "previousWaterMetering": "344",
  "currentWaterMetering": "352",
  "metersConsumed": "8",
  "differenceOfUse": "0",
  "total": "214",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "92",
  "previousWaterMetering": "490",
  "currentWaterMetering": "502",
  "metersConsumed": "12",
  "differenceOfUse": "0",
  "total": "318",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "93",
  "previousWaterMetering": "269",
  "currentWaterMetering": "282",
  "metersConsumed": "13",
  "differenceOfUse": "0",
  "total": "346",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "94",
  "previousWaterMetering": "501",
  "currentWaterMetering": "511",
  "metersConsumed": "10",
  "differenceOfUse": "0",
  "total": "270",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "95",
  "previousWaterMetering": "64",
  "currentWaterMetering": "64",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "66",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "96",
  "previousWaterMetering": "163",
  "currentWaterMetering": "167",
  "metersConsumed": "4",
  "differenceOfUse": "0",
  "total": "134",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "97",
  "previousWaterMetering": "219",
  "currentWaterMetering": "222",
  "metersConsumed": "3",
  "differenceOfUse": "0",
  "total": "116",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "98",
  "previousWaterMetering": "100",
  "currentWaterMetering": "100",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "66",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
},
{
  "houseId": "99",
  "previousWaterMetering": "237",
  "currentWaterMetering": "237",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "66",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Noviembre",
  "paymentMonth": "Enero",
  "year": "2026"
}]
;

export const reportShimul = data;
