
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =
[{
  "houseId": "1",
  "previousWaterMetering": "366",
  "currentWaterMetering": "379",
  "metersConsumed": "13",
  "differenceOfUse": "94",
  "total": "422",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "2",
  "previousWaterMetering": "98",
  "currentWaterMetering": "109",
  "metersConsumed": "11",
  "differenceOfUse": "94",
  "total": "372",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "3",
  "previousWaterMetering": "420",
  "currentWaterMetering": "430",
  "metersConsumed": "10",
  "differenceOfUse": "94",
  "total": "350",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "4",
  "previousWaterMetering": "334",
  "currentWaterMetering": "360",
  "metersConsumed": "26",
  "differenceOfUse": "94",
  "total": "852",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "5",
  "previousWaterMetering": "181",
  "currentWaterMetering": "187",
  "metersConsumed": "6",
  "differenceOfUse": "94",
  "total": "257",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "6",
  "previousWaterMetering": "304",
  "currentWaterMetering": "313",
  "metersConsumed": "9",
  "differenceOfUse": "94",
  "total": "327",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "7",
  "previousWaterMetering": "433",
  "currentWaterMetering": "445",
  "metersConsumed": "12",
  "differenceOfUse": "94",
  "total": "395",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "8",
  "previousWaterMetering": "107",
  "currentWaterMetering": "108",
  "metersConsumed": "1",
  "differenceOfUse": "94",
  "total": "172",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "9",
  "previousWaterMetering": "216",
  "currentWaterMetering": "225",
  "metersConsumed": "9",
  "differenceOfUse": "94",
  "total": "327",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "10",
  "previousWaterMetering": "406",
  "currentWaterMetering": "415",
  "metersConsumed": "9",
  "differenceOfUse": "94",
  "total": "327",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "11",
  "previousWaterMetering": "533",
  "currentWaterMetering": "545",
  "metersConsumed": "12",
  "differenceOfUse": "94",
  "total": "395",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "12",
  "previousWaterMetering": "296",
  "currentWaterMetering": "304",
  "metersConsumed": "8",
  "differenceOfUse": "94",
  "total": "297",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "13",
  "previousWaterMetering": "218",
  "currentWaterMetering": "219",
  "metersConsumed": "1",
  "differenceOfUse": "94",
  "total": "172",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "14",
  "previousWaterMetering": "404",
  "currentWaterMetering": "423",
  "metersConsumed": "19",
  "differenceOfUse": "94",
  "total": "576",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "15",
  "previousWaterMetering": "207",
  "currentWaterMetering": "210",
  "metersConsumed": "3",
  "differenceOfUse": "94",
  "total": "204",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "16",
  "previousWaterMetering": "190",
  "currentWaterMetering": "196",
  "metersConsumed": "6",
  "differenceOfUse": "94",
  "total": "257",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "17",
  "previousWaterMetering": "250",
  "currentWaterMetering": "260",
  "metersConsumed": "10",
  "differenceOfUse": "94",
  "total": "350",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "18",
  "previousWaterMetering": "298",
  "currentWaterMetering": "302",
  "metersConsumed": "4",
  "differenceOfUse": "94",
  "total": "221",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "19",
  "previousWaterMetering": "37",
  "currentWaterMetering": "44",
  "metersConsumed": "7",
  "differenceOfUse": "94",
  "total": "277",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "20",
  "previousWaterMetering": "277",
  "currentWaterMetering": "286",
  "metersConsumed": "9",
  "differenceOfUse": "94",
  "total": "327",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "21",
  "previousWaterMetering": "284",
  "currentWaterMetering": "294",
  "metersConsumed": "10",
  "differenceOfUse": "94",
  "total": "350",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "22",
  "previousWaterMetering": "287",
  "currentWaterMetering": "296",
  "metersConsumed": "9",
  "differenceOfUse": "94",
  "total": "327",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "23",
  "previousWaterMetering": "564",
  "currentWaterMetering": "579",
  "metersConsumed": "15",
  "differenceOfUse": "94",
  "total": "472",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "24",
  "previousWaterMetering": "257",
  "currentWaterMetering": "268",
  "metersConsumed": "11",
  "differenceOfUse": "94",
  "total": "372",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "25",
  "previousWaterMetering": "162",
  "currentWaterMetering": "168",
  "metersConsumed": "6",
  "differenceOfUse": "94",
  "total": "257",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "26",
  "previousWaterMetering": "34",
  "currentWaterMetering": "34",
  "metersConsumed": "0",
  "differenceOfUse": "94",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "27",
  "previousWaterMetering": "226",
  "currentWaterMetering": "233",
  "metersConsumed": "7",
  "differenceOfUse": "94",
  "total": "277",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "28",
  "previousWaterMetering": "42",
  "currentWaterMetering": "42",
  "metersConsumed": "0",
  "differenceOfUse": "94",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "29",
  "previousWaterMetering": "143",
  "currentWaterMetering": "150",
  "metersConsumed": "7",
  "differenceOfUse": "94",
  "total": "277",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "30",
  "previousWaterMetering": "435",
  "currentWaterMetering": "441",
  "metersConsumed": "6",
  "differenceOfUse": "94",
  "total": "257",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "31",
  "previousWaterMetering": "270",
  "currentWaterMetering": "280",
  "metersConsumed": "10",
  "differenceOfUse": "94",
  "total": "350",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "32",
  "previousWaterMetering": "431",
  "currentWaterMetering": "444",
  "metersConsumed": "13",
  "differenceOfUse": "94",
  "total": "422",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "33",
  "previousWaterMetering": "137",
  "currentWaterMetering": "139",
  "metersConsumed": "2",
  "differenceOfUse": "94",
  "total": "188",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "34",
  "previousWaterMetering": "394",
  "currentWaterMetering": "403",
  "metersConsumed": "9",
  "differenceOfUse": "94",
  "total": "327",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "35",
  "previousWaterMetering": "563",
  "currentWaterMetering": "583",
  "metersConsumed": "20",
  "differenceOfUse": "94",
  "total": "603",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "36",
  "previousWaterMetering": "347",
  "currentWaterMetering": "361",
  "metersConsumed": "14",
  "differenceOfUse": "94",
  "total": "447",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "37",
  "previousWaterMetering": "233",
  "currentWaterMetering": "241",
  "metersConsumed": "8",
  "differenceOfUse": "94",
  "total": "297",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "38",
  "previousWaterMetering": "409",
  "currentWaterMetering": "418",
  "metersConsumed": "9",
  "differenceOfUse": "94",
  "total": "327",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "39",
  "previousWaterMetering": "251",
  "currentWaterMetering": "252",
  "metersConsumed": "1",
  "differenceOfUse": "94",
  "total": "172",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "40",
  "previousWaterMetering": "90",
  "currentWaterMetering": "91",
  "metersConsumed": "1",
  "differenceOfUse": "94",
  "total": "172",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "41",
  "previousWaterMetering": "519",
  "currentWaterMetering": "528",
  "metersConsumed": "9",
  "differenceOfUse": "94",
  "total": "327",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "42",
  "previousWaterMetering": "449",
  "currentWaterMetering": "463",
  "metersConsumed": "14",
  "differenceOfUse": "94",
  "total": "447",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "43",
  "previousWaterMetering": "186",
  "currentWaterMetering": "187",
  "metersConsumed": "1",
  "differenceOfUse": "94",
  "total": "172",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "44",
  "previousWaterMetering": "85",
  "currentWaterMetering": "87",
  "metersConsumed": "2",
  "differenceOfUse": "94",
  "total": "188",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "45",
  "previousWaterMetering": "510",
  "currentWaterMetering": "528",
  "metersConsumed": "18",
  "differenceOfUse": "94",
  "total": "549",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "46",
  "previousWaterMetering": "182",
  "currentWaterMetering": "186",
  "metersConsumed": "4",
  "differenceOfUse": "94",
  "total": "221",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "47",
  "previousWaterMetering": "500",
  "currentWaterMetering": "504",
  "metersConsumed": "4",
  "differenceOfUse": "94",
  "total": "221",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "48",
  "previousWaterMetering": "163",
  "currentWaterMetering": "172",
  "metersConsumed": "9",
  "differenceOfUse": "94",
  "total": "327",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "49",
  "previousWaterMetering": "340",
  "currentWaterMetering": "352",
  "metersConsumed": "12",
  "differenceOfUse": "94",
  "total": "395",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "50",
  "previousWaterMetering": "162",
  "currentWaterMetering": "169",
  "metersConsumed": "7",
  "differenceOfUse": "94",
  "total": "277",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "51",
  "previousWaterMetering": "84",
  "currentWaterMetering": "86",
  "metersConsumed": "2",
  "differenceOfUse": "94",
  "total": "188",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "52",
  "previousWaterMetering": "281",
  "currentWaterMetering": "287",
  "metersConsumed": "6",
  "differenceOfUse": "94",
  "total": "257",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "53",
  "previousWaterMetering": "118",
  "currentWaterMetering": "120",
  "metersConsumed": "2",
  "differenceOfUse": "94",
  "total": "188",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "54",
  "previousWaterMetering": "416",
  "currentWaterMetering": "427",
  "metersConsumed": "11",
  "differenceOfUse": "94",
  "total": "372",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "94",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "56",
  "previousWaterMetering": "5",
  "currentWaterMetering": "6",
  "metersConsumed": "1",
  "differenceOfUse": "94",
  "total": "172",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "57",
  "previousWaterMetering": "600",
  "currentWaterMetering": "603",
  "metersConsumed": "3",
  "differenceOfUse": "94",
  "total": "204",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "58",
  "previousWaterMetering": "370",
  "currentWaterMetering": "375",
  "metersConsumed": "5",
  "differenceOfUse": "94",
  "total": "239",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "59",
  "previousWaterMetering": "209",
  "currentWaterMetering": "222",
  "metersConsumed": "13",
  "differenceOfUse": "94",
  "total": "422",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "60",
  "previousWaterMetering": "262",
  "currentWaterMetering": "271",
  "metersConsumed": "9",
  "differenceOfUse": "94",
  "total": "327",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "61",
  "previousWaterMetering": "80",
  "currentWaterMetering": "81",
  "metersConsumed": "1",
  "differenceOfUse": "94",
  "total": "172",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "62",
  "previousWaterMetering": "219",
  "currentWaterMetering": "223",
  "metersConsumed": "4",
  "differenceOfUse": "94",
  "total": "221",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "63",
  "previousWaterMetering": "575",
  "currentWaterMetering": "595",
  "metersConsumed": "20",
  "differenceOfUse": "94",
  "total": "603",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "64",
  "previousWaterMetering": "165",
  "currentWaterMetering": "173",
  "metersConsumed": "8",
  "differenceOfUse": "94",
  "total": "297",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "65",
  "previousWaterMetering": "655",
  "currentWaterMetering": "672",
  "metersConsumed": "17",
  "differenceOfUse": "94",
  "total": "524",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "66",
  "previousWaterMetering": "133",
  "currentWaterMetering": "135",
  "metersConsumed": "2",
  "differenceOfUse": "94",
  "total": "188",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "67",
  "previousWaterMetering": "219",
  "currentWaterMetering": "225",
  "metersConsumed": "6",
  "differenceOfUse": "94",
  "total": "257",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "94",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "69",
  "previousWaterMetering": "392",
  "currentWaterMetering": "406",
  "metersConsumed": "14",
  "differenceOfUse": "94",
  "total": "447",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "70",
  "previousWaterMetering": "79",
  "currentWaterMetering": "84",
  "metersConsumed": "5",
  "differenceOfUse": "94",
  "total": "239",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "71",
  "previousWaterMetering": "239",
  "currentWaterMetering": "245",
  "metersConsumed": "6",
  "differenceOfUse": "94",
  "total": "257",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "72",
  "previousWaterMetering": "208",
  "currentWaterMetering": "214",
  "metersConsumed": "6",
  "differenceOfUse": "94",
  "total": "257",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "73",
  "previousWaterMetering": "184",
  "currentWaterMetering": "191",
  "metersConsumed": "7",
  "differenceOfUse": "94",
  "total": "277",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "74",
  "previousWaterMetering": "113",
  "currentWaterMetering": "116",
  "metersConsumed": "3",
  "differenceOfUse": "94",
  "total": "204",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "75",
  "previousWaterMetering": "361",
  "currentWaterMetering": "375",
  "metersConsumed": "14",
  "differenceOfUse": "94",
  "total": "447",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "76",
  "previousWaterMetering": "32",
  "currentWaterMetering": "36",
  "metersConsumed": "4",
  "differenceOfUse": "94",
  "total": "221",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "77",
  "previousWaterMetering": "612",
  "currentWaterMetering": "631",
  "metersConsumed": "19",
  "differenceOfUse": "94",
  "total": "576",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "78",
  "previousWaterMetering": "37",
  "currentWaterMetering": "38",
  "metersConsumed": "1",
  "differenceOfUse": "94",
  "total": "172",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "79",
  "previousWaterMetering": "294",
  "currentWaterMetering": "307",
  "metersConsumed": "13",
  "differenceOfUse": "94",
  "total": "422",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "80",
  "previousWaterMetering": "372",
  "currentWaterMetering": "387",
  "metersConsumed": "15",
  "differenceOfUse": "94",
  "total": "472",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "81",
  "previousWaterMetering": "65",
  "currentWaterMetering": "73",
  "metersConsumed": "8",
  "differenceOfUse": "94",
  "total": "297",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "82",
  "previousWaterMetering": "289",
  "currentWaterMetering": "300",
  "metersConsumed": "11",
  "differenceOfUse": "94",
  "total": "372",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "83",
  "previousWaterMetering": "185",
  "currentWaterMetering": "189",
  "metersConsumed": "4",
  "differenceOfUse": "94",
  "total": "221",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "84",
  "previousWaterMetering": "225",
  "currentWaterMetering": "229",
  "metersConsumed": "4",
  "differenceOfUse": "94",
  "total": "221",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "85",
  "previousWaterMetering": "213",
  "currentWaterMetering": "222",
  "metersConsumed": "9",
  "differenceOfUse": "94",
  "total": "327",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "86",
  "previousWaterMetering": "44",
  "currentWaterMetering": "57",
  "metersConsumed": "13",
  "differenceOfUse": "94",
  "total": "422",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "87",
  "previousWaterMetering": "189",
  "currentWaterMetering": "192",
  "metersConsumed": "3",
  "differenceOfUse": "94",
  "total": "204",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "88",
  "previousWaterMetering": "316",
  "currentWaterMetering": "324",
  "metersConsumed": "8",
  "differenceOfUse": "94",
  "total": "297",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "89",
  "previousWaterMetering": "557",
  "currentWaterMetering": "570",
  "metersConsumed": "13",
  "differenceOfUse": "94",
  "total": "422",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "90",
  "previousWaterMetering": "495",
  "currentWaterMetering": "522",
  "metersConsumed": "27",
  "differenceOfUse": "94",
  "total": "911",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "91",
  "previousWaterMetering": "272",
  "currentWaterMetering": "284",
  "metersConsumed": "12",
  "differenceOfUse": "94",
  "total": "395",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "92",
  "previousWaterMetering": "379",
  "currentWaterMetering": "386",
  "metersConsumed": "7",
  "differenceOfUse": "94",
  "total": "277",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "93",
  "previousWaterMetering": "181",
  "currentWaterMetering": "188",
  "metersConsumed": "7",
  "differenceOfUse": "94",
  "total": "277",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "94",
  "previousWaterMetering": "372",
  "currentWaterMetering": "383",
  "metersConsumed": "11",
  "differenceOfUse": "94",
  "total": "372",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "95",
  "previousWaterMetering": "63",
  "currentWaterMetering": "63",
  "metersConsumed": "0",
  "differenceOfUse": "94",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "96",
  "previousWaterMetering": "123",
  "currentWaterMetering": "124",
  "metersConsumed": "1",
  "differenceOfUse": "94",
  "total": "172",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "97",
  "previousWaterMetering": "170",
  "currentWaterMetering": "174",
  "metersConsumed": "4",
  "differenceOfUse": "94",
  "total": "221",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "98",
  "previousWaterMetering": "75",
  "currentWaterMetering": "78",
  "metersConsumed": "3",
  "differenceOfUse": "94",
  "total": "204",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "99",
  "previousWaterMetering": "209",
  "currentWaterMetering": "217",
  "metersConsumed": "8",
  "differenceOfUse": "94",
  "total": "297",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "94",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "101",
  "previousWaterMetering": "179",
  "currentWaterMetering": "183",
  "metersConsumed": "4",
  "differenceOfUse": "94",
  "total": "221",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "102",
  "previousWaterMetering": "113",
  "currentWaterMetering": "117",
  "metersConsumed": "4",
  "differenceOfUse": "94",
  "total": "221",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
},
{
  "houseId": "103",
  "previousWaterMetering": "6",
  "currentWaterMetering": "6",
  "metersConsumed": "0",
  "differenceOfUse": "94",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2025"
}]
;

export const reportShimul = data;
