 
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =
[{
  "houseId": "1",
  "previousWaterMetering": "562",
  "currentWaterMetering": "569",
  "metersConsumed": "7",
  "differenceOfUse": "37",
  "total": "232",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "2",
  "previousWaterMetering": "197",
  "currentWaterMetering": "198",
  "metersConsumed": "1",
  "differenceOfUse": "37",
  "total": "121",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "3",
  "previousWaterMetering": "548",
  "currentWaterMetering": "548",
  "metersConsumed": "0",
  "differenceOfUse": "37",
  "total": "104",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "4",
  "previousWaterMetering": "502",
  "currentWaterMetering": "509",
  "metersConsumed": "7",
  "differenceOfUse": "37",
  "total": "232",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "5",
  "previousWaterMetering": "494",
  "currentWaterMetering": "504",
  "metersConsumed": "10",
  "differenceOfUse": "37",
  "total": "311",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "6",
  "previousWaterMetering": "456",
  "currentWaterMetering": "474",
  "metersConsumed": "18",
  "differenceOfUse": "37",
  "total": "523",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "7",
  "previousWaterMetering": "632",
  "currentWaterMetering": "648",
  "metersConsumed": "16",
  "differenceOfUse": "37",
  "total": "467",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "8",
  "previousWaterMetering": "213",
  "currentWaterMetering": "214",
  "metersConsumed": "1",
  "differenceOfUse": "37",
  "total": "121",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "9",
  "previousWaterMetering": "296",
  "currentWaterMetering": "301",
  "metersConsumed": "5",
  "differenceOfUse": "37",
  "total": "192",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "10",
  "previousWaterMetering": "545",
  "currentWaterMetering": "553",
  "metersConsumed": "8",
  "differenceOfUse": "37",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "11",
  "previousWaterMetering": "751",
  "currentWaterMetering": "767",
  "metersConsumed": "16",
  "differenceOfUse": "37",
  "total": "467",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "12",
  "previousWaterMetering": "443",
  "currentWaterMetering": "456",
  "metersConsumed": "13",
  "differenceOfUse": "37",
  "total": "387",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "13",
  "previousWaterMetering": "289",
  "currentWaterMetering": "293",
  "metersConsumed": "4",
  "differenceOfUse": "37",
  "total": "173",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "14",
  "previousWaterMetering": "597",
  "currentWaterMetering": "616",
  "metersConsumed": "19",
  "differenceOfUse": "37",
  "total": "551",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "15",
  "previousWaterMetering": "261",
  "currentWaterMetering": "267",
  "metersConsumed": "6",
  "differenceOfUse": "37",
  "total": "211",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "16",
  "previousWaterMetering": "291",
  "currentWaterMetering": "299",
  "metersConsumed": "8",
  "differenceOfUse": "37",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "17",
  "previousWaterMetering": "364",
  "currentWaterMetering": "371",
  "metersConsumed": "7",
  "differenceOfUse": "37",
  "total": "232",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "18",
  "previousWaterMetering": "376",
  "currentWaterMetering": "381",
  "metersConsumed": "5",
  "differenceOfUse": "37",
  "total": "192",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "19",
  "previousWaterMetering": "146",
  "currentWaterMetering": "156",
  "metersConsumed": "10",
  "differenceOfUse": "37",
  "total": "311",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "20.1",
  "previousWaterMetering": "320",
  "currentWaterMetering": "0",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "0",
  "condo": "0",
  "caKey": "0",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "20",
  "previousWaterMetering": "481",
  "currentWaterMetering": "496",
  "metersConsumed": "15",
  "differenceOfUse": "37",
  "total": "441",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "21",
  "previousWaterMetering": "439",
  "currentWaterMetering": "447",
  "metersConsumed": "8",
  "differenceOfUse": "37",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "22",
  "previousWaterMetering": "405",
  "currentWaterMetering": "413",
  "metersConsumed": "8",
  "differenceOfUse": "37",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "23",
  "previousWaterMetering": "810",
  "currentWaterMetering": "823",
  "metersConsumed": "13",
  "differenceOfUse": "37",
  "total": "387",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "24",
  "previousWaterMetering": "372",
  "currentWaterMetering": "380",
  "metersConsumed": "8",
  "differenceOfUse": "37",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "25",
  "previousWaterMetering": "260",
  "currentWaterMetering": "265",
  "metersConsumed": "5",
  "differenceOfUse": "37",
  "total": "192",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "26",
  "previousWaterMetering": "36",
  "currentWaterMetering": "36",
  "metersConsumed": "0",
  "differenceOfUse": "37",
  "total": "104",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "27",
  "previousWaterMetering": "371",
  "currentWaterMetering": "379",
  "metersConsumed": "8",
  "differenceOfUse": "37",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "28",
  "previousWaterMetering": "60",
  "currentWaterMetering": "63",
  "metersConsumed": "3",
  "differenceOfUse": "37",
  "total": "155",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "29",
  "previousWaterMetering": "219",
  "currentWaterMetering": "223",
  "metersConsumed": "4",
  "differenceOfUse": "37",
  "total": "173",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "30",
  "previousWaterMetering": "612",
  "currentWaterMetering": "622",
  "metersConsumed": "10",
  "differenceOfUse": "37",
  "total": "311",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "31",
  "previousWaterMetering": "431",
  "currentWaterMetering": "441",
  "metersConsumed": "10",
  "differenceOfUse": "37",
  "total": "311",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "32",
  "previousWaterMetering": "650",
  "currentWaterMetering": "663",
  "metersConsumed": "13",
  "differenceOfUse": "37",
  "total": "387",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "33",
  "previousWaterMetering": "165",
  "currentWaterMetering": "167",
  "metersConsumed": "2",
  "differenceOfUse": "37",
  "total": "137",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "34",
  "previousWaterMetering": "545",
  "currentWaterMetering": "557",
  "metersConsumed": "12",
  "differenceOfUse": "37",
  "total": "359",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "35",
  "previousWaterMetering": "869",
  "currentWaterMetering": "889",
  "metersConsumed": "20",
  "differenceOfUse": "37",
  "total": "580",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "36",
  "previousWaterMetering": "524",
  "currentWaterMetering": "532",
  "metersConsumed": "8",
  "differenceOfUse": "37",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "37",
  "previousWaterMetering": "361",
  "currentWaterMetering": "371",
  "metersConsumed": "10",
  "differenceOfUse": "37",
  "total": "311",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "38",
  "previousWaterMetering": "519",
  "currentWaterMetering": "523",
  "metersConsumed": "4",
  "differenceOfUse": "37",
  "total": "173",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "39",
  "previousWaterMetering": "343",
  "currentWaterMetering": "351",
  "metersConsumed": "8",
  "differenceOfUse": "37",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "40",
  "previousWaterMetering": "108",
  "currentWaterMetering": "110",
  "metersConsumed": "2",
  "differenceOfUse": "37",
  "total": "137",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "41",
  "previousWaterMetering": "681",
  "currentWaterMetering": "691",
  "metersConsumed": "10",
  "differenceOfUse": "37",
  "total": "311",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "42",
  "previousWaterMetering": "679",
  "currentWaterMetering": "694",
  "metersConsumed": "15",
  "differenceOfUse": "37",
  "total": "441",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "43",
  "previousWaterMetering": "229",
  "currentWaterMetering": "232",
  "metersConsumed": "3",
  "differenceOfUse": "37",
  "total": "155",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "44",
  "previousWaterMetering": "150",
  "currentWaterMetering": "154",
  "metersConsumed": "4",
  "differenceOfUse": "37",
  "total": "173",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "45",
  "previousWaterMetering": "751",
  "currentWaterMetering": "760",
  "metersConsumed": "9",
  "differenceOfUse": "37",
  "total": "286",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "46",
  "previousWaterMetering": "262",
  "currentWaterMetering": "267",
  "metersConsumed": "5",
  "differenceOfUse": "37",
  "total": "192",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "47",
  "previousWaterMetering": "607",
  "currentWaterMetering": "613",
  "metersConsumed": "6",
  "differenceOfUse": "37",
  "total": "211",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "48",
  "previousWaterMetering": "291",
  "currentWaterMetering": "298",
  "metersConsumed": "7",
  "differenceOfUse": "37",
  "total": "232",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "49",
  "previousWaterMetering": "526",
  "currentWaterMetering": "576",
  "metersConsumed": "50",
  "differenceOfUse": "37",
  "total": "2615",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "50",
  "previousWaterMetering": "565",
  "currentWaterMetering": "566",
  "metersConsumed": "1",
  "differenceOfUse": "37",
  "total": "121",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "51",
  "previousWaterMetering": "122",
  "currentWaterMetering": "124",
  "metersConsumed": "2",
  "differenceOfUse": "37",
  "total": "137",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "52",
  "previousWaterMetering": "370",
  "currentWaterMetering": "375",
  "metersConsumed": "5",
  "differenceOfUse": "37",
  "total": "192",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "53",
  "previousWaterMetering": "183",
  "currentWaterMetering": "188",
  "metersConsumed": "5",
  "differenceOfUse": "37",
  "total": "192",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "54",
  "previousWaterMetering": "595",
  "currentWaterMetering": "606",
  "metersConsumed": "11",
  "differenceOfUse": "37",
  "total": "334",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "37",
  "total": "104",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "56",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "37",
  "total": "104",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "57",
  "previousWaterMetering": "737",
  "currentWaterMetering": "749",
  "metersConsumed": "12",
  "differenceOfUse": "37",
  "total": "359",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "58",
  "previousWaterMetering": "470",
  "currentWaterMetering": "475",
  "metersConsumed": "5",
  "differenceOfUse": "37",
  "total": "192",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "59",
  "previousWaterMetering": "371",
  "currentWaterMetering": "382",
  "metersConsumed": "11",
  "differenceOfUse": "37",
  "total": "334",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "60",
  "previousWaterMetering": "413",
  "currentWaterMetering": "424",
  "metersConsumed": "11",
  "differenceOfUse": "37",
  "total": "334",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "61",
  "previousWaterMetering": "106",
  "currentWaterMetering": "108",
  "metersConsumed": "2",
  "differenceOfUse": "37",
  "total": "137",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "62",
  "previousWaterMetering": "373",
  "currentWaterMetering": "385",
  "metersConsumed": "12",
  "differenceOfUse": "37",
  "total": "359",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "63",
  "previousWaterMetering": "825",
  "currentWaterMetering": "838",
  "metersConsumed": "13",
  "differenceOfUse": "37",
  "total": "387",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "64",
  "previousWaterMetering": "259",
  "currentWaterMetering": "267",
  "metersConsumed": "8",
  "differenceOfUse": "37",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "65",
  "previousWaterMetering": "862",
  "currentWaterMetering": "878",
  "metersConsumed": "16",
  "differenceOfUse": "37",
  "total": "467",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "66",
  "previousWaterMetering": "179",
  "currentWaterMetering": "181",
  "metersConsumed": "2",
  "differenceOfUse": "37",
  "total": "137",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "67",
  "previousWaterMetering": "335",
  "currentWaterMetering": "342",
  "metersConsumed": "7",
  "differenceOfUse": "37",
  "total": "232",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "37",
  "total": "104",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "69",
  "previousWaterMetering": "603",
  "currentWaterMetering": "614",
  "metersConsumed": "11",
  "differenceOfUse": "37",
  "total": "334",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "70",
  "previousWaterMetering": "173",
  "currentWaterMetering": "178",
  "metersConsumed": "5",
  "differenceOfUse": "37",
  "total": "192",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "71",
  "previousWaterMetering": "366",
  "currentWaterMetering": "376",
  "metersConsumed": "10",
  "differenceOfUse": "37",
  "total": "311",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "72",
  "previousWaterMetering": "317",
  "currentWaterMetering": "325",
  "metersConsumed": "8",
  "differenceOfUse": "37",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "73",
  "previousWaterMetering": "273",
  "currentWaterMetering": "278",
  "metersConsumed": "5",
  "differenceOfUse": "37",
  "total": "192",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "74",
  "previousWaterMetering": "165",
  "currentWaterMetering": "169",
  "metersConsumed": "4",
  "differenceOfUse": "37",
  "total": "173",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "75",
  "previousWaterMetering": "508",
  "currentWaterMetering": "516",
  "metersConsumed": "8",
  "differenceOfUse": "37",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "76",
  "previousWaterMetering": "43",
  "currentWaterMetering": "45",
  "metersConsumed": "2",
  "differenceOfUse": "37",
  "total": "137",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "77",
  "previousWaterMetering": "859",
  "currentWaterMetering": "861",
  "metersConsumed": "2",
  "differenceOfUse": "37",
  "total": "137",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "78",
  "previousWaterMetering": "65",
  "currentWaterMetering": "66",
  "metersConsumed": "1",
  "differenceOfUse": "37",
  "total": "121",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "79",
  "previousWaterMetering": "422",
  "currentWaterMetering": "428",
  "metersConsumed": "6",
  "differenceOfUse": "37",
  "total": "211",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "80",
  "previousWaterMetering": "579",
  "currentWaterMetering": "596",
  "metersConsumed": "17",
  "differenceOfUse": "37",
  "total": "496",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "81",
  "previousWaterMetering": "218",
  "currentWaterMetering": "229",
  "metersConsumed": "11",
  "differenceOfUse": "37",
  "total": "334",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "82",
  "previousWaterMetering": "415",
  "currentWaterMetering": "424",
  "metersConsumed": "9",
  "differenceOfUse": "37",
  "total": "286",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "83",
  "previousWaterMetering": "246",
  "currentWaterMetering": "247",
  "metersConsumed": "1",
  "differenceOfUse": "37",
  "total": "121",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "84",
  "previousWaterMetering": "301",
  "currentWaterMetering": "308",
  "metersConsumed": "7",
  "differenceOfUse": "37",
  "total": "232",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "85",
  "previousWaterMetering": "341",
  "currentWaterMetering": "347",
  "metersConsumed": "6",
  "differenceOfUse": "37",
  "total": "211",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "86",
  "previousWaterMetering": "239",
  "currentWaterMetering": "249",
  "metersConsumed": "10",
  "differenceOfUse": "37",
  "total": "311",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "87",
  "previousWaterMetering": "390",
  "currentWaterMetering": "394",
  "metersConsumed": "4",
  "differenceOfUse": "37",
  "total": "173",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "88",
  "previousWaterMetering": "422",
  "currentWaterMetering": "430",
  "metersConsumed": "8",
  "differenceOfUse": "37",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "89",
  "previousWaterMetering": "769",
  "currentWaterMetering": "786",
  "metersConsumed": "17",
  "differenceOfUse": "37",
  "total": "496",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "90",
  "previousWaterMetering": "905",
  "currentWaterMetering": "934",
  "metersConsumed": "29",
  "differenceOfUse": "37",
  "total": "1044",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "91",
  "previousWaterMetering": "374",
  "currentWaterMetering": "383",
  "metersConsumed": "9",
  "differenceOfUse": "37",
  "total": "286",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "92",
  "previousWaterMetering": "522",
  "currentWaterMetering": "528",
  "metersConsumed": "6",
  "differenceOfUse": "37",
  "total": "211",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "93",
  "previousWaterMetering": "320",
  "currentWaterMetering": "333",
  "metersConsumed": "13",
  "differenceOfUse": "37",
  "total": "387",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "94",
  "previousWaterMetering": "538",
  "currentWaterMetering": "547",
  "metersConsumed": "9",
  "differenceOfUse": "37",
  "total": "286",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "95",
  "previousWaterMetering": "66",
  "currentWaterMetering": "66",
  "metersConsumed": "0",
  "differenceOfUse": "37",
  "total": "104",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "96",
  "previousWaterMetering": "174",
  "currentWaterMetering": "179",
  "metersConsumed": "5",
  "differenceOfUse": "37",
  "total": "192",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "97",
  "previousWaterMetering": "232",
  "currentWaterMetering": "237",
  "metersConsumed": "5",
  "differenceOfUse": "37",
  "total": "192",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "98",
  "previousWaterMetering": "106",
  "currentWaterMetering": "109",
  "metersConsumed": "3",
  "differenceOfUse": "37",
  "total": "155",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "99",
  "previousWaterMetering": "238",
  "currentWaterMetering": "239",
  "metersConsumed": "1",
  "differenceOfUse": "37",
  "total": "121",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "37",
  "total": "104",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "101",
  "previousWaterMetering": "262",
  "currentWaterMetering": "287",
  "metersConsumed": "25",
  "differenceOfUse": "37",
  "total": "787",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "102",
  "previousWaterMetering": "165",
  "currentWaterMetering": "170",
  "metersConsumed": "5",
  "differenceOfUse": "37",
  "total": "192",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
},
{
  "houseId": "103",
  "previousWaterMetering": "13",
  "currentWaterMetering": "13",
  "metersConsumed": "0",
  "differenceOfUse": "37",
  "total": "104",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Marzo",
  "paymentMonth": "Mayo",
  "year": "2026"
}]
;

export const reportShimul = data;
