 
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =
[{
  "houseId": "1",
  "previousWaterMetering": "531",
  "currentWaterMetering": "541",
  "metersConsumed": "10",
  "differenceOfUse": "4",
  "total": "274",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "2",
  "previousWaterMetering": "188",
  "currentWaterMetering": "193",
  "metersConsumed": "5",
  "differenceOfUse": "4",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "3",
  "previousWaterMetering": "548",
  "currentWaterMetering": "548",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "4",
  "previousWaterMetering": "464",
  "currentWaterMetering": "480",
  "metersConsumed": "16",
  "differenceOfUse": "4",
  "total": "428",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "5",
  "previousWaterMetering": "356",
  "currentWaterMetering": "471",
  "metersConsumed": "115",
  "differenceOfUse": "4",
  "total": "8888",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "6",
  "previousWaterMetering": "414",
  "currentWaterMetering": "419",
  "metersConsumed": "5",
  "differenceOfUse": "4",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "7",
  "previousWaterMetering": "582",
  "currentWaterMetering": "599",
  "metersConsumed": "17",
  "differenceOfUse": "4",
  "total": "457",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "8",
  "previousWaterMetering": "210",
  "currentWaterMetering": "211",
  "metersConsumed": "1",
  "differenceOfUse": "4",
  "total": "87",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "9",
  "previousWaterMetering": "280",
  "currentWaterMetering": "286",
  "metersConsumed": "6",
  "differenceOfUse": "4",
  "total": "176",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "10",
  "previousWaterMetering": "517",
  "currentWaterMetering": "523",
  "metersConsumed": "6",
  "differenceOfUse": "4",
  "total": "176",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "11",
  "previousWaterMetering": "708",
  "currentWaterMetering": "723",
  "metersConsumed": "15",
  "differenceOfUse": "4",
  "total": "403",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "12",
  "previousWaterMetering": "410",
  "currentWaterMetering": "422",
  "metersConsumed": "12",
  "differenceOfUse": "4",
  "total": "322",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "13",
  "previousWaterMetering": "286",
  "currentWaterMetering": "286",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "14",
  "previousWaterMetering": "549",
  "currentWaterMetering": "565",
  "metersConsumed": "16",
  "differenceOfUse": "4",
  "total": "428",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "15",
  "previousWaterMetering": "250",
  "currentWaterMetering": "252",
  "metersConsumed": "2",
  "differenceOfUse": "4",
  "total": "103",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "16",
  "previousWaterMetering": "273",
  "currentWaterMetering": "277",
  "metersConsumed": "4",
  "differenceOfUse": "4",
  "total": "138",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "17",
  "previousWaterMetering": "338",
  "currentWaterMetering": "346",
  "metersConsumed": "8",
  "differenceOfUse": "4",
  "total": "218",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "18",
  "previousWaterMetering": "371",
  "currentWaterMetering": "371",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "19",
  "previousWaterMetering": "127",
  "currentWaterMetering": "131",
  "metersConsumed": "4",
  "differenceOfUse": "4",
  "total": "138",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "20.1",
  "previousWaterMetering": "0",
  "currentWaterMetering": "0",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "0",
  "condo": "0",
  "caKey": "0",
  "periodOfUse": "0",
  "paymentMonth": "0",
  "year": "0"
},
{
  "houseId": "20",
  "previousWaterMetering": "446",
  "currentWaterMetering": "456",
  "metersConsumed": "10",
  "differenceOfUse": "4",
  "total": "274",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "21",
  "previousWaterMetering": "415",
  "currentWaterMetering": "422",
  "metersConsumed": "7",
  "differenceOfUse": "4",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "22",
  "previousWaterMetering": "382",
  "currentWaterMetering": "388",
  "metersConsumed": "6",
  "differenceOfUse": "4",
  "total": "176",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "23",
  "previousWaterMetering": "770",
  "currentWaterMetering": "781",
  "metersConsumed": "11",
  "differenceOfUse": "4",
  "total": "298",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "24",
  "previousWaterMetering": "345",
  "currentWaterMetering": "354",
  "metersConsumed": "9",
  "differenceOfUse": "4",
  "total": "250",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "25",
  "previousWaterMetering": "244",
  "currentWaterMetering": "249",
  "metersConsumed": "5",
  "differenceOfUse": "4",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "26",
  "previousWaterMetering": "36",
  "currentWaterMetering": "36",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "27",
  "previousWaterMetering": "353",
  "currentWaterMetering": "356",
  "metersConsumed": "3",
  "differenceOfUse": "4",
  "total": "120",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "28",
  "previousWaterMetering": "51",
  "currentWaterMetering": "53",
  "metersConsumed": "2",
  "differenceOfUse": "4",
  "total": "103",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "29",
  "previousWaterMetering": "205",
  "currentWaterMetering": "210",
  "metersConsumed": "5",
  "differenceOfUse": "4",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "30",
  "previousWaterMetering": "593",
  "currentWaterMetering": "593",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "31",
  "previousWaterMetering": "399",
  "currentWaterMetering": "409",
  "metersConsumed": "10",
  "differenceOfUse": "4",
  "total": "274",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "32",
  "previousWaterMetering": "605",
  "currentWaterMetering": "617",
  "metersConsumed": "12",
  "differenceOfUse": "4",
  "total": "322",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "33",
  "previousWaterMetering": "161",
  "currentWaterMetering": "161",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "34",
  "previousWaterMetering": "527",
  "currentWaterMetering": "527",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "35",
  "previousWaterMetering": "805",
  "currentWaterMetering": "827",
  "metersConsumed": "22",
  "differenceOfUse": "4",
  "total": "600",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "36",
  "previousWaterMetering": "504",
  "currentWaterMetering": "509",
  "metersConsumed": "5",
  "differenceOfUse": "4",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "37",
  "previousWaterMetering": "335",
  "currentWaterMetering": "343",
  "metersConsumed": "8",
  "differenceOfUse": "4",
  "total": "218",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "38",
  "previousWaterMetering": "502",
  "currentWaterMetering": "507",
  "metersConsumed": "5",
  "differenceOfUse": "4",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "39",
  "previousWaterMetering": "326",
  "currentWaterMetering": "329",
  "metersConsumed": "3",
  "differenceOfUse": "4",
  "total": "120",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "40",
  "previousWaterMetering": "105",
  "currentWaterMetering": "106",
  "metersConsumed": "1",
  "differenceOfUse": "4",
  "total": "87",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "41",
  "previousWaterMetering": "656",
  "currentWaterMetering": "660",
  "metersConsumed": "4",
  "differenceOfUse": "4",
  "total": "138",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "42",
  "previousWaterMetering": "636",
  "currentWaterMetering": "649",
  "metersConsumed": "13",
  "differenceOfUse": "4",
  "total": "350",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "43",
  "previousWaterMetering": "212",
  "currentWaterMetering": "215",
  "metersConsumed": "3",
  "differenceOfUse": "4",
  "total": "120",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "44",
  "previousWaterMetering": "137",
  "currentWaterMetering": "140",
  "metersConsumed": "3",
  "differenceOfUse": "4",
  "total": "120",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "45",
  "previousWaterMetering": "694",
  "currentWaterMetering": "711",
  "metersConsumed": "17",
  "differenceOfUse": "4",
  "total": "457",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "46",
  "previousWaterMetering": "247",
  "currentWaterMetering": "252",
  "metersConsumed": "5",
  "differenceOfUse": "4",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "47",
  "previousWaterMetering": "586",
  "currentWaterMetering": "592",
  "metersConsumed": "6",
  "differenceOfUse": "4",
  "total": "176",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "48",
  "previousWaterMetering": "272",
  "currentWaterMetering": "277",
  "metersConsumed": "5",
  "differenceOfUse": "4",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "49",
  "previousWaterMetering": "483",
  "currentWaterMetering": "495",
  "metersConsumed": "12",
  "differenceOfUse": "4",
  "total": "322",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "50",
  "previousWaterMetering": "563",
  "currentWaterMetering": "563",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "51",
  "previousWaterMetering": "116",
  "currentWaterMetering": "118",
  "metersConsumed": "2",
  "differenceOfUse": "4",
  "total": "103",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "52",
  "previousWaterMetering": "353",
  "currentWaterMetering": "357",
  "metersConsumed": "4",
  "differenceOfUse": "4",
  "total": "138",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "53",
  "previousWaterMetering": "167",
  "currentWaterMetering": "170",
  "metersConsumed": "3",
  "differenceOfUse": "4",
  "total": "120",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "54",
  "previousWaterMetering": "560",
  "currentWaterMetering": "570",
  "metersConsumed": "10",
  "differenceOfUse": "4",
  "total": "274",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "56",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "57",
  "previousWaterMetering": "705",
  "currentWaterMetering": "712",
  "metersConsumed": "7",
  "differenceOfUse": "4",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "58",
  "previousWaterMetering": "448",
  "currentWaterMetering": "453",
  "metersConsumed": "5",
  "differenceOfUse": "4",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "59",
  "previousWaterMetering": "341",
  "currentWaterMetering": "348",
  "metersConsumed": "7",
  "differenceOfUse": "4",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "60",
  "previousWaterMetering": "386",
  "currentWaterMetering": "390",
  "metersConsumed": "4",
  "differenceOfUse": "4",
  "total": "138",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "61",
  "previousWaterMetering": "102",
  "currentWaterMetering": "102",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "62",
  "previousWaterMetering": "366",
  "currentWaterMetering": "370",
  "metersConsumed": "4",
  "differenceOfUse": "4",
  "total": "138",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "63",
  "previousWaterMetering": "785",
  "currentWaterMetering": "795",
  "metersConsumed": "10",
  "differenceOfUse": "4",
  "total": "274",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "64",
  "previousWaterMetering": "239",
  "currentWaterMetering": "243",
  "metersConsumed": "4",
  "differenceOfUse": "4",
  "total": "138",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "65",
  "previousWaterMetering": "823",
  "currentWaterMetering": "835",
  "metersConsumed": "12",
  "differenceOfUse": "4",
  "total": "322",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "66",
  "previousWaterMetering": "172",
  "currentWaterMetering": "176",
  "metersConsumed": "4",
  "differenceOfUse": "4",
  "total": "138",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "67",
  "previousWaterMetering": "311",
  "currentWaterMetering": "318",
  "metersConsumed": "7",
  "differenceOfUse": "4",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "69",
  "previousWaterMetering": "556",
  "currentWaterMetering": "570",
  "metersConsumed": "14",
  "differenceOfUse": "4",
  "total": "376",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "70",
  "previousWaterMetering": "156",
  "currentWaterMetering": "160",
  "metersConsumed": "4",
  "differenceOfUse": "4",
  "total": "138",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "71",
  "previousWaterMetering": "347",
  "currentWaterMetering": "350",
  "metersConsumed": "3",
  "differenceOfUse": "4",
  "total": "120",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "72",
  "previousWaterMetering": "294",
  "currentWaterMetering": "301",
  "metersConsumed": "7",
  "differenceOfUse": "4",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "73",
  "previousWaterMetering": "257",
  "currentWaterMetering": "261",
  "metersConsumed": "4",
  "differenceOfUse": "4",
  "total": "138",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "74",
  "previousWaterMetering": "157",
  "currentWaterMetering": "160",
  "metersConsumed": "3",
  "differenceOfUse": "4",
  "total": "120",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "75",
  "previousWaterMetering": "486",
  "currentWaterMetering": "491",
  "metersConsumed": "5",
  "differenceOfUse": "4",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "76",
  "previousWaterMetering": "42",
  "currentWaterMetering": "42",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "77",
  "previousWaterMetering": "830",
  "currentWaterMetering": "847",
  "metersConsumed": "17",
  "differenceOfUse": "4",
  "total": "457",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "78",
  "previousWaterMetering": "60",
  "currentWaterMetering": "62",
  "metersConsumed": "2",
  "differenceOfUse": "4",
  "total": "103",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "79",
  "previousWaterMetering": "404",
  "currentWaterMetering": "410",
  "metersConsumed": "6",
  "differenceOfUse": "4",
  "total": "176",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "80",
  "previousWaterMetering": "535",
  "currentWaterMetering": "544",
  "metersConsumed": "9",
  "differenceOfUse": "4",
  "total": "250",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "81",
  "previousWaterMetering": "190",
  "currentWaterMetering": "198",
  "metersConsumed": "8",
  "differenceOfUse": "4",
  "total": "218",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "82",
  "previousWaterMetering": "395",
  "currentWaterMetering": "402",
  "metersConsumed": "7",
  "differenceOfUse": "4",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "83",
  "previousWaterMetering": "244",
  "currentWaterMetering": "245",
  "metersConsumed": "1",
  "differenceOfUse": "4",
  "total": "87",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "84",
  "previousWaterMetering": "286",
  "currentWaterMetering": "290",
  "metersConsumed": "4",
  "differenceOfUse": "4",
  "total": "138",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "85",
  "previousWaterMetering": "318",
  "currentWaterMetering": "324",
  "metersConsumed": "6",
  "differenceOfUse": "4",
  "total": "176",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "86",
  "previousWaterMetering": "210",
  "currentWaterMetering": "217",
  "metersConsumed": "7",
  "differenceOfUse": "4",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "87",
  "previousWaterMetering": "355",
  "currentWaterMetering": "364",
  "metersConsumed": "9",
  "differenceOfUse": "4",
  "total": "250",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "88",
  "previousWaterMetering": "407",
  "currentWaterMetering": "411",
  "metersConsumed": "4",
  "differenceOfUse": "4",
  "total": "138",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "89",
  "previousWaterMetering": "732",
  "currentWaterMetering": "742",
  "metersConsumed": "10",
  "differenceOfUse": "4",
  "total": "274",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "90",
  "previousWaterMetering": "827",
  "currentWaterMetering": "850",
  "metersConsumed": "23",
  "differenceOfUse": "4",
  "total": "631",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "91",
  "previousWaterMetering": "352",
  "currentWaterMetering": "357",
  "metersConsumed": "5",
  "differenceOfUse": "4",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "92",
  "previousWaterMetering": "502",
  "currentWaterMetering": "507",
  "metersConsumed": "5",
  "differenceOfUse": "4",
  "total": "157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "93",
  "previousWaterMetering": "282",
  "currentWaterMetering": "293",
  "metersConsumed": "11",
  "differenceOfUse": "4",
  "total": "298",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "94",
  "previousWaterMetering": "511",
  "currentWaterMetering": "517",
  "metersConsumed": "6",
  "differenceOfUse": "4",
  "total": "176",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "95",
  "previousWaterMetering": "64",
  "currentWaterMetering": "64",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "96",
  "previousWaterMetering": "167",
  "currentWaterMetering": "169",
  "metersConsumed": "2",
  "differenceOfUse": "4",
  "total": "103",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "97",
  "previousWaterMetering": "222",
  "currentWaterMetering": "222",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "98",
  "previousWaterMetering": "100",
  "currentWaterMetering": "100",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "99",
  "previousWaterMetering": "237",
  "currentWaterMetering": "237",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "101",
  "previousWaterMetering": "239",
  "currentWaterMetering": "246",
  "metersConsumed": "7",
  "differenceOfUse": "4",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "102",
  "previousWaterMetering": "158",
  "currentWaterMetering": "160",
  "metersConsumed": "2",
  "differenceOfUse": "4",
  "total": "103",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
},
{
  "houseId": "103",
  "previousWaterMetering": "13",
  "currentWaterMetering": "13",
  "metersConsumed": "0",
  "differenceOfUse": "4",
  "total": "70",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Diciembre",
  "paymentMonth": "Febrero",
  "year": "2026"
}]
;

export const reportShimul = data;
