
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =
[{
  "houseId": "1",
  "previousWaterMetering": "420",
  "currentWaterMetering": "433",
  "metersConsumed": "13",
  "differenceOfUse": "67",
  "total": "403",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "2",
  "previousWaterMetering": "131",
  "currentWaterMetering": "137",
  "metersConsumed": "6",
  "differenceOfUse": "67",
  "total": "234",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "3",
  "previousWaterMetering": "471",
  "currentWaterMetering": "485",
  "metersConsumed": "14",
  "differenceOfUse": "67",
  "total": "429",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "4",
  "previousWaterMetering": "393",
  "currentWaterMetering": "404",
  "metersConsumed": "11",
  "differenceOfUse": "67",
  "total": "352",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "5",
  "previousWaterMetering": "206",
  "currentWaterMetering": "212",
  "metersConsumed": "6",
  "differenceOfUse": "67",
  "total": "234",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "6",
  "previousWaterMetering": "339",
  "currentWaterMetering": "346",
  "metersConsumed": "7",
  "differenceOfUse": "67",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "7",
  "previousWaterMetering": "476",
  "currentWaterMetering": "485",
  "metersConsumed": "9",
  "differenceOfUse": "67",
  "total": "306",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "8",
  "previousWaterMetering": "108",
  "currentWaterMetering": "206",
  "metersConsumed": "98",
  "differenceOfUse": "67",
  "total": "6528",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "9",
  "previousWaterMetering": "240",
  "currentWaterMetering": "245",
  "metersConsumed": "5",
  "differenceOfUse": "67",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "10",
  "previousWaterMetering": "446",
  "currentWaterMetering": "456",
  "metersConsumed": "10",
  "differenceOfUse": "67",
  "total": "329",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "11",
  "previousWaterMetering": "592",
  "currentWaterMetering": "606",
  "metersConsumed": "14",
  "differenceOfUse": "67",
  "total": "429",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "12",
  "previousWaterMetering": "328",
  "currentWaterMetering": "338",
  "metersConsumed": "10",
  "differenceOfUse": "67",
  "total": "329",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "13",
  "previousWaterMetering": "241",
  "currentWaterMetering": "247",
  "metersConsumed": "6",
  "differenceOfUse": "67",
  "total": "234",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "14",
  "previousWaterMetering": "460",
  "currentWaterMetering": "467",
  "metersConsumed": "7",
  "differenceOfUse": "67",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "15",
  "previousWaterMetering": "216",
  "currentWaterMetering": "216",
  "metersConsumed": "0",
  "differenceOfUse": "67",
  "total": "131",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "16",
  "previousWaterMetering": "211",
  "currentWaterMetering": "221",
  "metersConsumed": "10",
  "differenceOfUse": "67",
  "total": "329",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "17",
  "previousWaterMetering": "283",
  "currentWaterMetering": "291",
  "metersConsumed": "8",
  "differenceOfUse": "67",
  "total": "275",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "18",
  "previousWaterMetering": "322",
  "currentWaterMetering": "328",
  "metersConsumed": "6",
  "differenceOfUse": "67",
  "total": "234",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "19",
  "previousWaterMetering": "63",
  "currentWaterMetering": "68",
  "metersConsumed": "5",
  "differenceOfUse": "67",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "20",
  "previousWaterMetering": "360",
  "currentWaterMetering": "382",
  "metersConsumed": "22",
  "differenceOfUse": "67",
  "total": "647",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "21",
  "previousWaterMetering": "323",
  "currentWaterMetering": "334",
  "metersConsumed": "11",
  "differenceOfUse": "67",
  "total": "352",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "22",
  "previousWaterMetering": "315",
  "currentWaterMetering": "322",
  "metersConsumed": "7",
  "differenceOfUse": "67",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "23",
  "previousWaterMetering": "627",
  "currentWaterMetering": "642",
  "metersConsumed": "15",
  "differenceOfUse": "67",
  "total": "455",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "24",
  "previousWaterMetering": "273",
  "currentWaterMetering": "282",
  "metersConsumed": "9",
  "differenceOfUse": "67",
  "total": "306",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "25",
  "previousWaterMetering": "187",
  "currentWaterMetering": "195",
  "metersConsumed": "8",
  "differenceOfUse": "67",
  "total": "275",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "26",
  "previousWaterMetering": "34",
  "currentWaterMetering": "34",
  "metersConsumed": "0",
  "differenceOfUse": "67",
  "total": "131",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "27",
  "previousWaterMetering": "254",
  "currentWaterMetering": "260",
  "metersConsumed": "6",
  "differenceOfUse": "67",
  "total": "234",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "28",
  "previousWaterMetering": "42",
  "currentWaterMetering": "42",
  "metersConsumed": "0",
  "differenceOfUse": "67",
  "total": "131",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "29",
  "previousWaterMetering": "178",
  "currentWaterMetering": "184",
  "metersConsumed": "6",
  "differenceOfUse": "67",
  "total": "234",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "30",
  "previousWaterMetering": "476",
  "currentWaterMetering": "490",
  "metersConsumed": "14",
  "differenceOfUse": "67",
  "total": "429",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "31",
  "previousWaterMetering": "309",
  "currentWaterMetering": "320",
  "metersConsumed": "11",
  "differenceOfUse": "67",
  "total": "352",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "32",
  "previousWaterMetering": "482",
  "currentWaterMetering": "495",
  "metersConsumed": "13",
  "differenceOfUse": "67",
  "total": "403",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "33",
  "previousWaterMetering": "144",
  "currentWaterMetering": "145",
  "metersConsumed": "1",
  "differenceOfUse": "67",
  "total": "147",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "34",
  "previousWaterMetering": "434",
  "currentWaterMetering": "441",
  "metersConsumed": "7",
  "differenceOfUse": "67",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "35",
  "previousWaterMetering": "640",
  "currentWaterMetering": "661",
  "metersConsumed": "21",
  "differenceOfUse": "67",
  "total": "618",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "36",
  "previousWaterMetering": "402",
  "currentWaterMetering": "414",
  "metersConsumed": "12",
  "differenceOfUse": "67",
  "total": "376",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "37",
  "previousWaterMetering": "267",
  "currentWaterMetering": "272",
  "metersConsumed": "5",
  "differenceOfUse": "67",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "38",
  "previousWaterMetering": "437",
  "currentWaterMetering": "441",
  "metersConsumed": "4",
  "differenceOfUse": "67",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "39",
  "previousWaterMetering": "277",
  "currentWaterMetering": "283",
  "metersConsumed": "6",
  "differenceOfUse": "67",
  "total": "234",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "40",
  "previousWaterMetering": "94",
  "currentWaterMetering": "95",
  "metersConsumed": "1",
  "differenceOfUse": "67",
  "total": "147",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "41",
  "previousWaterMetering": "566",
  "currentWaterMetering": "579",
  "metersConsumed": "13",
  "differenceOfUse": "67",
  "total": "403",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "42",
  "previousWaterMetering": "506",
  "currentWaterMetering": "521",
  "metersConsumed": "15",
  "differenceOfUse": "67",
  "total": "455",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "43",
  "previousWaterMetering": "193",
  "currentWaterMetering": "196",
  "metersConsumed": "3",
  "differenceOfUse": "67",
  "total": "180",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "44",
  "previousWaterMetering": "98",
  "currentWaterMetering": "103",
  "metersConsumed": "5",
  "differenceOfUse": "67",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "45",
  "previousWaterMetering": "572",
  "currentWaterMetering": "585",
  "metersConsumed": "13",
  "differenceOfUse": "67",
  "total": "403",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "46",
  "previousWaterMetering": "203",
  "currentWaterMetering": "207",
  "metersConsumed": "4",
  "differenceOfUse": "67",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "47",
  "previousWaterMetering": "521",
  "currentWaterMetering": "528",
  "metersConsumed": "7",
  "differenceOfUse": "67",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "48",
  "previousWaterMetering": "191",
  "currentWaterMetering": "201",
  "metersConsumed": "10",
  "differenceOfUse": "67",
  "total": "329",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "49",
  "previousWaterMetering": "385",
  "currentWaterMetering": "397",
  "metersConsumed": "12",
  "differenceOfUse": "67",
  "total": "376",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "50",
  "previousWaterMetering": "200",
  "currentWaterMetering": "218",
  "metersConsumed": "18",
  "differenceOfUse": "67",
  "total": "534",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "51",
  "previousWaterMetering": "94",
  "currentWaterMetering": "98",
  "metersConsumed": "4",
  "differenceOfUse": "67",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "52",
  "previousWaterMetering": "306",
  "currentWaterMetering": "312",
  "metersConsumed": "6",
  "differenceOfUse": "67",
  "total": "234",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "53",
  "previousWaterMetering": "134",
  "currentWaterMetering": "138",
  "metersConsumed": "4",
  "differenceOfUse": "67",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "54",
  "previousWaterMetering": "460",
  "currentWaterMetering": "471",
  "metersConsumed": "11",
  "differenceOfUse": "67",
  "total": "352",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "67",
  "total": "131",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "56",
  "previousWaterMetering": "6",
  "currentWaterMetering": "7",
  "metersConsumed": "1",
  "differenceOfUse": "67",
  "total": "147",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "57",
  "previousWaterMetering": "607",
  "currentWaterMetering": "622",
  "metersConsumed": "15",
  "differenceOfUse": "67",
  "total": "455",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "58",
  "previousWaterMetering": "397",
  "currentWaterMetering": "404",
  "metersConsumed": "7",
  "differenceOfUse": "67",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "59",
  "previousWaterMetering": "259",
  "currentWaterMetering": "268",
  "metersConsumed": "9",
  "differenceOfUse": "67",
  "total": "306",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "60",
  "previousWaterMetering": "302",
  "currentWaterMetering": "312",
  "metersConsumed": "10",
  "differenceOfUse": "67",
  "total": "329",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "61",
  "previousWaterMetering": "86",
  "currentWaterMetering": "89",
  "metersConsumed": "3",
  "differenceOfUse": "67",
  "total": "180",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "62",
  "previousWaterMetering": "247",
  "currentWaterMetering": "252",
  "metersConsumed": "5",
  "differenceOfUse": "67",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "63",
  "previousWaterMetering": "652",
  "currentWaterMetering": "672",
  "metersConsumed": "20",
  "differenceOfUse": "67",
  "total": "588",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "64",
  "previousWaterMetering": "187",
  "currentWaterMetering": "189",
  "metersConsumed": "2",
  "differenceOfUse": "67",
  "total": "163",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "65",
  "previousWaterMetering": "712",
  "currentWaterMetering": "725",
  "metersConsumed": "13",
  "differenceOfUse": "67",
  "total": "403",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "66",
  "previousWaterMetering": "143",
  "currentWaterMetering": "145",
  "metersConsumed": "2",
  "differenceOfUse": "67",
  "total": "163",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "67",
  "previousWaterMetering": "245",
  "currentWaterMetering": "254",
  "metersConsumed": "9",
  "differenceOfUse": "67",
  "total": "306",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "67",
  "total": "131",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "69",
  "previousWaterMetering": "448",
  "currentWaterMetering": "459",
  "metersConsumed": "11",
  "differenceOfUse": "67",
  "total": "352",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "70",
  "previousWaterMetering": "104",
  "currentWaterMetering": "111",
  "metersConsumed": "7",
  "differenceOfUse": "67",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "71",
  "previousWaterMetering": "272",
  "currentWaterMetering": "281",
  "metersConsumed": "9",
  "differenceOfUse": "67",
  "total": "306",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "72",
  "previousWaterMetering": "241",
  "currentWaterMetering": "246",
  "metersConsumed": "5",
  "differenceOfUse": "67",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "73",
  "previousWaterMetering": "209",
  "currentWaterMetering": "214",
  "metersConsumed": "5",
  "differenceOfUse": "67",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "74",
  "previousWaterMetering": "127",
  "currentWaterMetering": "132",
  "metersConsumed": "5",
  "differenceOfUse": "67",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "75",
  "previousWaterMetering": "406",
  "currentWaterMetering": "418",
  "metersConsumed": "12",
  "differenceOfUse": "67",
  "total": "376",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "76",
  "previousWaterMetering": "40",
  "currentWaterMetering": "40",
  "metersConsumed": "0",
  "differenceOfUse": "67",
  "total": "131",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "77",
  "previousWaterMetering": "680",
  "currentWaterMetering": "697",
  "metersConsumed": "17",
  "differenceOfUse": "67",
  "total": "507",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "78",
  "previousWaterMetering": "41",
  "currentWaterMetering": "43",
  "metersConsumed": "2",
  "differenceOfUse": "67",
  "total": "163",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "79",
  "previousWaterMetering": "333",
  "currentWaterMetering": "341",
  "metersConsumed": "8",
  "differenceOfUse": "67",
  "total": "275",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "80",
  "previousWaterMetering": "412",
  "currentWaterMetering": "426",
  "metersConsumed": "14",
  "differenceOfUse": "67",
  "total": "429",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "81",
  "previousWaterMetering": "107",
  "currentWaterMetering": "108",
  "metersConsumed": "1",
  "differenceOfUse": "67",
  "total": "147",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "82",
  "previousWaterMetering": "335",
  "currentWaterMetering": "346",
  "metersConsumed": "11",
  "differenceOfUse": "67",
  "total": "352",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "83",
  "previousWaterMetering": "205",
  "currentWaterMetering": "210",
  "metersConsumed": "5",
  "differenceOfUse": "67",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "84",
  "previousWaterMetering": "247",
  "currentWaterMetering": "253",
  "metersConsumed": "6",
  "differenceOfUse": "67",
  "total": "234",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "85",
  "previousWaterMetering": "248",
  "currentWaterMetering": "257",
  "metersConsumed": "9",
  "differenceOfUse": "67",
  "total": "306",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "86",
  "previousWaterMetering": "93",
  "currentWaterMetering": "99",
  "metersConsumed": "6",
  "differenceOfUse": "67",
  "total": "234",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "87",
  "previousWaterMetering": "225",
  "currentWaterMetering": "237",
  "metersConsumed": "12",
  "differenceOfUse": "67",
  "total": "376",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "88",
  "previousWaterMetering": "350",
  "currentWaterMetering": "359",
  "metersConsumed": "9",
  "differenceOfUse": "67",
  "total": "306",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "89",
  "previousWaterMetering": "619",
  "currentWaterMetering": "636",
  "metersConsumed": "17",
  "differenceOfUse": "67",
  "total": "507",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "90",
  "previousWaterMetering": "604",
  "currentWaterMetering": "632",
  "metersConsumed": "28",
  "differenceOfUse": "67",
  "total": "967",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "91",
  "previousWaterMetering": "301",
  "currentWaterMetering": "308",
  "metersConsumed": "7",
  "differenceOfUse": "67",
  "total": "254",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "92",
  "previousWaterMetering": "430",
  "currentWaterMetering": "438",
  "metersConsumed": "8",
  "differenceOfUse": "67",
  "total": "275",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "93",
  "previousWaterMetering": "207",
  "currentWaterMetering": "212",
  "metersConsumed": "5",
  "differenceOfUse": "67",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "94",
  "previousWaterMetering": "423",
  "currentWaterMetering": "436",
  "metersConsumed": "13",
  "differenceOfUse": "67",
  "total": "403",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "95",
  "previousWaterMetering": "64",
  "currentWaterMetering": "64",
  "metersConsumed": "0",
  "differenceOfUse": "67",
  "total": "131",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "96",
  "previousWaterMetering": "135",
  "currentWaterMetering": "139",
  "metersConsumed": "4",
  "differenceOfUse": "67",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "97",
  "previousWaterMetering": "182",
  "currentWaterMetering": "184",
  "metersConsumed": "2",
  "differenceOfUse": "67",
  "total": "163",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "98",
  "previousWaterMetering": "90",
  "currentWaterMetering": "94",
  "metersConsumed": "4",
  "differenceOfUse": "67",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "99",
  "previousWaterMetering": "232",
  "currentWaterMetering": "233",
  "metersConsumed": "1",
  "differenceOfUse": "67",
  "total": "147",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "67",
  "total": "131",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "101",
  "previousWaterMetering": "197",
  "currentWaterMetering": "202",
  "metersConsumed": "5",
  "differenceOfUse": "67",
  "total": "215",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "102",
  "previousWaterMetering": "131",
  "currentWaterMetering": "134",
  "metersConsumed": "3",
  "differenceOfUse": "67",
  "total": "180",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
},
{
  "houseId": "103",
  "previousWaterMetering": "10",
  "currentWaterMetering": "11",
  "metersConsumed": "1",
  "differenceOfUse": "67",
  "total": "147",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2025"
}]
;

export const reportShimul = data;
