 
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =
[{
  "houseId": "1",
  "previousWaterMetering": "569",
  "currentWaterMetering": "580",
  "metersConsumed": "11",
  "differenceOfUse": "204",
  "total": "507",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "2",
  "previousWaterMetering": "198",
  "currentWaterMetering": "198",
  "metersConsumed": "0",
  "differenceOfUse": "204",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "3",
  "previousWaterMetering": "548",
  "currentWaterMetering": "548",
  "metersConsumed": "0",
  "differenceOfUse": "204",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "4",
  "previousWaterMetering": "509",
  "currentWaterMetering": "519",
  "metersConsumed": "10",
  "differenceOfUse": "204",
  "total": "482",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "5",
  "previousWaterMetering": "504",
  "currentWaterMetering": "515",
  "metersConsumed": "11",
  "differenceOfUse": "204",
  "total": "507",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "6",
  "previousWaterMetering": "474",
  "currentWaterMetering": "487",
  "metersConsumed": "13",
  "differenceOfUse": "204",
  "total": "561",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "7",
  "previousWaterMetering": "648",
  "currentWaterMetering": "664",
  "metersConsumed": "16",
  "differenceOfUse": "204",
  "total": "641",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "8",
  "previousWaterMetering": "214",
  "currentWaterMetering": "217",
  "metersConsumed": "3",
  "differenceOfUse": "204",
  "total": "324",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "9",
  "previousWaterMetering": "301",
  "currentWaterMetering": "306",
  "metersConsumed": "5",
  "differenceOfUse": "204",
  "total": "361",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "10",
  "previousWaterMetering": "553",
  "currentWaterMetering": "560",
  "metersConsumed": "7",
  "differenceOfUse": "204",
  "total": "403",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "11",
  "previousWaterMetering": "767",
  "currentWaterMetering": "779",
  "metersConsumed": "12",
  "differenceOfUse": "204",
  "total": "531",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "12",
  "previousWaterMetering": "456",
  "currentWaterMetering": "473",
  "metersConsumed": "17",
  "differenceOfUse": "204",
  "total": "671",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "13",
  "previousWaterMetering": "293",
  "currentWaterMetering": "301",
  "metersConsumed": "8",
  "differenceOfUse": "204",
  "total": "425",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "14",
  "previousWaterMetering": "616",
  "currentWaterMetering": "636",
  "metersConsumed": "20",
  "differenceOfUse": "204",
  "total": "756",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "15",
  "previousWaterMetering": "267",
  "currentWaterMetering": "273",
  "metersConsumed": "6",
  "differenceOfUse": "204",
  "total": "381",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "16",
  "previousWaterMetering": "299",
  "currentWaterMetering": "306",
  "metersConsumed": "7",
  "differenceOfUse": "204",
  "total": "403",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "17",
  "previousWaterMetering": "371",
  "currentWaterMetering": "379",
  "metersConsumed": "8",
  "differenceOfUse": "204",
  "total": "425",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "18",
  "previousWaterMetering": "381",
  "currentWaterMetering": "389",
  "metersConsumed": "8",
  "differenceOfUse": "204",
  "total": "425",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "19",
  "previousWaterMetering": "156",
  "currentWaterMetering": "167",
  "metersConsumed": "11",
  "differenceOfUse": "204",
  "total": "507",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "20.1",
  "previousWaterMetering": "326",
  "currentWaterMetering": "0",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "0",
  "condo": "0",
  "caKey": "0",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "20",
  "previousWaterMetering": "496",
  "currentWaterMetering": "506",
  "metersConsumed": "10",
  "differenceOfUse": "204",
  "total": "482",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "21",
  "previousWaterMetering": "447",
  "currentWaterMetering": "457",
  "metersConsumed": "10",
  "differenceOfUse": "204",
  "total": "482",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "22",
  "previousWaterMetering": "413",
  "currentWaterMetering": "421",
  "metersConsumed": "8",
  "differenceOfUse": "204",
  "total": "425",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "23",
  "previousWaterMetering": "823",
  "currentWaterMetering": "840",
  "metersConsumed": "17",
  "differenceOfUse": "204",
  "total": "671",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "24",
  "previousWaterMetering": "380",
  "currentWaterMetering": "389",
  "metersConsumed": "9",
  "differenceOfUse": "204",
  "total": "457",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "25",
  "previousWaterMetering": "265",
  "currentWaterMetering": "271",
  "metersConsumed": "6",
  "differenceOfUse": "204",
  "total": "381",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "26",
  "previousWaterMetering": "36",
  "currentWaterMetering": "37",
  "metersConsumed": "1",
  "differenceOfUse": "204",
  "total": "289",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "27",
  "previousWaterMetering": "379",
  "currentWaterMetering": "387",
  "metersConsumed": "8",
  "differenceOfUse": "204",
  "total": "425",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "28",
  "previousWaterMetering": "63",
  "currentWaterMetering": "67",
  "metersConsumed": "4",
  "differenceOfUse": "204",
  "total": "342",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "29",
  "previousWaterMetering": "223",
  "currentWaterMetering": "228",
  "metersConsumed": "5",
  "differenceOfUse": "204",
  "total": "361",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "30",
  "previousWaterMetering": "622",
  "currentWaterMetering": "635",
  "metersConsumed": "13",
  "differenceOfUse": "204",
  "total": "561",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "31",
  "previousWaterMetering": "441",
  "currentWaterMetering": "451",
  "metersConsumed": "10",
  "differenceOfUse": "204",
  "total": "482",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "32",
  "previousWaterMetering": "663",
  "currentWaterMetering": "679",
  "metersConsumed": "16",
  "differenceOfUse": "204",
  "total": "641",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "33",
  "previousWaterMetering": "167",
  "currentWaterMetering": "168",
  "metersConsumed": "1",
  "differenceOfUse": "204",
  "total": "289",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "34",
  "previousWaterMetering": "557",
  "currentWaterMetering": "573",
  "metersConsumed": "16",
  "differenceOfUse": "204",
  "total": "641",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "35",
  "previousWaterMetering": "889",
  "currentWaterMetering": "911",
  "metersConsumed": "22",
  "differenceOfUse": "204",
  "total": "819",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "36",
  "previousWaterMetering": "532",
  "currentWaterMetering": "540",
  "metersConsumed": "8",
  "differenceOfUse": "204",
  "total": "425",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "37",
  "previousWaterMetering": "371",
  "currentWaterMetering": "381",
  "metersConsumed": "10",
  "differenceOfUse": "204",
  "total": "482",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "38",
  "previousWaterMetering": "523",
  "currentWaterMetering": "529",
  "metersConsumed": "6",
  "differenceOfUse": "204",
  "total": "381",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "39",
  "previousWaterMetering": "351",
  "currentWaterMetering": "373",
  "metersConsumed": "22",
  "differenceOfUse": "204",
  "total": "819",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "40",
  "previousWaterMetering": "110",
  "currentWaterMetering": "111",
  "metersConsumed": "1",
  "differenceOfUse": "204",
  "total": "289",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "41",
  "previousWaterMetering": "691",
  "currentWaterMetering": "702",
  "metersConsumed": "11",
  "differenceOfUse": "204",
  "total": "507",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "42",
  "previousWaterMetering": "694",
  "currentWaterMetering": "709",
  "metersConsumed": "15",
  "differenceOfUse": "204",
  "total": "615",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "43",
  "previousWaterMetering": "232",
  "currentWaterMetering": "234",
  "metersConsumed": "2",
  "differenceOfUse": "204",
  "total": "306",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "44",
  "previousWaterMetering": "154",
  "currentWaterMetering": "159",
  "metersConsumed": "5",
  "differenceOfUse": "204",
  "total": "361",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "45",
  "previousWaterMetering": "760",
  "currentWaterMetering": "769",
  "metersConsumed": "9",
  "differenceOfUse": "204",
  "total": "457",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "46",
  "previousWaterMetering": "267",
  "currentWaterMetering": "276",
  "metersConsumed": "9",
  "differenceOfUse": "204",
  "total": "457",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "47",
  "previousWaterMetering": "613",
  "currentWaterMetering": "619",
  "metersConsumed": "6",
  "differenceOfUse": "204",
  "total": "381",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "48",
  "previousWaterMetering": "298",
  "currentWaterMetering": "306",
  "metersConsumed": "8",
  "differenceOfUse": "204",
  "total": "425",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "49",
  "previousWaterMetering": "576",
  "currentWaterMetering": "594",
  "metersConsumed": "18",
  "differenceOfUse": "204",
  "total": "699",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "50",
  "previousWaterMetering": "566",
  "currentWaterMetering": "568",
  "metersConsumed": "2",
  "differenceOfUse": "204",
  "total": "306",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "51",
  "previousWaterMetering": "124",
  "currentWaterMetering": "126",
  "metersConsumed": "2",
  "differenceOfUse": "204",
  "total": "306",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "52",
  "previousWaterMetering": "375",
  "currentWaterMetering": "383",
  "metersConsumed": "8",
  "differenceOfUse": "204",
  "total": "425",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "53",
  "previousWaterMetering": "188",
  "currentWaterMetering": "192",
  "metersConsumed": "4",
  "differenceOfUse": "204",
  "total": "342",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "54",
  "previousWaterMetering": "606",
  "currentWaterMetering": "619",
  "metersConsumed": "13",
  "differenceOfUse": "204",
  "total": "561",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "204",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "56",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "204",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "57",
  "previousWaterMetering": "749",
  "currentWaterMetering": "759",
  "metersConsumed": "10",
  "differenceOfUse": "204",
  "total": "482",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "58",
  "previousWaterMetering": "475",
  "currentWaterMetering": "483",
  "metersConsumed": "8",
  "differenceOfUse": "204",
  "total": "425",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "59",
  "previousWaterMetering": "382",
  "currentWaterMetering": "394",
  "metersConsumed": "12",
  "differenceOfUse": "204",
  "total": "531",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "60",
  "previousWaterMetering": "424",
  "currentWaterMetering": "435",
  "metersConsumed": "11",
  "differenceOfUse": "204",
  "total": "507",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "61",
  "previousWaterMetering": "108",
  "currentWaterMetering": "111",
  "metersConsumed": "3",
  "differenceOfUse": "204",
  "total": "324",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "62",
  "previousWaterMetering": "385",
  "currentWaterMetering": "399",
  "metersConsumed": "14",
  "differenceOfUse": "204",
  "total": "587",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "63",
  "previousWaterMetering": "838",
  "currentWaterMetering": "853",
  "metersConsumed": "15",
  "differenceOfUse": "204",
  "total": "615",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "64",
  "previousWaterMetering": "267",
  "currentWaterMetering": "275",
  "metersConsumed": "8",
  "differenceOfUse": "204",
  "total": "425",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "65",
  "previousWaterMetering": "878",
  "currentWaterMetering": "893",
  "metersConsumed": "15",
  "differenceOfUse": "204",
  "total": "615",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "66",
  "previousWaterMetering": "181",
  "currentWaterMetering": "183",
  "metersConsumed": "2",
  "differenceOfUse": "204",
  "total": "306",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "67",
  "previousWaterMetering": "342",
  "currentWaterMetering": "349",
  "metersConsumed": "7",
  "differenceOfUse": "204",
  "total": "403",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "204",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "69",
  "previousWaterMetering": "614",
  "currentWaterMetering": "630",
  "metersConsumed": "16",
  "differenceOfUse": "204",
  "total": "641",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "70",
  "previousWaterMetering": "178",
  "currentWaterMetering": "188",
  "metersConsumed": "10",
  "differenceOfUse": "204",
  "total": "482",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "71",
  "previousWaterMetering": "376",
  "currentWaterMetering": "389",
  "metersConsumed": "13",
  "differenceOfUse": "204",
  "total": "561",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "72",
  "previousWaterMetering": "325",
  "currentWaterMetering": "331",
  "metersConsumed": "6",
  "differenceOfUse": "204",
  "total": "381",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "73",
  "previousWaterMetering": "278",
  "currentWaterMetering": "284",
  "metersConsumed": "6",
  "differenceOfUse": "204",
  "total": "381",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "74",
  "previousWaterMetering": "169",
  "currentWaterMetering": "172",
  "metersConsumed": "3",
  "differenceOfUse": "204",
  "total": "324",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "75",
  "previousWaterMetering": "516",
  "currentWaterMetering": "522",
  "metersConsumed": "6",
  "differenceOfUse": "204",
  "total": "381",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "76",
  "previousWaterMetering": "45",
  "currentWaterMetering": "50",
  "metersConsumed": "5",
  "differenceOfUse": "204",
  "total": "361",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "77",
  "previousWaterMetering": "861",
  "currentWaterMetering": "866",
  "metersConsumed": "5",
  "differenceOfUse": "204",
  "total": "361",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "78",
  "previousWaterMetering": "66",
  "currentWaterMetering": "68",
  "metersConsumed": "2",
  "differenceOfUse": "204",
  "total": "306",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "79",
  "previousWaterMetering": "428",
  "currentWaterMetering": "434",
  "metersConsumed": "6",
  "differenceOfUse": "204",
  "total": "381",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "80",
  "previousWaterMetering": "596",
  "currentWaterMetering": "611",
  "metersConsumed": "15",
  "differenceOfUse": "204",
  "total": "615",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "81",
  "previousWaterMetering": "229",
  "currentWaterMetering": "238",
  "metersConsumed": "9",
  "differenceOfUse": "204",
  "total": "457",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "82",
  "previousWaterMetering": "424",
  "currentWaterMetering": "431",
  "metersConsumed": "7",
  "differenceOfUse": "204",
  "total": "403",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "83",
  "previousWaterMetering": "247",
  "currentWaterMetering": "247",
  "metersConsumed": "0",
  "differenceOfUse": "204",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "84",
  "previousWaterMetering": "308",
  "currentWaterMetering": "315",
  "metersConsumed": "7",
  "differenceOfUse": "204",
  "total": "403",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "85",
  "previousWaterMetering": "347",
  "currentWaterMetering": "355",
  "metersConsumed": "8",
  "differenceOfUse": "204",
  "total": "425",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "86",
  "previousWaterMetering": "249",
  "currentWaterMetering": "259",
  "metersConsumed": "10",
  "differenceOfUse": "204",
  "total": "482",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "87",
  "previousWaterMetering": "394",
  "currentWaterMetering": "397",
  "metersConsumed": "3",
  "differenceOfUse": "204",
  "total": "324",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "88",
  "previousWaterMetering": "430",
  "currentWaterMetering": "436",
  "metersConsumed": "6",
  "differenceOfUse": "204",
  "total": "381",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "89",
  "previousWaterMetering": "786",
  "currentWaterMetering": "799",
  "metersConsumed": "13",
  "differenceOfUse": "204",
  "total": "561",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "90",
  "previousWaterMetering": "934",
  "currentWaterMetering": "962",
  "metersConsumed": "28",
  "differenceOfUse": "204",
  "total": "1157",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "91",
  "previousWaterMetering": "383",
  "currentWaterMetering": "391",
  "metersConsumed": "8",
  "differenceOfUse": "204",
  "total": "425",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "92",
  "previousWaterMetering": "528",
  "currentWaterMetering": "533",
  "metersConsumed": "5",
  "differenceOfUse": "204",
  "total": "361",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "93",
  "previousWaterMetering": "333",
  "currentWaterMetering": "345",
  "metersConsumed": "12",
  "differenceOfUse": "204",
  "total": "531",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "94",
  "previousWaterMetering": "547",
  "currentWaterMetering": "557",
  "metersConsumed": "10",
  "differenceOfUse": "204",
  "total": "482",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "95",
  "previousWaterMetering": "66",
  "currentWaterMetering": "66",
  "metersConsumed": "0",
  "differenceOfUse": "204",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "96",
  "previousWaterMetering": "179",
  "currentWaterMetering": "183",
  "metersConsumed": "4",
  "differenceOfUse": "204",
  "total": "342",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "97",
  "previousWaterMetering": "237",
  "currentWaterMetering": "240",
  "metersConsumed": "3",
  "differenceOfUse": "204",
  "total": "324",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "98",
  "previousWaterMetering": "109",
  "currentWaterMetering": "110",
  "metersConsumed": "1",
  "differenceOfUse": "204",
  "total": "289",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "99",
  "previousWaterMetering": "239",
  "currentWaterMetering": "240",
  "metersConsumed": "1",
  "differenceOfUse": "204",
  "total": "289",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "204",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "101",
  "previousWaterMetering": "287",
  "currentWaterMetering": "345",
  "metersConsumed": "58",
  "differenceOfUse": "204",
  "total": "3707",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "102",
  "previousWaterMetering": "170",
  "currentWaterMetering": "175",
  "metersConsumed": "5",
  "differenceOfUse": "204",
  "total": "361",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
},
{
  "houseId": "103",
  "previousWaterMetering": "13",
  "currentWaterMetering": "13",
  "metersConsumed": "0",
  "differenceOfUse": "204",
  "total": "272",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Abril",
  "paymentMonth": "Junio",
  "year": "2026"
}]
;

export const reportShimul = data;
