
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =
[{
  "houseId": "1",
  "previousWaterMetering": "460",
  "currentWaterMetering": "474",
  "metersConsumed": "14",
  "differenceOfUse": "16",
  "total": "383",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "2",
  "previousWaterMetering": "154",
  "currentWaterMetering": "164",
  "metersConsumed": "10",
  "differenceOfUse": "16",
  "total": "282",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "3",
  "previousWaterMetering": "510",
  "currentWaterMetering": "524",
  "metersConsumed": "14",
  "differenceOfUse": "16",
  "total": "383",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "4",
  "previousWaterMetering": "419",
  "currentWaterMetering": "430",
  "metersConsumed": "11",
  "differenceOfUse": "16",
  "total": "305",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "5",
  "previousWaterMetering": "226",
  "currentWaterMetering": "238",
  "metersConsumed": "12",
  "differenceOfUse": "16",
  "total": "329",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "6",
  "previousWaterMetering": "360",
  "currentWaterMetering": "363",
  "metersConsumed": "3",
  "differenceOfUse": "16",
  "total": "130",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "7",
  "previousWaterMetering": "512",
  "currentWaterMetering": "525",
  "metersConsumed": "13",
  "differenceOfUse": "16",
  "total": "357",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "8",
  "previousWaterMetering": "207",
  "currentWaterMetering": "208",
  "metersConsumed": "1",
  "differenceOfUse": "16",
  "total": "97",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "9",
  "previousWaterMetering": "254",
  "currentWaterMetering": "258",
  "metersConsumed": "4",
  "differenceOfUse": "16",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "10",
  "previousWaterMetering": "476",
  "currentWaterMetering": "487",
  "metersConsumed": "11",
  "differenceOfUse": "16",
  "total": "305",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "11",
  "previousWaterMetering": "640",
  "currentWaterMetering": "653",
  "metersConsumed": "13",
  "differenceOfUse": "16",
  "total": "357",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "12",
  "previousWaterMetering": "360",
  "currentWaterMetering": "370",
  "metersConsumed": "10",
  "differenceOfUse": "16",
  "total": "282",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "13",
  "previousWaterMetering": "257",
  "currentWaterMetering": "267",
  "metersConsumed": "10",
  "differenceOfUse": "16",
  "total": "282",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "14",
  "previousWaterMetering": "490",
  "currentWaterMetering": "501",
  "metersConsumed": "11",
  "differenceOfUse": "16",
  "total": "305",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "15",
  "previousWaterMetering": "224",
  "currentWaterMetering": "232",
  "metersConsumed": "8",
  "differenceOfUse": "16",
  "total": "227",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "16",
  "previousWaterMetering": "238",
  "currentWaterMetering": "245",
  "metersConsumed": "7",
  "differenceOfUse": "16",
  "total": "206",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "17",
  "previousWaterMetering": "305",
  "currentWaterMetering": "311",
  "metersConsumed": "6",
  "differenceOfUse": "16",
  "total": "185",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "18",
  "previousWaterMetering": "341",
  "currentWaterMetering": "349",
  "metersConsumed": "8",
  "differenceOfUse": "16",
  "total": "227",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "19",
  "previousWaterMetering": "82",
  "currentWaterMetering": "89",
  "metersConsumed": "7",
  "differenceOfUse": "16",
  "total": "206",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "20",
  "previousWaterMetering": "425",
  "currentWaterMetering": "426",
  "metersConsumed": "1",
  "differenceOfUse": "16",
  "total": "97",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "21",
  "previousWaterMetering": "362",
  "currentWaterMetering": "371",
  "metersConsumed": "9",
  "differenceOfUse": "16",
  "total": "258",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "22",
  "previousWaterMetering": "336",
  "currentWaterMetering": "344",
  "metersConsumed": "8",
  "differenceOfUse": "16",
  "total": "227",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "23",
  "previousWaterMetering": "677",
  "currentWaterMetering": "694",
  "metersConsumed": "17",
  "differenceOfUse": "16",
  "total": "462",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "24",
  "previousWaterMetering": "300",
  "currentWaterMetering": "308",
  "metersConsumed": "8",
  "differenceOfUse": "16",
  "total": "227",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "25",
  "previousWaterMetering": "209",
  "currentWaterMetering": "216",
  "metersConsumed": "7",
  "differenceOfUse": "16",
  "total": "206",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "26",
  "previousWaterMetering": "34",
  "currentWaterMetering": "34",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "81",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "27",
  "previousWaterMetering": "272",
  "currentWaterMetering": "305",
  "metersConsumed": "33",
  "differenceOfUse": "16",
  "total": "1271",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "28",
  "previousWaterMetering": "42",
  "currentWaterMetering": "43",
  "metersConsumed": "1",
  "differenceOfUse": "16",
  "total": "97",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "29",
  "previousWaterMetering": "193",
  "currentWaterMetering": "194",
  "metersConsumed": "1",
  "differenceOfUse": "16",
  "total": "97",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "30",
  "previousWaterMetering": "511",
  "currentWaterMetering": "516",
  "metersConsumed": "5",
  "differenceOfUse": "16",
  "total": "166",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "31",
  "previousWaterMetering": "343",
  "currentWaterMetering": "354",
  "metersConsumed": "11",
  "differenceOfUse": "16",
  "total": "305",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "32",
  "previousWaterMetering": "523",
  "currentWaterMetering": "543",
  "metersConsumed": "20",
  "differenceOfUse": "16",
  "total": "544",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "33",
  "previousWaterMetering": "147",
  "currentWaterMetering": "153",
  "metersConsumed": "6",
  "differenceOfUse": "16",
  "total": "185",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "34",
  "previousWaterMetering": "467",
  "currentWaterMetering": "480",
  "metersConsumed": "13",
  "differenceOfUse": "16",
  "total": "357",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "35",
  "previousWaterMetering": "699",
  "currentWaterMetering": "722",
  "metersConsumed": "23",
  "differenceOfUse": "16",
  "total": "634",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "36",
  "previousWaterMetering": "436",
  "currentWaterMetering": "453",
  "metersConsumed": "17",
  "differenceOfUse": "16",
  "total": "462",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "37",
  "previousWaterMetering": "289",
  "currentWaterMetering": "299",
  "metersConsumed": "10",
  "differenceOfUse": "16",
  "total": "282",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "38",
  "previousWaterMetering": "455",
  "currentWaterMetering": "460",
  "metersConsumed": "5",
  "differenceOfUse": "16",
  "total": "166",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "39",
  "previousWaterMetering": "293",
  "currentWaterMetering": "300",
  "metersConsumed": "7",
  "differenceOfUse": "16",
  "total": "206",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "40",
  "previousWaterMetering": "97",
  "currentWaterMetering": "99",
  "metersConsumed": "2",
  "differenceOfUse": "16",
  "total": "113",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "41",
  "previousWaterMetering": "598",
  "currentWaterMetering": "611",
  "metersConsumed": "13",
  "differenceOfUse": "16",
  "total": "357",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "42",
  "previousWaterMetering": "556",
  "currentWaterMetering": "572",
  "metersConsumed": "16",
  "differenceOfUse": "16",
  "total": "434",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "43",
  "previousWaterMetering": "199",
  "currentWaterMetering": "201",
  "metersConsumed": "2",
  "differenceOfUse": "16",
  "total": "113",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "44",
  "previousWaterMetering": "112",
  "currentWaterMetering": "117",
  "metersConsumed": "5",
  "differenceOfUse": "16",
  "total": "166",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "45",
  "previousWaterMetering": "606",
  "currentWaterMetering": "619",
  "metersConsumed": "13",
  "differenceOfUse": "16",
  "total": "357",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "46",
  "previousWaterMetering": "218",
  "currentWaterMetering": "223",
  "metersConsumed": "5",
  "differenceOfUse": "16",
  "total": "166",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "47",
  "previousWaterMetering": "546",
  "currentWaterMetering": "554",
  "metersConsumed": "8",
  "differenceOfUse": "16",
  "total": "227",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "48",
  "previousWaterMetering": "218",
  "currentWaterMetering": "229",
  "metersConsumed": "11",
  "differenceOfUse": "16",
  "total": "305",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "49",
  "previousWaterMetering": "418",
  "currentWaterMetering": "431",
  "metersConsumed": "13",
  "differenceOfUse": "16",
  "total": "357",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "50",
  "previousWaterMetering": "550",
  "currentWaterMetering": "557",
  "metersConsumed": "7",
  "differenceOfUse": "16",
  "total": "206",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "51",
  "previousWaterMetering": "103",
  "currentWaterMetering": "106",
  "metersConsumed": "3",
  "differenceOfUse": "16",
  "total": "130",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "52",
  "previousWaterMetering": "323",
  "currentWaterMetering": "330",
  "metersConsumed": "7",
  "differenceOfUse": "16",
  "total": "206",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "53",
  "previousWaterMetering": "144",
  "currentWaterMetering": "149",
  "metersConsumed": "5",
  "differenceOfUse": "16",
  "total": "166",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "54",
  "previousWaterMetering": "494",
  "currentWaterMetering": "507",
  "metersConsumed": "13",
  "differenceOfUse": "16",
  "total": "357",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "81",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "56",
  "previousWaterMetering": "7",
  "currentWaterMetering": "7",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "81",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "57",
  "previousWaterMetering": "652",
  "currentWaterMetering": "666",
  "metersConsumed": "14",
  "differenceOfUse": "16",
  "total": "383",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "58",
  "previousWaterMetering": "414",
  "currentWaterMetering": "421",
  "metersConsumed": "7",
  "differenceOfUse": "16",
  "total": "206",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "59",
  "previousWaterMetering": "290",
  "currentWaterMetering": "299",
  "metersConsumed": "9",
  "differenceOfUse": "16",
  "total": "258",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "60",
  "previousWaterMetering": "331",
  "currentWaterMetering": "341",
  "metersConsumed": "10",
  "differenceOfUse": "16",
  "total": "282",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "61",
  "previousWaterMetering": "92",
  "currentWaterMetering": "93",
  "metersConsumed": "1",
  "differenceOfUse": "16",
  "total": "97",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "62",
  "previousWaterMetering": "296",
  "currentWaterMetering": "327",
  "metersConsumed": "31",
  "differenceOfUse": "16",
  "total": "1135",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "63",
  "previousWaterMetering": "705",
  "currentWaterMetering": "722",
  "metersConsumed": "17",
  "differenceOfUse": "16",
  "total": "462",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "64",
  "previousWaterMetering": "195",
  "currentWaterMetering": "205",
  "metersConsumed": "10",
  "differenceOfUse": "16",
  "total": "282",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "65",
  "previousWaterMetering": "749",
  "currentWaterMetering": "764",
  "metersConsumed": "15",
  "differenceOfUse": "16",
  "total": "409",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "66",
  "previousWaterMetering": "150",
  "currentWaterMetering": "153",
  "metersConsumed": "3",
  "differenceOfUse": "16",
  "total": "130",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "67",
  "previousWaterMetering": "271",
  "currentWaterMetering": "280",
  "metersConsumed": "9",
  "differenceOfUse": "16",
  "total": "258",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "81",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "69",
  "previousWaterMetering": "485",
  "currentWaterMetering": "501",
  "metersConsumed": "16",
  "differenceOfUse": "16",
  "total": "434",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "70",
  "previousWaterMetering": "123",
  "currentWaterMetering": "130",
  "metersConsumed": "7",
  "differenceOfUse": "16",
  "total": "206",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "71",
  "previousWaterMetering": "298",
  "currentWaterMetering": "308",
  "metersConsumed": "10",
  "differenceOfUse": "16",
  "total": "282",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "72",
  "previousWaterMetering": "260",
  "currentWaterMetering": "265",
  "metersConsumed": "5",
  "differenceOfUse": "16",
  "total": "166",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "73",
  "previousWaterMetering": "226",
  "currentWaterMetering": "232",
  "metersConsumed": "6",
  "differenceOfUse": "16",
  "total": "185",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "74",
  "previousWaterMetering": "139",
  "currentWaterMetering": "143",
  "metersConsumed": "4",
  "differenceOfUse": "16",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "75",
  "previousWaterMetering": "439",
  "currentWaterMetering": "449",
  "metersConsumed": "10",
  "differenceOfUse": "16",
  "total": "282",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "76",
  "previousWaterMetering": "41",
  "currentWaterMetering": "41",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "81",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "77",
  "previousWaterMetering": "734",
  "currentWaterMetering": "752",
  "metersConsumed": "18",
  "differenceOfUse": "16",
  "total": "489",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "78",
  "previousWaterMetering": "45",
  "currentWaterMetering": "46",
  "metersConsumed": "1",
  "differenceOfUse": "16",
  "total": "97",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "79",
  "previousWaterMetering": "361",
  "currentWaterMetering": "374",
  "metersConsumed": "13",
  "differenceOfUse": "16",
  "total": "357",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "80",
  "previousWaterMetering": "464",
  "currentWaterMetering": "472",
  "metersConsumed": "8",
  "differenceOfUse": "16",
  "total": "227",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "81",
  "previousWaterMetering": "129",
  "currentWaterMetering": "137",
  "metersConsumed": "8",
  "differenceOfUse": "16",
  "total": "227",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "82",
  "previousWaterMetering": "362",
  "currentWaterMetering": "362",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "81",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "83",
  "previousWaterMetering": "220",
  "currentWaterMetering": "224",
  "metersConsumed": "4",
  "differenceOfUse": "16",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "84",
  "previousWaterMetering": "265",
  "currentWaterMetering": "268",
  "metersConsumed": "3",
  "differenceOfUse": "16",
  "total": "130",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "85",
  "previousWaterMetering": "275",
  "currentWaterMetering": "284",
  "metersConsumed": "9",
  "differenceOfUse": "16",
  "total": "258",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "86",
  "previousWaterMetering": "122",
  "currentWaterMetering": "143",
  "metersConsumed": "21",
  "differenceOfUse": "16",
  "total": "575",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "87",
  "previousWaterMetering": "271",
  "currentWaterMetering": "285",
  "metersConsumed": "14",
  "differenceOfUse": "16",
  "total": "383",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "88",
  "previousWaterMetering": "373",
  "currentWaterMetering": "380",
  "metersConsumed": "7",
  "differenceOfUse": "16",
  "total": "206",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "89",
  "previousWaterMetering": "668",
  "currentWaterMetering": "681",
  "metersConsumed": "13",
  "differenceOfUse": "16",
  "total": "357",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "90",
  "previousWaterMetering": "685",
  "currentWaterMetering": "713",
  "metersConsumed": "28",
  "differenceOfUse": "16",
  "total": "928",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "91",
  "previousWaterMetering": "323",
  "currentWaterMetering": "328",
  "metersConsumed": "5",
  "differenceOfUse": "16",
  "total": "166",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "92",
  "previousWaterMetering": "461",
  "currentWaterMetering": "467",
  "metersConsumed": "6",
  "differenceOfUse": "16",
  "total": "185",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "93",
  "previousWaterMetering": "231",
  "currentWaterMetering": "241",
  "metersConsumed": "10",
  "differenceOfUse": "16",
  "total": "282",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "94",
  "previousWaterMetering": "459",
  "currentWaterMetering": "472",
  "metersConsumed": "13",
  "differenceOfUse": "16",
  "total": "357",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "95",
  "previousWaterMetering": "64",
  "currentWaterMetering": "64",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "81",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "96",
  "previousWaterMetering": "147",
  "currentWaterMetering": "151",
  "metersConsumed": "4",
  "differenceOfUse": "16",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "97",
  "previousWaterMetering": "197",
  "currentWaterMetering": "205",
  "metersConsumed": "8",
  "differenceOfUse": "16",
  "total": "227",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "98",
  "previousWaterMetering": "100",
  "currentWaterMetering": "100",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "81",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "99",
  "previousWaterMetering": "233",
  "currentWaterMetering": "234",
  "metersConsumed": "1",
  "differenceOfUse": "16",
  "total": "97",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "81",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "101",
  "previousWaterMetering": "212",
  "currentWaterMetering": "217",
  "metersConsumed": "5",
  "differenceOfUse": "16",
  "total": "166",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "102",
  "previousWaterMetering": "141",
  "currentWaterMetering": "145",
  "metersConsumed": "4",
  "differenceOfUse": "16",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
},
{
  "houseId": "103",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "16",
  "total": "81",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Julio",
  "paymentMonth": "Septiembre",
  "year": "2025"
}]
;

export const reportShimul = data;
