 
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =
[{
  "houseId": "1",
  "previousWaterMetering": "580",
  "currentWaterMetering": "590",
  "metersConsumed": "10",
  "differenceOfUse": "-130",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "2",
  "previousWaterMetering": "198",
  "currentWaterMetering": "198",
  "metersConsumed": "0",
  "differenceOfUse": "-68",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "3",
  "previousWaterMetering": "548",
  "currentWaterMetering": "548",
  "metersConsumed": "0",
  "differenceOfUse": "-68",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "4",
  "previousWaterMetering": "519",
  "currentWaterMetering": "533",
  "metersConsumed": "14",
  "differenceOfUse": "-130",
  "total": "253",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "5",
  "previousWaterMetering": "515",
  "currentWaterMetering": "527",
  "metersConsumed": "12",
  "differenceOfUse": "-130",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "6",
  "previousWaterMetering": "487",
  "currentWaterMetering": "503",
  "metersConsumed": "16",
  "differenceOfUse": "-130",
  "total": "307",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "7",
  "previousWaterMetering": "664",
  "currentWaterMetering": "679",
  "metersConsumed": "15",
  "differenceOfUse": "-130",
  "total": "281",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "8",
  "previousWaterMetering": "217",
  "currentWaterMetering": "220",
  "metersConsumed": "3",
  "differenceOfUse": "-120",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "9",
  "previousWaterMetering": "306",
  "currentWaterMetering": "311",
  "metersConsumed": "5",
  "differenceOfUse": "-130",
  "total": "27",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "10",
  "previousWaterMetering": "560",
  "currentWaterMetering": "568",
  "metersConsumed": "8",
  "differenceOfUse": "-130",
  "total": "91",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "11",
  "previousWaterMetering": "779",
  "currentWaterMetering": "797",
  "metersConsumed": "18",
  "differenceOfUse": "-130",
  "total": "365",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "12",
  "previousWaterMetering": "473",
  "currentWaterMetering": "496",
  "metersConsumed": "23",
  "differenceOfUse": "-130",
  "total": "516",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "13",
  "previousWaterMetering": "301",
  "currentWaterMetering": "312",
  "metersConsumed": "11",
  "differenceOfUse": "-130",
  "total": "173",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "14",
  "previousWaterMetering": "636",
  "currentWaterMetering": "659",
  "metersConsumed": "23",
  "differenceOfUse": "-130",
  "total": "516",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "15",
  "previousWaterMetering": "273",
  "currentWaterMetering": "278",
  "metersConsumed": "5",
  "differenceOfUse": "-130",
  "total": "27",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "16",
  "previousWaterMetering": "306",
  "currentWaterMetering": "314",
  "metersConsumed": "8",
  "differenceOfUse": "-130",
  "total": "91",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "17",
  "previousWaterMetering": "379",
  "currentWaterMetering": "385",
  "metersConsumed": "6",
  "differenceOfUse": "-130",
  "total": "47",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "18",
  "previousWaterMetering": "389",
  "currentWaterMetering": "398",
  "metersConsumed": "9",
  "differenceOfUse": "-130",
  "total": "123",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "19",
  "previousWaterMetering": "167",
  "currentWaterMetering": "175",
  "metersConsumed": "8",
  "differenceOfUse": "-130",
  "total": "91",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "20.1",
  "previousWaterMetering": "0",
  "currentWaterMetering": "0",
  "metersConsumed": "0",
  "differenceOfUse": "0",
  "total": "0",
  "condo": "0",
  "caKey": "0",
  "periodOfUse": "0",
  "paymentMonth": "0",
  "year": "0"
},
{
  "houseId": "20",
  "previousWaterMetering": "506",
  "currentWaterMetering": "516",
  "metersConsumed": "10",
  "differenceOfUse": "-130",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "21",
  "previousWaterMetering": "457",
  "currentWaterMetering": "468",
  "metersConsumed": "11",
  "differenceOfUse": "-130",
  "total": "173",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "22",
  "previousWaterMetering": "421",
  "currentWaterMetering": "430",
  "metersConsumed": "9",
  "differenceOfUse": "-130",
  "total": "123",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "23",
  "previousWaterMetering": "840",
  "currentWaterMetering": "855",
  "metersConsumed": "15",
  "differenceOfUse": "-130",
  "total": "281",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "24",
  "previousWaterMetering": "389",
  "currentWaterMetering": "401",
  "metersConsumed": "12",
  "differenceOfUse": "-130",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "25",
  "previousWaterMetering": "271",
  "currentWaterMetering": "278",
  "metersConsumed": "7",
  "differenceOfUse": "-130",
  "total": "69",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "26",
  "previousWaterMetering": "37",
  "currentWaterMetering": "37",
  "metersConsumed": "0",
  "differenceOfUse": "-68",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "27",
  "previousWaterMetering": "387",
  "currentWaterMetering": "391",
  "metersConsumed": "4",
  "differenceOfUse": "-130",
  "total": "8",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "28",
  "previousWaterMetering": "67",
  "currentWaterMetering": "72",
  "metersConsumed": "5",
  "differenceOfUse": "-130",
  "total": "27",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "29",
  "previousWaterMetering": "228",
  "currentWaterMetering": "237",
  "metersConsumed": "9",
  "differenceOfUse": "-130",
  "total": "123",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "30",
  "previousWaterMetering": "635",
  "currentWaterMetering": "648",
  "metersConsumed": "13",
  "differenceOfUse": "-130",
  "total": "227",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "31",
  "previousWaterMetering": "451",
  "currentWaterMetering": "462",
  "metersConsumed": "11",
  "differenceOfUse": "-130",
  "total": "173",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "32",
  "previousWaterMetering": "679",
  "currentWaterMetering": "683",
  "metersConsumed": "4",
  "differenceOfUse": "-130",
  "total": "8",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "33",
  "previousWaterMetering": "168",
  "currentWaterMetering": "172",
  "metersConsumed": "4",
  "differenceOfUse": "-130",
  "total": "8",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "34",
  "previousWaterMetering": "573",
  "currentWaterMetering": "605",
  "metersConsumed": "32",
  "differenceOfUse": "-130",
  "total": "1112",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "35",
  "previousWaterMetering": "911",
  "currentWaterMetering": "935",
  "metersConsumed": "24",
  "differenceOfUse": "-130",
  "total": "572",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "36",
  "previousWaterMetering": "540",
  "currentWaterMetering": "548",
  "metersConsumed": "8",
  "differenceOfUse": "-130",
  "total": "91",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "37",
  "previousWaterMetering": "381",
  "currentWaterMetering": "394",
  "metersConsumed": "13",
  "differenceOfUse": "-130",
  "total": "227",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "38",
  "previousWaterMetering": "529",
  "currentWaterMetering": "534",
  "metersConsumed": "5",
  "differenceOfUse": "-130",
  "total": "27",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "39",
  "previousWaterMetering": "373",
  "currentWaterMetering": "380",
  "metersConsumed": "7",
  "differenceOfUse": "-130",
  "total": "69",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "40",
  "previousWaterMetering": "111",
  "currentWaterMetering": "112",
  "metersConsumed": "1",
  "differenceOfUse": "-85",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "41",
  "previousWaterMetering": "702",
  "currentWaterMetering": "715",
  "metersConsumed": "13",
  "differenceOfUse": "-130",
  "total": "227",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "42",
  "previousWaterMetering": "709",
  "currentWaterMetering": "726",
  "metersConsumed": "17",
  "differenceOfUse": "-130",
  "total": "337",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "43",
  "previousWaterMetering": "234",
  "currentWaterMetering": "235",
  "metersConsumed": "1",
  "differenceOfUse": "-85",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "44",
  "previousWaterMetering": "159",
  "currentWaterMetering": "163",
  "metersConsumed": "4",
  "differenceOfUse": "-130",
  "total": "8",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "45",
  "previousWaterMetering": "769",
  "currentWaterMetering": "782",
  "metersConsumed": "13",
  "differenceOfUse": "-130",
  "total": "227",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "46",
  "previousWaterMetering": "276",
  "currentWaterMetering": "284",
  "metersConsumed": "8",
  "differenceOfUse": "-130",
  "total": "91",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "47",
  "previousWaterMetering": "619",
  "currentWaterMetering": "625",
  "metersConsumed": "6",
  "differenceOfUse": "-130",
  "total": "47",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "48",
  "previousWaterMetering": "306",
  "currentWaterMetering": "362",
  "metersConsumed": "56",
  "differenceOfUse": "-130",
  "total": "3221",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "49",
  "previousWaterMetering": "594",
  "currentWaterMetering": "610",
  "metersConsumed": "16",
  "differenceOfUse": "-130",
  "total": "307",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "50",
  "previousWaterMetering": "568",
  "currentWaterMetering": "569",
  "metersConsumed": "1",
  "differenceOfUse": "-85",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "51",
  "previousWaterMetering": "126",
  "currentWaterMetering": "128",
  "metersConsumed": "2",
  "differenceOfUse": "-102",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "52",
  "previousWaterMetering": "383",
  "currentWaterMetering": "392",
  "metersConsumed": "9",
  "differenceOfUse": "-130",
  "total": "123",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "53",
  "previousWaterMetering": "192",
  "currentWaterMetering": "198",
  "metersConsumed": "6",
  "differenceOfUse": "-130",
  "total": "47",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "54",
  "previousWaterMetering": "619",
  "currentWaterMetering": "632",
  "metersConsumed": "13",
  "differenceOfUse": "-130",
  "total": "227",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "-68",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "56",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "-68",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "57",
  "previousWaterMetering": "759",
  "currentWaterMetering": "770",
  "metersConsumed": "11",
  "differenceOfUse": "-130",
  "total": "173",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "58",
  "previousWaterMetering": "483",
  "currentWaterMetering": "492",
  "metersConsumed": "9",
  "differenceOfUse": "-130",
  "total": "123",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "59",
  "previousWaterMetering": "394",
  "currentWaterMetering": "409",
  "metersConsumed": "15",
  "differenceOfUse": "-130",
  "total": "281",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "60",
  "previousWaterMetering": "435",
  "currentWaterMetering": "448",
  "metersConsumed": "13",
  "differenceOfUse": "-130",
  "total": "227",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "61",
  "previousWaterMetering": "111",
  "currentWaterMetering": "113",
  "metersConsumed": "2",
  "differenceOfUse": "-102",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "62",
  "previousWaterMetering": "399",
  "currentWaterMetering": "416",
  "metersConsumed": "17",
  "differenceOfUse": "-130",
  "total": "337",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "63",
  "previousWaterMetering": "853",
  "currentWaterMetering": "868",
  "metersConsumed": "15",
  "differenceOfUse": "-130",
  "total": "281",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "64",
  "previousWaterMetering": "275",
  "currentWaterMetering": "286",
  "metersConsumed": "11",
  "differenceOfUse": "-130",
  "total": "173",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "65",
  "previousWaterMetering": "893",
  "currentWaterMetering": "911",
  "metersConsumed": "18",
  "differenceOfUse": "-130",
  "total": "365",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "66",
  "previousWaterMetering": "183",
  "currentWaterMetering": "185",
  "metersConsumed": "2",
  "differenceOfUse": "-102",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "67",
  "previousWaterMetering": "349",
  "currentWaterMetering": "357",
  "metersConsumed": "8",
  "differenceOfUse": "-130",
  "total": "91",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "-68",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "69",
  "previousWaterMetering": "630",
  "currentWaterMetering": "648",
  "metersConsumed": "18",
  "differenceOfUse": "-130",
  "total": "365",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "70",
  "previousWaterMetering": "188",
  "currentWaterMetering": "199",
  "metersConsumed": "11",
  "differenceOfUse": "-130",
  "total": "173",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "71",
  "previousWaterMetering": "389",
  "currentWaterMetering": "401",
  "metersConsumed": "12",
  "differenceOfUse": "-130",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "72",
  "previousWaterMetering": "331",
  "currentWaterMetering": "343",
  "metersConsumed": "12",
  "differenceOfUse": "-130",
  "total": "197",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "73",
  "previousWaterMetering": "284",
  "currentWaterMetering": "290",
  "metersConsumed": "6",
  "differenceOfUse": "-130",
  "total": "47",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "74",
  "previousWaterMetering": "172",
  "currentWaterMetering": "175",
  "metersConsumed": "3",
  "differenceOfUse": "-120",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "75",
  "previousWaterMetering": "522",
  "currentWaterMetering": "529",
  "metersConsumed": "7",
  "differenceOfUse": "-130",
  "total": "69",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "76",
  "previousWaterMetering": "50",
  "currentWaterMetering": "55",
  "metersConsumed": "5",
  "differenceOfUse": "-130",
  "total": "27",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "77",
  "previousWaterMetering": "866",
  "currentWaterMetering": "872",
  "metersConsumed": "6",
  "differenceOfUse": "-130",
  "total": "47",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "78",
  "previousWaterMetering": "68",
  "currentWaterMetering": "70",
  "metersConsumed": "2",
  "differenceOfUse": "-102",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "79",
  "previousWaterMetering": "434",
  "currentWaterMetering": "444",
  "metersConsumed": "10",
  "differenceOfUse": "-130",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "80",
  "previousWaterMetering": "611",
  "currentWaterMetering": "629",
  "metersConsumed": "18",
  "differenceOfUse": "-130",
  "total": "365",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "81",
  "previousWaterMetering": "238",
  "currentWaterMetering": "246",
  "metersConsumed": "8",
  "differenceOfUse": "-130",
  "total": "91",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "82",
  "previousWaterMetering": "431",
  "currentWaterMetering": "442",
  "metersConsumed": "11",
  "differenceOfUse": "-130",
  "total": "173",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "83",
  "previousWaterMetering": "247",
  "currentWaterMetering": "247",
  "metersConsumed": "0",
  "differenceOfUse": "-68",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "84",
  "previousWaterMetering": "315",
  "currentWaterMetering": "319",
  "metersConsumed": "4",
  "differenceOfUse": "-130",
  "total": "8",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "85",
  "previousWaterMetering": "355",
  "currentWaterMetering": "363",
  "metersConsumed": "8",
  "differenceOfUse": "-130",
  "total": "91",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "86",
  "previousWaterMetering": "259",
  "currentWaterMetering": "275",
  "metersConsumed": "16",
  "differenceOfUse": "-130",
  "total": "307",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "87",
  "previousWaterMetering": "397",
  "currentWaterMetering": "412",
  "metersConsumed": "15",
  "differenceOfUse": "-130",
  "total": "281",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "88",
  "previousWaterMetering": "436",
  "currentWaterMetering": "443",
  "metersConsumed": "7",
  "differenceOfUse": "-130",
  "total": "69",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "89",
  "previousWaterMetering": "799",
  "currentWaterMetering": "812",
  "metersConsumed": "13",
  "differenceOfUse": "-130",
  "total": "227",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "90",
  "previousWaterMetering": "962",
  "currentWaterMetering": "994",
  "metersConsumed": "32",
  "differenceOfUse": "-130",
  "total": "1112",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "91",
  "previousWaterMetering": "391",
  "currentWaterMetering": "402",
  "metersConsumed": "11",
  "differenceOfUse": "-130",
  "total": "173",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "92",
  "previousWaterMetering": "533",
  "currentWaterMetering": "542",
  "metersConsumed": "9",
  "differenceOfUse": "-130",
  "total": "123",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "93",
  "previousWaterMetering": "345",
  "currentWaterMetering": "358",
  "metersConsumed": "13",
  "differenceOfUse": "-130",
  "total": "227",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "94",
  "previousWaterMetering": "557",
  "currentWaterMetering": "567",
  "metersConsumed": "10",
  "differenceOfUse": "-130",
  "total": "148",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "95",
  "previousWaterMetering": "66",
  "currentWaterMetering": "66",
  "metersConsumed": "0",
  "differenceOfUse": "-68",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "96",
  "previousWaterMetering": "183",
  "currentWaterMetering": "186",
  "metersConsumed": "3",
  "differenceOfUse": "-120",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "97",
  "previousWaterMetering": "240",
  "currentWaterMetering": "241",
  "metersConsumed": "1",
  "differenceOfUse": "-85",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "98",
  "previousWaterMetering": "110",
  "currentWaterMetering": "110",
  "metersConsumed": "0",
  "differenceOfUse": "-68",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "99",
  "previousWaterMetering": "240",
  "currentWaterMetering": "240",
  "metersConsumed": "0",
  "differenceOfUse": "-68",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "4",
  "metersConsumed": "1",
  "differenceOfUse": "-85",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "101",
  "previousWaterMetering": "345",
  "currentWaterMetering": "387",
  "metersConsumed": "42",
  "differenceOfUse": "-130",
  "total": "1889",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "102",
  "previousWaterMetering": "175",
  "currentWaterMetering": "180",
  "metersConsumed": "5",
  "differenceOfUse": "-130",
  "total": "27",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
},
{
  "houseId": "103",
  "previousWaterMetering": "13",
  "currentWaterMetering": "13",
  "metersConsumed": "0",
  "differenceOfUse": "-68",
  "total": "0",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Mayo",
  "paymentMonth": "Julio",
  "year": "2026"
}]
;

export const reportShimul = data;
