
interface periodShimul {
    condo: string,
    caKey: string,
    type?: string,
    color?: string,
    previousWaterMetering: string,
    currentWaterMetering: string,
    metersConsumed: string,
    periodOfUse: string,
    differenceOfUse: string,
    token?: string,
    houseId: string,
    total: string,
    paymentMonth: string,
    year: string,
    comments?:string,
};

const data: periodShimul[] =
[{
  "houseId": "1",
  "previousWaterMetering": "474",
  "currentWaterMetering": "490",
  "metersConsumed": "16",
  "differenceOfUse": "24",
  "total": "442",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "2",
  "previousWaterMetering": "164",
  "currentWaterMetering": "174",
  "metersConsumed": "10",
  "differenceOfUse": "24",
  "total": "290",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "3",
  "previousWaterMetering": "524",
  "currentWaterMetering": "542",
  "metersConsumed": "18",
  "differenceOfUse": "24",
  "total": "497",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "4",
  "previousWaterMetering": "430",
  "currentWaterMetering": "441",
  "metersConsumed": "11",
  "differenceOfUse": "24",
  "total": "313",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "5",
  "previousWaterMetering": "238",
  "currentWaterMetering": "239",
  "metersConsumed": "1",
  "differenceOfUse": "24",
  "total": "105",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "6",
  "previousWaterMetering": "363",
  "currentWaterMetering": "365",
  "metersConsumed": "2",
  "differenceOfUse": "24",
  "total": "121",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "7",
  "previousWaterMetering": "525",
  "currentWaterMetering": "542",
  "metersConsumed": "17",
  "differenceOfUse": "24",
  "total": "470",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "8",
  "previousWaterMetering": "208",
  "currentWaterMetering": "208",
  "metersConsumed": "0",
  "differenceOfUse": "24",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "9",
  "previousWaterMetering": "258",
  "currentWaterMetering": "264",
  "metersConsumed": "6",
  "differenceOfUse": "24",
  "total": "193",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "10",
  "previousWaterMetering": "487",
  "currentWaterMetering": "496",
  "metersConsumed": "9",
  "differenceOfUse": "24",
  "total": "266",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "11",
  "previousWaterMetering": "653",
  "currentWaterMetering": "662",
  "metersConsumed": "9",
  "differenceOfUse": "24",
  "total": "266",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "12",
  "previousWaterMetering": "370",
  "currentWaterMetering": "378",
  "metersConsumed": "8",
  "differenceOfUse": "24",
  "total": "235",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "13",
  "previousWaterMetering": "267",
  "currentWaterMetering": "268",
  "metersConsumed": "1",
  "differenceOfUse": "24",
  "total": "105",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "14",
  "previousWaterMetering": "501",
  "currentWaterMetering": "509",
  "metersConsumed": "8",
  "differenceOfUse": "24",
  "total": "235",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "15",
  "previousWaterMetering": "232",
  "currentWaterMetering": "236",
  "metersConsumed": "4",
  "differenceOfUse": "24",
  "total": "156",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "16",
  "previousWaterMetering": "245",
  "currentWaterMetering": "251",
  "metersConsumed": "6",
  "differenceOfUse": "24",
  "total": "193",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "17",
  "previousWaterMetering": "311",
  "currentWaterMetering": "318",
  "metersConsumed": "7",
  "differenceOfUse": "24",
  "total": "214",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "18",
  "previousWaterMetering": "349",
  "currentWaterMetering": "356",
  "metersConsumed": "7",
  "differenceOfUse": "24",
  "total": "214",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "19",
  "previousWaterMetering": "89",
  "currentWaterMetering": "90",
  "metersConsumed": "1",
  "differenceOfUse": "24",
  "total": "105",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "20",
  "previousWaterMetering": "426",
  "currentWaterMetering": "427",
  "metersConsumed": "1",
  "differenceOfUse": "24",
  "total": "105",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "21",
  "previousWaterMetering": "371",
  "currentWaterMetering": "382",
  "metersConsumed": "11",
  "differenceOfUse": "24",
  "total": "313",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "22",
  "previousWaterMetering": "344",
  "currentWaterMetering": "354",
  "metersConsumed": "10",
  "differenceOfUse": "24",
  "total": "290",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "23",
  "previousWaterMetering": "694",
  "currentWaterMetering": "712",
  "metersConsumed": "18",
  "differenceOfUse": "24",
  "total": "497",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "24",
  "previousWaterMetering": "308",
  "currentWaterMetering": "318",
  "metersConsumed": "10",
  "differenceOfUse": "24",
  "total": "290",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "25",
  "previousWaterMetering": "216",
  "currentWaterMetering": "223",
  "metersConsumed": "7",
  "differenceOfUse": "24",
  "total": "214",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "26",
  "previousWaterMetering": "34",
  "currentWaterMetering": "34",
  "metersConsumed": "0",
  "differenceOfUse": "24",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "27",
  "previousWaterMetering": "305",
  "currentWaterMetering": "322",
  "metersConsumed": "17",
  "differenceOfUse": "24",
  "total": "470",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "28",
  "previousWaterMetering": "43",
  "currentWaterMetering": "43",
  "metersConsumed": "0",
  "differenceOfUse": "24",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "29",
  "previousWaterMetering": "194",
  "currentWaterMetering": "196",
  "metersConsumed": "2",
  "differenceOfUse": "24",
  "total": "121",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "30",
  "previousWaterMetering": "516",
  "currentWaterMetering": "549",
  "metersConsumed": "33",
  "differenceOfUse": "24",
  "total": "1279",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "31",
  "previousWaterMetering": "354",
  "currentWaterMetering": "366",
  "metersConsumed": "12",
  "differenceOfUse": "24",
  "total": "337",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "32",
  "previousWaterMetering": "543",
  "currentWaterMetering": "559",
  "metersConsumed": "16",
  "differenceOfUse": "24",
  "total": "442",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "33",
  "previousWaterMetering": "153",
  "currentWaterMetering": "155",
  "metersConsumed": "2",
  "differenceOfUse": "24",
  "total": "121",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "34",
  "previousWaterMetering": "480",
  "currentWaterMetering": "494",
  "metersConsumed": "14",
  "differenceOfUse": "24",
  "total": "391",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "35",
  "previousWaterMetering": "722",
  "currentWaterMetering": "742",
  "metersConsumed": "20",
  "differenceOfUse": "24",
  "total": "552",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "36",
  "previousWaterMetering": "453",
  "currentWaterMetering": "476",
  "metersConsumed": "23",
  "differenceOfUse": "24",
  "total": "642",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "37",
  "previousWaterMetering": "299",
  "currentWaterMetering": "304",
  "metersConsumed": "5",
  "differenceOfUse": "24",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "38",
  "previousWaterMetering": "460",
  "currentWaterMetering": "470",
  "metersConsumed": "10",
  "differenceOfUse": "24",
  "total": "290",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "39",
  "previousWaterMetering": "300",
  "currentWaterMetering": "307",
  "metersConsumed": "7",
  "differenceOfUse": "24",
  "total": "214",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "40",
  "previousWaterMetering": "99",
  "currentWaterMetering": "101",
  "metersConsumed": "2",
  "differenceOfUse": "24",
  "total": "121",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "41",
  "previousWaterMetering": "611",
  "currentWaterMetering": "624",
  "metersConsumed": "13",
  "differenceOfUse": "24",
  "total": "365",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "42",
  "previousWaterMetering": "572",
  "currentWaterMetering": "590",
  "metersConsumed": "18",
  "differenceOfUse": "24",
  "total": "497",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "43",
  "previousWaterMetering": "201",
  "currentWaterMetering": "204",
  "metersConsumed": "3",
  "differenceOfUse": "24",
  "total": "138",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "44",
  "previousWaterMetering": "117",
  "currentWaterMetering": "122",
  "metersConsumed": "5",
  "differenceOfUse": "24",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "45",
  "previousWaterMetering": "619",
  "currentWaterMetering": "642",
  "metersConsumed": "23",
  "differenceOfUse": "24",
  "total": "642",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "46",
  "previousWaterMetering": "223",
  "currentWaterMetering": "228",
  "metersConsumed": "5",
  "differenceOfUse": "24",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "47",
  "previousWaterMetering": "554",
  "currentWaterMetering": "563",
  "metersConsumed": "9",
  "differenceOfUse": "24",
  "total": "266",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "48",
  "previousWaterMetering": "229",
  "currentWaterMetering": "239",
  "metersConsumed": "10",
  "differenceOfUse": "24",
  "total": "290",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "49",
  "previousWaterMetering": "431",
  "currentWaterMetering": "444",
  "metersConsumed": "13",
  "differenceOfUse": "24",
  "total": "365",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "50",
  "previousWaterMetering": "557",
  "currentWaterMetering": "557",
  "metersConsumed": "0",
  "differenceOfUse": "24",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "51",
  "previousWaterMetering": "106",
  "currentWaterMetering": "108",
  "metersConsumed": "2",
  "differenceOfUse": "24",
  "total": "121",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "52",
  "previousWaterMetering": "330",
  "currentWaterMetering": "337",
  "metersConsumed": "7",
  "differenceOfUse": "24",
  "total": "214",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "53",
  "previousWaterMetering": "149",
  "currentWaterMetering": "155",
  "metersConsumed": "6",
  "differenceOfUse": "24",
  "total": "193",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "54",
  "previousWaterMetering": "507",
  "currentWaterMetering": "518",
  "metersConsumed": "11",
  "differenceOfUse": "24",
  "total": "313",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "55",
  "previousWaterMetering": "11",
  "currentWaterMetering": "11",
  "metersConsumed": "0",
  "differenceOfUse": "24",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "56",
  "previousWaterMetering": "7",
  "currentWaterMetering": "7",
  "metersConsumed": "0",
  "differenceOfUse": "24",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "57",
  "previousWaterMetering": "666",
  "currentWaterMetering": "670",
  "metersConsumed": "4",
  "differenceOfUse": "24",
  "total": "156",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "58",
  "previousWaterMetering": "421",
  "currentWaterMetering": "428",
  "metersConsumed": "7",
  "differenceOfUse": "24",
  "total": "214",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "59",
  "previousWaterMetering": "299",
  "currentWaterMetering": "311",
  "metersConsumed": "12",
  "differenceOfUse": "24",
  "total": "337",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "60",
  "previousWaterMetering": "341",
  "currentWaterMetering": "352",
  "metersConsumed": "11",
  "differenceOfUse": "24",
  "total": "313",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "61",
  "previousWaterMetering": "93",
  "currentWaterMetering": "97",
  "metersConsumed": "4",
  "differenceOfUse": "24",
  "total": "156",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "62",
  "previousWaterMetering": "327",
  "currentWaterMetering": "332",
  "metersConsumed": "5",
  "differenceOfUse": "24",
  "total": "174",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "63",
  "previousWaterMetering": "722",
  "currentWaterMetering": "738",
  "metersConsumed": "16",
  "differenceOfUse": "24",
  "total": "442",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "64",
  "previousWaterMetering": "205",
  "currentWaterMetering": "215",
  "metersConsumed": "10",
  "differenceOfUse": "24",
  "total": "290",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "65",
  "previousWaterMetering": "764",
  "currentWaterMetering": "778",
  "metersConsumed": "14",
  "differenceOfUse": "24",
  "total": "391",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "66",
  "previousWaterMetering": "153",
  "currentWaterMetering": "155",
  "metersConsumed": "2",
  "differenceOfUse": "24",
  "total": "121",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "67",
  "previousWaterMetering": "280",
  "currentWaterMetering": "289",
  "metersConsumed": "9",
  "differenceOfUse": "24",
  "total": "266",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "68",
  "previousWaterMetering": "8",
  "currentWaterMetering": "8",
  "metersConsumed": "0",
  "differenceOfUse": "24",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "69",
  "previousWaterMetering": "501",
  "currentWaterMetering": "513",
  "metersConsumed": "12",
  "differenceOfUse": "24",
  "total": "337",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "70",
  "previousWaterMetering": "130",
  "currentWaterMetering": "137",
  "metersConsumed": "7",
  "differenceOfUse": "24",
  "total": "214",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "71",
  "previousWaterMetering": "308",
  "currentWaterMetering": "320",
  "metersConsumed": "12",
  "differenceOfUse": "24",
  "total": "337",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "72",
  "previousWaterMetering": "265",
  "currentWaterMetering": "273",
  "metersConsumed": "8",
  "differenceOfUse": "24",
  "total": "235",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "73",
  "previousWaterMetering": "232",
  "currentWaterMetering": "239",
  "metersConsumed": "7",
  "differenceOfUse": "24",
  "total": "214",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "74",
  "previousWaterMetering": "143",
  "currentWaterMetering": "147",
  "metersConsumed": "4",
  "differenceOfUse": "24",
  "total": "156",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "75",
  "previousWaterMetering": "449",
  "currentWaterMetering": "458",
  "metersConsumed": "9",
  "differenceOfUse": "24",
  "total": "266",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "76",
  "previousWaterMetering": "41",
  "currentWaterMetering": "41",
  "metersConsumed": "0",
  "differenceOfUse": "24",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "77",
  "previousWaterMetering": "752",
  "currentWaterMetering": "770",
  "metersConsumed": "18",
  "differenceOfUse": "24",
  "total": "497",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "78",
  "previousWaterMetering": "46",
  "currentWaterMetering": "48",
  "metersConsumed": "2",
  "differenceOfUse": "24",
  "total": "121",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "79",
  "previousWaterMetering": "374",
  "currentWaterMetering": "384",
  "metersConsumed": "10",
  "differenceOfUse": "24",
  "total": "290",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "80",
  "previousWaterMetering": "472",
  "currentWaterMetering": "486",
  "metersConsumed": "14",
  "differenceOfUse": "24",
  "total": "391",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "81",
  "previousWaterMetering": "137",
  "currentWaterMetering": "151",
  "metersConsumed": "14",
  "differenceOfUse": "24",
  "total": "391",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "82",
  "previousWaterMetering": "362",
  "currentWaterMetering": "365",
  "metersConsumed": "3",
  "differenceOfUse": "24",
  "total": "138",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "83",
  "previousWaterMetering": "224",
  "currentWaterMetering": "228",
  "metersConsumed": "4",
  "differenceOfUse": "24",
  "total": "156",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "84",
  "previousWaterMetering": "268",
  "currentWaterMetering": "270",
  "metersConsumed": "2",
  "differenceOfUse": "24",
  "total": "121",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "85",
  "previousWaterMetering": "284",
  "currentWaterMetering": "292",
  "metersConsumed": "8",
  "differenceOfUse": "24",
  "total": "235",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "86",
  "previousWaterMetering": "143",
  "currentWaterMetering": "159",
  "metersConsumed": "16",
  "differenceOfUse": "24",
  "total": "442",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "87",
  "previousWaterMetering": "285",
  "currentWaterMetering": "303",
  "metersConsumed": "18",
  "differenceOfUse": "24",
  "total": "497",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "88",
  "previousWaterMetering": "380",
  "currentWaterMetering": "388",
  "metersConsumed": "8",
  "differenceOfUse": "24",
  "total": "235",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "89",
  "previousWaterMetering": "681",
  "currentWaterMetering": "696",
  "metersConsumed": "15",
  "differenceOfUse": "24",
  "total": "417",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "90",
  "previousWaterMetering": "713",
  "currentWaterMetering": "741",
  "metersConsumed": "28",
  "differenceOfUse": "24",
  "total": "936",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "91",
  "previousWaterMetering": "328",
  "currentWaterMetering": "330",
  "metersConsumed": "2",
  "differenceOfUse": "24",
  "total": "121",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "92",
  "previousWaterMetering": "467",
  "currentWaterMetering": "476",
  "metersConsumed": "9",
  "differenceOfUse": "24",
  "total": "266",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "93",
  "previousWaterMetering": "241",
  "currentWaterMetering": "251",
  "metersConsumed": "10",
  "differenceOfUse": "24",
  "total": "290",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "94",
  "previousWaterMetering": "472",
  "currentWaterMetering": "485",
  "metersConsumed": "13",
  "differenceOfUse": "24",
  "total": "365",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "95",
  "previousWaterMetering": "64",
  "currentWaterMetering": "64",
  "metersConsumed": "0",
  "differenceOfUse": "24",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "96",
  "previousWaterMetering": "151",
  "currentWaterMetering": "155",
  "metersConsumed": "4",
  "differenceOfUse": "24",
  "total": "156",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "97",
  "previousWaterMetering": "205",
  "currentWaterMetering": "211",
  "metersConsumed": "6",
  "differenceOfUse": "24",
  "total": "193",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "98",
  "previousWaterMetering": "100",
  "currentWaterMetering": "100",
  "metersConsumed": "0",
  "differenceOfUse": "24",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "99",
  "previousWaterMetering": "234",
  "currentWaterMetering": "234",
  "metersConsumed": "0",
  "differenceOfUse": "24",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "100",
  "previousWaterMetering": "3",
  "currentWaterMetering": "3",
  "metersConsumed": "0",
  "differenceOfUse": "24",
  "total": "89",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "101",
  "previousWaterMetering": "217",
  "currentWaterMetering": "223",
  "metersConsumed": "6",
  "differenceOfUse": "24",
  "total": "193",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "102",
  "previousWaterMetering": "145",
  "currentWaterMetering": "149",
  "metersConsumed": "4",
  "differenceOfUse": "24",
  "total": "156",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
},
{
  "houseId": "103",
  "previousWaterMetering": "11",
  "currentWaterMetering": "13",
  "metersConsumed": "2",
  "differenceOfUse": "24",
  "total": "121",
  "condo": "Shimul",
  "caKey": "shimulac",
  "periodOfUse": "Agosto",
  "paymentMonth": "Octubre",
  "year": "2025"
}]
;

export const reportShimul = data;
