
interface paymentsHydra {
    type?: string,
    color?: string,
    amount?: string,
    comprobation?: string,
    house?: string,
    houseId?: string,
    ordinaryPayment?: string,
    waterPayment?: string,
    sanctionPayment?: string,
    pendingPayment?: string,
    sanctionDescription?: string,
    total?: string,
    paymentMonth?: string,
    year?: string,
    token?: string,
    comments?:string,
    waterPaymentDelay?:string,
    ordinaryPaymentDelay?:string,
    sanctionPaymentDelay?:string,
    sanctionPaymentDelayDescription?:string,
    caKey?:string,
    condo?:string,
    periodOfWaterUse?: string,
    metersConsumed?: string,
    amountPayed?: string
  };

const data: paymentsHydra[] = 
[{
  "houseId": "1",
  "ordinaryPayment": "165",
  "waterPayment": "103",
  "pendingPayment": "284",
  "sanctionPayment": "500",
  "paymentMonth": "Mayo",
  "comments": "1a sanción por pago tardio cuota interna.",
  "total": "1052",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "1052"
},
{
  "houseId": "2",
  "ordinaryPayment": "165",
  "waterPayment": "169",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "334",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "334"
},
{
  "houseId": "3",
  "ordinaryPayment": "165",
  "waterPayment": "186",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "351",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "351"
},
{
  "houseId": "4",
  "ordinaryPayment": "165",
  "waterPayment": "186",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "351",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "351"
},
{
  "houseId": "5",
  "ordinaryPayment": "165",
  "waterPayment": "186",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "351",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "351"
},
{
  "houseId": "6",
  "ordinaryPayment": "165",
  "waterPayment": "186",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "351",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "351"
},
{
  "houseId": "7",
  "ordinaryPayment": "165",
  "waterPayment": "135",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "300",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "300"
},
{
  "houseId": "8",
  "ordinaryPayment": "165",
  "waterPayment": "322",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "487",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "11",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "487"
},
{
  "houseId": "9",
  "ordinaryPayment": "165",
  "waterPayment": "585",
  "pendingPayment": "693",
  "sanctionPayment": "500",
  "paymentMonth": "Mayo",
  "comments": "1a sanción por pago tardio cuota interna.",
  "total": "1943",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "21",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "1943"
},
{
  "houseId": "10",
  "ordinaryPayment": "165",
  "waterPayment": "103",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "268",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "268"
},
{
  "houseId": "11",
  "ordinaryPayment": "165",
  "waterPayment": "205",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "370",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "370"
},
{
  "houseId": "12",
  "ordinaryPayment": "165",
  "waterPayment": "186",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "351",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "351"
},
{
  "houseId": "13",
  "ordinaryPayment": "165",
  "waterPayment": "276",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Ingresar correctamente el concepto bancario como HYDRA13",
  "total": "441",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "9",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "441"
},
{
  "houseId": "14",
  "ordinaryPayment": "165",
  "waterPayment": "397",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "562",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "14",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "562"
},
{
  "houseId": "15",
  "ordinaryPayment": "165",
  "waterPayment": "225",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "390",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "7",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "390"
},
{
  "houseId": "16",
  "ordinaryPayment": "165",
  "waterPayment": "169",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "334",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "334"
},
{
  "houseId": "17",
  "ordinaryPayment": "165",
  "waterPayment": "152",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "317",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "317"
},
{
  "houseId": "18",
  "ordinaryPayment": "165",
  "waterPayment": "205",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "370",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "370"
},
{
  "houseId": "20",
  "ordinaryPayment": "165",
  "waterPayment": "276",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "441",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "9",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "441"
},
{
  "houseId": "21",
  "ordinaryPayment": "165",
  "waterPayment": "169",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Ingresar correctamente el concepto bancario como HYDRA21",
  "total": "334",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "334"
},
{
  "houseId": "22",
  "ordinaryPayment": "165",
  "waterPayment": "152",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "317",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "317"
},
{
  "houseId": "23",
  "ordinaryPayment": "165",
  "waterPayment": "169",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "334",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "334"
},
{
  "houseId": "24",
  "ordinaryPayment": "165",
  "waterPayment": "205",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "370",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "370"
},
{
  "houseId": "25",
  "ordinaryPayment": "165",
  "waterPayment": "152",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "317",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "317"
},
{
  "houseId": "27",
  "ordinaryPayment": "165",
  "waterPayment": "103",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "268",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "268"
},
{
  "houseId": "28",
  "ordinaryPayment": "165",
  "waterPayment": "808",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "973",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "26",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "973"
},
{
  "houseId": "29",
  "ordinaryPayment": "165",
  "waterPayment": "135",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "300",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "300"
},
{
  "houseId": "30",
  "ordinaryPayment": "165",
  "waterPayment": "103",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "268",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "268"
},
{
  "houseId": "31",
  "ordinaryPayment": "165",
  "waterPayment": "225",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "390",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "7",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "390"
},
{
  "houseId": "32",
  "ordinaryPayment": "165",
  "waterPayment": "103",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "268",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "268"
},
{
  "houseId": "33",
  "ordinaryPayment": "165",
  "waterPayment": "135",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "300",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "300"
},
{
  "houseId": "34",
  "ordinaryPayment": "165",
  "waterPayment": "103",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "268",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "268"
},
{
  "houseId": "35",
  "ordinaryPayment": "165",
  "waterPayment": "186",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "351",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "351"
},
{
  "houseId": "36",
  "ordinaryPayment": "165",
  "waterPayment": "119",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "284",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "1",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "284"
},
{
  "houseId": "37",
  "ordinaryPayment": "165",
  "waterPayment": "152",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "317",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "317"
},
{
  "houseId": "38",
  "ordinaryPayment": "165",
  "waterPayment": "372",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "537",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "13",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "537"
},
{
  "houseId": "39",
  "ordinaryPayment": "165",
  "waterPayment": "103",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "268",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "268"
},
{
  "houseId": "40",
  "ordinaryPayment": "165",
  "waterPayment": "205",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "370",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "370"
},
{
  "houseId": "41",
  "ordinaryPayment": "165",
  "waterPayment": "135",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Ingresar correctamente el concepto bancario como HYDRA41",
  "total": "300",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "300"
},
{
  "houseId": "42",
  "ordinaryPayment": "165",
  "waterPayment": "186",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "351",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "351"
},
{
  "houseId": "43",
  "ordinaryPayment": "165",
  "waterPayment": "135",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "300",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "300"
},
{
  "houseId": "44",
  "ordinaryPayment": "165",
  "waterPayment": "152",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "317",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "317"
},
{
  "houseId": "45",
  "ordinaryPayment": "165",
  "waterPayment": "423",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "588",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "15",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "588"
},
{
  "houseId": "46",
  "ordinaryPayment": "165",
  "waterPayment": "225",
  "pendingPayment": "2",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "En su pago previo le faltaron 2 pesos",
  "total": "392",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "7",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "392"
},
{
  "houseId": "47",
  "ordinaryPayment": "165",
  "waterPayment": "152",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "317",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "317"
},
{
  "houseId": "48",
  "ordinaryPayment": "165",
  "waterPayment": "245",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "410",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "8",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "410"
},
{
  "houseId": "49",
  "ordinaryPayment": "165",
  "waterPayment": "119",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "284",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "1",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "284"
},
{
  "houseId": "50",
  "ordinaryPayment": "165",
  "waterPayment": "152",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "317",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "317"
},
{
  "houseId": "51",
  "ordinaryPayment": "165",
  "waterPayment": "103",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "268",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "268"
},
{
  "houseId": "52",
  "ordinaryPayment": "165",
  "waterPayment": "169",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "334",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "334"
},
{
  "houseId": "53",
  "ordinaryPayment": "165",
  "waterPayment": "245",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "410",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "8",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "410"
},
{
  "houseId": "54",
  "ordinaryPayment": "165",
  "waterPayment": "186",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "351",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "351"
},
{
  "houseId": "55",
  "ordinaryPayment": "165",
  "waterPayment": "152",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Ingresar correctamente el concepto bancario como HYDRA55",
  "total": "317",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "317"
},
{
  "houseId": "56",
  "ordinaryPayment": "165",
  "waterPayment": "103",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "268",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "268"
},
{
  "houseId": "57",
  "ordinaryPayment": "165",
  "waterPayment": "372",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "537",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "13",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "537"
},
{
  "houseId": "58",
  "ordinaryPayment": "165",
  "waterPayment": "555",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "720",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "20",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "720"
},
{
  "houseId": "59",
  "ordinaryPayment": "165",
  "waterPayment": "186",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "351",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "351"
},
{
  "houseId": "60",
  "ordinaryPayment": "165",
  "waterPayment": "119",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "284",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "1",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "284"
},
{
  "houseId": "61",
  "ordinaryPayment": "165",
  "waterPayment": "103",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "268",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "268"
},
{
  "houseId": "62",
  "ordinaryPayment": "165",
  "waterPayment": "205",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "370",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "370"
},
{
  "houseId": "63",
  "ordinaryPayment": "165",
  "waterPayment": "205",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "370",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "370"
},
{
  "houseId": "64",
  "ordinaryPayment": "165",
  "waterPayment": "169",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "334",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "334"
},
{
  "houseId": "65",
  "ordinaryPayment": "165",
  "waterPayment": "322",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "487",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "11",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "487"
},
{
  "houseId": "66",
  "ordinaryPayment": "165",
  "waterPayment": "205",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "370",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "370"
},
{
  "houseId": "67",
  "ordinaryPayment": "165",
  "waterPayment": "169",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "334",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "334"
},
{
  "houseId": "68",
  "ordinaryPayment": "165",
  "waterPayment": "103",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "268",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "268"
},
{
  "houseId": "69",
  "ordinaryPayment": "165",
  "waterPayment": "205",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "370",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "370"
},
{
  "houseId": "70",
  "ordinaryPayment": "165",
  "waterPayment": "299",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "464",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "10",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "464"
},
{
  "houseId": "71",
  "ordinaryPayment": "165",
  "waterPayment": "276",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "441",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "9",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "441"
},
{
  "houseId": "72",
  "ordinaryPayment": "165",
  "waterPayment": "225",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "390",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "7",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "390"
},
{
  "houseId": "73",
  "ordinaryPayment": "165",
  "waterPayment": "205",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "370",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "370"
},
{
  "houseId": "74",
  "ordinaryPayment": "165",
  "waterPayment": "186",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "351",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "351"
},
{
  "houseId": "75",
  "ordinaryPayment": "165",
  "waterPayment": "299",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "464",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "10",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "464"
},
{
  "houseId": "77",
  "ordinaryPayment": "165",
  "waterPayment": "103",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "268",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "268"
},
{
  "houseId": "78",
  "ordinaryPayment": "165",
  "waterPayment": "169",
  "pendingPayment": "169",
  "sanctionPayment": "500",
  "paymentMonth": "Mayo",
  "comments": "1a sanción por pago tardio cuota interna.",
  "total": "1003",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "1003"
},
{
  "houseId": "80",
  "ordinaryPayment": "165",
  "waterPayment": "135",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "300",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "300"
},
{
  "houseId": "81",
  "ordinaryPayment": "165",
  "waterPayment": "205",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "370",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "370"
},
{
  "houseId": "82",
  "ordinaryPayment": "165",
  "waterPayment": "186",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "351",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "351"
},
{
  "houseId": "83",
  "ordinaryPayment": "165",
  "waterPayment": "225",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "390",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "7",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "390"
},
{
  "houseId": "84",
  "ordinaryPayment": "165",
  "waterPayment": "103",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "268",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "268"
},
{
  "houseId": "85",
  "ordinaryPayment": "165",
  "waterPayment": "448",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "613",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "16",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "613"
},
{
  "houseId": "86",
  "ordinaryPayment": "165",
  "waterPayment": "135",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Ingresar correctamente el concepto bancario como HYDRA86",
  "total": "300",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "300"
},
{
  "houseId": "87",
  "ordinaryPayment": "165",
  "waterPayment": "372",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "537",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "13",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "537"
},
{
  "houseId": "88",
  "ordinaryPayment": "165",
  "waterPayment": "186",
  "pendingPayment": "1117",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Retiro de servicios inmediato, al no pagar en una exibición",
  "total": "1468",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "1468"
},
{
  "houseId": "89",
  "ordinaryPayment": "165",
  "waterPayment": "448",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "613",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "16",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "613"
},
{
  "houseId": "90",
  "ordinaryPayment": "165",
  "waterPayment": "299",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Mayo",
  "comments": "Sin comentarios",
  "total": "464",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "10",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025",
  "amountPayed": "464"
}]
;

export const recibosHydra = data;
