
interface paymentsHydra {
    type?: string,
    color?: string,
    
    comprobation?: string,
    house?: string,
    
    ordinaryPayment: string,
    waterPayment: string,
   
    sanctionDescription?: string,
    total: string,
    
    
    token?: string,
    
    waterPaymentDelay?:string,
    ordinaryPaymentDelay?:string,
    sanctionPaymentDelay?:string,
    sanctionPaymentDelayDescription?:string,

    houseId: string,
    paymentMonth: string,
    year: string,
    caKey?:string,
    condo?:string,
    sanctionPayment?: string,
    pendingPayment?: string,
    metersConsumed?: string,
    periodOfWaterUse?: string,
    comments?:string,
    amount?: string,
  };

const data: paymentsHydra[] = 
[{
  "houseId": "1",
  "ordinaryPayment": "165",
  "waterPayment": "138",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "303",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "2",
  "ordinaryPayment": "165",
  "waterPayment": "172",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "337",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "3",
  "ordinaryPayment": "165",
  "waterPayment": "172",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "337",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "4",
  "ordinaryPayment": "165",
  "waterPayment": "172",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "337",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "5",
  "ordinaryPayment": "165",
  "waterPayment": "229",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "394",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "6",
  "ordinaryPayment": "165",
  "waterPayment": "190",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "355",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "7",
  "ordinaryPayment": "165",
  "waterPayment": "122",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "287",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "10",
  "ordinaryPayment": "165",
  "waterPayment": "106",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "271",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "11",
  "ordinaryPayment": "165",
  "waterPayment": "209",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "374",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "12",
  "ordinaryPayment": "165",
  "waterPayment": "138",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "303",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "13",
  "ordinaryPayment": "165",
  "waterPayment": "229",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "394",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "9",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "14",
  "ordinaryPayment": "165",
  "waterPayment": "378",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "543",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "14",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "15",
  "ordinaryPayment": "165",
  "waterPayment": "250",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "415",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "7",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "16",
  "ordinaryPayment": "165",
  "waterPayment": "172",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "337",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "17",
  "ordinaryPayment": "165",
  "waterPayment": "172",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "337",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "18",
  "ordinaryPayment": "165",
  "waterPayment": "190",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "355",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "19",
  "ordinaryPayment": "165",
  "waterPayment": "106",
  "pendingPayment": "5049",
  "sanctionPayment": "1500",
  "paymentMonth": "Julio",
  "comments": "Sin servicios",
  "total": "6820",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "20",
  "ordinaryPayment": "165",
  "waterPayment": "250",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "415",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "9",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "21",
  "ordinaryPayment": "165",
  "waterPayment": "172",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "337",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "22",
  "ordinaryPayment": "165",
  "waterPayment": "106",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "271",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "23",
  "ordinaryPayment": "165",
  "waterPayment": "190",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "355",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "24",
  "ordinaryPayment": "165",
  "waterPayment": "304",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "469",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "25",
  "ordinaryPayment": "165",
  "waterPayment": "155",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "320",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "26",
  "ordinaryPayment": "165",
  "waterPayment": "351",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "516",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "11",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "27",
  "ordinaryPayment": "165",
  "waterPayment": "190",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "355",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "28",
  "ordinaryPayment": "165",
  "waterPayment": "378",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "543",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "26",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "29",
  "ordinaryPayment": "165",
  "waterPayment": "138",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "303",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "30",
  "ordinaryPayment": "165",
  "waterPayment": "378",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "543",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "31",
  "ordinaryPayment": "165",
  "waterPayment": "209",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "374",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "7",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "32",
  "ordinaryPayment": "165",
  "waterPayment": "122",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "287",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "33",
  "ordinaryPayment": "165",
  "waterPayment": "250",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "415",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "34",
  "ordinaryPayment": "165",
  "waterPayment": "106",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "271",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "35",
  "ordinaryPayment": "165",
  "waterPayment": "229",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "394",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "36",
  "ordinaryPayment": "165",
  "waterPayment": "122",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "287",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "1",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "37",
  "ordinaryPayment": "165",
  "waterPayment": "122",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "287",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "38",
  "ordinaryPayment": "165",
  "waterPayment": "281",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "446",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "13",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "39",
  "ordinaryPayment": "165",
  "waterPayment": "138",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "303",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "40",
  "ordinaryPayment": "165",
  "waterPayment": "155",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "320",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "41",
  "ordinaryPayment": "165",
  "waterPayment": "122",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "287",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "42",
  "ordinaryPayment": "165",
  "waterPayment": "190",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "355",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "43",
  "ordinaryPayment": "165",
  "waterPayment": "155",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "320",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "44",
  "ordinaryPayment": "165",
  "waterPayment": "172",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "337",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "45",
  "ordinaryPayment": "165",
  "waterPayment": "378",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "543",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "15",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "46",
  "ordinaryPayment": "165",
  "waterPayment": "281",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "446",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "7",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "47",
  "ordinaryPayment": "165",
  "waterPayment": "138",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "303",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "48",
  "ordinaryPayment": "165",
  "waterPayment": "281",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "446",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "8",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "49",
  "ordinaryPayment": "165",
  "waterPayment": "122",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "287",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "1",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "50",
  "ordinaryPayment": "165",
  "waterPayment": "155",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "320",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "51",
  "ordinaryPayment": "165",
  "waterPayment": "106",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "271",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "52",
  "ordinaryPayment": "165",
  "waterPayment": "172",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "337",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "53",
  "ordinaryPayment": "165",
  "waterPayment": "281",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "446",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "8",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "54",
  "ordinaryPayment": "165",
  "waterPayment": "190",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "355",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "55",
  "ordinaryPayment": "165",
  "waterPayment": "138",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "303",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "56",
  "ordinaryPayment": "165",
  "waterPayment": "106",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "271",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "57",
  "ordinaryPayment": "165",
  "waterPayment": "455",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "620",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "13",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "58",
  "ordinaryPayment": "165",
  "waterPayment": "404",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "569",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "20",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "59",
  "ordinaryPayment": "165",
  "waterPayment": "209",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "374",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "60",
  "ordinaryPayment": "165",
  "waterPayment": "106",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "271",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "1",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "61",
  "ordinaryPayment": "165",
  "waterPayment": "106",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "271",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "62",
  "ordinaryPayment": "165",
  "waterPayment": "229",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "394",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "63",
  "ordinaryPayment": "165",
  "waterPayment": "209",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "374",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "64",
  "ordinaryPayment": "165",
  "waterPayment": "155",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "320",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "65",
  "ordinaryPayment": "165",
  "waterPayment": "455",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "620",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "11",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "66",
  "ordinaryPayment": "165",
  "waterPayment": "250",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "415",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "67",
  "ordinaryPayment": "165",
  "waterPayment": "138",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "303",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "69",
  "ordinaryPayment": "165",
  "waterPayment": "190",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "355",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "70",
  "ordinaryPayment": "165",
  "waterPayment": "327",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "492",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "10",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "71",
  "ordinaryPayment": "165",
  "waterPayment": "304",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "469",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "9",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "72",
  "ordinaryPayment": "165",
  "waterPayment": "229",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "394",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "7",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "73",
  "ordinaryPayment": "165",
  "waterPayment": "209",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "374",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "74",
  "ordinaryPayment": "165",
  "waterPayment": "209",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "374",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "75",
  "ordinaryPayment": "165",
  "waterPayment": "327",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "492",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "10",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "77",
  "ordinaryPayment": "165",
  "waterPayment": "106",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "271",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "78",
  "ordinaryPayment": "165",
  "waterPayment": "172",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "337",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "80",
  "ordinaryPayment": "165",
  "waterPayment": "138",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "303",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "81",
  "ordinaryPayment": "165",
  "waterPayment": "209",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "374",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "82",
  "ordinaryPayment": "165",
  "waterPayment": "327",
  "pendingPayment": "0",
  "sanctionPayment": "250",
  "paymentMonth": "Julio",
  "comments": "1er sanción-dejar heces fecales de mascota en áreas comunes",
  "total": "742",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "83",
  "ordinaryPayment": "165",
  "waterPayment": "281",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "446",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "7",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "84",
  "ordinaryPayment": "165",
  "waterPayment": "106",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "271",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "85",
  "ordinaryPayment": "165",
  "waterPayment": "455",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "620",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "16",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "86",
  "ordinaryPayment": "165",
  "waterPayment": "155",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "320",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "87",
  "ordinaryPayment": "165",
  "waterPayment": "378",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "543",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "13",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "89",
  "ordinaryPayment": "165",
  "waterPayment": "430",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "595",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "16",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "90",
  "ordinaryPayment": "165",
  "waterPayment": "281",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Julio",
  "comments": "Sin comentarios",
  "total": "446",
  "periodOfWaterUse": "Marzo",
  "metersConsumed": "10",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
}]
;

export const recibosHydra = data;
