
interface paymentsHydra {
    type: string,
    color?: string,
    amount: string,
    comprobation: string,
    house: string,
    houseId: string,
    ordinaryPayment: string,
    waterPayment: string,
    sanctionPayment: string,
    sanctionDescription: string,
    total: string,
    paymentMonth: string,
    year: string,
    token?: string,
    comments?:string,
    waterPaymentDelay?:string,
    ordinaryPaymentDelay?:string,
    sanctionPaymentDelay?:string,
    sanctionPaymentDelayDescription?:string
};

const data: paymentsHydra[] = 
[
    {
      "type": "redemption",
      "houseId": "1",
      "amount": "267",
      "waterPayment": "102",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "267",
      "comprobation": "0",
      "house": "1",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": "Amortización del excedente de pago en Agosto 2024"
    },
    {
      "type": "house",
      "houseId": "2",
      "amount": "348",
      "waterPayment": "183",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "348",
      "comprobation": "0",
      "house": "2",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "3",
      "amount": "330",
      "waterPayment": "165",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "330",
      "comprobation": "0",
      "house": "3",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "4",
      "amount": "366",
      "waterPayment": "201",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "366",
      "comprobation": "0",
      "house": "4",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "5",
      "amount": "529",
      "waterPayment": "364",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "529",
      "comprobation": "0",
      "house": "5",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "6",
      "amount": "330",
      "waterPayment": "165",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "330",
      "comprobation": "0",
      "house": "6",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "7",
      "amount": "267",
      "waterPayment": "102",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "267",
      "comprobation": "0",
      "house": "7",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "8",
      "amount": "366",
      "waterPayment": "201",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "366",
      "comprobation": "0",
      "house": "8",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "9",
      "amount": "502",
      "waterPayment": "337",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "502",
      "comprobation": "0",
      "house": "9",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "10",
      "amount": "366",
      "waterPayment": "201",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "366",
      "comprobation": "0",
      "house": "10",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "11",
      "amount": "330",
      "waterPayment": "165",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "330",
      "comprobation": "0",
      "house": "11",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "12",
      "amount": "267",
      "waterPayment": "102",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "267",
      "comprobation": "0",
      "house": "12",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "13",
      "amount": "405",
      "waterPayment": "240",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "405",
      "comprobation": "0",
      "house": "13",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "14",
      "amount": "553",
      "waterPayment": "388",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "553",
      "comprobation": "0",
      "house": "14",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "15",
      "amount": "1397",
      "waterPayment": "1232",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "1397",
      "comprobation": "0",
      "house": "15",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "16",
      "amount": "330",
      "waterPayment": "165",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "330",
      "comprobation": "0",
      "house": "16",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "17",
      "amount": "330",
      "waterPayment": "165",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "330",
      "comprobation": "0",
      "house": "17",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "18",
      "amount": "298",
      "waterPayment": "133",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "298",
      "comprobation": "0",
      "house": "18",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "mora",
      "houseId": "19",
      "amount": "0",
      "waterPayment": "102",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "267",
      "comprobation": "-267",
      "house": "19",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": "Sin servicios"
    },
    {
      "type": "house",
      "houseId": "20",
      "amount": "366",
      "waterPayment": "201",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "366",
      "comprobation": "0",
      "house": "20",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "21",
      "amount": "330",
      "waterPayment": "165",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "330",
      "comprobation": "0",
      "house": "21",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "22",
      "amount": "330",
      "waterPayment": "165",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "330",
      "comprobation": "0",
      "house": "22",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "23",
      "amount": "282",
      "waterPayment": "117",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "282",
      "comprobation": "0",
      "house": "23",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "24",
      "amount": "480",
      "waterPayment": "315",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "480",
      "comprobation": "0",
      "house": "24",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "25",
      "amount": "267",
      "waterPayment": "102",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "267",
      "comprobation": "0",
      "house": "25",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "26",
      "amount": "366",
      "waterPayment": "201",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "366",
      "comprobation": "0",
      "house": "26",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "27",
      "amount": "898",
      "waterPayment": "733",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "898",
      "comprobation": "0",
      "house": "27",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "28",
      "amount": "348",
      "waterPayment": "183",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "348",
      "comprobation": "0",
      "house": "28",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "29",
      "amount": "314",
      "waterPayment": "149",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "314",
      "comprobation": "0",
      "house": "29",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "redemption",
      "houseId": "30",
      "amount": "625",
      "waterPayment": "117",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "343",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "625",
      "comprobation": "343",
      "house": "30",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": "Realizo un abono parcial de $343 a su deuda acumulada"
    },
    {
      "type": "house",
      "houseId": "31",
      "amount": "385",
      "waterPayment": "220",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "385",
      "comprobation": "0",
      "house": "31",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "32",
      "amount": "267",
      "waterPayment": "102",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "267",
      "comprobation": "0",
      "house": "32",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "33",
      "amount": "315",
      "waterPayment": "149",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "314",
      "comprobation": "1",
      "house": "33",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "34",
      "amount": "267",
      "waterPayment": "102",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "267",
      "comprobation": "0",
      "house": "34",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "35",
      "amount": "298",
      "waterPayment": "133",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "298",
      "comprobation": "0",
      "house": "35",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "36",
      "amount": "502",
      "waterPayment": "337",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "502",
      "comprobation": "0",
      "house": "36",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "37",
      "amount": "267",
      "waterPayment": "102",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "267",
      "comprobation": "0",
      "house": "37",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "38",
      "amount": "480",
      "waterPayment": "315",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "480",
      "comprobation": "0",
      "house": "38",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "39",
      "amount": "385",
      "waterPayment": "220",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "385",
      "comprobation": "0",
      "house": "39",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "40",
      "amount": "330",
      "waterPayment": "165",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "330",
      "comprobation": "0",
      "house": "40",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "41",
      "amount": "267",
      "waterPayment": "102",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "267",
      "comprobation": "0",
      "house": "41",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "42",
      "amount": "314",
      "waterPayment": "149",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "314",
      "comprobation": "0",
      "house": "42",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "43",
      "amount": "502",
      "waterPayment": "337",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "502",
      "comprobation": "0",
      "house": "43",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "44",
      "amount": "330",
      "waterPayment": "165",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "330",
      "comprobation": "0",
      "house": "44",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "45",
      "amount": "529",
      "waterPayment": "364",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "529",
      "comprobation": "0",
      "house": "45",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "46",
      "amount": "267",
      "waterPayment": "102",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "267",
      "comprobation": "0",
      "house": "46",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "47",
      "amount": "282",
      "waterPayment": "117",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "282",
      "comprobation": "0",
      "house": "47",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "48",
      "amount": "502",
      "waterPayment": "337",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "502",
      "comprobation": "0",
      "house": "48",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "49",
      "amount": "298",
      "waterPayment": "133",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "298",
      "comprobation": "0",
      "house": "49",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "50",
      "amount": "348",
      "waterPayment": "183",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "348",
      "comprobation": "0",
      "house": "50",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "51",
      "amount": "366",
      "waterPayment": "201",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "366",
      "comprobation": "0",
      "house": "51",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "52",
      "amount": "330",
      "waterPayment": "165",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "330",
      "comprobation": "0",
      "house": "52",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "53",
      "amount": "405",
      "waterPayment": "240",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "405",
      "comprobation": "0",
      "house": "53",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "54",
      "amount": "314",
      "waterPayment": "149",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "314",
      "comprobation": "0",
      "house": "54",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "55",
      "amount": "314",
      "waterPayment": "149",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "314",
      "comprobation": "0",
      "house": "55",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "56",
      "amount": "282",
      "waterPayment": "117",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "282",
      "comprobation": "0",
      "house": "56",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "57",
      "amount": "458",
      "waterPayment": "293",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "458",
      "comprobation": "0",
      "house": "57",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "58",
      "amount": "435",
      "waterPayment": "270",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "435",
      "comprobation": "0",
      "house": "58",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "59",
      "amount": "366",
      "waterPayment": "201",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "366",
      "comprobation": "0",
      "house": "59",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "60",
      "amount": "267",
      "waterPayment": "102",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "267",
      "comprobation": "0",
      "house": "60",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "61",
      "amount": "330",
      "waterPayment": "165",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "330",
      "comprobation": "0",
      "house": "61",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "62",
      "amount": "348",
      "waterPayment": "183",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "348",
      "comprobation": "0",
      "house": "62",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "63",
      "amount": "435",
      "waterPayment": "270",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "435",
      "comprobation": "0",
      "house": "63",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "64",
      "amount": "405",
      "waterPayment": "240",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "405",
      "comprobation": "0",
      "house": "64",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "65",
      "amount": "435",
      "waterPayment": "270",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "435",
      "comprobation": "0",
      "house": "65",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "66",
      "amount": "366",
      "waterPayment": "201",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "366",
      "comprobation": "0",
      "house": "66",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "67",
      "amount": "435",
      "waterPayment": "270",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "435",
      "comprobation": "0",
      "house": "67",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "mora",
      "houseId": "68",
      "amount": "0",
      "waterPayment": "220",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "385",
      "comprobation": "-385",
      "house": "68",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": "Recargo 500 para Octubre"
    },
    {
      "type": "house",
      "houseId": "69",
      "amount": "330",
      "waterPayment": "165",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "330",
      "comprobation": "0",
      "house": "69",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "70",
      "amount": "458",
      "waterPayment": "293",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "458",
      "comprobation": "0",
      "house": "70",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "71",
      "amount": "348",
      "waterPayment": "183",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "348",
      "comprobation": "0",
      "house": "71",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "72",
      "amount": "385",
      "waterPayment": "220",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "385",
      "comprobation": "0",
      "house": "72",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "73",
      "amount": "348",
      "waterPayment": "183",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "348",
      "comprobation": "0",
      "house": "73",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "74",
      "amount": "348",
      "waterPayment": "183",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "348",
      "comprobation": "0",
      "house": "74",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "75",
      "amount": "435",
      "waterPayment": "270",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "435",
      "comprobation": "0",
      "house": "75",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "mora",
      "houseId": "76",
      "amount": "0",
      "waterPayment": "102",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "267",
      "comprobation": "-267",
      "house": "76",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": "Sin servicios"
    },
    {
      "type": "house",
      "houseId": "77",
      "amount": "1011",
      "waterPayment": "846",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "1011",
      "comprobation": "0",
      "house": "77",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "78",
      "amount": "298",
      "waterPayment": "133",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "298",
      "comprobation": "0",
      "house": "78",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "mora",
      "houseId": "79",
      "amount": "0",
      "waterPayment": "102",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "267",
      "comprobation": "-267",
      "house": "79",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": "Sin servicios"
    },
    {
      "type": "house",
      "houseId": "80",
      "amount": "298",
      "waterPayment": "133",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "298",
      "comprobation": "0",
      "house": "80",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "81",
      "amount": "385",
      "waterPayment": "220",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "385",
      "comprobation": "0",
      "house": "81",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "82",
      "amount": "435",
      "waterPayment": "270",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "435",
      "comprobation": "0",
      "house": "82",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "83",
      "amount": "405",
      "waterPayment": "240",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "405",
      "comprobation": "0",
      "house": "83",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "mora",
      "houseId": "84",
      "amount": "0",
      "waterPayment": "201",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "366",
      "comprobation": "-366",
      "house": "84",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": "Recargo 500 para Octubre"
    },
    {
      "type": "house",
      "houseId": "85",
      "amount": "480",
      "waterPayment": "315",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "480",
      "comprobation": "0",
      "house": "85",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "86",
      "amount": "382",
      "waterPayment": "117",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "282",
      "comprobation": "100",
      "house": "86",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "87",
      "amount": "480",
      "waterPayment": "315",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "480",
      "comprobation": "0",
      "house": "87",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "88",
      "amount": "314",
      "waterPayment": "149",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "314",
      "comprobation": "0",
      "house": "88",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "mora",
      "houseId": "89",
      "amount": "0",
      "waterPayment": "117",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "282",
      "comprobation": "-282",
      "house": "89",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": "Recargo 500 para Octubre"
    },
    {
      "type": "house",
      "houseId": "90",
      "amount": "512",
      "waterPayment": "337",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "502",
      "comprobation": "10",
      "house": "90",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": ""
    },
    {
      "type": "house",
      "houseId": "71.1",
      "amount": "348",
      "waterPayment": "183",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "",
      "comprobation": "",
      "house": "",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": "Pago duplicado por el inquilino"
    },
    {
      "type": "redemption",
      "houseId": "71.2",
      "amount": "348",
      "waterPayment": "183",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "",
      "comprobation": "",
      "house": "",
      "paymentMonth": "Septiembre",
      "year": "2024",
      "comments": "Amortización del excedente de pago en Septiembre 2024"
    },
    {
      "type": "extrapay",
      "houseId": "80",
      "amount": "366",
      "waterPayment": "",
      "ordinaryPayment": "165",
      "sanctionPayment": "0",
      "sanctionDescription": "",
      "waterPaymentDelay": "0",
      "ordinaryPaymentDelay": "0",
      "sanctionPaymentDelay": "0",
      "sanctionPaymentDelayDescription": "",
      "total": "",
      "comprobation": "",
      "house": "",
      "paymentMonth": "",
      "year": "",
      "comments": ""
    }
  ]
;

export const recibosHydra = data;
