
interface paymentsHydra {
    type?: string,
    color?: string,
    
    comprobation?: string,
    house?: string,
    
    ordinaryPayment: string,
    waterPayment: string,
   
    sanctionDescription?: string,
    total: string,
    
    
    token?: string,
    
    waterPaymentDelay?:string,
    ordinaryPaymentDelay?:string,
    sanctionPaymentDelay?:string,
    sanctionPaymentDelayDescription?:string,

    houseId: string,
    paymentMonth: string,
    year: string,
    caKey?:string,
    condo?:string,
    sanctionPayment?: string,
    pendingPayment?: string,
    metersConsumed?: string,
    periodOfWaterUse?: string,
    comments?:string,
    amount?: string,
  };

const data: paymentsHydra[] = 
[{
  "houseId": "1",
  "ordinaryPayment": "165",
  "waterPayment": "120",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "285",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "1",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "2",
  "ordinaryPayment": "165",
  "waterPayment": "170",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "335",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "3",
  "ordinaryPayment": "165",
  "waterPayment": "170",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "335",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "4",
  "ordinaryPayment": "165",
  "waterPayment": "188",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "353",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "5",
  "ordinaryPayment": "165",
  "waterPayment": "207",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "372",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "6",
  "ordinaryPayment": "165",
  "waterPayment": "136",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "301",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "7",
  "ordinaryPayment": "165",
  "waterPayment": "136",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "301",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "8",
  "ordinaryPayment": "165",
  "waterPayment": "302",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "467",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "10",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "9",
  "ordinaryPayment": "165",
  "waterPayment": "877",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "1042",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "27",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "10",
  "ordinaryPayment": "165",
  "waterPayment": "136",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "301",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "11",
  "ordinaryPayment": "165",
  "waterPayment": "153",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "318",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "12",
  "ordinaryPayment": "165",
  "waterPayment": "207",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "372",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "13",
  "ordinaryPayment": "165",
  "waterPayment": "248",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Favor de ingresar correctamente el concepto bancario como HYDRA13",
  "total": "413",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "8",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "14",
  "ordinaryPayment": "165",
  "waterPayment": "302",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "467",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "10",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "15",
  "ordinaryPayment": "165",
  "waterPayment": "207",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "372",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "16",
  "ordinaryPayment": "165",
  "waterPayment": "170",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "335",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "17",
  "ordinaryPayment": "165",
  "waterPayment": "153",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "318",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "18",
  "ordinaryPayment": "165",
  "waterPayment": "188",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "353",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "19",
  "ordinaryPayment": "165",
  "waterPayment": "104",
  "pendingPayment": "4780",
  "sanctionPayment": "1500",
  "paymentMonth": "Junio",
  "comments": "Sin servicios",
  "total": "6549",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "20",
  "ordinaryPayment": "165",
  "waterPayment": "207",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "372",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "21",
  "ordinaryPayment": "165",
  "waterPayment": "170",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "335",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "22",
  "ordinaryPayment": "165",
  "waterPayment": "104",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "269",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "23",
  "ordinaryPayment": "165",
  "waterPayment": "153",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "318",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "24",
  "ordinaryPayment": "165",
  "waterPayment": "188",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "353",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "25",
  "ordinaryPayment": "165",
  "waterPayment": "153",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "318",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "26",
  "ordinaryPayment": "165",
  "waterPayment": "302",
  "pendingPayment": "487",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "954",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "10",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "27",
  "ordinaryPayment": "165",
  "waterPayment": "104",
  "pendingPayment": "0",
  "sanctionPayment": "750",
  "paymentMonth": "Junio",
  "comments": "Ruido fuera de horarios permitidos. Primera sanción y reincidencia el mismo mes",
  "total": "1019",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "28",
  "ordinaryPayment": "165",
  "waterPayment": "170",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "335",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "29",
  "ordinaryPayment": "165",
  "waterPayment": "153",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "318",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "30",
  "ordinaryPayment": "165",
  "waterPayment": "325",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "490",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "11",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "31",
  "ordinaryPayment": "165",
  "waterPayment": "188",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "353",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "32",
  "ordinaryPayment": "165",
  "waterPayment": "104",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "269",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "33",
  "ordinaryPayment": "165",
  "waterPayment": "188",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "353",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "34",
  "ordinaryPayment": "165",
  "waterPayment": "104",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "269",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "35",
  "ordinaryPayment": "165",
  "waterPayment": "207",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "372",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "36",
  "ordinaryPayment": "165",
  "waterPayment": "136",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "301",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "37",
  "ordinaryPayment": "165",
  "waterPayment": "170",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "335",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "38",
  "ordinaryPayment": "165",
  "waterPayment": "325",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "490",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "11",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "39",
  "ordinaryPayment": "165",
  "waterPayment": "104",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "269",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "40",
  "ordinaryPayment": "165",
  "waterPayment": "170",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "335",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "41",
  "ordinaryPayment": "165",
  "waterPayment": "104",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "269",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "42",
  "ordinaryPayment": "165",
  "waterPayment": "188",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "353",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "43",
  "ordinaryPayment": "165",
  "waterPayment": "136",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "301",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "44",
  "ordinaryPayment": "165",
  "waterPayment": "188",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "353",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "45",
  "ordinaryPayment": "165",
  "waterPayment": "453",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "618",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "16",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "46",
  "ordinaryPayment": "165",
  "waterPayment": "227",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Favor de ingresar correctamente el concepto bancario como HYDRA46",
  "total": "392",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "7",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "47",
  "ordinaryPayment": "165",
  "waterPayment": "136",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "301",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "48",
  "ordinaryPayment": "165",
  "waterPayment": "325",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "490",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "11",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "49",
  "ordinaryPayment": "165",
  "waterPayment": "104",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "269",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "50",
  "ordinaryPayment": "165",
  "waterPayment": "170",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "335",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "51",
  "ordinaryPayment": "165",
  "waterPayment": "104",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "269",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "52",
  "ordinaryPayment": "165",
  "waterPayment": "153",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "318",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "53",
  "ordinaryPayment": "165",
  "waterPayment": "279",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "444",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "9",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "54",
  "ordinaryPayment": "165",
  "waterPayment": "153",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "318",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "55",
  "ordinaryPayment": "165",
  "waterPayment": "136",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "301",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "56",
  "ordinaryPayment": "165",
  "waterPayment": "120",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "285",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "1",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "57",
  "ordinaryPayment": "165",
  "waterPayment": "428",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "593",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "15",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "58",
  "ordinaryPayment": "165",
  "waterPayment": "620",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "785",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "22",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "59",
  "ordinaryPayment": "165",
  "waterPayment": "170",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "335",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "60",
  "ordinaryPayment": "165",
  "waterPayment": "104",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "269",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "61",
  "ordinaryPayment": "165",
  "waterPayment": "104",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "269",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "62",
  "ordinaryPayment": "165",
  "waterPayment": "227",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "392",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "7",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "63",
  "ordinaryPayment": "165",
  "waterPayment": "207",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "372",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "64",
  "ordinaryPayment": "165",
  "waterPayment": "153",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "318",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "65",
  "ordinaryPayment": "165",
  "waterPayment": "376",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "541",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "13",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "66",
  "ordinaryPayment": "165",
  "waterPayment": "207",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "372",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "67",
  "ordinaryPayment": "165",
  "waterPayment": "136",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "301",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "68",
  "ordinaryPayment": "165",
  "waterPayment": "104",
  "pendingPayment": "0",
  "sanctionPayment": "500",
  "paymentMonth": "Junio",
  "comments": "1er sanción-pago tardio cuota interna",
  "total": "769",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "69",
  "ordinaryPayment": "165",
  "waterPayment": "188",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "353",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "70",
  "ordinaryPayment": "165",
  "waterPayment": "325",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "490",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "11",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "71",
  "ordinaryPayment": "165",
  "waterPayment": "279",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "444",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "9",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "72",
  "ordinaryPayment": "165",
  "waterPayment": "227",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "392",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "7",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "73",
  "ordinaryPayment": "165",
  "waterPayment": "170",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "335",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "74",
  "ordinaryPayment": "165",
  "waterPayment": "207",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "372",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "6",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "75",
  "ordinaryPayment": "165",
  "waterPayment": "402",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "567",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "14",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "76",
  "ordinaryPayment": "165",
  "waterPayment": "104",
  "pendingPayment": "20281",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin servicios",
  "total": "20550",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "77",
  "ordinaryPayment": "165",
  "waterPayment": "104",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "269",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "78",
  "ordinaryPayment": "165",
  "waterPayment": "170",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "335",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "4",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "79",
  "ordinaryPayment": "165",
  "waterPayment": "104",
  "pendingPayment": "20352",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin servicios",
  "total": "20621",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "80",
  "ordinaryPayment": "165",
  "waterPayment": "136",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "301",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "2",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "81",
  "ordinaryPayment": "165",
  "waterPayment": "188",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "353",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "5",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "82",
  "ordinaryPayment": "165",
  "waterPayment": "248",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "413",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "8",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "83",
  "ordinaryPayment": "165",
  "waterPayment": "248",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "413",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "8",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "84",
  "ordinaryPayment": "165",
  "waterPayment": "104",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "269",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "0",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "85",
  "ordinaryPayment": "165",
  "waterPayment": "480",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "645",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "17",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "86",
  "ordinaryPayment": "165",
  "waterPayment": "120",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Favor de ingresar correctamente el concepto bancario como HYDRA86",
  "total": "285",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "1",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "87",
  "ordinaryPayment": "165",
  "waterPayment": "279",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "444",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "9",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "88",
  "ordinaryPayment": "165",
  "waterPayment": "153",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "318",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "3",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "89",
  "ordinaryPayment": "165",
  "waterPayment": "402",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "567",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "14",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
},
{
  "houseId": "90",
  "ordinaryPayment": "165",
  "waterPayment": "302",
  "pendingPayment": "0",
  "sanctionPayment": "0",
  "paymentMonth": "Junio",
  "comments": "Sin comentarios",
  "total": "467",
  "periodOfWaterUse": "Abril",
  "metersConsumed": "10",
  "condo": "Hydra",
  "caKey": "colonoshydraac",
  "year": "2025"
}]
;

export const recibosHydra = data;
